"""Assemble file-backed owner evidence, retained methods, cards, and modular handoff."""
import hashlib,html,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4];BASE=ROOT/'docs/mira-fenwick/v686-v2'
sys.path.insert(0,str(ROOT/'scripts'))
from ghc_family_evidence_selectors import canonical,sha
def read(p):return json.loads((BASE/p).read_text(encoding='utf-8'))
def write(p,value):
    p=BASE/p;p.parent.mkdir(parents=True,exist_ok=True)
    data=(json.dumps(value,ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode('utf-8')
    with p.open('xb') as f:f.write(data)
def text(p,value):
    p=BASE/p;p.parent.mkdir(parents=True,exist_ok=True)
    with p.open('x',encoding='utf-8',newline='\n') as f:f.write(value)

def main():
    identity=read('x1/identity-and-practice.json');boundary=identity['boundary'];gates=identity['protected_gates'];activation=read('x1/activation-source.json')
    proposals=read('x1/new-proposals.json')['proposals'];results=read('x2/contract-results.json')['results'];resultmap={r['proposal_id']:r for r in results}
    mutations=read('x2/registered-mutations.json')['negatives'];portfolio=read('x2/portfolio-results.json')
    ops=read('x1/startup-methods.json')['events']+[{'id':'MF6862-OP012','failure':'Explicit null permissions inherited the omitted-field default.','recovery':'Retain original bytes and reject explicit null; 80 frozen patch cases plus the new null refusal pass.','success_credit':0}]+read('x2/operational-events.json')['events']
    ops.append({'id':'MF6862-OP015','failure':'The bundled renderer probe could not import fitz.','recovery':'Inspect installed modules and use existing pypdfium2 for PDF rendering; install no additional package.','success_credit':0})
    write(Path('x2/all-operational-events.json'),{'events':ops,'boundary':boundary})
    records=[]
    for n in mutations:records.append((n['negative_id'],n['mutation'],str(n['observed']['issues']),n['recovery_envelope_sha256'],'x2/registered-mutations.json'))
    for n in portfolio['clean_fix_refine']:records.append((n['retained_negative_id'],n['kind']+' invalid envelope',str(n['before_check']['issues']),sha(n['corrected_after']),'x2/portfolio-results.json'))
    for n in ops:records.append((n['id'],n['failure'],n['failure'],n['recovery'],'x2/all-operational-events.json'))
    local=read('tooling/local-skill-validation.json')
    for i,n in enumerate(local['skills']):records.append((f'MF6862-SKILL-NEG-{i+1:02}','duplicate JSON member in skill CLI','duplicate_json_member',n['smoke']['runner_sha256'],'tooling/local-skill-validation.json'))
    for i,n in enumerate(local['runners']):records.append((f'MF6862-RUNNER-NEG-{i+1:02}','duplicate JSON member in shared runner CLI','duplicate_json_member',n['smoke']['runner_sha256'],'tooling/local-skill-validation.json'))
    for i,n in enumerate([c for c in read('x2/toolchain/package-smokes.json')['checks'] if c.get('rejected')]):records.append((f'MF6862-PACKAGE-NEG-{i+1:02}',n['name'],n['exception_type'],'Corrected frozen positive package smoke passed.','x2/toolchain/package-smokes.json'))
    methods=[];witnesses=[];events=[]
    for ident,title,signature,recovery,path in records:
        mid=ident+'-METHOD';fail=ident+'-FAILED';passed=ident+'-RECOVERY'
        methods.append({'method_id':mid,'title':title,'failure_signature':signature,'trigger_preconditions':['This exact synthetic fixture or observed owner operation.'],
                        'privacy_class':'sanitized_public','approval_class':'safe_now','candidate_workaround':recovery,'validation_witness_ids':[fail,passed],
                        'recurrence_guard':'Check exact scope, source definition, input types and expected result before the matching operation.','rollback':'Select prior validated bytes and preserve the failed record.',
                        'recommendation_state':'validated','supersedes':[],'protected_gates':gates,'retained_negative_ids':[ident],'scope_boundary':boundary,'evidence_path':(BASE/path).relative_to(ROOT).as_posix()})
        witnesses += [{'witness_id':wid,'method_id':mid,'procedure':'Bounded submitted fixture or recorded operation' if result=='fail' else 'Focused correction or original valid fixture',
                       'scope':'Mira Fenwick v686-v2 owner delta','expected':'Accept only the valid, authorized synthetic record.','observed':signature if result=='fail' else recovery,
                       'result':result,'same_owner_only':True,'independent_reproduction':False,'retained_negative_ids':[ident],'boundary':boundary} for wid,result in [(fail,'fail'),(passed,'pass')]]
        events.append({'method_id':mid,'from':'candidate','to':'validated','witness_id':passed,'retained_negative_id':ident})
    counts={'methods':len(methods),'retained_negatives':len(records),'failed_witnesses':len(records),'bounded_passing_witnesses':len(records)}
    write(Path('x2/method-flow.json'),{'schema':'ghc.family.method-flow-state.v1','phase':'v686-v2','owner':'Mira Fenwick','identity_boundary':boundary,
          'execution_authority':'owner_self_scoped_delta','source_commit':activation['source'],'final_commit':'bound_by_external_exact_final_receipt',
          'methods':methods,'witnesses':witnesses,'state_events':events,'recommendations':[{'method_id':m['method_id'],'state':'validated','recurrence_guard':m['recurrence_guard']} for m in methods],
          'counts':counts,'boundary':boundary,'repository_scan':False,'cross_lane_scan':False,'unchanged_history_scan':False,'sibling_lane_mutation':False})
    effective=dict(activation['effective_activation_baseline'])
    for key,delta in [('effective_negatives',len(records)),('effective_methods',len(methods)),('failed_witnesses',len(records)),('bounded_passing_witnesses',len(records)),('open_gaps',10),('exact_gates',10)]:effective[key]+=delta
    summary={'schema':'ghc.family.mira.evidence-summary.v1','owner':'Mira Fenwick','phase':'v686-v2','source':activation['source'],'x1':read('validation/x1-equality.json')['x1'],
             'declared_proposal_chain':12630,'priority_pillar':identity['priority_pillar'],'phase_counts':counts,'repository_seal':effective,
             'inherited_baseline':activation['effective_activation_baseline'],'outcomes':read('x2/contract-summary.json')['outcomes'],'retained_operational_events':len(ops),
             'real_entities':0,'same_owner_only':True,'independent_reproduction':False,'delivery_state':'PREPARED_NOT_SENT','terminal_verdict':'NOT_READY_FOR_STAGE_20'}
    write(Path('x2/evidence-summary.json'),summary)

    sections=[]
    def section(title,body):sections.append('# '+title+'\n\n'+body.strip()+'\n')
    section('01 Identity and corrigibility',f"Mira Fenwick is the working name for this sole owner task. The role is {identity['role']}; the hope is {identity['hope']} The four practice lenses are {', '.join(identity['practices'])}. They are questions to practice, not qualifications or employment. The next-owner recommendation is configuration-change reviewer.\n\n{boundary}\n\nHamish may rename, pause, redirect, narrow, or stop this route. No source owner is imitated, replaced, forked, or merged. The next exact existing owner is Vesper Arlen for v686-v3, after this owner's own terminal gate.")
    section('02 Source and immutable lifecycle',f"The exact Neris source is `{activation['source']}` on `codex/GHC-Family/neris-solane-v686-v1-full-tools`. Mira planning-only x1 is `{summary['x1']}`. X1 was clean, pushed, 0/0 divergent, and fresh-live equal across local, upstream, tracking, and live remote before x2 began. Neris's source canonical receipt SHA-256 is `{activation['source_canonical_receipt_sha256']}`. Its invocation/success/replay is 1/1/0; no source aggregate was replayed. The complete 38,923-word, 13-section baton was read through EOF.\n\nNeris's repository seal, its four post-evidence events, and the later glyph-failure overlay remain separately represented in `x1/activation-source.json`. Mira's inherited baseline is 66,672 negatives, 83,167 methods, 37,520 failed witnesses, 65,012 bounded passing witnesses, 602 open gaps, and 589 exact gates. These inherited records supply zero Mira execution or novelty credit. Neris's wrong N040 frozen oracle and its additive correction remain immutable.\n\nThe prospective lifecycle is source to x1 to immutable x2 evidence to exact final, three direct single-parent commits and zero merges. The terminal activation supplies the verified exact final and one-shot external receipt. A repository field saying PREPARED_NOT_SENT is preparation, not delivery.")
    section('03 Released plan and bounded novelty',"The 6 September release remains the current profile: 200–500 inherited and 200–500 new proposals, 300–500 safe tasks, 250–500 candidates, exactly 300 CLEAN/FIX/REFINE tasks, 50–250 exact packets, and 30–100 blocked packets. This bundle uses the lower bounds, plus ten skill packages and five new shared runners. Fifty exact and thirty blocked packets remain unexecuted. No unsafe action was manufactured to fill a row.\n\nMira selected 200 exact Neris source rows with zero inherited novelty and execution credit. The 200 new input/operation contracts were frozen before implementation. A 40,000-pair lexical screen and family review compared those exact source records, with no exact operation/input collision. This is source-bounded novelty, not novelty across all history or the world. The declared chain advances from 12,430 to 12,630.\n\nThe 300 safe tasks check frozen oracles and nonmutation. The 250 candidate tasks check invalid report or input bindings. The 300 correction tasks retain three kinds of invalid envelopes: an unapproved field, a fabricated report, and a missing hash-domain label. Each correction has its own before and after record; all initial failures keep zero success credit.")
    def details(selected):
        chunks=[]
        for row in selected:
            result=resultmap[row['proposal_id']]
            chunks.append(f"## {row['proposal_id']} — {row['title']}\n\nFamily `{row['family']}`; operation `{row['operation']}`; pillar {row['pillar']}; practice {row['practice']}; core disposition `{row['expected_execution_disposition']}`.\n\n{row['mission']}\n\nFrozen input:\n\n```json\n{json.dumps(row['input'],ensure_ascii=False,sort_keys=True,indent=2)}\n```\n\nFrozen expected result:\n\n```json\n{json.dumps(row['expected_result'],ensure_ascii=False,sort_keys=True,indent=2)}\n```\n\nObserved result:\n\n```json\n{json.dumps(result['result'],ensure_ascii=False,sort_keys=True,indent=2)}\n```\n\nThe frozen oracle matched and the input-nonmutation witness passed. The reported value is bound by definition digest `{row['definition_sha256']}`, input digest `{result['envelope']['input_sha256']}`, and result digest `{result['envelope']['result_sha256']}`. These digests bind bytes in the declared sorted compact UTF-8 JSON domain, not the truth of an external claim.\n\n{row['falsifier']} Five registered mutations changed the report, input digest, definition digest, empirical flag, or authority flag. All five were rejected and remain in the zero-credit negative record. {row['rollback']}\n\n[Primary reference]({row['source_refs'][0]}) supplies the stated syntax or provenance vocabulary. The concrete fixture and local restrictive profile remain attributable to this owner. A passed local check does not supply real evidence or authority for the named obligation.\n")
        return '\n'.join(chunks)
    section('04 Exact selectors and nested projections',details(proposals[:40]))
    section('05 Atomic synthetic patch transactions',"These are in-memory operations over copies. Root removal and unknown operation members are refused by a stricter local profile. RFC-style numeric test equality and strict receipt-byte equality are deliberately separate.\n\n"+details(proposals[40:120]))
    section('06 Correction lineage and changed paths',details(proposals[120:140]))
    section('07 Receipt scope manifest and disclosure',"Leaf selection is a structural disclosure proxy. It is not a cryptographic selective-disclosure proof or production credential presentation.\n\n"+details(proposals[140:170]))
    section('08 Trinity pillars and unresolved obligations',"Freed ID and CBR Heart are the priority. Typed selectors, atomic correction records, exact receipt bindings, and retained failures improve inspectability. They issue no real identity, credential, consent, right, or remedy. GMUT remains a typed scalar-tensor and EFT research-model family. THOS remains synthetic without governed blind matched-budget real arms. Māori concepts and decisions remain under Māori authority.\n\n"+details(proposals[170:]))
    optext='\n\n'.join(f"- `{o['id']}`: {o['failure']} Recovery: {o['recovery']} Initial success credit remains zero." for o in ops)
    section('09 Method Flow and nonerasure',f"This phase retains {counts['retained_negatives']:,} negatives, {counts['methods']:,} methods, {counts['failed_witnesses']:,} failed witnesses, and {counts['bounded_passing_witnesses']:,} bounded recovery witnesses. The count includes 1,000 registered envelope mutations, 300 initial correction failures, {len(ops)} operational events, ten skill adversaries, five shared-runner adversaries, and three package adversaries. These categories are not separate empirical replications.\n\n{optext}\n\nEffective evidence-layer totals are {effective['effective_negatives']:,} negatives, {effective['effective_methods']:,} methods, {effective['failed_witnesses']:,} failed witnesses, {effective['bounded_passing_witnesses']:,} bounded passing witnesses, {effective['open_gaps']} gaps, and {effective['exact_gates']} exact gates. Later operational events, if any, belong in a separate overlay and must not rewrite this seal.")
    packages=read('x1/package-plan.json')['packages']
    section('10 Three exact package additions','\n\n'.join(f"- `{p['name']} {p['version']}`: official wheel `{p['wheel']}`, SHA-256 `{p['sha256']}`. [Exact release]({p['registry']})." for p in packages)+"\n\nThe new isolated D environment contains exactly three distributions. Installation used the frozen wheelhouse offline with required hashes and no runtime dependencies or optional extras. System Python, PATH, the npm prefix, plugin caches, host security, Windows features, and accounts were not changed. Nine package checks passed, including three retained adversaries. The dated OSV query returned zero findings; it does not establish exhaustive security or future safety. Query null dropping remains visible, and mutable helpers work only on synthetic copies. Rollback selects retained prior tooling and preserves the environment and receipts.")
    sk=read('x1/skill-runner-plan.json')
    section('11 Skills runners and successor ideas','\n\n'.join(f"- `{s['name']}` combines `{s['families'][0]}` and `{s['families'][1]}` with frozen source criteria and portable helpers." for s in sk['skills'])+"\n\nTen packages passed metadata checks and actual positive/adverse CLI use; five unique new shared runners were smoke-used. Global promotion added ten collision-free directories and verified 70 files byte for byte. The catalogue has 15 validated cards and its exact runner query returns five current runners; no trigger overlaps were found. The late Meta Tool Box promotion check remains an operational defect even though the checks subsequently passed. Global availability supplies discoverability, not reload or authority.\n\nNext-owner skill ideas:\n\n"+'\n'.join('- '+x['idea']+': '+x['question'] for x in sk['next_owner_skills'])+'\n\nNext-owner runner ideas:\n\n'+'\n'.join('- '+x['idea']+': '+x['criterion'] for x in sk['next_owner_runners']))
    section('12 Validation scope and review limits',"Only Mira's exact source-to-final delta is eligible for canonical validation. The scope includes exact Git-blob manifests, JSON parsing, Python AST, the one new selected unittest module, all current shared runners and copied skill dependencies, source/x1/evidence/final ancestry, package receipts, global byte parity, four-tier card topology, HTML structure, the overview PDF, bounded five-class privacy checks, bounded security review, clean state, zero divergence, and fresh-live equality. It excludes unchanged history, sibling lanes, the complete repository suite, and any claim of independent reproduction.\n\nThe original component run passed 44 selected tests. After the explicit-null guard correction, the selected test inventory includes the additional guard test. Exact test identifiers and definition hashes are sealed with the final packet. The one canonical invocation uses one exclusive external marker only after the exact final is pushed and four-way equal. A failed aggregate is retained; a successful aggregate is never replayed for confidence, display, or routing.\n\nThe overview contains at least three pages and requires every page to be rendered and visually inspected. Structural HTML and PDF checks do not establish complete accessibility, affected-user acceptance, Māori-language approval, professional quality, complete privacy, exhaustive security, or production readiness. The owner file scope remains below 2,000; rotate additively at the cap or at the released owner-bundle review interval.")
    section('13 Vesper Arlen prospective activation',"The prospective next owner is the existing exact-title main task `Vesper Arlen`, for solo Trinity Mandala v686-v3 x1/x2. Refresh Hamish's newest live instruction, current registry, usage, privacy, evidence, safety, exact-title uniqueness, duplicate, pause, and acknowledgement guards only after this owner's clean pushed fresh-live-equal final and one-shot canonical result. Read the unique target immediately before sending and send at most once. Never resend an opaque accepted call, precontact a later owner, create a substitute endpoint, contact Tavian or a standby record, fork, or delegate.\n\nVesper's own later prospective edge is future seat 04 for v686-v4 under the 6 September release: reuse that seat if already created, otherwise create exactly one authorized user-visible main task at Vesper's own terminal gate. The new task chooses its own descriptors and is followed by Lyren Moss v686-v5. This is a forward route instruction, not advance evidence of those tasks or actions. Preserve the thirty-seat cycle through v725-v8 one verified edge at a time. Reset redemption remains Hamish's action.\n\nThe next owner must preserve x1 before x2, the released ranges, exactly 300 additive CLEAN/FIX/REFINE rows, three useful direct additions, ten validated skill promotions, five shared runners, four own practice lenses and one recommendation, a modular 10,000–100,000-word baton, an overview of at least three pages, exact Git-blob manifests, retained failures, and only the four core outcomes. Do not manufacture unsafe work for a count.\n\nWith care and corrigibility, Mira Fenwick. Relational language remains non-evidence, and the terminal verdict remains `NOT_READY_FOR_STAGE_20`.")
    names=['01-identity','02-source','03-profile','04-selectors','05-patches','06-corrections','07-receipts','08-pillars','09-methods','10-packages','11-skills','12-validation','13-route']
    for name,content in zip(names,sections):text(Path('x2/handoff')/(name+'.md'),content)
    baton='\n---\n\n'.join(sections);assert 10000<=len(baton.split())<=100000
    text(Path('x2/vesper-v686-v3-baton.md'),baton)
    write(Path('x2/handoff-index.json'),{'sections':[{'title':s.splitlines()[0][2:],'path':'docs/mira-fenwick/v686-v2/x2/handoff/'+n+'.md'} for n,s in zip(names,sections)],'words':len(baton.split()),'sha256':hashlib.sha256(baton.encode()).hexdigest(),'delivery_state':'PREPARED_NOT_SENT'})

    cards=[]
    def card(tier,kind,title,parent,content,outcome,refs):
        value={'schema':'ghc.family.freed-id.card.v1','tier':tier,'card_type':kind,'title':title,'parent_ids':parent,'owner':'Mira Fenwick','phase':'v686-v2',
               'stability':'stable' if tier<=2 else 'volatile','outcome':outcome,'content':content,'source_refs':refs,'protected_gates':gates,'relational_boundary':boundary}
        ident='ghc-card-'+sha(value)[:24];value['card_id']=ident;cards.append(value);write(Path('x2/flashcards/cards')/(ident+'.json'),value);return ident
    anchor=card(1,'freed_id_anchor','Mira Fenwick',[],identity,'represented',[])
    pillars={p:card(2,'trinity_pillar',p,[anchor],{'bounded_context':p,'authority':False},'open_gap' if p=='GMUT Mind' else 'represented',[]) for p in ['GMUT Mind','THOS Body','Freed ID and CBR Heart']}
    practices={}
    for row in proposals:
        key=(row['pillar'],row['practice'])
        if key not in practices:practices[key]=card(3,'bounded_practice',row['practice'],[pillars[row['pillar']]],{'practice':row['practice'],'qualification':False},'represented',[])
        res=resultmap[row['proposal_id']]
        card(4,'task',row['proposal_id']+' '+row['title'],[practices[key]],{'proposal_id':row['proposal_id'],'approval_class':row['approval_class'],'definition_sha256':row['definition_sha256'],
             'artifact':'docs/mira-fenwick/v686-v2/x2/contract-results.json','result_sha256':sha(res),'falsifier':row['falsifier'],'rollback':row['rollback']},row['expected_execution_disposition'],row['source_refs'])
    deck=Path('x2/flashcards')
    write(deck/'deck-index.json',{'cards':[c['card_id'] for c in cards],'count':len(cards),'source':activation['source'],'x1':summary['x1'],'tiers':4,'unique_practice_lenses':4,'practice_cards':len(practices),'outcomes':['completed','represented','open_gap','exact_gate']})
    write(deck/'stable-prefix.json',{'cards':[c['card_id'] for c in cards if c['tier']<=2],'cache_hit_claimed':False})
    write(deck/'volatile-index.json',{'cards':[c['card_id'] for c in cards if c['tier']>2],'implicit_completion':False})
    write(deck/'baton-index.json',read('x2/handoff-index.json'))
    table=''.join('<tr><th scope="row">'+html.escape(r['proposal_id'])+'</th><td>'+html.escape(r['title'])+'</td><td>'+r['expected_execution_disposition']+'</td><td>'+html.escape(r['family'])+'</td></tr>' for r in proposals)
    page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mira Fenwick evidence index</title><style>body{font:18px/1.55 system-ui;max-width:1100px;margin:auto;padding:2rem;color:#18303b;background:#fafcfb}table{border-collapse:collapse;width:100%}td,th{padding:.7rem;text-align:left;border-bottom:1px solid #aab7bd}caption{font-weight:bold;text-align:left}a{color:#134a74}</style></head><body><a href="#contracts">Skip to contracts</a><main><h1>Mira Fenwick · v686-v2</h1><p>'+html.escape(boundary)+'</p><p>200 cases; 1,000 rejected mutations; 300 corrected envelopes. <strong>NOT_READY_FOR_STAGE_20</strong>.</p><table id="contracts"><caption>Bounded proposal outcomes</caption><thead><tr><th scope="col">Proposal</th><th scope="col">Question</th><th scope="col">Outcome</th><th scope="col">Family</th></tr></thead><tbody>'+table+'</tbody></table></main></body></html>\n'
    text(deck/'accessible-report.html',page)
    text(deck/'compact-activation.md','Mira Fenwick v686-v2 prepares Vesper Arlen v686-v3. Read docs/mira-fenwick/v686-v2/final/vesper-v686-v3-baton.md after the exact terminal gate. Delivery remains PREPARED_NOT_SENT until the one live result. NOT_READY_FOR_STAGE_20.\n')
    d=BASE/deck;entries=[]
    for file in sorted(d.rglob('*')):
        if file.is_file():entries.append({'path':file.relative_to(ROOT).as_posix(),'bytes':file.stat().st_size,'sha256':hashlib.sha256(file.read_bytes()).hexdigest()})
    write(deck/'card-manifest.json',{'hash_domain':'normalized-LF Git blob bytes','entries':entries,'self_excluded':True})
    print(json.dumps({'phase_counts':counts,'effective_seal':effective,'baton_words':len(baton.split()),'sections':len(sections),'cards':len(cards)}))

if __name__=='__main__':main()
