import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {PassThrough,Writable} from 'node:stream';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createSession,serveStdio,SUPPORTED_PROTOCOL_VERSIONS} from './adapter.mjs';
import {fixtureBindings} from './fixtures/bindings.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const fixture=JSON.parse(fs.readFileSync(path.join(root,'fixtures/protocol.json'),'utf8'));
const request=(id,method,params)=>({jsonrpc:'2.0',id,method,...(params===undefined?{}:{params})});
const tick=()=>new Promise(r=>setImmediate(r));
function ready(overrides={},limits={}){const bindings=fixtureBindings(overrides),session=createSession({...bindings,limits});assert.equal(session.dispatch(structuredClone(fixture.initialize)).result.protocolVersion,'2025-11-25');assert.equal(session.dispatch(fixture.initialized),null);return {session,...bindings};}
function streams({overrides={},limits={},output}={}){const input=new PassThrough(),chunks=[];output??=new Writable({write(chunk,_encoding,cb){chunks.push(Buffer.from(chunk));cb();}});const bindings=fixtureBindings(overrides),transport=serveStdio({input,output,...bindings,limits});return {...bindings,input,output,transport,chunks,text:()=>Buffer.concat(chunks).toString('utf8'),messages:()=>Buffer.concat(chunks).toString('utf8').split('\n').filter(Boolean).map(JSON.parse)};}
const send=(io,value)=>io.input.write(Buffer.from(JSON.stringify(value)+'\n'));
async function runWire(chunks,options={}){const io=streams(options);for(const c of chunks)io.input.write(Buffer.isBuffer(c)?c:Buffer.from(c));io.input.end();const outcome=await io.transport.done;return {...io,outcome};}
const opening=JSON.stringify(fixture.initialize)+'\n'+JSON.stringify(fixture.initialized)+'\n';

test('P01 handshake advertises only tools and requires initialized notification',()=>{const b=fixtureBindings(),s=createSession(b);assert.equal(s.dispatch(request(0,'tools/list')).error.code,-32002);const r=s.dispatch(fixture.initialize);assert.deepEqual(r,{jsonrpc:'2.0',id:1,result:{protocolVersion:'2025-11-25',capabilities:{tools:{listChanged:false}},serverInfo:{name:'nexus-hub-readonly',version:'0.1.0'}}});assert.equal(s.dispatch(request(2,'tools/list')).error.code,-32002);s.dispatch(fixture.initialized);assert.ok(s.dispatch(request(3,'tools/list')).result);assert.equal(b.calls.length,0);});
test('P02 unsupported version negotiates the actually supported legacy version',()=>{const s=createSession(fixtureBindings());const init=structuredClone(fixture.initialize);init.params.protocolVersion='2026-07-28';assert.equal(s.dispatch(init).result.protocolVersion,'2025-11-25');});
test('P03 malformed or repeated initialization has fixed errors',()=>{const s=createSession(fixtureBindings());assert.equal(s.dispatch(request(0,'initialize',{})).error.code,-32602);s.dispatch(fixture.initialize);assert.equal(s.dispatch({...fixture.initialize,id:2}).error.code,-32600);});
test('P04 inventory is fixed, valid object schemas and non-executing read-only annotations',()=>{const {session,calls}=ready();const tools=session.dispatch(request(2,'tools/list')).result.tools;assert.deepEqual(tools.map(t=>t.name),fixture.expectedTools);for(const t of tools){assert.equal(t.inputSchema.type,'object');assert.equal(t.inputSchema.additionalProperties,false);assert.equal(t.annotations.readOnlyHint,true);assert.equal(t.annotations.destructiveHint,false);}assert.equal(calls.length,0);});
test('P05 all nine injected callbacks obey independent expected public projections',async()=>{const {session,calls}=ready();let id=2;for(const c of fixture.calls){const r=await session.dispatch(request(id++,'tools/call',{name:c.tool,arguments:c.arguments}));assert.equal(r.result.isError,false);assert.deepEqual(r.result.structuredContent,c.expected);assert.deepEqual(JSON.parse(r.result.content[0].text),c.expected);}assert.equal(calls.length,9);assert.ok(calls.every(c=>c.readOnly===true&&c.signal instanceof AbortSignal&&Object.isFrozen(c.args)));});
test('P06 malicious domain aliases never reach a callback',async()=>{const {session,calls}=ready();let id=2;for(const alias of fixture.badAliases){const r=await session.dispatch(request(id++,'tools/call',{name:'nexus.chats.resolve',arguments:{alias}}));assert.equal(r.result.isError,true);assert.equal(calls.length,0);} });
test('P07 unapproved executable and extra argument fields are rejected',async()=>{const {session,calls}=ready();for(const [i,args] of [{alias:'quay',shell:true},{alias:'quay',command:'anything'},JSON.parse('{"alias":"quay","__proto__":{"polluted":true}}')].entries()){const r=await session.dispatch(request(i+2,'tools/call',{name:'nexus.chats.plan',arguments:args}));assert.equal(r.result.isError,true);}assert.equal(calls.length,0);assert.equal({}.polluted,undefined);});
test('P08 unknown methods and tools use protocol errors without backend dispatch',()=>{const {session,calls}=ready();let id=2;for(const r of fixture.unknownRequests)assert.equal(session.dispatch(request(id++,r.method,r.params)).error.code,r.expectedCode);assert.equal(calls.length,0);});
test('P09 notifications never receive responses or invoke tools',async()=>{const {session,calls}=ready();for(const note of [{method:'tools/call',params:{name:'nexus.chats.list'}},{method:'unknown'},{method:'notifications/cancelled',params:{requestId:7,reason:'PRIVATE_REASON'}},{method:'tools/call',params:[]},{method:'initialize',params:{}}])assert.equal(await session.dispatch({jsonrpc:'2.0',...note}),null);assert.equal(calls.length,0);});
test('P10 notification carrying ID is not the initialized notification',()=>{const s=createSession(fixtureBindings());s.dispatch(fixture.initialize);assert.equal(s.dispatch(request(2,'notifications/initialized')).error.code,-32601);assert.equal(s.dispatch(request(3,'tools/list')).error.code,-32002);});
test('P11 legal prototype-like RPC IDs are preserved without property dispatch',()=>{const {session}=ready();for(const id of ['__proto__','constructor','prototype','',0,-1,'1']){const r=session.dispatch(request(id,'ping'));assert.equal(r.id,id);assert.deepEqual(r.result,{});}assert.equal({}.polluted,undefined);});
test('P12 invalid null, object, fractional, oversized and unsafe numeric IDs are not echoed',()=>{const {session}=ready();for(const id of [null,{},[],true,1.5,Number.MAX_SAFE_INTEGER+1,'x'.repeat(129)]){const r=session.dispatch(request(id,'ping'));assert.equal(r.error.code,-32600);assert.equal(Object.hasOwn(r,'id'),false);}});
test('P13 request IDs cannot be reused and numeric/string IDs stay distinct',()=>{const {session}=ready();assert.ok(session.dispatch(request('2','ping')).result);assert.ok(session.dispatch(request(2,'ping')).result);assert.equal(session.dispatch(request(2,'ping')).error.code,-32600);});
test('P14 client responses are silently ignored without reflection',()=>{const {session,calls}=ready();assert.equal(session.dispatch({jsonrpc:'2.0',id:4,result:{secret:'PRIVATE_REPLY'}}),null);assert.equal(session.dispatch({jsonrpc:'2.0',id:5,error:{code:1,message:'PRIVATE_ERROR'}}),null);assert.equal(calls.length,0);});
test('P15 ping before initialization is safe and does not ready the session',()=>{const s=createSession(fixtureBindings());assert.deepEqual(s.dispatch(request(7,'ping')),{jsonrpc:'2.0',id:7,result:{}});assert.equal(s.dispatch(request(8,'tools/list')).error.code,-32002);});
test('P16 callback failure and parser fields never leak private exception prose',async()=>{const {session}=ready({chatsList(){throw new Error('PRIVATE_EXCEPTION_TOKEN');}});const r=await session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));assert.equal(r.result.isError,true);assert.ok(!JSON.stringify(r).includes('PRIVATE_EXCEPTION_TOKEN'));const unknown=session.dispatch(request(3,'PRIVATE_UNKNOWN_METHOD'));assert.ok(!JSON.stringify(unknown).includes('PRIVATE_UNKNOWN_METHOD'));});
test('P17 human, transcript and credential fields are excluded by output projection',async()=>{const {session}=ready();for(const [i,name] of ['nexus.identity.summary','nexus.chats.list','nexus.chats.resolve'].entries()){const r=await session.dispatch(request(2+i,'tools/call',{name,arguments:name==='nexus.chats.resolve'?{alias:'quay'}:{}}));assert.ok(!JSON.stringify(r).includes('PRIVATE_'));assert.equal(r.result.isError,false);}});
test('P18 provider-supplied unregistered aliases, control text and arrays above 128 fail closed',async()=>{for(const data of [{items:[{alias:'native-session-id',available:true}]},{items:[{alias:'quay\u202e',available:true}]},{items:[{alias:'quay',available:true},{alias:'quay',available:true}]},{items:Array.from({length:129},()=>({alias:'quay',available:true}))}]){const {session}=ready({chatsList:()=>data});const r=await session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));assert.equal(r.result.isError,true);assert.ok(!JSON.stringify(r).includes('native-session-id'));}});
test('P19 plans cannot propagate caller-supplied execute claims or command strings',async()=>{const {session}=ready({remotePlan:()=>({available:true,route:'cloud',steps:['review'],executed:true,requiresReview:false,command:'PRIVATE_EXECUTABLE',token:'PRIVATE_TOKEN'})});const r=await session.dispatch(request(2,'tools/call',{name:'nexus.remote.plan',arguments:{alias:'cloud-worker'}}));assert.equal(r.result.structuredContent.executed,false);assert.equal(r.result.structuredContent.requiresReview,true);assert.ok(!JSON.stringify(r).includes('PRIVATE_'));});
test('P20 invalid call envelope, task request and list cursor are protocol errors',()=>{const {session,calls}=ready();for(const [i,params] of [{}, {name:'nexus.chats.list',arguments:[]},{name:'nexus.chats.list',task:{ttl:1}}].entries())assert.equal(session.dispatch(request(i+2,'tools/call',params)).error.code,-32602);assert.equal(session.dispatch(request(6,'tools/list',{cursor:'PRIVATE_CURSOR'})).error.code,-32602);assert.equal(calls.length,0);});
test('P21 only one callback runs while ping remains responsive',async()=>{let release;const {session}=ready({chatsList:()=>new Promise(r=>release=r)});const first=session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));await tick();assert.equal(session.dispatch(request(3,'tools/call',{name:'nexus.chats.list'})).error.code,-32001);assert.deepEqual(session.dispatch(request(4,'ping')).result,{});release({items:[]});assert.equal((await first).result.isError,false);});
test('P22 cancellation suppresses response, aborts callback and ends session',async()=>{let signal;const {session}=ready({chatsList:(_a,c)=>{signal=c.signal;return new Promise(()=>{});}});const pending=session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));await tick();assert.equal(session.dispatch({jsonrpc:'2.0',method:'notifications/cancelled',params:{requestId:2,reason:'PRIVATE_REASON'}}),null);assert.equal(await pending,null);assert.equal(signal.aborted,true);assert.equal(session.phase,'closed');});
test('P23 cancellation before deferred invocation avoids callback execution',async()=>{let called=0;const {session}=ready({chatsList:()=>{called++;return {items:[]};}});const pending=session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));session.dispatch({jsonrpc:'2.0',method:'notifications/cancelled',params:{requestId:2}});assert.equal(await pending,null);assert.equal(called,0);});
test('P24 callback timeout returns fixed tool error and prevents orphan accumulation',async()=>{let signal;const {session}=ready({chatsList:(_a,c)=>{signal=c.signal;return new Promise(()=>{});}}, {callbackTimeoutMs:20});const result=await session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));assert.equal(result.result.isError,true);assert.match(result.result.content[0].text,/time limit/);assert.equal(signal.aborted,true);assert.equal(session.phase,'closed');assert.equal(session.dispatch(request(3,'tools/call',{name:'nexus.chats.list'})),null);});
test('P25 callback rate and ID retention limits are explicit',async()=>{const {session,calls}=ready({}, {callbacksPerSecond:1});await session.dispatch(request(2,'tools/call',{name:'nexus.chats.list'}));assert.equal((await session.dispatch(request(3,'tools/call',{name:'nexus.chats.list'}))).result.isError,true);assert.equal(calls.length,1);const s=createSession({...fixtureBindings(),limits:{requestIds:1}});s.dispatch(request(1,'ping'));assert.equal(s.dispatch(request(2,'ping')).error.code,-32000);assert.equal(s.phase,'closed');});
test('P26 strict UTF-8 and malformed JSON return fixed errors only',async()=>{for(const raw of [Buffer.from([0xc3,0x28,10]),'{"PRIVATE_TOKEN":\n']){const io=await runWire([raw]);assert.equal(io.messages().length,1);assert.equal(io.messages()[0].error.code,-32700);assert.ok(!io.text().includes('PRIVATE_TOKEN'));}});
test('P27 batches and scalar JSON are rejected under the selected MCP message schema',async()=>{const io=await runWire(['[]\nnull\n7\n']);assert.equal(io.messages().length,3);assert.ok(io.messages().every(m=>m.error.code===-32600));});
test('P28 CRLF and fragmented multibyte IDs preserve one response per line',async()=>{const id='a😀\r\n\u202e',wire=Buffer.from(JSON.stringify(request(id,'ping'))+'\r\n');const io=await runWire(Array.from(wire,b=>Buffer.from([b])));assert.equal(io.messages()[0].id,id);assert.ok(!/[\x00-\x09\x0b-\x1f\x7f-\x9f\u202e]/.test(io.text()));assert.equal(io.text().split('\n').filter(Boolean).length,1);});
test('P29 oversized line closes after one bounded error, including fragmented input',async()=>{for(const chunks of [['x'.repeat(2000)+'\n'],['x'.repeat(500),'x'.repeat(525),'\n']]){const io=await runWire(chunks,{limits:{lineBytes:1024}});assert.equal(io.outcome.reason,'line_limit');assert.equal(io.messages().length,1);assert.match(io.messages()[0].error.message,/line limit/);assert.ok(io.text().length<1024);}});
test('P30 EOF rejects an unterminated frame and never dispatches it',async()=>{const io=await runWire([JSON.stringify(request(3,'tools/call',{name:'nexus.chats.list'}))]);assert.equal(io.messages()[0].error.code,-32700);assert.equal(io.calls.length,0);});
test('P31 oversized responses become bounded protocol errors',async()=>{const io=await runWire([opening+JSON.stringify(request(2,'tools/list'))+'\n'],{limits:{outputLineBytes:1024}});const list=io.messages().find(m=>m.id===2);assert.equal(list.error.code,-32603);assert.ok(io.text().split('\n').every(line=>Buffer.byteLength(line)<=1024));});
test('P32 output backpressure is bounded and does not collect unlimited queued data',async()=>{const sink=new Writable({write(_c,_e,_cb){}});const io=streams({output:sink,limits:{outputLineBytes:1024,queuedOutputBytes:1024,writeTimeoutMs:100}});for(let i=0;i<80;i++)send(io,request(i,'ping'));const outcome=await io.transport.done;assert.equal(outcome.reason,'output_limit');assert.ok(outcome.outputBytes<=1024);sink.destroy();});
test('P33 output stall deadline terminates boundedly',async()=>{const sink=new Writable({write(_c,_e,_cb){}}),io=streams({output:sink,limits:{writeTimeoutMs:20}});send(io,request(1,'ping'));const out=await io.transport.done;assert.equal(out.reason,'output_timeout');sink.destroy();});
test('P34 aggregate input and message budgets stop further dispatch',async()=>{const a=await runWire(['x'.repeat(101)],{limits:{sessionInputBytes:100}});assert.equal(a.outcome.reason,'input_limit');const b=await runWire([JSON.stringify(request(1,'ping'))+'\n'+JSON.stringify(request(2,'ping'))+'\n'],{limits:{messages:1}});assert.equal(b.outcome.reason,'message_limit');assert.equal(b.messages().length,2);});
test('P35 JSON nesting and node budgets reject before any callback',()=>{const {session,calls}=ready({}, {jsonDepth:4,jsonNodes:40});const r=session.dispatch(request(2,'tools/call',{name:'nexus.chats.list',_meta:{a:{b:{c:{d:{}}}}}}));assert.equal(r.error.code,-32600);assert.equal(calls.length,0);});
test('P36 callback output getters cannot leak thrown provider errors',async()=>{const {session}=ready({identitySummary:()=>({get platform(){throw new Error('PRIVATE_GETTER');},capabilities:{}})});const r=await session.dispatch(request(2,'tools/call',{name:'nexus.identity.summary'}));assert.equal(r.result.isError,true);assert.ok(!JSON.stringify(r).includes('PRIVATE_GETTER'));});
test('P37 registries allow 128 reviewed aliases and reject 129, duplicates or unsafe bindings',()=>{assert.throws(()=>createSession({handlers:{},selectors:{}}));const b=fixtureBindings();b.selectors.chats=['constructor'];assert.throws(()=>createSession(b));assert.throws(()=>createSession({...fixtureBindings(),limits:{callbackTimeoutMs:Infinity}}));for(const domain of ['chats','labs','sentinels','remotes']){const aliases=Array.from({length:128},(_,i)=>`entry-${String(i).padStart(3,'0')}`),bindings=fixtureBindings();bindings.selectors[domain]=aliases;const session=createSession(bindings);session.close();bindings.selectors[domain]=[...aliases,'entry-128'];assert.throws(()=>createSession(bindings),{message:'Invalid selector registry'});bindings.selectors[domain]=[...aliases.slice(0,127),aliases[0]];assert.throws(()=>createSession(bindings),{message:'Invalid selector registry'});}});
test('P38 actual stdio subprocess emits only framed MCP messages using synthetic bindings',()=>{const scratch=fs.mkdtempSync(path.join(root,'scratch/stdio-'));const input=opening+JSON.stringify(request(2,'tools/list'))+'\n'+JSON.stringify(request(3,'tools/call',{name:'nexus.remote.plan',arguments:{alias:'cloud-worker'}}))+'\n';const inputPath=path.join(scratch,'input.jsonl'),outPath=path.join(scratch,'output.jsonl'),errPath=path.join(scratch,'stderr.log');fs.writeFileSync(inputPath,input,{mode:0o600});const a=fs.openSync(inputPath,'r'),b=fs.openSync(outPath,'wx',0o600),c=fs.openSync(errPath,'wx',0o600);const r=spawnSync(process.execPath,[path.join(root,'fixtures/server.mjs')],{cwd:root,shell:false,stdio:[a,b,c],timeout:5000});fs.closeSync(a);fs.closeSync(b);fs.closeSync(c);assert.equal(r.error,undefined);assert.equal(r.status,0);assert.equal(fs.readFileSync(errPath,'utf8'),'');const replies=fs.readFileSync(outPath,'utf8').trim().split('\n').map(JSON.parse);assert.deepEqual(replies.map(m=>m.id),[1,2,3]);assert.deepEqual(replies[1].result.tools.map(t=>t.name),fixture.expectedTools);assert.deepEqual(replies[2].result.structuredContent,fixture.calls[8].expected);});
test('P39 callback timeout after input EOF retains failure shutdown accounting',async()=>{const io=await runWire([opening+JSON.stringify(request(2,'tools/call',{name:'nexus.chats.list'}))+'\n'],{overrides:{chatsList:()=>new Promise(()=>{})},limits:{callbackTimeoutMs:20}});assert.equal(io.messages().find(m=>m.id===2).result.isError,true);assert.equal(io.outcome.reason,'operation_stopped');});
test('P40 failed writable callback is contained without an unhandled stream error',async()=>{const output=new Writable({write(_c,_e,cb){cb(new Error('PRIVATE_WRITE_ERROR'));}});const io=streams({output});send(io,request(1,'ping'));const result=await io.transport.done;await tick();assert.equal(result.reason,'output_error');});
test('P41 structurally valid notifications above tree limits are silently discarded',()=>{const {session,calls}=ready({}, {jsonDepth:4});const r=session.dispatch({jsonrpc:'2.0',method:'tools/call',params:{name:'nexus.chats.list',arguments:{a:{b:{c:{d:{}}}}}}});assert.equal(r,null);assert.equal(calls.length,0);});
test('P42 exact two-argument async dispatcher receives only the prefixed fixed name and validated args',async()=>{const b=fixtureBindings(),calls=[];const session=createSession({selectors:b.selectors,dispatch:async function(name,args){calls.push({name,args,declaredArity:2});return {available:true,route:'manual',steps:['review']};}});session.dispatch(fixture.initialize);session.dispatch(fixture.initialized);const r=await session.dispatch(request(2,'tools/call',{name:'nexus.remote.plan',arguments:{alias:'cloud-worker'}}));assert.deepEqual(calls,[{name:'nexus.remote.plan',args:{alias:'cloud-worker'},declaredArity:2}]);assert.equal(r.result.structuredContent.executed,false);assert.equal(session.dispatch(request(3,'tools/call',{name:'remote.plan',arguments:{alias:'cloud-worker'}})).error.code,-32602);assert.equal(calls.length,1);});
test('P43 advertised supported versions are explicit and old unsupported offers negotiate honestly',()=>{assert.deepEqual(SUPPORTED_PROTOCOL_VERSIONS,['2025-11-25']);const s=createSession(fixtureBindings()),init=structuredClone(fixture.initialize);init.params.protocolVersion='2024-11-05';assert.equal(s.dispatch(init).result.protocolVersion,'2025-11-25');});

test('P44 40, 43 and 128 reviewed items survive both catalogue wire projections within byte caps',async()=>{
  for(const count of [40,43,128])for(const name of ['nexus.chats.list','nexus.lab.catalogue']){
    const aliases=Array.from({length:count},(_,i)=>`entry-${String(i).padStart(3,'0')}`);
    const items=aliases.map(alias=>({alias,available:true})),calls=[],chunks=[];
    const input=new PassThrough(),output=new Writable({write(chunk,_encoding,cb){chunks.push(Buffer.from(chunk));cb();}});
    const selectors=Object.fromEntries(['chats','labs','sentinels','remotes'].map(domain=>[domain,aliases]));
    const transport=serveStdio({input,output,selectors,dispatch:async(tool,args,context)=>{calls.push({tool,args,readOnly:context.readOnly});return {items};}});
    input.end(Buffer.from(opening+JSON.stringify(request(2,'tools/call',{name,arguments:{}}))+'\n'));
    assert.equal((await transport.done).reason,'eof');
    const lines=Buffer.concat(chunks).toString('utf8').trimEnd().split('\n'),messages=lines.map(JSON.parse);
    const reply=messages.find(message=>message.id===2);
    assert.equal(reply.result.isError,false);assert.deepEqual(reply.result.structuredContent,{items});
    assert.deepEqual(JSON.parse(reply.result.content[0].text),{items});assert.equal(reply.result.structuredContent.items.at(-1).alias,aliases.at(-1));
    assert.ok(lines.every(line=>Buffer.byteLength(line+'\n')<=16384));
    assert.deepEqual(calls,[{tool:name,args:{},readOnly:true}]);
  }
});

test('P45 128 maximum-length aliases retain the fixed response-byte error without partial catalogues',async()=>{
  for(const name of ['nexus.chats.list','nexus.lab.catalogue']){
    const aliases=Array.from({length:128},(_,i)=>`entry-${String(i).padStart(3,'0')}-`.padEnd(64,'a'));
    const items=aliases.map(alias=>({alias,available:true})),chunks=[];
    const input=new PassThrough(),output=new Writable({write(chunk,_encoding,cb){chunks.push(Buffer.from(chunk));cb();}});
    const selectors=Object.fromEntries(['chats','labs','sentinels','remotes'].map(domain=>[domain,aliases]));
    const transport=serveStdio({input,output,selectors,dispatch:async()=>({items})});
    input.end(Buffer.from(opening+JSON.stringify(request(2,'tools/call',{name,arguments:{}}))+'\n'));
    assert.equal((await transport.done).reason,'eof');
    const lines=Buffer.concat(chunks).toString('utf8').trimEnd().split('\n'),messages=lines.map(JSON.parse);
    const reply=messages.find(message=>message.id===2);
    assert.deepEqual(reply,{jsonrpc:'2.0',id:2,error:{code:-32603,message:'Response limit exceeded'}});
    assert.ok(lines.every(line=>Buffer.byteLength(line+'\n')<=16384));
    assert.equal(Object.hasOwn(reply,'result'),false);
  }
});
