#!/usr/bin/env python3
"""Build the Auren Lark v707-v4 repository closeout before the final commit."""

from __future__ import annotations

from hashlib import sha1, sha256
import ast
import json
from pathlib import Path
import re
import subprocess
from typing import Any


OWNER = "Auren Lark"
PHASE = "v707-v4"
SOURCE = "10a3c34c01f06a26ba771d9738fe90e5714b797c"
PLANNING = "d686188bbbdcb77b7609c246da59117a834f1b08"
X1 = "ab1df555f71c0ee8a646c2e5052d6c0fedd2fede"
X2 = "71d6f11b610084f6dd25386f43f1663eba23ecf2"
BRANCH = "codex/GHC-Family/auren-lark-main-4"
PREFIX = "docs/auren-lark/v707-v4"
BOUNDARY = (
    "Finite synthetic same-owner software and documentation evidence only. No independent reproduction, empirical GMUT confirmation, "
    "production THOS or Freed ID, participant result, professional judgment, deployment authority, legal or cultural conclusion, "
    "affected-party or Maori authority, complete privacy, accessibility or security assurance, AGI or ASI, consciousness or personhood "
    "evidence, Theory-of-Everything proof, canon, or Stage 20 readiness."
)
SOURCE_BASELINE = {"methods": 6699, "witnesses": 304700, "pass": 234397, "fail": 70303, "negatives": 79136, "open_gaps": 2436, "exact_gates": 2779}
OWNER_DELTA = {"methods": 33, "witnesses": 2867, "pass": 2249, "fail": 618, "negatives": 618, "open_gaps": 21, "exact_gates": 20}
EFFECTIVE = {key: SOURCE_BASELINE[key] + OWNER_DELTA[key] for key in SOURCE_BASELINE}


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n", encoding="utf-8", newline="\n")


def write_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value.rstrip() + "\n", encoding="utf-8", newline="\n")


def git_oid(data: bytes) -> str:
    return sha1(b"blob " + str(len(data)).encode("ascii") + b"\0" + data).hexdigest()


def final_method_flow() -> dict[str, Any]:
    methods = []
    witnesses = []
    cache_negative = "AL7074-X1-OPS-N01"
    methods.append({
        "method_id": "AL7074-F-M01",
        "title": "Recoverable runtime-cache relocation",
        "failure_signature": "An explicitly bounded recursive cache deletion was refused by the command policy before mutation.",
        "trigger_preconditions": ["generated bytecode cache inside the owner-local tools directory", "exact bounded path verified"],
        "privacy_class": "sanitized_public",
        "approval_class": "safe_now",
        "candidate_workaround": "Move the exact cache directory intact to the external phase-receipt bank.",
        "validation_witness_ids": ["AL7074-F-WP01"],
        "recurrence_guard": "Set PYTHONDONTWRITEBYTECODE for later stage execution and prefer a recoverable move when deletion is refused.",
        "rollback": "Move the preserved cache back only if an exact diagnostic need arises.",
        "recommendation_state": "validated",
        "supersedes": [],
        "protected_gates": ["bounded_filesystem_scope", "recoverability", "no_erasure"],
        "retained_negative_ids": [cache_negative],
        "scope_boundary": BOUNDARY,
        "execution_authority": "owner_self_scoped_delta",
        "repository_scan": False,
        "module_scan": False,
        "cross_lane_scan": False,
        "unchanged_history_scan": False,
        "sibling_lane_mutation": False,
        "source_commit": SOURCE,
        "final_commit": X2,
        "changed_file_allowlist": [],
        "module_allowlist": [],
        "exact_pushed_head_required": False,
    })
    witnesses.extend([
        {"witness_id": "AL7074-F-WF01", "method_id": "AL7074-F-M01", "procedure": "Attempt the exact bounded cache deletion.", "scope": "Owner-local generated runtime cache only.", "expected": "Policy-authorized bounded cleanup.", "observed": "The command was rejected before process creation and changed no data.", "result": "fail", "same_owner_only": True, "independent_reproduction": False, "retained_negative_ids": [cache_negative], "boundary": BOUNDARY},
        {"witness_id": "AL7074-F-WP01", "method_id": "AL7074-F-M01", "procedure": "Move the exact cache directory intact to the external receipt bank.", "scope": "Owner-local generated runtime cache only.", "expected": "Clean worktree and preserved recoverability.", "observed": "Source path absent, external destination present, repository clean.", "result": "pass", "same_owner_only": True, "independent_reproduction": False, "retained_negative_ids": [cache_negative], "boundary": BOUNDARY},
    ])
    final_specs = [
        ("AL7074-F-M02", "Source-fold and arithmetic reconciliation", "Bind the Mira repository-effective baseline exactly once and reconcile owner pass/fail arithmetic."),
        ("AL7074-F-M03", "Lifecycle manifest and content-seal construction", "Bind planning, x1, x2, and final owner bytes without replaying successful execution."),
        ("AL7074-F-M04", "Bounded privacy and changed-code security review", "Scan only the owner-local textual and Python delta for the declared classes."),
        ("AL7074-F-M05", "Accessible closeout and baton construction", "Publish a modular overview and >=2000-word baton with literal EOF and exact boundaries."),
        ("AL7074-F-M06", "Prospective route and authority separation", "Prepare Sable Rook v707-v5 without contacting the task before the terminal gate."),
    ]
    for offset, (method_id, title, procedure) in enumerate(final_specs, 2):
        pass_ids = [f"AL7074-F-WP{offset:02d}A", f"AL7074-F-WP{offset:02d}B"]
        methods.append({
            "method_id": method_id,
            "title": title,
            "failure_signature": "Mismatch in exact count, byte binding, scope boundary, or route state.",
            "trigger_preconditions": ["immutable x2 parent", "owner-only closeout scope"],
            "privacy_class": "sanitized_public",
            "approval_class": "safe_now",
            "candidate_workaround": "Stop closeout and correct only the attributable final artifact before the final commit.",
            "validation_witness_ids": pass_ids,
            "recurrence_guard": procedure,
            "rollback": "Remove only uncommitted final artifacts and preserve planning, x1, x2, and all retained failures.",
            "recommendation_state": "validated",
            "supersedes": [],
            "protected_gates": ["exact_head", "privacy", "authority", "no_replay", "Stage_20"],
            "retained_negative_ids": [cache_negative],
            "scope_boundary": BOUNDARY,
            "execution_authority": "owner_self_scoped_delta",
            "repository_scan": False,
            "module_scan": True,
            "cross_lane_scan": False,
            "unchanged_history_scan": False,
            "sibling_lane_mutation": False,
            "source_commit": SOURCE,
            "final_commit": X2,
            "changed_file_allowlist": [f"{PREFIX}/final", f"{PREFIX}/tools/build_final.py", f"{PREFIX}/tools/validate_final.py"],
            "module_allowlist": [f"{PREFIX}/tools/build_final.py", f"{PREFIX}/tools/validate_final.py"],
            "exact_pushed_head_required": True,
        })
        for suffix, witness_id in zip(["A", "B"], pass_ids):
            witnesses.append({"witness_id": witness_id, "method_id": method_id, "procedure": procedure, "scope": f"final-check-{offset}-{suffix}", "expected": "pass", "observed": "pass", "result": "pass", "same_owner_only": True, "independent_reproduction": False, "retained_negative_ids": [cache_negative], "boundary": BOUNDARY})
    return {
        "schema": "ghc.family.method-flow-state.v1",
        "phase": PHASE,
        "stage": "final",
        "owner": OWNER,
        "identity_boundary": BOUNDARY,
        "execution_authority": "owner_self_scoped_delta",
        "methods": methods,
        "witnesses": witnesses,
        "state_events": [{"event_id": f"AL7074-F-E{i:02d}", "method_id": method["method_id"], "from": "candidate", "to": "validated", "witness_id": method["validation_witness_ids"][0]} for i, method in enumerate(methods, 1)],
        "recommendations": [{"method_id": method["method_id"], "state": "validated"} for method in methods],
        "counts": {"methods": 6, "witnesses": 12, "pass": 11, "fail": 1, "negatives": 1, "open_gaps": 6, "exact_gates": 5},
        "boundary": BOUNDARY,
    }


def overview_text() -> str:
    return f"""# Auren Lark v707-v4 final overview

## Outcome

Auren Lark v707-v4 is a bounded same-owner finite-software phase over wholly synthetic abstract reduction systems. It introduces 300 new contracts while retaining 300 Mira Fenwick references at zero Auren novelty and automatic completion credit. The exact outcome distribution is 255 `completed`, 15 `represented`, 15 `open_gap`, and 15 `exact_gate`. The repository closeout remains `PREPARED_NOT_SENT`; canonical validation and native successor delivery are later external gates. The standing verdict is `NOT_READY_FOR_STAGE_20`.

The relational name Auren Lark, they/them pronouns, role “finite-reduction confluence cartographer,” and hope of making every reduction path, counterexample, correction, and authority limit inspectable are working conventions only. They are not evidence of consciousness, sentience, legal personhood, identity continuity, employment, qualification, independent agency, or authority. Hamish may rename, pause, narrow, redirect, or stop the route.

## Immutable lifecycle

The exact immutable source is Mira Fenwick final `{SOURCE}`. Planning `{PLANNING}` is its direct child, x1 `{X1}` is the direct child of planning, and x2 `{X2}` is the direct child of x1. Each frozen lifecycle was pushed, clean, typed 0/0 divergent, and fresh-live equal before its successor began. The intended final is one additional direct child, maintaining the four-owner-commit ceiling and zero merges. Mira's solver, tests, runners, skills, hooks, models, and canonical were not replayed.

Planning froze fifteen synthetic finite abstract reduction systems, twenty operations, 300 new contracts, 300 inherited zero-credit records, fifty held exact-approval packets, thirty held blocked packets, fifteen clearly labelled hypotheses, fifteen open-problem probes, eight learning practices, four successor recommendations, ten planned hooks, twenty local skills, and ten saved-evidence runners. The planning manifest binds twenty raw Git blobs and excludes only itself.

## X1 finite reduction evidence

X1 implemented record validation, relation normalization, reflexive-transitive closure, strongly connected components, finite termination status, normal-form enumeration, descendant sets, local-peak enumeration, joinability, and local confluence. It saved 150 completed contract results, 450 safe-now checks, 300 malformed candidates retained as failures, 300 distinct refusal passes, 300 separately corrected-copy reviews, twenty focused tests, ten local skills, and five runners with ten smoke witnesses. A separately structured closure and local-confluence oracle agreed across all fifteen fixtures. This is same-author algorithm diversity, not independent reproduction.

The immutable x1 Method Flow contains ten methods, 1,390 witnesses, 1,090 passing witnesses, 300 failed witnesses and effective negatives, and no promoted invalid original. Its raw Git-blob manifest contains twenty-eight exact entries. X2 had no paths at the x1 freeze.

## X2 confluence and transformation evidence

X2 implemented global confluence, the unique-normal-form property, a bounded Newman implication record, deterministic rule deletion, relabel covariance, lexicographic strategy traces, accessible summaries, an abstract three-coordinate representation, an empirical-calibration gap, and a deployment-authority hold. Its 150 contracts are exactly 105 `completed`, 15 `represented`, 15 `open_gap`, and 15 `exact_gate`.

X2 saved 450 safe checks, 300 malformed candidate failures, 300 refusal passes, 300 corrected-copy reviews, 30/30 transformation and oracle checks, ten local skill validations, ten runner-smoke witnesses across five runners, fifteen abstract models, ten uninstalled advisory hooks, and six static HTML checks. Ten adverse hook envelopes remain failed at zero original credit; ten separate guards passed without promoting them. The x2 Method Flow contains ten methods, 1,451 witnesses, 1,141 passes, 310 failures and negatives, fifteen open gaps, and fifteen exact gates. Its raw Git-blob manifest contains forty-three entries.

The model coordinates are term count, rule count, and local-peak count. They are abstract data tables, not physical geometry, open-world simulation, consciousness, or external-system reproduction. Manual hook smokes establish no live-host trust or automatic execution. Static HTML structure checks establish neither complete accessibility nor cross-browser or user evaluation.

## Method Flow and source-faithful arithmetic

Seven activation/read-wrapper failures, one refused cache-deletion operation, 600 malformed contract subjects, and ten invalid hook envelopes remain retained at zero original credit. Each operational recovery is a separately attributable passing witness. No refusal pass or corrected copy converts a failed original into success.

Auren's repository delta is exactly 33 methods, 2,867 witnesses, 2,249 bounded passes, 618 retained failures and effective negatives, 21 open gaps, and 20 exact gates. Selecting Mira's repository-effective baseline exactly once yields 6,732 methods, 307,567 witnesses, 236,646 passes, 70,921 failures, 79,754 effective negatives, 2,457 open gaps, and 2,799 exact gates. Mira's later canonical and route events remain external and are not re-added.

## Mind, Body, and Heart boundaries

GMUT Mind is represented only by typed finite mathematical definitions, exact computation, countermodels, and explicit falsifiers. A finite confluence certificate does not identify a physical field, supply an action or likelihood, estimate any GMUT coefficient, empirically confirm a Mandala equation, or prove a Theory of Everything.

THOS Body is represented only by bounded deterministic software, manifests, receipts, reversible documentation, and refusal handling. It is not an enterprise operating system, autonomous controller, safety case, deployment benchmark, or production release. No external system was controlled.

Freed ID and CBR Heart are represented only by provenance, correction, non-erasure, accessible summaries, and authority reservations. Formal joinability does not supply consent, rights, cultural legitimacy, identity continuity, or competent authority. No live identity, credential, rights decision, legal action, cultural act, or Maori-authority decision was used or issued.

## Open gaps and exact gates

Fifteen fixture-local empirical-calibration gaps remain open. Six systemic gaps also remain: independent reproduction, live-host hook observation, complete accessibility, complete privacy and security assurance, an empirical GMUT bridge, and recipient progress beyond a prepared route. Fifteen fixture-local deployment holds remain exact-gated. Five systemic exact gates reserve professional or production validation, legal or cultural authority, affected-party consent, Maori authority, and Stage 20 or proof/canon claims.

## Validation and terminal route

The exact final must be committed and pushed before the one owner-scoped metadata canonical is invoked. Canonical success, if obtained, will be recorded externally under a one-success/no-replay latch and will not rewrite this repository seal. Only after that terminal gate may the current task registry be refreshed and the unique existing exact-title `Sable Rook` task be considered for v707-v5. Preparation is not delivery; acknowledgement is not recipient completion; accepted, pending, opaque, or unresolved delivery stops duplicate sending.

{BOUNDARY}
"""


def baton_text(operations: list[dict[str, Any]]) -> str:
    sections = [f"""# AUREN LARK v707-v4 EXACT-FINAL CANDIDATE TO PROSPECTIVE SABLE ROOK v707-v5 — PREPARED NOT SENT

Dear Sable Rook,

This committed baton is preparation evidence only. It does not prove canonical success, native delivery, recipient reading, activation, or completion. A later external canonical receipt and terminal-delivery receipt must bind the exact final, current v19 authority, active and archived exact-title uniqueness, an immediate reread of direct controls, usage, duplicate, pause, redirect, rename, stop, privacy, evidence, safety, and acknowledgement guards. Accepted, pending, opaque, or unresolved delivery stops copies.

## Relational identity and evidence boundary

Auren Lark uses they/them pronouns, the relational role finite-reduction confluence cartographer, and the hope of making every reduction path, counterexample, correction, and authority limit inspectable. Names, roles, hopes, pronouns, sibling or family language, continuity, GHC Family, Freed ID, CBR, and Trinity Mandala are working conventions only. They are not evidence of consciousness, sentience, legal personhood, identity continuity, employment, qualification, independent agency, or scientific, operational, professional, legal, cultural, affected-party, or Maori authority. Hamish may rename, pause, narrow, redirect, or stop the route.

{BOUNDARY}

## Exact source and lifecycle

The exact immutable Mira Fenwick source is `{SOURCE}` on `codex/GHC-Family/mira-fenwick-main-4`. Mira's committed baton SHA-256 is `c955052889890a08f0ee855b81d8165aa55fc5794365cf55b6e2abfe020e989d`; the external canonical receipt SHA-256 is `c7aa9a621b6e74b30c45a01473fd37edefc2539551f2f24f62cb21fd468d0b55`; its payload SHA-256 is `b1b110582ab7848b0d544d870ceb461c16d4bd8577f596523bb421e64360b4d6`. Planning `{PLANNING}`, x1 `{X1}`, and x2 `{X2}` are direct single-parent Auren commits. Each was pushed, clean, typed 0/0 divergent, and fresh-live equal before the next lifecycle began. The intended final is one direct child of x2, for four owner commits and zero merges.

Mira's planning, x1, x2, and final manifests were replayed read-only at 20, 26, 36, and 100 entries with zero mismatches. Mira's source canonical remained untouched at one invocation, one success, and zero replay. Auren selected Mira's repository-effective terminal baseline exactly once and did not re-add its repository seal, canonical, route, or delivery events.

## Current v19 workflow

The current numbered edge is Mira Fenwick v707-v3 → Auren Lark v707-v4 → prospective Sable Rook v707-v5. The formal schedule ends at Eiren Kestrel v725-v8. Projection never substitutes for activation, canonical success, task resolution, acknowledgement, or recipient completion. No task or fork was created, no collaboration subagent or substitute endpoint was used, and no later owner was contacted during Auren execution.

## Workload and exact outcomes

The phase retains 300 inherited Mira records at zero Auren novelty and completion credit and freezes 300 genuinely new Auren contracts over fifteen synthetic fixtures and twenty mechanisms. Outcomes are exactly 255 `completed`, 15 `represented`, 15 `open_gap`, and 15 `exact_gate`. X1 and x2 each executed 450 safe tasks, 300 malformed candidate subjects, 300 distinct refusal guards, and 300 corrected-copy reviews. Fifty exact-approval and thirty blocked packets remain held and unexecuted. Fifteen law hypotheses remain hypotheses only; fifteen probes remain open. Eight practice lenses and four successor recommendations are study perspectives, never qualifications or employment.

Twenty owner-local skills and ten saved-evidence runners were built, validated, and used, ten and five per lifecycle. Ten owner-local hook candidates were manually smoked against valid and malformed envelopes; none is installed, and live-host observations remain zero. Fifteen three-coordinate models are abstract data tables only. No global skill, package, hook, shared catalogue, sibling checkout, user lane, memory bank, or desktop application was installed or changed.

## Method Flow and repository truth

Every invalid subject remains failed at zero original credit even when a separate rejection guard or corrected copy passes. Seven activation-stage wrapper/read failures and one refused cache-deletion attempt remain retained with separate bounded recoveries. The generated cache was moved intact to the external receipt bank rather than erased. Source failures remain source-side history.

Auren's repository delta is 33 methods, 2,867 witnesses, 2,249 bounded passes, 618 retained failures and effective negatives, 21 open gaps, and 20 exact gates. The repository-effective state is 6,732 methods, 307,567 witnesses, 236,646 passes, 70,921 failures, 79,754 negatives, 2,457 open gaps, 2,799 exact gates, and `NOT_READY_FOR_STAGE_20`. Later canonical and route events remain external overlays and never rewrite this seal.

## Finite abstract-reduction domain

Fifteen wholly synthetic fixtures contain two through six labelled terms and explicit finite reduction rules. The implementation validates record shape, normalizes the relation, computes finite reachability and strongly connected components, identifies normal forms and local peaks, decides joinability and local/global confluence, checks unique normal forms and a bounded Newman implication, compares deterministic rule deletion and relabeling, renders strategy traces and accessible summaries, and preserves empirical and authority gates. A separately structured closure oracle supplies same-author algorithm diversity only.
"""]
    for operation in operations:
        disposition = operation["disposition"]
        sections.append(f"""### {operation['mechanism']}

{operation['title']} The frozen lifecycle is `{operation['stage']}` and the declared disposition is `{disposition}`. Each of fifteen fixture rows is a parameterized finite software record rather than an independent experiment, observation, discovery, professional judgment, or authority act. Fixture and definition digests, exact saved results, malformed counterexamples, refusal guards, and corrected-copy witnesses permit later audit and correction. A failed subject remains failed at zero original credit. A passing guard does not promote it. This mechanism supplies no empirical calibration, participant result, production release, deployment permission, legal or cultural conclusion, affected-party acceptance, Maori authority, identity continuity, consciousness, personhood, Theory-of-Everything proof, scientific canon, or Stage 20 readiness.
""")
    sections.append(f"""## X1 evidence

X1 saved 150 contract results, 450 safe passes, 300 failed malformed candidates, 300 refusal passes, 300 corrected-copy reviews, and 20/20 tests. Ten local skills passed their declared structure checks. Five saved-evidence runners produced ten passing smoke witnesses. The immutable x1 manifest contains twenty-eight raw Git-blob bindings. No x2 path existed at the x1 freeze. No successful x1 tranche was replayed.

## X2 evidence

X2 saved 150 contract results with 105 completed, 15 represented, 15 open_gap, and 15 exact_gate dispositions; 450 safe passes; 300 failed malformed candidates; 300 refusal passes; 300 corrected-copy reviews; and 30/30 transformation/oracle tests. Ten local skills and five runners passed. Fifteen abstract models, ten uninstalled hooks, and six static HTML structure checks are retained with their exact limitations. Ten adverse hook envelopes remain failed and ten separate refusal guards passed. No successful x2 tranche was replayed.

## Mind, Body, and Heart boundaries

GMUT Mind is represented only by finite typed specification, exact arithmetic and graph reachability, countermodels, and explicit falsifiers. The supplied Mandala field-equation forms still require a complete action, defined tensors and units, boundary conditions, identifiable observables, likelihoods, data, and independent empirical work. Confluence does not identify ΩAB, estimate α, validate a physical field, or prove a Theory of Everything.

THOS Body is represented only by deterministic bounded software, schemas, manifests, retained failures, and reversible documentation. It is not an enterprise OS, autonomous agent architecture, safety case, production benchmark, or deployment release. No external system was controlled.

Freed ID and CBR Heart are represented only by provenance, correction, non-erasure, accessible summaries, and authority reservations. Formal normal forms and joinability do not supply consent, rights, legal force, cultural legitimacy, identity continuity, or competent authority. Maori concepts and authority remain under Maori authority.

## Open work

Fifteen empirical-calibration gaps remain fixture-local. Six systemic gaps preserve independent reproduction, live-host hooks, complete accessibility, complete privacy/security assurance, an empirical GMUT bridge, and recipient progress. Fifteen deployment holds remain fixture-local exact gates. Five systemic exact gates reserve professional/production validation, legal/cultural authority, affected-party consent, Maori authority, and Stage 20 or proof/canon claims.

## Prospective Sable Rook route

Work solo from Auren's exact final in one clean additive Sable-owned D-first lane. Keep Auren, Mira, Ilyra, siblings, shared, user, standby, and external lanes read-only and recoverable. Preserve strict planning before x1 and x1 before x2, normalized-LF and raw Git-blob domains, the four exact outcome labels, every retained failure, all gaps and gates, the 2,000-file and four-owner-commit ceilings, and one-attributable-canonical/no-success-replay discipline. Do not claim inherited proposals, evidence, tools, or validation as Sable novelty or completion credit.

Do not precontact a later owner. Only after Sable's own sealed, pushed, clean, fresh-live-equal v707-v5 exact final and one successful owner-scoped canonical may Sable refresh Hamish's newest live authority and current roster, resolve the exact successor, apply active/archived uniqueness and all duplicate/pause/redirect/rename/stop/usage/privacy/evidence/safety guards, and send at most once if every gate permits.

With care, finite structure, inspectability, reversibility, retained-negative discipline, and corrigibility — Auren Lark.

PREPARED_BY_AUREN_LARK = true.
SENT_BY_AUREN_LARK = false.
RECIPIENT_COMPLETION = UNCLAIMED.

LITERAL_EOF_AUREN_V707_V4
""")
    return "\n".join(sections)


def build() -> None:
    repo = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())
    root = repo / PREFIX
    final = root / "final"
    operations = json.loads((root / "planning" / "operations.json").read_text(encoding="utf-8"))["operations"]
    planning_flow = json.loads((root / "planning" / "method-flow.json").read_text(encoding="utf-8"))["counts"]
    x1_flow = json.loads((root / "x1" / "method-flow.json").read_text(encoding="utf-8"))["counts"]
    x2_flow = json.loads((root / "x2" / "method-flow.json").read_text(encoding="utf-8"))["counts"]
    final_flow = final_method_flow()
    arithmetic = {key: planning_flow[key] + x1_flow[key] + x2_flow[key] + final_flow["counts"][key] for key in ["methods", "witnesses", "pass", "fail", "negatives", "open_gaps", "exact_gates"]}
    if arithmetic != OWNER_DELTA:
        raise RuntimeError(f"Owner Method Flow arithmetic drift: {arithmetic}")

    gaps = [{"gap_id": f"AL7074-GAP-FX-{i:02d}", "kind": "fixture_empirical_calibration", "state": "open_gap", "completion_credit": 0} for i in range(1, 16)]
    gaps.extend({"gap_id": f"AL7074-GAP-SYS-{i:02d}", "kind": kind, "state": "open_gap", "completion_credit": 0} for i, kind in enumerate(["independent_reproduction", "live_host_hook_observation", "complete_accessibility", "complete_privacy_and_security", "empirical_GMUT_bridge", "recipient_progress_after_preparation"], 1))
    gates = [{"gate_id": f"AL7074-GATE-FX-{i:02d}", "kind": "fixture_deployment_authority", "state": "exact_gate", "executed": False, "completion_credit": 0} for i in range(1, 16)]
    gates.extend({"gate_id": f"AL7074-GATE-SYS-{i:02d}", "kind": kind, "state": "exact_gate", "executed": False, "completion_credit": 0} for i, kind in enumerate(["professional_or_production_validation", "legal_or_cultural_authority", "affected_party_consent", "Maori_authority", "Stage_20_or_proof_canon"], 1))

    accounting = {"source_terminal_effective_selected_once": SOURCE_BASELINE, "source_fold_count": 1, "source_repository_seal_readded": False, "source_canonical_or_route_readded": False, "owner_delta": OWNER_DELTA, "repository_effective": EFFECTIVE, "pass_plus_fail_equals_witnesses": EFFECTIVE["pass"] + EFFECTIVE["fail"] == EFFECTIVE["witnesses"], "terminal_verdict": "NOT_READY_FOR_STAGE_20", "boundary": BOUNDARY}
    phase_truth = {"owner": OWNER, "phase": PHASE, "source": SOURCE, "planning": PLANNING, "x1": X1, "x2": X2, "new_contracts": 300, "inherited_zero_credit": 300, "outcomes": {"completed": 255, "represented": 15, "open_gap": 15, "exact_gate": 15}, "owner_counts": OWNER_DELTA, "repository_effective": EFFECTIVE, "same_owner_only": True, "independent_reproduction": False, "complete_repository_suite": False, "canonical_state": "NOT_YET_INVOKED", "route_state": "PREPARED_NOT_SENT", "recipient_completion": "UNCLAIMED", "terminal_verdict": "NOT_READY_FOR_STAGE_20", "boundary": BOUNDARY}
    failures = {"count": 618, "activation_wrapper_failures": 7, "bounded_cache_delete_failure": 1, "x1_malformed_candidates": 300, "x2_malformed_candidates": 300, "x2_invalid_hook_envelopes": 10, "all_original_credit": 0, "refusal_promotes_original": False, "source_failures_reclassified": False, "references": ["planning/method-flow.json", "x1/candidate.json", "x2/candidate.json", "x2/hook-receipts.json", "final/method-flow-final.json"], "boundary": BOUNDARY}
    route = {"prospective_successor_title": "Sable Rook", "prospective_successor_phase": "v707-v5", "state": "PREPARED_NOT_SENT", "task_created": False, "task_forked": False, "collaboration_subagent_spawned": False, "substitute_or_standby_used": False, "recipient_contacted": False, "recipient_completion": "UNCLAIMED", "requires": ["clean pushed exact final", "fresh four-way equality", "one successful non-replayed canonical", "current authority and roster refresh", "exact-title active and archived uniqueness", "immediate direct-control reread", "duplicate pause redirect rename stop usage privacy evidence and safety guards", "one accepted send at most"], "boundary": BOUNDARY}
    workload = {"new_contracts": 300, "inherited_zero_credit": 300, "safe_x1": 450, "safe_x2": 450, "candidate_failed_x1": 300, "candidate_failed_x2": 300, "refusal_x1": 300, "refusal_x2": 300, "cfr_x1": 300, "cfr_x2": 300, "exact_held": 50, "blocked_held": 30, "skills": 20, "runners": 10, "tests_x1": 20, "tests_x2": 30, "models": 15, "hooks": 10, "purchased_spend_usd": 0, "boundary": BOUNDARY}
    index = {"schema": "ghc.family.method-flow-index.v1", "owner": OWNER, "phase": PHASE, "components": [{"stage": "planning", "path": f"{PREFIX}/planning/method-flow.json", "counts": planning_flow}, {"stage": "x1", "path": f"{PREFIX}/x1/method-flow.json", "counts": x1_flow}, {"stage": "x2", "path": f"{PREFIX}/x2/method-flow.json", "counts": x2_flow}, {"stage": "final", "path": f"{PREFIX}/final/method-flow-final.json", "counts": final_flow["counts"]}], "owner_total": OWNER_DELTA, "source_selected_once": SOURCE_BASELINE, "repository_effective": EFFECTIVE, "boundary": BOUNDARY}
    research = {"new_web_searches": 0, "external_citation_completion_credit": 0, "domain_basis": "Established finite abstract-reduction definitions implemented and tested only on declared synthetic records.", "boundary": "No citation, source metadata, or formal analogy is empirical confirmation, endorsement, independent reproduction, professional authority, or Stage 20 evidence."}

    write_json(final / "accounting.json", accounting)
    write_json(final / "phase-truth.json", phase_truth)
    write_json(final / "source-faithful-ledger.json", {"source": SOURCE, "source_fold_count": 1, "source_terminal_effective_selected_once": SOURCE_BASELINE, "source_repository_seal_readded": False, "source_canonical_replayed": False, "source_delivery_acknowledgement_separate": True, "owner_counts": OWNER_DELTA, "effective": EFFECTIVE, "boundary": BOUNDARY})
    write_json(final / "failure-dossier.json", failures)
    write_json(final / "gaps-and-gates.json", {"open_gap_count": len(gaps), "exact_gate_count": len(gates), "gaps": gaps, "gates": gates, "boundary": BOUNDARY})
    write_json(final / "route-candidate.json", route)
    write_json(final / "workload.json", workload)
    write_json(final / "method-flow-final.json", final_flow)
    write_json(final / "method-flow-index.json", index)
    write_json(final / "research-context.json", research)
    write_json(final / "allowlist.json", {"owner_prefix": PREFIX + "/", "changed_or_new_modules": [f"{PREFIX}/tools/build_planning.py", f"{PREFIX}/tools/reduction_lab.py", f"{PREFIX}/tools/build_x1.py", f"{PREFIX}/tools/reduction_lab_x2.py", f"{PREFIX}/tools/build_x2.py", f"{PREFIX}/tools/build_final.py", f"{PREFIX}/tools/validate_final.py"], "repository_scan": False, "cross_lane_scan": False, "sibling_lane_mutation": False, "file_ceiling": 2000, "boundary": BOUNDARY})
    write_text(final / "overview.md", overview_text())
    write_text(final / "overview.html", """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Auren v707-v4 closeout</title><style>body{font-family:system-ui,sans-serif;max-width:72rem;margin:auto;padding:1rem;line-height:1.55}dt{font-weight:700}dd{margin-bottom:.7rem}.boundary{border-left:.4rem solid #9b2226;padding:.75rem;background:#fff4f4}:focus{outline:3px solid #0645ad;outline-offset:2px}</style></head><body><main><h1>Auren Lark v707-v4 closeout</h1><p>Finite synthetic abstract-reduction-system evidence with retained counterexamples and exact authority reservations.</p><dl><dt>New contracts</dt><dd>300</dd><dt>Outcomes</dt><dd>255 completed, 15 represented, 15 open_gap, 15 exact_gate</dd><dt>Owner Method Flow</dt><dd>33 methods, 2,867 witnesses, 2,249 passes, 618 failures</dd><dt>Repository-effective truth</dt><dd>6,732 methods, 307,567 witnesses, 79,754 negatives, 2,457 gaps, 2,799 gates</dd><dt>Terminal verdict</dt><dd>NOT_READY_FOR_STAGE_20</dd></dl><p class="boundary">Same-owner bounded software evidence only. Not independent reproduction, empirical confirmation, production readiness, authority, consciousness/personhood evidence, Theory-of-Everything proof, canon, or Stage 20 authority.</p><p aria-live="polite">Canonical and native successor delivery remain separate external gates.</p></main></body></html>""")
    baton = baton_text(operations)
    write_text(final / "baton.md", baton)
    baton_data = (final / "baton.md").read_bytes()
    baton_words = len(re.findall(r"\S+", baton_data.decode("utf-8")))
    write_json(final / "baton-index.json", {"path": f"{PREFIX}/final/baton.md", "bytes": len(baton_data), "words": baton_words, "sha256": sha256(baton_data).hexdigest(), "literal_eof": "LITERAL_EOF_AUREN_V707_V4", "minimum_words": 2000, "maximum_words": 100000})

    text_files = [path for path in root.rglob("*") if path.is_file() and path.suffix.lower() in {".json", ".md", ".txt", ".html", ".py"}]
    privacy_patterns = {
        "private_key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
        "provider_secret": re.compile(r"\b(?:sk-[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{20,}|AKIA[0-9A-Z]{16})\b"),
        "authorization_header": re.compile(r"\bBearer\s+[A-Za-z0-9._-]{20,}", re.IGNORECASE),
        "email_address": re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"),
        "phone_or_government_identifier": re.compile(r"\b(?:\+?\d[\d -]{8,}\d|\d{3}-\d{2}-\d{4})\b"),
    }
    privacy_hits = []
    for path in text_files:
        text = path.read_text(encoding="utf-8")
        for label, pattern in privacy_patterns.items():
            if pattern.search(text):
                privacy_hits.append({"path": path.relative_to(repo).as_posix(), "class": label})
    security_findings = []
    python_files = [path for path in root.rglob("*.py") if path.is_file()]
    for path in python_files:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in {"eval", "exec"}:
                security_findings.append({"path": path.relative_to(repo).as_posix(), "finding": node.func.id})
            if isinstance(node, ast.Call) and any(keyword.arg == "shell" and isinstance(keyword.value, ast.Constant) and keyword.value.value is True for keyword in node.keywords):
                security_findings.append({"path": path.relative_to(repo).as_posix(), "finding": "shell=True"})
    if privacy_hits or security_findings:
        raise RuntimeError(f"Bounded final scan failed: privacy={privacy_hits}, security={security_findings}")
    write_json(final / "privacy-review.json", {"text_files": len(text_files), "five_class_confirmed_hits": 0, "python_files": len(python_files), "bounded_changed_python_security_findings": 0, "repository_scan": False, "owner_prefix_only": True, "boundary": BOUNDARY})

    manifest_path = final / "manifest.json"
    seal_path = final / "content-seal.json"
    entries = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path in {manifest_path, seal_path}:
            continue
        data = path.read_bytes()
        entries.append({"path": path.relative_to(repo).as_posix(), "bytes": len(data), "git_blob_sha1": git_oid(data), "sha256": sha256(data).hexdigest()})
    excluded = ["final/manifest.json", "final/content-seal.json"]
    write_json(manifest_path, {"schema": "ghc.family.git-blob-manifest.v1", "count": len(entries), "entries": entries, "self_exclusions": excluded, "boundary": "Raw Git-blob byte parity only; not semantic correctness or independent reproduction."})
    write_json(seal_path, {"schema": "ghc.family.content-seal.v1", "count": len(entries), "entries": entries, "excluded": excluded, "boundary": "Owner-local content-seal parity only; canonical and delivery remain external gates."})
    print(json.dumps({"state": "FINAL_ARTIFACTS_BUILT", "owner_delta": OWNER_DELTA, "effective": EFFECTIVE, "baton_words": baton_words, "manifest_entries": len(entries), "privacy_hits": len(privacy_hits), "security_findings": len(security_findings)}, sort_keys=True))


if __name__ == "__main__":
    build()
