import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {clean,uuid,plan,bounded,runPlan,journal,context,safeJson} from './core.mjs';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';

const testBase=path.resolve(process.env.GHC_HUB_TEST_TMP||(process.platform==='win32'?'D:/GHC-Archives/phase-banks/ghc-nexus-tests':os.tmpdir()));fs.mkdirSync(testBase,{recursive:true});
const root=fs.mkdtempSync(path.join(testBase,'ghc-hub-test-'));
const launcher=path.join(root,'admin.ps1');fs.writeFileSync(launcher,'# inert fixture\n');
const c={platform:'linux',cwd:root,state:path.join(root,'state'),codex:process.execPath,pwsh:process.execPath,bash:process.execPath,sudo:null,wsl:process.execPath,adminLauncher:launcher,node:process.execPath,uid:1000};
const valid='11111111-1111-4111-8111-111111111111';
test('session selector accepts exact UUID only',()=>{assert.ok(uuid(valid));for(const s of ['--last','other; echo X','../auth.json',valid+' extra',''])assert.equal(uuid(s),false);});
test('resume argv preserves the existing session without model or permission overrides',()=>{const p=plan('codex-resume',{session:valid},c);assert.deepEqual(p.args,['--no-daemon','--no-alt-screen','resume',valid]);assert.equal(p.shell,false);assert.equal(p.interactive,true);});
test('existing-chat overrides are refused by the hub',()=>assert.throws(()=>plan('codex-resume',{session:valid,override:true},c),/inherited/));
test('unsupported names cannot become executable commands',()=>{for(const s of ['sh -c','app; whoami','__proto__','constructor',''])assert.throws(()=>plan(s,{},c));});
test('missing or injected session refuses before launch',()=>{for(const s of [null,'--all','x && y'])assert.throws(()=>plan('codex-resume',{session:s},c));});
test('cloud environment validation keeps argv separate',()=>{assert.deepEqual(plan('cloud-list',{env:'env_123-a'},c).args.slice(-2),['--env','env_123-a']);for(const env of ['--env bad','a;b','$(bad)','a\nb'])assert.throws(()=>plan('cloud-list',{env},c));});
test('Windows app launch is unavailable on Linux',()=>assert.throws(()=>plan('app',{},c),/Windows/));
test('Windows normal app action requests registered activation through the guard',()=>{const w={...c,platform:'win32'};assert.deepEqual(plan('app',{},w).args.slice(-5),[launcher,'-Target','Codex','-AppActivation','Registered']);assert.equal(plan('app-check',{},w).args.at(-1),'-Check');assert.ok(plan('app-check',{},w).args.includes('Registered'));});
test('Administrator App requests the registered elevation route without a direct fallback',()=>{const w={...c,platform:'win32'};assert.deepEqual(plan('app-admin',{},w).args.slice(-5),[launcher,'-Target','Codex','-AppActivation','RegisteredAdministrator']);assert.ok(plan('app-admin-check',{},w).args.includes('-Check'));assert.ok(plan('app-direct',{},w).args.includes('DirectAdministrator'));});
test('Linux root request retains normal sudo boundary',()=>{assert.throws(()=>plan('linux-admin',{},c),/unavailable/);assert.deepEqual(plan('linux-admin',{}, {...c,sudo:'/usr/bin/sudo'}).args,['-i']);});
test('local Ubuntu request does not claim a remote cloud executor',()=>{const p=plan('linux',{}, {...c,platform:'win32'});assert.ok(p.note.includes('laptop RAM'));assert.ok(p.args.includes('Ubuntu'));});
test('cloud route invokes official task picker, not a local Linux substitute',()=>{const p=plan('cloud',{},c);assert.deepEqual(p.args,['cloud']);assert.equal(p.command,c.codex);assert.ok(p.note.includes('not SSH'));});
test('CLI inherits context and requests the observed Fast tier identifier',()=>{const p=plan('codex',{},c);assert.ok(p.args.includes('service_tier="priority"'));assert.ok(!p.args.some(a=>/model_context_window|model_auto_compact/.test(a)));});
test('terminal text cannot inject cursor or bidi controls',()=>{const s=clean('\x1b[2Jhello\r\n\u202eabc');assert.ok(!/[\x00-\x1f\u202e]/.test(s));assert.ok(s.includes('hello'));});
test('noninteractive terminal actions cannot silently open a new CLI session',async()=>{await assert.rejects(runPlan(plan('codex',{},c),c,{interactive:false}),/interactive terminal/);});
test('bounded child captures normal exit',async()=>{const r=await bounded(process.execPath,['-e','process.stdout.write("done")'],{cwd:root});assert.equal(r.status,'ok');assert.equal(r.exitCode,0);assert.equal(r.output,'done');});
test('bounded child preserves nonzero exit',async()=>{const r=await bounded(process.execPath,['-e','process.exit(7)'],{cwd:root});assert.equal(r.status,'failed');assert.equal(r.exitCode,7);});
test('missing executable never reports zero',async()=>{const r=await bounded(path.join(root,'missing'),[],{cwd:root});assert.equal(r.status,'spawn_error');assert.equal(r.exitCode,null);});
test('excess child output is bounded and not success',async()=>{const r=await bounded(process.execPath,['-e','process.stdout.write("x".repeat(100000));setInterval(()=>{},1000)'],{cwd:root,maxBytes:1000});assert.equal(r.status,'output_limit');assert.ok(Buffer.byteLength(r.output)<=1000);});
test('timed-out owned child is stopped even if TERM is ignored',async()=>{const r=await bounded(process.execPath,['-e','process.on("SIGTERM",()=>{});setInterval(()=>{},1000)'],{cwd:root,timeoutMs:250});assert.equal(r.status,'timeout');assert.ok(r.elapsedMs<10000);});
test('invalid timeout rejected before process creation',()=>{for(const t of [0,Infinity,NaN,60001,'1000'])assert.throws(()=>bounded('x',[],{timeoutMs:t}));});
test('non-finite and excessive output limits are refused',()=>{for(const b of [0,Infinity,NaN,-1,4194305,'1000'])assert.throws(()=>bounded('x',[],{maxBytes:b}));});
test('JSON rendering escapes bidi while preserving parsed data',()=>{const original={path:'folder\u202eINERT'};const rendered=safeJson(original,2);assert.ok(!rendered.includes('\u202e'));assert.deepEqual(JSON.parse(rendered),original);});
test('post-spawn errors retain tracking until the owned child closes',async()=>{
 let calls=0;const factory=()=>{const ch=new EventEmitter();Object.assign(ch,{pid:123,exitCode:null,signalCode:null,stdout:new PassThrough(),stderr:new PassThrough(),unref(){},kill(){calls++;this.exitCode=1;queueMicrotask(()=>this.emit('close',1,null));return true;}});queueMicrotask(()=>{ch.emit('spawn');ch.emit('error',new Error('synthetic post-spawn error'));});return ch;};
 const r=await bounded('inert',[],{spawnFn:factory});assert.equal(calls,1);assert.equal(r.status,'process_error');assert.equal(r.childCloseObserved,true);
});
test('unconfirmed close remains visible through the action result',async()=>{
 let calls=0;const factory=()=>{const ch=new EventEmitter();Object.assign(ch,{pid:123,exitCode:null,signalCode:null,stdout:new PassThrough(),stderr:new PassThrough(),unref(){},kill(){calls++;return false;}});queueMicrotask(()=>{ch.emit('spawn');ch.emit('error',new Error('synthetic post-spawn error'));});return ch;};
 const r=await runPlan({action:'auth-status',command:'inert',args:[],cwd:root,interactive:false},c,{spawnFn:factory});assert.equal(calls,2);assert.equal(r.childCloseObserved,false);assert.match(r.cleanup,/unconfirmed/);assert.equal(r.signedIn,null);
});
test('auth status and journal exclude provider raw credential-like output',async()=>{const p={action:'auth-status',command:process.execPath,args:['-e','console.log("API key DUMMY_TEST_ONLY_TOKEN_123")'],cwd:root,interactive:false};const r=await runPlan(p,c);assert.equal(r.signedIn,true);assert.equal(r.method,'API key');assert.ok(!JSON.stringify(r).includes('DUMMY_TEST'));const text=fs.readFileSync(path.join(c.state,'events',r.journal.id+'.json'),'utf8');assert.ok(!text.includes('DUMMY_TEST'));});
test('failed auth observation remains unknown',async()=>{const r=await runPlan({action:'auth-status',command:process.execPath,args:['-e','process.exit(9)'],cwd:root,interactive:false},c);assert.equal(r.signedIn,null);assert.equal(r.method,'unknown');});
test('invalid cloud provider response is not a successful list',async()=>{const r=await runPlan({action:'cloud-list',command:process.execPath,args:['-e','console.log("not json")'],cwd:root,interactive:false},c);assert.equal(r.status,'invalid_provider_json');});
test('journal failure does not fabricate execution failure',()=>{const f=path.join(root,'not-directory');fs.writeFileSync(f,'fixture');assert.equal(journal({...c,state:f},{action:'test',status:'ok'}).saved,false);});
test('unknown option is rejected with a machine-readable error',()=>{const hub=fileURLToPath(new URL('./hub.mjs',import.meta.url));const r=spawnSync(process.execPath,[hub,'doctor','--invented','--json'],{encoding:'utf8'});assert.equal(r.status,1);assert.equal(JSON.parse(r.stderr).status,'error');});
test('execute flag is required and failure is JSON',()=>{const hub=fileURLToPath(new URL('./hub.mjs',import.meta.url));const r=spawnSync(process.execPath,[hub,'run','auth-status','--json'],{encoding:'utf8',env:{...process.env,GHC_HUB_WORKSPACE:root,GHC_HUB_CODEX:process.execPath}});assert.equal(r.status,1);assert.ok(JSON.parse(r.stderr).message.includes('--execute'));});
test('no-tty menu fails promptly instead of looping',()=>{const hub=fileURLToPath(new URL('./hub.mjs',import.meta.url));const r=spawnSync(process.execPath,[hub,'menu','--json'],{encoding:'utf8',env:{...process.env,GHC_HUB_WORKSPACE:root},timeout:5000});assert.equal(r.status,1);assert.ok(JSON.parse(r.stderr).message.includes('terminal'));});
test('explicit executable override must be absolute',()=>{assert.throws(()=>context({...process.env,GHC_HUB_WORKSPACE:root,GHC_HUB_CODEX:'relative/codex'}),/absolute/);});
// The small test directory is kept for inspection; no user files are removed.
