import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {clean,uuid,plan,bounded,runPlan,journal,context} from './core.mjs';

const root=fs.mkdtempSync(path.join(process.env.GHC_HUB_TEST_TMP||os.tmpdir(),'ghc-hub-test-'));
const launcher=path.join(root,'admin.ps1');fs.writeFileSync(launcher,'# inert fixture\n');
const c={platform:'linux',cwd:root,state:path.join(root,'state'),codex:process.execPath,pwsh:process.execPath,bash:process.execPath,sudo:null,wsl:process.execPath,adminLauncher:launcher,node:process.execPath,uid:1000};
const valid='01a1053e-7707-7870-b87e-be0bf468e861';
test('session selector accepts exact UUID only',()=>{assert.ok(uuid(valid));for(const s of ['--last','other; echo X','../auth.json',valid+' extra',''])assert.equal(uuid(s),false);});
test('resume argv preserves the exact existing session and requests explicit controls',()=>{const p=plan('codex-resume',{session:valid},c);assert.deepEqual(p.args.slice(-2),['resume',valid]);assert.equal(p.shell,false);assert.ok(p.args.includes('danger-full-access'));assert.ok(p.args.includes('--no-daemon'));assert.equal(p.interactive,true);});
test('unsupported names cannot become executable commands',()=>{for(const s of ['sh -c','app; whoami','__proto__','constructor',''])assert.throws(()=>plan(s,{},c));});
test('missing or injected session refuses before launch',()=>{for(const s of [null,'--all','x && y'])assert.throws(()=>plan('codex-resume',{session:s},c));});
test('cloud environment validation keeps argv separate',()=>{assert.deepEqual(plan('cloud-list',{env:'env_123-a'},c).args.slice(-2),['--env','env_123-a']);for(const env of ['--env bad','a;b','$(bad)','a\nb'])assert.throws(()=>plan('cloud-list',{env},c));});
test('Windows app launch is unavailable on Linux',()=>assert.throws(()=>plan('app',{},c),/Windows/));
test('Windows app and app-check delegate to existing guard',()=>{const w={...c,platform:'win32'};assert.deepEqual(plan('app',{},w).args.slice(-3),[launcher,'-Target','Codex']);assert.equal(plan('app-check',{},w).args.at(-1),'-Check');});
test('Linux root request retains normal sudo boundary',()=>{assert.throws(()=>plan('linux-admin',{},c),/unavailable/);assert.deepEqual(plan('linux-admin',{}, {...c,sudo:'/usr/bin/sudo'}).args,['-i']);});
test('local Ubuntu request does not claim a remote cloud executor',()=>{const p=plan('linux',{}, {...c,platform:'win32'});assert.ok(p.note.includes('laptop RAM'));assert.ok(p.args.includes('Ubuntu'));});
test('terminal text cannot inject cursor or bidi controls',()=>{const s=clean('\x1b[2Jhello\r\n\u202eabc');assert.ok(!/[\x00-\x1f\u202e]/.test(s));assert.ok(s.includes('hello'));});
test('noninteractive terminal actions cannot silently open a new CLI session',async()=>{await assert.rejects(runPlan(plan('codex',{},c),c,{interactive:false}),/interactive terminal/);});
test('bounded child captures normal exit',async()=>{const r=await bounded(process.execPath,['-e','process.stdout.write("done")'],{cwd:root});assert.equal(r.status,'ok');assert.equal(r.exitCode,0);assert.equal(r.output,'done');});
test('bounded child preserves nonzero exit',async()=>{const r=await bounded(process.execPath,['-e','process.exit(7)'],{cwd:root});assert.equal(r.status,'failed');assert.equal(r.exitCode,7);});
test('missing executable never reports zero',async()=>{const r=await bounded(path.join(root,'missing'),[],{cwd:root});assert.equal(r.status,'spawn_error');assert.equal(r.exitCode,null);});
test('excess child output is bounded and not success',async()=>{const r=await bounded(process.execPath,['-e','process.stdout.write("x".repeat(100000));setInterval(()=>{},1000)'],{cwd:root,maxBytes:1000});assert.equal(r.status,'output_limit');assert.ok(Buffer.byteLength(r.output)<=1000);});
test('timed-out owned child is stopped even if TERM is ignored',async()=>{const r=await bounded(process.execPath,['-e','process.on("SIGTERM",()=>{});setInterval(()=>{},1000)'],{cwd:root,timeoutMs:250});assert.equal(r.status,'timeout');assert.ok(r.elapsedMs<10000);});
test('invalid timeout rejected before process creation',()=>{for(const t of [0,Infinity,NaN,60001,'1000'])assert.throws(()=>bounded('x',[],{timeoutMs:t}));});
test('auth status and journal exclude provider raw credential-like output',async()=>{const p={action:'auth-status',command:process.execPath,args:['-e','console.log("API key DUMMY_TEST_ONLY_TOKEN_123")'],cwd:root,interactive:false};const r=await runPlan(p,c);assert.equal(r.signedIn,true);assert.equal(r.method,'API key');assert.ok(!JSON.stringify(r).includes('DUMMY_TEST'));const text=fs.readFileSync(path.join(c.state,'events',r.journal.id+'.json'),'utf8');assert.ok(!text.includes('DUMMY_TEST'));});
test('failed auth observation remains unknown',async()=>{const r=await runPlan({action:'auth-status',command:process.execPath,args:['-e','process.exit(9)'],cwd:root,interactive:false},c);assert.equal(r.signedIn,null);assert.equal(r.method,'unknown');});
test('invalid cloud provider response is not a successful list',async()=>{const r=await runPlan({action:'cloud-list',command:process.execPath,args:['-e','console.log("not json")'],cwd:root,interactive:false},c);assert.equal(r.status,'invalid_provider_json');});
test('journal failure does not fabricate execution failure',()=>{const f=path.join(root,'not-directory');fs.writeFileSync(f,'fixture');assert.equal(journal({...c,state:f},{action:'test',status:'ok'}).saved,false);});
test('unknown option is rejected with a machine-readable error',()=>{const hub=fileURLToPath(new URL('./hub.mjs',import.meta.url));const r=spawnSync(process.execPath,[hub,'doctor','--invented','--json'],{encoding:'utf8'});assert.equal(r.status,1);assert.equal(JSON.parse(r.stderr).status,'error');});
test('execute flag is required and failure is JSON',()=>{const hub=fileURLToPath(new URL('./hub.mjs',import.meta.url));const r=spawnSync(process.execPath,[hub,'run','auth-status','--json'],{encoding:'utf8',env:{...process.env,GHC_HUB_WORKSPACE:root,GHC_HUB_CODEX:process.execPath}});assert.equal(r.status,1);assert.ok(JSON.parse(r.stderr).message.includes('--execute'));});
test('no-tty menu fails promptly instead of looping',()=>{const hub=fileURLToPath(new URL('./hub.mjs',import.meta.url));const r=spawnSync(process.execPath,[hub,'menu','--json'],{encoding:'utf8',env:{...process.env,GHC_HUB_WORKSPACE:root},timeout:5000});assert.equal(r.status,1);assert.ok(JSON.parse(r.stderr).message.includes('terminal'));});
test('explicit executable override must be absolute',()=>{assert.throws(()=>context({...process.env,GHC_HUB_WORKSPACE:root,GHC_HUB_CODEX:'relative/codex'}),/absolute/);});
// The small test directory is kept for inspection; no user files are removed.
