import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createNexusBindings} from './mcp-server.mjs';
import {writePrivate} from './private-store.mjs';
import {saveRegistry} from './chats.mjs';
import {createSession} from './mcp/adapter.mjs';
import {saveSentinel,sentinelTemplate} from './sentinel.mjs';

function setup(t){const base=path.resolve(process.platform==='win32'?'D:/GHC-Archives/phase-banks/ghc-nexus-tests':os.tmpdir());fs.mkdirSync(base,{recursive:true});const root=fs.mkdtempSync(path.join(base,'mcp-binding-'));t.after(()=>{const rel=path.relative(base,path.resolve(root));if(!rel||rel.startsWith('..')||path.isAbsolute(rel))throw new Error();fs.rmSync(root,{recursive:true,force:true});});const c={nexusHome:root,state:root,cwd:root,platform:process.platform,node:process.execPath,codex:process.execPath};const id='11111111-2222-3333-4444-555555555555';saveRegistry(c,[{id,title:'PRIVATE_TITLE_CANARY',kind:'codex-local',status:'idle',observedAt:'2026-10-06T00:00:00Z'}]);writePrivate(root,'mcp/selectors.json',{schema:'ghc.nexus.mcp-selectors.v1',chats:[{id,kind:'codex-local',alias:'reviewed-chat'}]});writePrivate(root,'personal/contact.json',{phone:'PERSONAL_CANARY',address:'ADDRESS_CANARY'});return c;}
test('MCP dispatcher projects real hub modules without human contacts or chat titles',async t=>{const c=setup(t),b=createNexusBindings(c);const results=[];for(const [name,args]of [['nexus.chats.list',{}],['nexus.chats.resolve',{alias:'reviewed-chat'}],['nexus.chats.plan',{alias:'reviewed-chat'}],['nexus.lab.catalogue',{}],['nexus.lab.plan',{alias:'diffusion'}],['nexus.identity.summary',{}],['nexus.remote.plan',{alias:'primary'}]])results.push(await b.dispatch(name,args));const wire=JSON.stringify(results);assert.ok(!wire.includes('CANARY'));assert.ok(!wire.includes('11111111'));assert.ok(!wire.includes(process.execPath));});
test('hidden contact changes do not change MCP output',async t=>{const c=setup(t),a=await createNexusBindings(c).dispatch('nexus.identity.summary',{});writePrivate(c.nexusHome,'personal/contact.json',{phone:'DIFFERENT_CANARY'},{replace:true});const b=await createNexusBindings(c).dispatch('nexus.identity.summary',{});assert.deepEqual(a,b);});
test('selector kind mismatch refuses before the server starts',t=>{const c=setup(t);writePrivate(c.nexusHome,'mcp/selectors.json',{schema:'ghc.nexus.mcp-selectors.v1',chats:[{id:'11111111-2222-3333-4444-555555555555',kind:'chatgpt',alias:'wrong-provider'}]},{replace:true});assert.throws(()=>createNexusBindings(c));});
test('all nine MCP tools accept the real read-only dispatcher',async t=>{const c=setup(t);saveSentinel(c,sentinelTemplate());const b=createNexusBindings(c),s=createSession(b);s.dispatch({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'fixture',version:'1'}}});s.dispatch({jsonrpc:'2.0',method:'notifications/initialized'});const tools=s.dispatch({jsonrpc:'2.0',id:2,method:'tools/list',params:{}}).result.tools;assert.equal(tools.length,9);let n=3;for(const tool of tools){const domain=tool.name.split('.')[1];const needs=tool.inputSchema.required?.includes('alias');const alias={chats:'reviewed-chat',lab:'diffusion',sentinel:'sentinel-1',remote:'primary'}[domain];const response=await s.dispatch({jsonrpc:'2.0',id:n++,method:'tools/call',params:{name:tool.name,arguments:needs?{alias}:{}}});assert.equal(response.result.isError,false,tool.name);}s.close();});
