import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {saveRegistry} from './chats.mjs';
import {writePrivate} from './private-store.mjs';
import {queueMessage,messageStatus,listMessages} from './messages.mjs';
import {createMessageRelay} from './message-relay.mjs';

function fixture(kind='codex-local'){
 const base=process.platform==='win32'?'D:/GHC-Archives/phase-banks/ghc-nexus-tests':os.tmpdir();fs.mkdirSync(base,{recursive:true});
 const home=fs.mkdtempSync(path.join(base,'relay-'));const c={nexusHome:home,platform:process.platform,hostId:'local'};
 const row={id:randomUUID(),title:'Synthetic selected chat',kind,hostId:kind==='chatgpt'?null:kind==='codex-managed'?'durable':'local',status:'idle',observedAt:new Date().toISOString()};
 saveRegistry(c,[row]);writePrivate(home,'mcp/selectors.json',{schema:'ghc.nexus.mcp-selectors.v1',chats:[{alias:'selected',id:row.id,kind}]});
 return {c,row,dispatch:createMessageRelay(c),draft:{requestId:randomUUID(),alias:'selected',body:'Synthetic delivery fixture; never transmitted.'}};
}
const call=(f,n,a)=>f.dispatch('nexus.messages.'+n,a);
test('draft and claim yield exact native arguments but cannot transmit a message',async()=>{const f=fixture();const p=await call(f,'prepare',f.draft);assert.equal(p.deliveryState,'queued');assert.equal(p.automaticDelivery,false);const r=await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256});assert.deepEqual(r.nativeAction.arguments,{threadId:f.row.id,hostId:'local',prompt:f.draft.body});assert.equal(r.deliveryState,'claimed_outcome_unknown');assert.equal((await call(f,'receipt',{requestId:p.requestId})).recipientCompletion,'not_observed');});
test('ChatGPT and managed Cloud retain their own native route bindings',async()=>{for(const kind of ['chatgpt','codex-managed']){const f=fixture(kind),p=await call(f,'prepare',f.draft),r=await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256});assert.equal(r.nativeAction.arguments.threadId,f.row.id);assert.equal(r.nativeAction.arguments.hostId,kind==='chatgpt'?undefined:'durable');}});
test('stale draft cannot be claimed until supported observation refresh',async()=>{const f=fixture();saveRegistry(f.c,[{...f.row,observedAt:new Date(Date.now()-600000).toISOString()}]);const p=await call(f,'prepare',f.draft);assert.equal((await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256})).status,'unverified');assert.equal(messageStatus(f.c,p.requestId).claim,null);});
test('new holds and host changes prevent claim',async()=>{for(const change of [{held:true},{hostId:'different'}]){const f=fixture(),p=await call(f,'prepare',f.draft);saveRegistry(f.c,[{...f.row,...change}]);if(change.held)assert.equal((await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256})).status,'held');else await assert.rejects(call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256}));assert.equal(messageStatus(f.c,p.requestId).claim,null);}});
test('unknown sender result prevents a second claim and preserves first receipt',async()=>{const f=fixture(),p=await call(f,'prepare',f.draft);await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256});const record={requestId:p.requestId,messageSha256:p.messageSha256,outcome:'unknown',deliveryReference:'synthetic-timeout'};assert.equal((await call(f,'record',record)).deliveryState,'unknown');assert.equal((await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256})).status,'held');await assert.rejects(call(f,'record',{...record,outcome:'accepted'}));});
test('same request ID is idempotent; changed text cannot replace it',async()=>{const f=fixture(),p=await call(f,'prepare',f.draft);assert.equal((await call(f,'prepare',f.draft)).messageSha256,p.messageSha256);await assert.rejects(call(f,'prepare',{...f.draft,body:'Different'}));});
test('unselected aliases and records never expose a native action',async()=>{const f=fixture();await assert.rejects(call(f,'prepare',{...f.draft,alias:'unselected'}));const other={...f.row,id:randomUUID(),title:'Unselected'};saveRegistry(f.c,[f.row,other]);const id=randomUUID();queueMessage(f.c,{requestId:id,toId:other.id,body:'Unselected private body'});await assert.rejects(call(f,'receipt',{requestId:id}));});
test('wrong digests, claimless receipts and extra caller fields are refused',async()=>{const f=fixture(),p=await call(f,'prepare',f.draft);await assert.rejects(call(f,'claim',{requestId:p.requestId,messageSha256:'0'.repeat(64)}));await assert.rejects(call(f,'record',{requestId:p.requestId,messageSha256:p.messageSha256,outcome:'accepted',deliveryReference:'synthetic'}));await assert.rejects(call(f,'prepare',{...f.draft,hostId:'other'}));});
test('MCP body bound rejects oversized new drafts and existing local drafts before claim',async()=>{const f=fixture();await assert.rejects(call(f,'prepare',{...f.draft,body:'x'.repeat(2049)}));const id=randomUUID(),p=queueMessage(f.c,{requestId:id,toId:f.row.id,body:'x'.repeat(3000)});await assert.rejects(call(f,'claim',{requestId:id,messageSha256:p.messageSha256}));assert.equal(messageStatus(f.c,id).claim,null);});
test('receipt read omits prompt and private target IDs while keeping evidence limits',async()=>{const f=fixture(),p=await call(f,'prepare',f.draft);await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256});await call(f,'record',{requestId:p.requestId,messageSha256:p.messageSha256,outcome:'accepted',deliveryReference:'synthetic-ack'});const r=await call(f,'receipt',{requestId:p.requestId});assert.equal(r.receipt.evidenceType,'caller-reported-native-tool-result');assert.equal(r.recipientCompletion,'not_observed');assert.ok(!JSON.stringify(r).includes(f.row.id));assert.ok(!JSON.stringify(r).includes(f.draft.body));});
test('route pages are bounded and never advertise a server sender',async()=>{const f=fixture();const rows=Array.from({length:128},(_,i)=>({...f.row,id:randomUUID(),title:'Synthetic '+i}));saveRegistry(f.c,rows);writePrivate(f.c.nexusHome,'mcp/selectors.json',{schema:'ghc.nexus.mcp-selectors.v1',chats:rows.map((r,i)=>({id:r.id,kind:r.kind,alias:'route-'+i}))},{replace:true});const dispatch=createMessageRelay(f.c),seen=[];let offset=0;do{const r=await dispatch('nexus.messages.routes',{offset});assert.ok(r.items.length<=16);assert.equal(r.serverSenderAvailable,false);seen.push(...r.items.map(x=>x.alias));offset=r.nextOffset;}while(offset!==null);assert.equal(new Set(seen).size,128);});
test('duplicate target aliases are refused before a draft can be saved',async()=>{const base=process.platform==='win32'?'D:/GHC-Archives/phase-banks/ghc-nexus-tests':os.tmpdir();fs.mkdirSync(base,{recursive:true});const home=fs.mkdtempSync(path.join(base,'duplicate-relay-'));const c={nexusHome:home,platform:process.platform,hostId:'local'},row={id:randomUUID(),title:'Synthetic duplicate target',kind:'codex-local',hostId:'local',status:'idle',observedAt:new Date().toISOString()};saveRegistry(c,[row]);writePrivate(home,'mcp/selectors.json',{schema:'ghc.nexus.mcp-selectors.v1',chats:[{alias:'selected',id:row.id,kind:row.kind},{alias:'synonym',id:row.id,kind:row.kind}]});assert.throws(()=>createMessageRelay(c),/Duplicate message target binding refused/);assert.equal(listMessages(c).messages.length,0,'a rejected duplicate-target configuration must not leave a saved draft');});

test('mixed-case receipt UUIDs remain canonical and readable after record and replay',async()=>{const f=fixture(),p=await call(f,'prepare',{...f.draft,requestId:f.draft.requestId.toUpperCase()});await call(f,'claim',{requestId:p.requestId.toUpperCase(),messageSha256:p.messageSha256});const r={requestId:p.requestId.toUpperCase(),messageSha256:p.messageSha256,outcome:'accepted',deliveryReference:'synthetic-case-test'};assert.equal((await call(f,'record',r)).deliveryState,'accepted');assert.equal((await call(f,'receipt',{requestId:p.requestId})).deliveryState,'accepted');assert.equal((await call(f,'record',{...r,requestId:p.requestId})).deliveryState,'accepted');assert.equal(messageStatus(f.c,p.requestId).receipt.requestId,p.requestId);});
test('ChatGPT host metadata is normalized before selection and persistent drafting',async()=>{const f=fixture('chatgpt');saveRegistry(f.c,[{...f.row,hostId:'local'}]);f.dispatch=createMessageRelay(f.c);const p=await call(f,'prepare',f.draft);assert.equal(p.deliveryState,'queued');const c=await call(f,'claim',{requestId:p.requestId,messageSha256:p.messageSha256});assert.equal(c.nativeAction.arguments.hostId,undefined);assert.equal(messageStatus(f.c,p.requestId).target.hostId,null);assert.equal(listMessages(f.c).messages.length,1);});

test('route capability labels honor status and host requirements before claiming',async()=>{for(const status of ['failed','unknown','running','completed']){const f=fixture();saveRegistry(f.c,[{...f.row,status}]);assert.equal((await call(f,'routes',{})).items[0].state,'refresh_required');}const f=fixture('codex-managed');saveRegistry(f.c,[{...f.row,hostId:null}]);f.dispatch=createMessageRelay(f.c);assert.equal((await call(f,'routes',{})).items[0].state,'host_binding_missing');assert.equal((await call(f,'prepare',f.draft)).reason,'host_binding_missing');assert.equal(listMessages(f.c).messages.length,0);});

test('a UUID shared across providers is labelled ambiguous before any draft write',async()=>{const f=fixture();saveRegistry(f.c,[f.row,{...f.row,kind:'chatgpt',hostId:null}]);f.dispatch=createMessageRelay(f.c);assert.equal((await call(f,'routes',{})).items[0].state,'ambiguous_target');await assert.rejects(call(f,'prepare',f.draft));assert.equal(listMessages(f.c).messages.length,0);});
