import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {randomUUID} from 'node:crypto';
import {saveRegistry,readRegistry} from './chats.mjs';
import {messagePlan,queueMessage,messageStatus,listMessages,claimMessage,recordMessageReceipt} from './messages.mjs';
import {validateCommandOptions} from './hub.mjs';

const testRoot=process.env.GHC_NEXUS_TEST_ARTIFACTS||(process.platform==='win32'?'D:/GHC-Archives/phase-banks/saelin-cmd-remaster-20261007/message-tests':path.join(os.tmpdir(),'ghc-message-tests'));
fs.mkdirSync(testRoot,{recursive:true});
function fixture(kind='codex-local'){
 const home=fs.mkdtempSync(path.join(testRoot,'message-'));
 const c={platform:process.platform,nexusHome:home,hostId:'local'};
 const entry={id:randomUUID(),kind,hostId:kind==='chatgpt'?null:kind==='codex-managed'?'durable':'local',title:'Fixture chat',status:'idle',observedAt:new Date().toISOString(),source:'synthetic native observation'};
 saveRegistry(c,[entry]);return {c,entry,raw:{requestId:randomUUID(),toId:entry.id,body:'Synthetic request only. No model is started.'}};
}
function receipt(f,overrides={}){const p=messageStatus(f.c,f.raw.requestId);return {requestId:f.raw.requestId,messageSha256:p.messageSha256,threadId:f.entry.id,hostId:f.entry.hostId,outcome:'accepted',tool:'mcp__codex_app__send_message_to_thread',deliveryReference:'synthetic-tool-1',...overrides};}
test('planning preserves exact local target and settings, without writes',()=>{const f=fixture();const p=messagePlan(f.c,f.raw);assert.equal(p.status,'ready');assert.deepEqual(Object.keys(p.nativeAction.arguments).sort(),['hostId','prompt','threadId']);assert.equal(p.automaticDelivery,false);assert.equal(listMessages(f.c).messages.length,0);});
test('ChatGPT route omits the Codex host argument',()=>{const f=fixture('chatgpt');const p=messagePlan(f.c,f.raw);assert.equal(p.target.hostId,null);assert.equal('hostId' in p.nativeAction.arguments,false);});
test('managed cloud keeps its actual host',()=>{const f=fixture('codex-managed');assert.equal(messagePlan(f.c,f.raw).nativeAction.arguments.hostId,'durable');});
test('held and unsupported remote records cannot be queued',()=>{const f=fixture();saveRegistry(f.c,[{...f.entry,held:true}]);assert.equal(queueMessage(f.c,f.raw).status,'held');const r=fixture('cli-remote');assert.equal(queueMessage(r.c,r.raw).status,'unavailable');});
test('stale, future and failed observations do not admit a message',()=>{for(const delta of [-300001,1000]){const f=fixture();saveRegistry(f.c,[{...f.entry,observedAt:new Date(Date.now()+delta).toISOString()}]);assert.equal(messagePlan(f.c,f.raw).status,'unverified');}const f=fixture();saveRegistry(f.c,[{...f.entry,status:'systemError'}]);assert.equal(messagePlan(f.c,f.raw).status,'unverified');});
test('active native chat is identified as active without starting a CLI',()=>{const f=fixture();saveRegistry(f.c,[{...f.entry,status:'active'}]);assert.equal(messagePlan(f.c,f.raw).providerStatus,'active');});
test('queue is idempotent by explicit request ID and rejects changed content',()=>{const f=fixture();assert.equal(queueMessage(f.c,f.raw).deliveryState,'queued');assert.equal(queueMessage(f.c,f.raw).alreadyQueued,true);assert.throws(()=>queueMessage(f.c,{...f.raw,body:'Changed content'}));assert.equal(listMessages(f.c).messages.length,1);});
test('claim is create-once and an unknown outcome cannot be retried',()=>{const f=fixture();queueMessage(f.c,f.raw);assert.equal(claimMessage(f.c,f.raw.requestId).status,'saved');assert.equal(claimMessage(f.c,f.raw.requestId).status,'held');assert.equal(messageStatus(f.c,f.raw.requestId).deliveryState,'claimed_outcome_unknown');});
test('renamed or newly held target is blocked at claim time',()=>{const f=fixture();queueMessage(f.c,f.raw);saveRegistry(f.c,[{...f.entry,title:'Changed name'}]);assert.throws(()=>claimMessage(f.c,f.raw.requestId));const g=fixture();queueMessage(g.c,g.raw);saveRegistry(g.c,[{...g.entry,held:true}]);assert.equal(claimMessage(g.c,g.raw.requestId).status,'held');});
test('receipt requires matching claim, target and digest',()=>{const f=fixture();queueMessage(f.c,f.raw);assert.throws(()=>recordMessageReceipt(f.c,receipt(f)));claimMessage(f.c,f.raw.requestId);assert.throws(()=>recordMessageReceipt(f.c,receipt(f,{threadId:randomUUID()})));assert.throws(()=>recordMessageReceipt(f.c,receipt(f,{messageSha256:'0'.repeat(64)})));assert.throws(()=>recordMessageReceipt(f.c,receipt(f,{hostId:'other'})));});
test('accepted receipt is immutable and does not attest completion',()=>{const f=fixture();queueMessage(f.c,f.raw);claimMessage(f.c,f.raw.requestId);const raw=receipt(f);assert.equal(recordMessageReceipt(f.c,raw).deliveryState,'accepted');assert.equal(recordMessageReceipt(f.c,raw).alreadyRecorded,true);assert.throws(()=>recordMessageReceipt(f.c,{...raw,outcome:'unknown'}));assert.equal(messageStatus(f.c,f.raw.requestId).recipientCompletion,'not_observed');});
test('unknown result stays unknown after a repeated queue',()=>{const f=fixture();queueMessage(f.c,f.raw);claimMessage(f.c,f.raw.requestId);recordMessageReceipt(f.c,receipt(f,{outcome:'unknown'}));assert.equal(queueMessage(f.c,f.raw).deliveryState,'unknown');assert.equal(claimMessage(f.c,f.raw.requestId).status,'held');});
test('control sequences, oversized inputs, traversal IDs and unexpected keys are rejected',()=>{const f=fixture();for(const patch of [{body:'\u001b[2J'},{body:'x'.repeat(16385)},{body:' '},{requestId:'../invalid'},{extra:true}])assert.throws(()=>messagePlan(f.c,{...f.raw,...patch}));});
test('listing omits message bodies, explicit show includes selected content',()=>{const f=fixture();queueMessage(f.c,f.raw);assert.equal('request' in listMessages(f.c).messages[0],false);assert.equal(messageStatus(f.c,f.raw.requestId,{includeBody:true}).request.body,f.raw.body);});
test('stored content tampering is detected before claim',()=>{const f=fixture();queueMessage(f.c,f.raw);const p=path.join(f.c.nexusHome,'messages','outbox',f.raw.requestId+'.json');const row=JSON.parse(fs.readFileSync(p));row.request.body+=' altered';fs.writeFileSync(p,JSON.stringify(row));assert.throws(()=>claimMessage(f.c,f.raw.requestId));});
test('message CLI rejects unrelated options and retains explicit execute boundary',()=>{assert.doesNotThrow(()=>validateCommandOptions('messages','queue',{file:'D:/request.json',execute:true,json:true}));assert.throws(()=>validateCommandOptions('messages','queue',{file:'D:/request.json',override:true}));assert.throws(()=>validateCommandOptions('messages','list',{file:'D:/request.json'}));});
test('explicit stale draft is saved but cannot be claimed until native observation refresh',()=>{const f=fixture();saveRegistry(f.c,[{...f.entry,observedAt:new Date(Date.now()-600000).toISOString()}]);const draft=queueMessage(f.c,f.raw,{draft:true});assert.equal(draft.status,'saved');assert.equal(draft.requiresFreshObservation,true);assert.equal(claimMessage(f.c,f.raw.requestId).status,'unverified');assert.equal(messageStatus(f.c,f.raw.requestId).claim,null);saveRegistry(f.c,[{...f.entry,observedAt:new Date().toISOString()}]);assert.equal(claimMessage(f.c,f.raw.requestId).status,'saved');});
test('draft option never releases a hold or supplies an unsupported destination route',()=>{const f=fixture();saveRegistry(f.c,[{...f.entry,held:true}]);assert.equal(queueMessage(f.c,f.raw,{draft:true}).status,'held');assert.equal(listMessages(f.c).messages.length,0);const r=fixture('cli-remote');assert.equal(queueMessage(r.c,r.raw,{draft:true}).status,'unavailable');});
