import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {appServerRead} from './app-server-client.mjs';
import {normalizeEntry,mergeEntries,chatPlan,admitChat,resolveChat,listChats,saveRegistry,localResumePickerPlan} from './chats.mjs';
import {checkPath,writePrivate,readPrivate} from './private-store.mjs';
import {profile,saveProfile,issueCertificate,verifyCertificate} from './identity.mjs';
import {saveMemory,exportMemory,readMemory} from './memory-bank.mjs';
import {sentinelTemplate,validateSentinel,sentinelPlan} from './sentinel.mjs';
import {simulate} from './lab-worker.mjs';
import {remoteConfig,remotePlan} from './remote.mjs';
import {nexusCommand} from './nexus.mjs';

const id='11111111-2222-3333-4444-555555555555';
const date=new Date().toISOString();
const row=(extra={})=>normalizeEntry({id,title:'Example',kind:'codex-local',status:'idle',...extra},'fixture',date);
function fixture(t){const base=path.resolve(process.platform==='win32'?'D:/GHC-Archives/phase-banks/ghc-nexus-tests':os.tmpdir());fs.mkdirSync(base,{recursive:true});const root=fs.mkdtempSync(path.join(base,'ghc-nexus-test-'));t.after(()=>{const relative=path.relative(base,path.resolve(root));if(!relative||relative.startsWith('..')||path.isAbsolute(relative))throw new Error('Test cleanup escaped its root');fs.rmSync(root,{recursive:true,force:true});});return {nexusHome:root,state:root,cwd:root,platform:process.platform,codex:process.execPath,node:process.execPath,pwsh:null};}
test('chat kinds cannot silently fall back to local execution',()=>assert.throws(()=>normalizeEntry({id,kind:'unknown-provider'},'x',date)));
test('local resume preserves model and permission flags',()=>{const p=chatPlan(row(),{codex:'C:/codex.exe',cwd:'D:/lab'});assert.deepEqual(p.args,['--no-daemon','--no-alt-screen','resume',id]);assert.equal(p.preservesModelAndSettings,true);});
test('a fresh unloaded local record can ask the official CLI to acquire its lock',()=>{const p=chatPlan(row({status:'notLoaded'}),{codex:'C:/codex.exe',cwd:'D:/lab'});assert.equal(p.status,'ready');assert.equal(p.providerStatus,'notLoaded');assert.equal(p.executionGate,'official_cli_session_lock');assert.deepEqual(p.args,['--no-daemon','--no-alt-screen','resume',id]);});
test('stale unloaded, unknown and held records cannot bypass admission',()=>{const c={codex:'C:/codex.exe',cwd:'D:/lab'};const stale={...row({status:'notLoaded'}),observedAt:new Date(Date.now()-360000).toISOString()};assert.equal(chatPlan(stale,c).status,'unverified');assert.equal(chatPlan(row({status:'unknown'}),c).status,'unverified');assert.equal(chatPlan(row({status:'notLoaded',held:true}),c).status,'held');});
test('hub refuses an existing-chat override; provider model controls remain separate',()=>assert.throws(()=>chatPlan(row(),{codex:'C:/codex.exe',cwd:'D:/lab'},{override:true}),/inherited/));
test('held original record cannot produce a launch',()=>{assert.equal(chatPlan(row({held:true}),{}).status,'held');});
test('official all-session picker cannot bypass a saved local hold',t=>{const c=fixture(t);saveRegistry(c,[row({held:true})]);const p=localResumePickerPlan(c);assert.equal(p.status,'held');assert.equal(p.command,undefined);});
test('held cloud records do not disable an unrelated local picker',t=>{const c=fixture(t);saveRegistry(c,[row({held:true,kind:'codex-managed',hostId:'durable'})]);assert.equal(localResumePickerPlan(c).status,'ready');});
test('active and conflicting observations cannot resume',()=>{const merged=mergeEntries([[row({status:'active'})],[row({status:'idle'})]]);assert.equal(chatPlan(merged[0],{}).status,'busy');});
test('same provider and ID deduplicate while different providers remain distinct',()=>{const rows=mergeEntries([[row(),row({kind:'chatgpt'})],[row()]]);assert.equal(rows.length,2);assert.throws(()=>resolveChat(rows,id),/Ambiguous/);});
test('managed cloud remains a native route rather than a local resume',()=>{const p=chatPlan(row({kind:'codex-managed',hostId:'durable'}),{});assert.equal(p.status,'native-route');assert.equal(p.command,undefined);});
test('unknown or malformed IDs fail before command construction',()=>{for(const bad of ['../foo','-oProxyCommand=bad','\u001b[2J'])assert.throws(()=>row({id:bad}));});
test('terminal controls are removed from titles',()=>assert.ok(!row({title:'x\u001b[2J\u202Eabc'}).title.includes('\u001b')));
test('saved chat list does not invoke providers',async t=>{const c=fixture(t);saveRegistry(c,[row()]);let calls=0;const r=await listChats(c,{read:async()=>{calls++;}});assert.equal(calls,0);assert.equal(r.total,1);});
test('failed live adapters preserve saved rows and report the gap',async t=>{const c=fixture(t);saveRegistry(c,[row()]);const r=await listChats(c,{refresh:true,read:async()=>({status:'unavailable',reason:'timeout'}),run:async()=>({status:'failed'})});assert.equal(r.total,1);assert.equal(r.observations[0].reason,'timeout');});
test('newer catalogue busy state wins over a pending idle provider response',async t=>{const c=fixture(t),selected=row();saveRegistry(c,[selected]);const result=await admitChat(c,selected,{read:async()=>{saveRegistry(c,[row({status:'running',reportedActive:true})]);return {status:'ok',data:{thread:{id,status:{type:'idle'}}}};}});assert.equal(result.status,'busy');});
test('unchanged cached activity explains the required refresh without claiming a race',async t=>{const c=fixture(t),selected=row({status:'active'});saveRegistry(c,[selected]);const result=await admitChat(c,selected,{read:async()=>({status:'ok',data:{thread:{id,status:{type:'idle'}}}})});assert.equal(result.status,'busy');assert.equal(result.reason,'cached_catalogue_activity_requires_refresh');assert.match(result.nextStep,/chats list --refresh/);});
test('private path rejects traversal, absolute paths and empty segments',t=>{const c=fixture(t);for(const p of ['../x','a/../b','a//b',path.resolve(c.cwd,'outside')])assert.throws(()=>checkPath(c.cwd,p));});
test('private write is exclusive unless an explicit replacement is requested',t=>{const c=fixture(t);writePrivate(c.cwd,'x/a.json',{v:1});assert.throws(()=>writePrivate(c.cwd,'x/a.json',{v:2}));assert.equal(readPrivate(c.cwd,'x/a.json').v,1);});
test('hard-linked private records are rejected',t=>{const c=fixture(t);writePrivate(c.cwd,'x/a.json',{v:1});fs.linkSync(path.join(c.cwd,'x/a.json'),path.join(c.cwd,'alias.json'));assert.throws(()=>readPrivate(c.cwd,'x/a.json'));});
test('human contact fields are rejected from profiles',()=>{for(const key of ['address','homeAddress','birthDate','phone','email','password','token','apiKey'])assert.throws(()=>profile({id:'test',name:'Test',[key]:'private-canary'}));});
test('unverified capabilities stay unverified and age is not inferred',()=>{const p=profile({id:'test',name:'Test',age:30,capabilities:[{claim:'root everywhere',state:'verified'}]});assert.equal(p.age,null);assert.equal(p.capabilities[0].state,'unverified');});
test('certificate integrity and separately pinned issuer trust',t=>{const c=fixture(t);saveProfile(c,{id:'test',name:'Test'});issueCertificate(c,'test');const cert=readPrivate(c.cwd,'certificates/test.json');assert.equal(verifyCertificate(cert).signatureValid,true);assert.equal(verifyCertificate(cert).issuerTrusted,false);assert.equal(verifyCertificate(cert,cert.issuerFingerprint).issuerTrusted,true);cert.profile.name='Tampered';assert.equal(verifyCertificate(cert).signatureValid,false);});
test('private memory export is denied without weakening the record',t=>{const c=fixture(t);saveMemory(c,{id:'private',classification:'private',body:'private-canary'});assert.throws(()=>exportMemory(c,['private']));assert.equal(readMemory(c,'private').body,'private-canary');});
test('shareable memory exports only named records',t=>{const c=fixture(t);saveMemory(c,{id:'public-note',classification:'shareable',body:'selected'});saveMemory(c,{id:'private',classification:'private',body:'private-canary'});const r=exportMemory(c,['public-note']);assert.ok(!fs.readFileSync(r.path,'utf8').includes('private-canary'));});
test('known credential-shaped values do not enter memory',t=>{const c=fixture(t);assert.throws(()=>saveMemory(c,{id:'secret',classification:'private',body:'{"access_token":"example"}'}));});
test('Sentinel template validates as an offline agent design',()=>{const s=sentinelTemplate();assert.equal(validateSentinel(s).valid,true);assert.equal(sentinelPlan(s).liveActions,0);});
test('Sentinel rejects unsupported execution and unbounded spending',()=>{for(const mutate of [s=>s.deployment.enabled=true,s=>s.budget.maxUsd=51,s=>s.tools.push('shell.arbitrary'),s=>s.memory.automaticExport=true]){const s=sentinelTemplate();mutate(s);assert.equal(validateSentinel(s).valid,false);}});
test('diffusion converges to the independent uniform equilibrium',()=>{const r=simulate('diffusion',5000);assert.equal(r.passed,true);assert.ok(Math.abs(r.observation.energy-1/32)<1e-10);});
test('queue known finite schedule has bounded waiting',()=>{const r=simulate('queue',6);assert.equal(r.observation.lastCompletion,19);assert.equal(r.observation.totalWait,4);assert.equal(r.passed,true);});
test('consent one complete 385-state cycle partitions every case',()=>{const r=simulate('consent',385);assert.equal(r.observation.allowed,84);assert.equal(r.observation.denied,301);});
test('laboratory size limit rejects unbounded requests',()=>assert.throws(()=>simulate('diffusion',200001)));
test('SSH aliases cannot inject options or shell fragments',()=>{for(const alias of ['-oProxyCommand=x','host;echo bad','a b'])assert.throws(()=>remoteConfig({id:'host',kind:'ssh',alias}));});
test('unconfigured remote terminal does not silently start a process',t=>assert.equal(remotePlan(fixture(t)).status,'setup_required'));
test('write operations require explicit execution',async t=>await assert.rejects(()=>nexusCommand('memory','add',{},fixture(t)),/--execute/));
test('app-server metadata refuses mutation methods',()=>assert.throws(()=>appServerRead({},'turn/start',{})));
test('app-server initialization and split UTF-8 response',async()=>{
 const child=new EventEmitter();child.stdin=new PassThrough();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>true;child.unref=()=>{};let requests='';
 child.stdin.on('data',d=>{requests+=d.toString();for(const line of d.toString().trim().split('\n')){const m=JSON.parse(line);if(m.id===1)queueMicrotask(()=>child.stdout.write(JSON.stringify({id:1,result:{}})+'\n'));if(m.id===2){const b=Buffer.from(JSON.stringify({id:2,result:{data:[{name:'Māori'}],nextCursor:null}})+'\n');const i=b.indexOf(Buffer.from('ā'))+1;queueMicrotask(()=>{child.stdout.write(b.subarray(0,i));child.stdout.write(b.subarray(i));});}}});
 child.stdin.on('finish',()=>queueMicrotask(()=>child.emit('close',0,null)));
 const result=appServerRead({codex:'test',cwd:'.'},'thread/list',{limit:10,archived:false,sortKey:'updated_at',sourceKinds:['cli'],useStateDbOnly:true}, {spawnFn:()=>{queueMicrotask(()=>child.emit('spawn'));return child;},timeoutMs:1000});
 const r=await result;assert.equal(r.status,'ok');assert.equal(r.data.data[0].name,'Māori');assert.equal(r.childCloseObserved,true);assert.ok(!requests.includes('turn/start'));
});
test('metadata reader waits for asynchronous close after terminating its owned child',async()=>{
 const child=new EventEmitter();child.stdin=new PassThrough();child.stdout=new PassThrough();child.stderr=new PassThrough();let kills=0;child.unref=()=>{};
 child.kill=()=>{kills++;setTimeout(()=>child.emit('close',null,'SIGKILL'),25);return true;};
 child.stdin.on('data',d=>{for(const line of d.toString().trim().split('\n')){const m=JSON.parse(line);if(m.id===1)queueMicrotask(()=>child.stdout.write(JSON.stringify({id:1,result:{}})+'\n'));if(m.id===2)queueMicrotask(()=>child.stdout.write(JSON.stringify({id:2,result:{thread:{id,status:{type:'notLoaded'}}}})+'\n'));}});
 const result=await appServerRead({codex:'fixture',cwd:'.'},'thread/read',{threadId:id,includeTurns:false},{spawnFn:()=>{queueMicrotask(()=>child.emit('spawn'));return child;},timeoutMs:10000});
 assert.equal(kills,1);assert.equal(result.status,'ok');assert.equal(result.childCloseObserved,true);assert.equal(result.diagnostics.cleanupErrors,0);
});
