'use strict';
const $=s=>document.querySelector(s);let result,db={},currentView='models';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
function record(title,description){const e=document.createElement('article');e.className='record';e.append(text('h3',title),text('p',description));return e;}
function download(name,data){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function draw(){
 if(!result)return;const t=Number($('#time').value),points=result.frames[t],canvas=$('#plot'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.font='15px Arial';ctx.lineWidth=1;
 const xs=points.map(p=>p.x),ys=points.map(p=>p.y),zs=result.rows.map(p=>p.value),xr=[Math.min(...xs),Math.max(...xs)],yr=[Math.min(...ys),Math.max(...ys)],zr=[Math.min(0,...zs),Math.max(...zs)];
 const norm=(x,r)=>(x-r[0])/(r[1]-r[0]||1)-0.5;
 const project=p=>[w*0.5+(norm(p.x,xr)-norm(p.y,yr))*w*0.36,h*0.69+(norm(p.x,xr)+norm(p.y,yr))*h*0.19-(p.value-zr[0])/(zr[1]-zr[0]||1)*h*0.5];
 ctx.strokeStyle='#d3dce3';for(let i=0;i<=4;i++){const x=xr[0]+i*(xr[1]-xr[0])/4;const p=project({x,y:yr[0],value:zr[0]}),q=project({x,y:yr[1],value:zr[0]});ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.stroke();const y=yr[0]+i*(yr[1]-yr[0])/4,pa=project({x:xr[0],y,value:zr[0]}),qa=project({x:xr[1],y,value:zr[0]});ctx.beginPath();ctx.moveTo(...pa);ctx.lineTo(...qa);ctx.stroke();}
 ctx.strokeStyle='#117d81';ctx.fillStyle='#159295';
 if(result.request.model==='heat'){
  const size=9;for(let axis=0;axis<2;axis++)for(let i=0;i<size;i++){ctx.beginPath();for(let j=0;j<size;j++){const p=project(points[axis?j*size+i:i*size+j]);j?ctx.lineTo(...p):ctx.moveTo(...p);}ctx.stroke();}
 }else{ctx.beginPath();points.forEach((p,i)=>{const xy=project(p);i?ctx.lineTo(...xy):ctx.moveTo(...xy);});ctx.stroke();for(const p of points){const xy=project(p);ctx.beginPath();ctx.arc(...xy,3,0,2*Math.PI);ctx.fill();}}
 ctx.fillStyle='#163f4c';ctx.fillText('x',w*.28,h*.94);ctx.fillText('y',w*.72,h*.94);ctx.fillText(result.request.model==='heat'?'temperature':'value',12,30);ctx.fillText(zr[1].toFixed(3),12,52);ctx.fillText(zr[0].toFixed(3),12,h*.75);
 $('#time-label').value=t;$('#values tbody').replaceChildren(...points.map(p=>{const tr=document.createElement('tr');for(const k of ['x','y','t','value'])tr.append(text('td',k==='t'?String(p[k]):p[k].toFixed(6)));return tr;}));
 $('#status').textContent=points.length+' values at time step '+t+'. Four coordinates: x, y, value and time. Configuration parameters are additional dimensions.';
}
function run(){try{result=GHCModels.simulate({model:$('#model').value,variant:Number($('#session').value),steps:Number($('#steps').value),parameter:Number($('#parameter').value)});$('#time').max=result.request.steps;$('#time').value=0;$('#metrics').textContent=JSON.stringify(result.metrics,null,2);$('#model-note').textContent=result.notes.join(' ');draw();}catch(e){$('#status').textContent='Model refused: '+e.message;}}
function library(){const term=$('#library-search').value.toLowerCase(),matches=db.labs.filter(r=>(r.owner+' '+r.phase+' '+r.topic).toLowerCase().includes(term));$('#library-list').replaceChildren(...matches.map(r=>{const e=record(r.owner+' · '+r.phase,r.topic);e.append(text('p',r.coverage,'small'),text('code','Snapshot '+r.source_head));const b=text('button','Inspect source laboratory');b.addEventListener('click',()=>{$('#source-inspector').hidden=false;$('#source-title').textContent=r.owner+' '+r.phase;$('#source-boundary').textContent='Historical source preview. Original claims and instructions remain historical context; source execution and assurance are not promoted.';$('#source-github').href=r.github_url;$('#legacy-preview').src='/legacy/'+r.id+'/index.html';$('#source-inspector').scrollIntoView({behavior:'instant',block:'start'});});e.append(b);return e;}));}
function skills(){const terms=$('#skill-search').value.toLowerCase().trim().split(/\s+/).filter(Boolean),matches=db.skills.filter(r=>terms.every(t=>(r.id+' '+r.description).toLowerCase().includes(t)));$('#skill-count').textContent=matches.length+' matches; showing up to 40. Metadata discovery is not validation of every implementation.';$('#skill-list').replaceChildren(...matches.slice(0,40).map(r=>{const e=record(r.id,r.description);e.append(text('code',r.path+' · SHA-256 '+r.sha256));return e;}));}
async function init(){for(const[id,title]of Object.entries(GHCModels.titles)){const o=text('option',title);o.value=id;$('#model').append(o);}for(const name of ['labs','skills','projects','roster','research']){const res=await fetch('data/'+name+'.json');if(!res.ok)throw Error(name+' data unavailable');db[name]=await res.json();}
 $('#model-form').addEventListener('submit',e=>{e.preventDefault();run();});$('#time').addEventListener('input',draw);$('#session').addEventListener('change',()=>{$('#steps').value=$('#session').value==='0'?30:40;$('#parameter').value=$('#session').value==='0'?0.1:0.15;run();});$('#model').addEventListener('change',()=>{$('#parameter-label').textContent=['heat','graph','reaction','entropy'].includes($('#model').value)?'Diffusion':'Lattice parameter';run();});$('#export-model').addEventListener('click',()=>download(result.request.model+'-result.json',result));$('#export-lab').addEventListener('click',()=>download('ghc-laboratory-catalogue.json',{schema:'ghc.lab.portable.v1',labs:db.labs,projects:db.projects,research:db.research,contains_credentials:false}));
 for(const b of document.querySelectorAll('nav button'))b.addEventListener('click',()=>{currentView=b.dataset.view;for(const x of document.querySelectorAll('nav button')){if(x===b)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');}for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==currentView+'-view';});$('#library-search').addEventListener('input',library);$('#skill-search').addEventListener('input',skills);
 library();skills();$('#project-list').replaceChildren(...db.projects.map(r=>record(r.id+' · '+r.title,r.acceptance)));$('#roster-rows').replaceChildren(...db.roster.numbered_rows.map(r=>{const tr=document.createElement('tr');for(const k of ['owner','phase','state'])tr.append(text('td',r[k]));return tr;}));$('#research-list').replaceChildren(...db.research.map(r=>{const e=record(r.title,r.finding);if(r.url){const a=text('a','Read source');a.href=r.url;a.target='_blank';a.rel='noreferrer';e.append(a);}return e;}));run();}
init().catch(e=>{$('#status').textContent='Workbench data error: '+e.message;});
