from pathlib import Path
import json,hashlib,datetime
ROOT=Path(__file__).resolve().parents[3];DATA=ROOT/'laboratory/data';BASE=Path(__file__).resolve().parent
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
rows=[
('heat',['lattice x','lattice y','temperature'],['grid index','grid index','dimensionless'],'Periodic 9 by 9 lattice, explicit nearest-neighbour update; coefficient 0..0.25.','Mass stays at initial mass; values stay between initial extrema.','1e-9 mass; 1e-12 extrema','A boundary leak or unstable coefficient defeats this invariant.'),
('wave',['site','zero plane','displacement'],['grid index','dimensionless','dimensionless'],'Periodic 16-site wave; zero initial velocity; Courant 0.5 or 0.6.','Mean displacement stays zero and declared finite trace remains bounded.','1e-9 mean; finite amplitude <1.2','A high Courant number can make an explicit wave scheme unstable.'),
('oscillator',['position','momentum','energy'],['dimensionless','dimensionless','dimensionless'],'Unit spring and mass, dt 0.05, positive damping.','Energy stays below 0.53 for the declared trace.','Energy bound includes discretization drift.','Removing the step-size or damping restriction invalidates this bound.'),
('reaction',['site','growth rate','concentration'],['grid index','per step','dimensionless'],'Logistic reaction with periodic diffusion and nonnegative initial concentration.','Concentration remains in [0,1] for declared coefficients.','1e-12 boundary','Unbounded growth or an unstable discretization may overshoot.'),
('entropy',['state index','Shannon entropy','probability'],['index','bits','dimensionless'],'Three-state doubly stochastic mixing, no empirical observations.','Mass 1; entropy does not decrease.','1e-9 mass; 1e-12 entropy','A reset channel can lower entropy and is outside the stated condition.'),
('queue',['arrivals','served','backlog'],['items per step','items per step','items'],'Deterministic arrival pattern and fixed service capacity.','Cumulative arrivals minus service equals backlog.','Exact integer arithmetic','Dropping a queued item without an explicit loss term breaks conservation.'),
('replication',['version A','version B','concurrency flag'],['counter','counter','Boolean 0 or 1'],'Two synthetic version vectors with periodic componentwise-max merge.','Counters never decrease; incomparable histories remain detectable.','Exact integer arithmetic','Last-write-wins alone hides a concurrent history.'),
('retry',['attempt count','expected attempts','remaining failure probability'],['count','expected count','dimensionless'],'Independent constant success probability and a fixed cap.','Capped geometric closed form; no retry after acknowledgement.','1e-9 expectation','Correlated failures invalidate the geometric assumption.'),
('graph',['ring x','ring y','node mass'],['layout coordinate','layout coordinate','dimensionless'],'Undirected ring and a conservative mixing kernel.','Total mass remains 1.','1e-9','A directed or leaking operator needs a different conservation contract.'),
('coding',['word','error mask','detection flag'],['binary integer','binary integer','Boolean 0 or 1'],'Parity on 4 or 5 data bits; exact enumerated masks.','Odd-weight errors detected; even-weight errors can be missed.','Exact integer arithmetic','Mask 3 is a retained two-bit-error counterexample.'),
('consent',['expiry','withdrawal step','access allowed'],['step index','step index','Boolean 0 or 1'],'One synthetic subject, read scope, strict expiry boundary.','No access at or after expiry or withdrawal.','Exact integer arithmetic','A cached grant without expiry or withdrawal checking fails.'),
('allocation',['claimant index','declared demand','allocation'],['index','synthetic units','synthetic units'],'Equal-weight max-min allocation with public synthetic demands.','No demand exceeded; capacity conserved up to total demand.','1e-9','Changing weights or deservingness cannot be inferred from this model.'),
('voting',['candidate i','candidate j','pairwise margin'],['index','index','votes'],'Three declared preference orders; no real electorate.','First profile cycles; second has candidate 0 as Condorcet winner.','Exact integer arithmetic','Pairwise majority need not produce a transitive ranking.'),
('bayes',['posterior alpha','posterior beta','posterior mean'],['pseudo-count','pseudo-count','probability'],'Synthetic Bernoulli sequence with declared beta prior.','Closed-form conjugate update matches counts.','1e-9','Dependent or selected observations require a different likelihood.'),
('remedy',['record count','original failure count','correction count'],['count','count','count'],'Append-only correction chain with a preserved failed original.','Original failure survives every correction with zero original success credit.','Exact integer arithmetic','Overwriting the original destroys this property.')]
contracts=[{'schema':'ghc.model.contract.v2','model':m,'quantities':dict(zip(['x','y','value'],q)),'units':dict(zip(['x','y','value'],u)),'time':{'quantity':'simulation step','unit':'step index','physical_seconds_claim':False},'assumptions':a,'expected_baseline':b,'tolerance':t,'falsifier':f,'supersedes':'docs/avelin-reed/v707-v6-r2/model-definitions.json#'+m,'evidence':'synthetic; no independent reproduction or empirical confirmation'} for m,q,u,a,b,t,f in rows]
save(DATA/'model-contracts.json',contracts)
labs=load(DATA/'labs.json')
for r in labs:
 r.update({'schema':'ghc.lab.source-summary.v1','inputs':{'kind':'source_artifact_references','paths':[a['path'] for a in r['artifacts']]},'result':{'kind':'historical_overview_summary','original_individual_result_status':'not_imported_by_this_summary'},'checks':['committed artifact located','raw selected artifact digest recorded'],'limitations':['A source catalogue entry does not independently reproduce its results.','See the exact source for original outcomes and gaps.'],'superseded_record_links':[]})
save(DATA/'labs.json',labs)
skills=load(DATA/'skills.json')
for r in skills:r['capability_states']={'catalogued':True,'locally_tested':'not_observed_in_this_run','installed':'source_file_present_at_snapshot','host_observed':False}
save(DATA/'skills.json',skills)
roster=load(DATA/'roster.json')
roster['sibling_records']=[{'name':name,'model_configuration_label':'not_read_or_changed','last_observed_session_status':'not_observed','status_observation_time':None,'scheduled_turns':[r['phase'] for r in roster['numbered_rows'] if r['owner']==name]} for name in sorted(set(roster['cycle']))]
save(DATA/'roster.json',roster)
save(BASE/'review-adaptive-plan.json',{'authority':'Hamish direct steering to apply the Review and refine GHC Lab advice','defined_before_execution':['intake source and negative checks','model-specific contracts','roster activity separation','capability-state separation'],'intake_tests':8,'intake_domain_completion_credit':0,'frozen_prior_definitions_preserved':True,'source_summary_schema':'ghc.lab.source-summary.v1','model_contract_count':len(contracts),'sibling_record_count':len(roster['sibling_records'])})
print(json.dumps({'specific_model_contracts':len(contracts),'source_summaries':len(labs),'capability_state_records':len(skills),'sibling_records':len(roster['sibling_records'])}))
