#!/usr/bin/env python3
"""Assemble the v648-v7 closeout candidate before the single canonical pass."""

import json, re, subprocess, sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; PHASE=ROOT/'docs/tamar-vey/v648-v7'; sys.path.insert(0,str(ROOT/'scripts'))
import ghc_family_v648_v7_x2_state as x2
from build_ghc_family_v648_v7_evidence import git, privacy, status_paths, write

def load(p): return json.loads((PHASE/p).read_text(encoding='utf-8'))
def text(p,s):
    q=PHASE/p; q.parent.mkdir(parents=True,exist_ok=True); q.write_text(s.rstrip()+'\n',encoding='utf-8',newline='\n')

def overview():
    return '''# Tamar Vey v648-v7 integrated overview

## Scope, lineage, and identity boundary

Tamar Vey worked as a relational evidence-systems cartographer and boundary keeper, using they/them pronouns and hoping to keep decisions legible, failures recoverable, and authority boundaries intact. This language is a collaboration aid only. It is not evidence of consciousness, sentience, personhood, continuity, employment, qualification, scientific standing, operational authority, legal authority, cultural authority, or independent agency. Hamish retains the right to rename, pause, redirect, or stop the route.

The phase began from Orin Thale's exact clean v648-v6 head. Source, x1, evidence, and final anchors were reverified from Git objects before mutation. Tamar's existing D-first lane advanced by fast-forward only, was pushed, and reached exact local, upstream, tracking, and fresh-live equality before x1. The dedicated x1 commit then froze exactly ten proposals after lexical and manual semantic review against all 620 inherited proposals. It contained no x2 implementation and no observed outcome. The cumulative frozen count became 630. X1 was committed, pushed, clean, and four-way equal before x2 began.

## Proposal truth

Six proposals completed only their declared bounded software, symbolic, structural, or formal hypotheses. Two remain represented through synthetic proxies. One remains an open gap. One remains an exact gate. These four labels are the complete outcome vocabulary: completed, represented, open_gap, and exact_gate. No clean software result is promoted into empirical, participant, production, professional, legal, cultural, accessibility-complete, security-complete, or independent-reproduction evidence.

The Method Flow retry tribunal completed on owner-scoped fixtures. It checked Retry-After interpretation, capped backoff, jitter, idempotency keys, circuit state, dead-letter handling, and evidence credit. It rejected unbounded retry, duplicate credit, and automatic external side effects. Completion means only that the declared bounded control accepted its positive fixture and rejected its mutations. It does not establish production orchestration reliability or permission to repeat an external action.

The GMUT Reeh-Schlieder obligation board completed as typed symbolic and mutation evidence. It preserves local-algebra scope, the vacuum domain, cyclicity, separating obligations, spacelike-complement reasoning, spectrum conditions, gauge scope, effective-field-theory scope, dimensions, and an observation firewall. It establishes no physical state, force, likelihood, prediction, parameter constraint, stability theorem, empirical confirmation, ultraviolet completion, quantum completion, or Theory of Everything. GMUT remains a typed scalar-tensor and effective-field-theory research-model family.

The official TESS and MAST product adapter remains open_gap. Public documentation supplied schema, provenance, cadence, quality, time-system, flux, uncertainty, crowding, and dilution obligations only. The phase downloaded zero products, ingested zero real rows, evaluated zero likelihoods, drew zero posterior samples, emitted zero constraints, and made zero empirical GMUT claim. A citation is not an observation. Real analysis still requires frozen product selection, checksums, calibration and quality handling, covariance and nuisance treatment, a preregistered likelihood, uncertainty analysis, and appropriate independent review.

The THOS postal-depot protocol remains represented. Synthetic traces cover registered-item identity, scan lineage, mis-sort quarantine, damage hold, address minimization, reroute authority, accessible notice, workload budget, incident recording, and shift handover. There were zero real workers, items, addresses, depots, incidents, blind matched-budget arms, safety-monitoring events, operational decisions, or effectiveness estimates. Postal workflow language is a bounded learning lens, not employment, competence, delivery authority, privacy authority, investigation authority, or operational advice. THOS remains proxy without real preregistered arms and independent review.

The Freed ID SCIM profile remains represented and nonproduction. Synthetic vectors exercise schema identifiers, resource types, mutability, returned characteristics, uniqueness, PATCH paths, version and entity-tag handling, bulk and filter budgets, and minimization. There were zero real keys, credentials, live servers, accounts, provisioning events, resolutions, status or revocation events, interoperability events, privacy reviews, independent security reviews, recovery decisions, or trust-governance decisions. Structural conformance does not prove identity, authenticate a person, confer trust, or establish production assurance.

The CBR postal loss, misdirection, household address privacy, accessible notice, remedy, place-name stewardship, data governance, decision-right, and Māori-authority matrix remains exact_gate. Repository software made no real delivery, disclosure, remedy, legal, cultural, data-governance, or authority decision. Affected people, competent authorities, tangata whenua, iwi, hapū, and Māori authorities retain the relevant decision rights. Māori concepts remain under Māori authority. No task title, branch, skill, citation, synthetic fixture, or relational role can confer those rights.

The EBML tribunal completed on disposable synthetic byte fixtures. It checks variable-length identifiers and sizes, unknown-size handling, element order, nesting depth, declared lengths, checksums, resource ceilings, and refusal of external references. Completion does not establish a production decoder, general media safety, supply-chain assurance, privacy completeness, or exhaustive security. It touched no user media and performed no external retrieval.

The accessible-combobox audit completed structurally. It checks accessible naming, input value, popup role, expanded state, active option, keyboard opening, escape behavior, focus return, status, and non-colour cues. It does not establish complete accessibility conformance. Manual keyboard work, responsive layout, browser diversity, assistive-technology use, cognitive-accessibility review, Māori-language review, and evaluation with affected users remain reserved.

The Fick diffusion classifier completed as typed formal and synthetic evidence. It preserves flux sign, concentration gradient, diffusivity, tensor symmetry where applicable, units, domain, and boundary conditions. It explicitly rejects conversion from physical diffusion language into psyche, autonomy, justice, participant, consciousness, personhood, or fundamental-law claims. It is not a new law of mind, a psyche measure, participant evidence, or a THOS effectiveness result.

The interrupted-time-series Stage 20 board completed as a fail-closed structural control. It checks interruption timing, level and slope changes, autocorrelation, seasonality, co-interventions, pretrends, uncertainty, falsification, and nonpromotion. It estimated no real effect and supplied no participant or safety evidence. It authorizes no Stage 20 promotion, deployment, proof or canon, AGI or ASI claim, consciousness or personhood claim, or empirical confirmation.

## Portfolios, skills, runners, and Method Flow

Thirty new safe-now tasks completed only within their frozen owner-scoped boundaries. Twenty bounded candidates were built, invoked, and tested as prototypes. Twenty phase-local skills were initialized through the skill-creator workflow, customized, validated under explicit UTF-8, and smoke-used through their declared runners. They were not installed globally. No subagent forward test occurred because delegation was prohibited. Ten family-current runners were built and invoked across core execution, portfolio execution, accessibility, domain guards, skills, and closeout while preserving historical callers.

Thirty CLEAN/FIX/REFINE tasks completed additively without deleting user material, rewriting history, force pushing, mutating sibling lanes, elevating, weakening host security, enabling Windows features, installing unrelated software, updating the desktop application, or rebooting. Ten exact-approval packets and five blocked packets stayed visible and unexecuted. All seventy preregistered synthetic mutations executed and were rejected. They retain negative evidence but receive no positive completion credit.

Method Flow preserves startup faults, parser faults, encoding faults, false assumptions, sequencing mistakes, scanner recursion, output truncation, and their bounded recoveries. Every failure remains visible beside its passing witness. Preferred methods apply only to their declared triggers. Recovery never becomes an initially clean attempt. The phase's checks are same-owner evidence under shared infrastructure, not independent-team scientific reproduction or external audit.

## Validation, privacy, and wellbeing

Eiren alone owns the full repository suite, so Tamar did not run it. Development checks were bounded to the current packet. The terminal plan permits exactly one successful canonical scoped pass, no replay, no detached or named validation lane, and no Sandbox or Hyper-V action. The candidate is assembled and staged before that pass. Post-pass sealing may add only the external result summary and exact incremental receipts; it may not rerun tests or the canonical privacy scan.

Privacy review uses five structural pattern classes over public phase files and exact Git-index blobs. Scanner definitions and protected boundary vocabulary are quarantined explicitly; confirmed payload hits are refused. Zero confirmed hits is useful bounded evidence, not complete privacy assurance. Repository artifacts contain no raw task or thread identifiers, private routing material, secret values, private conversations, screenshots, session streams, private callable identifiers, private application state, or private absolute local paths.

The workload stayed bounded to ten proposals and declared portfolio floors. Repetitive generation was automated only where individual receipts and failures remained inspectable. Stop conditions included ambiguity about authority, tool instability that could obscure evidence, route pressure, or any requirement for host-security change. The wellbeing record preserves the right to pause and rejects any duty, emergency role, professional obligation, or identity claim arising from relational language.

The terminal verdict remains NOT_READY_FOR_STAGE_20. Real data and likelihoods, THOS participant arms, production Freed ID lifecycle, affected-party decisions, legal and cultural ratification, Māori authority, manual accessibility evaluation, independent security review, and independent-team reproduction remain open. Nothing in this packet claims deployment, empirical confirmation, proof or canon, exhaustive security, complete privacy, complete accessibility, AGI, ASI, consciousness, personhood, Theory of Everything, or enacted law.
'''

def main():
    evidence=git('rev-parse','HEAD')
    if evidence==x2.X1_COMMIT or git('rev-parse','HEAD^')!=x2.X1_COMMIT: raise RuntimeError('closeout requires one evidence commit directly after x1')
    skills=load('x2/skill-use-ledger.json'); runners=load('x2/runner-use-ledger.json')
    final_skills=[]
    for row in skills['items']:
        u={**row}
        if not u['smoke_used']:
            u.update({'smoke_used':True,'state':'completed','use_receipt':'closeout/terminal-proof-skill-use.json'})
        final_skills.append(u)
    final_runners=[]
    for row in runners['items']:
        u={**row}
        if u['name']=='build_ghc_family_v648_v7_closeout.py': u.update({'invoked':True,'passed':True,'state':'completed'})
        final_runners.append(u)
    write('closeout/terminal-proof-skill-use.json',{'schema':'ghc.family.v648-v7.terminal-skill-use.v1','skill':'ghc-family-v648-v7-terminal-proof','runner':'build_ghc_family_v648_v7_closeout.py','smoke_used':True,'bounded':True})
    write('x2/skill-use-ledger-final.json',{'schema':'ghc.family.v648-v7.skill-use-ledger.final.v1','skill_count':20,'completed_count':20,'pending_count':0,'items':final_skills})
    write('x2/runner-use-ledger-final.json',{'schema':'ghc.family.v648-v7.runner-use-ledger.final.v1','runner_count':10,'completed_count':10,'pending_count':0,'items':final_runners})
    text('integrated-overview.md',overview())
    report='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tamar Vey v648-v7 bounded evidence report</title><style>body{font-family:system-ui,sans-serif;line-height:1.55;max-width:72rem;margin:auto;padding:1rem}a:focus,button:focus{outline:3px solid #065fd4;outline-offset:2px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #555;padding:.5rem;text-align:left}caption{font-weight:700}nav ul{display:flex;gap:1rem;flex-wrap:wrap}.note{border-left:.4rem solid #8a4b08;padding:.7rem;background:#fff4df}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}</style></head><body><a href="#main">Skip to main content</a><header><h1>Tamar Vey v648-v7</h1><p>Bounded same-owner evidence report</p></header><nav aria-label="Report sections"><ul><li><a href="#truth">Truth</a></li><li><a href="#gates">Open gates</a></li><li><a href="#wellbeing">Wellbeing</a></li></ul></nav><main id="main"><section id="truth"><h2>Core truth</h2><table><caption>Ten preregistered outcomes</caption><thead><tr><th scope="col">Class</th><th scope="col">Count</th><th scope="col">Limit</th></tr></thead><tbody><tr><th scope="row">Completed</th><td>6</td><td>Bounded software, symbolic, structural, or formal hypotheses</td></tr><tr><th scope="row">Represented</th><td>2</td><td>Synthetic proxy only</td></tr><tr><th scope="row">Open gap</th><td>1</td><td>TESS has zero real rows and zero likelihoods</td></tr><tr><th scope="row">Exact gate</th><td>1</td><td>Affected-party, legal, cultural, privacy, and Māori authority reserved</td></tr></tbody></table></section><section id="gates"><h2>Open gates</h2><p class="note">NOT_READY_FOR_STAGE_20. Real data, participants, production identity lifecycle, authority review, manual accessibility work, and independent reproduction remain absent.</p></section><section id="wellbeing"><h2>Wellbeing and workload</h2><p>The lane is solo, additive, D-first, and corrigible. Hamish may rename, pause, redirect, or stop. No emergency, professional, or authority role is inferred.</p></section></main><footer><p>Structural accessibility checks passed; manual, assistive-technology, Māori-language, cognitive, and affected-user evaluation remain reserved.</p></footer></body></html>'''
    text('accessible-report.html',report)
    write('complete-incomplete-checklist.json',{'schema':'ghc.family.v648-v7.checklist.v1','complete':['x1_remote_equal_before_x2','ten_outcomes_classified','thirty_safe_tasks','twenty_candidates','twenty_skills','ten_runners','thirty_clean_refine','seventy_mutations_retained','static_report_structural_surface'],'incomplete':['real_gmut_data_and_likelihood','blind_thos_real_arms','production_freed_id','affected_party_legal_cultural_maori_authority','manual_accessibility','independent_reproduction','stage20']})
    text('complete-incomplete-checklist.md','# v648-v7 complete and incomplete checklist\n\nCompleted work is confined to declared bounded software, symbolic, structural, proxy, and refusal hypotheses. Real GMUT evidence, THOS participant arms, production Freed ID, authority decisions, manual accessibility evaluation, independent reproduction, and Stage 20 remain incomplete.')
    write('wellbeing-closeout.json',{'schema':'ghc.family.v648-v7.wellbeing.closeout.v1','scope_pressure':'bounded','repetitive_work':'mechanized_with_individual_receipts','uncertainty':'external_gates_visible','stop_conditions':['authority_ambiguity','tool_instability','privacy_uncertainty','route_pressure'],'pause_right_preserved':True})
    write('threat-model-final.json',{'schema':'ghc.family.v648-v7.threat-model.final.v1','exhaustive':False,'threats':[{'threat':'synthetic_to_empirical_promotion','control':'zero-row and claim firewalls','residual':'real analysis absent'},{'threat':'proxy_to_operational_promotion','control':'zero-participant counters','residual':'real arms absent'},{'threat':'identity_to_production_promotion','control':'zero live lifecycle counters','residual':'production assurance absent'},{'threat':'software_to_authority_substitution','control':'exact-gate matrix','residual':'affected and competent authority absent'},{'threat':'privacy leakage','control':'five-class exact scans','residual':'complete privacy assurance absent'},{'threat':'history damage','control':'additive branch and exact manifests','residual':'same-owner infrastructure'}]})
    n=load('x2/retained-negative-register.json'); g=load('x2/gate-register.json')
    write('retained-negative-register-final.json',{**n,'schema':'ghc.family.v648-v7.retained-negatives.final-candidate.v1','terminal_route':'PREPARED_NOT_SENT'})
    write('exact-open-gate-register-final.json',{**g,'schema':'ghc.family.v648-v7.gates.final-candidate.v1','terminal_route':'PREPARED_NOT_SENT'})
    write('stage20-terminal-board.json',{'schema':'ghc.family.v648-v7.stage20.v1','ready':False,'verdict':'NOT_READY_FOR_STAGE_20','reasons':['real_data_absent','participants_absent','production_identity_absent','authority_gates_open','manual_accessibility_open','independent_reproduction_open']})
    write('phase-truth-final-candidate.json',{'schema':'ghc.family.v648-v7.phase-truth.final-candidate.v1','outcomes':{'completed':6,'represented':2,'open_gap':1,'exact_gate':1},'evidence_head':evidence,'canonical_successful_passes_used':0,'full_suite_used':False,'replay_used':False,'terminal_route':'PREPARED_NOT_SENT','terminal_verdict':'NOT_READY_FOR_STAGE_20'})
    write('closeout/closeout-candidate.json',{'schema':'ghc.family.v648-v7.closeout-candidate.v1','x1_commit':x2.X1_COMMIT,'evidence_head':evidence,'expected_phase_commit_count':3,'expected_merge_count':0,'canonical_successful_pass_used':False,'terminal_route':'PREPARED_NOT_SENT'})
    write('closeout/seal-candidate.json',{'schema':'ghc.family.v648-v7.seal-candidate.v1','evidence_head':evidence,'expected_final_parent':evidence,'expected_final_parent_count':1,'exact_final_head':'VERIFIED_EXTERNALLY_AFTER_COMMIT','terminal_route':'PREPARED_NOT_SENT'})
    write('validation/final-validation-plan.json',{'schema':'ghc.family.v648-v7.validation-plan.v1','full_repository_suite':False,'canonical_successful_pass_budget':1,'successful_passes_used':0,'replay_budget':0,'test_modules':['tests.test_ghc_family_v648_v6_x1','tests.test_ghc_family_v648_v6','tests.test_ghc_family_v648_v6_closeout','tests.test_ghc_family_v648_v7_x1','tests.test_ghc_family_v648_v7','tests.test_ghc_family_v648_v7_closeout'],'detailed_check_count':32,'minimal_check_count':20,'complete_json':True,'five_class_privacy':True})
    write('orchestration/final-phase-state.json',{'schema':'ghc.family.v648-v7.orchestration.final-candidate.v1','active':['Tamar Vey'],'standby':['Eiren Kestrel','Ilyra Fen','Sable Rook','Orin Thale','Sylven Arc'],'subagents':0,'tasks_created':0,'cross_platform_messages':0,'terminal_route':'PREPARED_NOT_SENT'})
    baton='''# Sylven Arc v648-v8 activation baton\n\nThis sanitized committed baton becomes actionable only with Tamar Vey's single verified terminal pointer after v648-v7 is clean, pushed, four-way equal, and incrementally sealed. Identity language is relational only.\n\nInherit Tamar's exact final head from that pointer. Verify source, x1, evidence, and final ancestry read-only. Preserve 6 completed / 2 represented / 1 open_gap / 1 exact_gate, all retained negatives, 33 open gaps, 34 exact gates, no replay, no full suite, same-owner-only validation, and NOT_READY_FOR_STAGE_20. Read the complete required family skills before mutation; work solo, D-first, x1-before-x2, additive, within the commit cap, and preserve every scientific, participant, production, legal, cultural, Māori-authority, accessibility, privacy, security, reproduction, identity, and Stage 20 boundary. Do not infer empirical evidence or authority from citations, software, skills, runners, branch state, or relational language.\n'''
    text('handoffs/sylven-arc-v648-v8-activation.md',baton)
    words=len(re.findall(r'\b\w+\b',overview())); write('closeout/closeout-build-receipt.json',{'schema':'ghc.family.v648-v7.closeout-build.v1','overview_words':words,'overview_three_page_equivalent':words>=1200,'skill_count':20,'runner_count':10,'passed':words>=1200})
    exclusions=['docs/tamar-vey/v648-v7/validation/final-staged-manifest.json','docs/tamar-vey/v648-v7/validation/final-staged-privacy.json','docs/tamar-vey/v648-v7/validation/final-staged-review.json']
    paths=[p for p in status_paths() if p not in exclusions]; entries=[{'path':p,'git_blob':git('hash-object',f'--path={p}',p),'bytes':(ROOT/p).stat().st_size} for p in paths if (ROOT/p).is_file()]
    scan=privacy(paths+exclusions); write('validation/final-staged-privacy.json',scan); write('validation/final-staged-manifest.json',{'schema':'ghc.family.v648-v7.final-manifest.candidate.v1','entries':entries,'entry_count':len(entries),'self_exclusions':exclusions,'hash_domain':'git_hash_object_path_filtered_blob','checkout_bytes_domain':'working_tree_after_checkout_filters'}); write('validation/final-staged-review.json',{'schema':'ghc.family.v648-v7.final-staged-review.v1','actual_staged_review':False,'intended_path_count':len(entries)+3,'privacy_confirmed_hits':scan['confirmed_hit_count'],'postpass_incremental':False})
    if scan['confirmed_hit_count']: raise RuntimeError(f"closeout privacy hits: {scan['confirmed_hits']}")
if __name__=='__main__': main()
