"""Project executed evidence into Method Flow, cards, and a modular baton."""
from __future__ import annotations
import hashlib,html,json
from collections import Counter
from pathlib import Path
from build_ghc_family_ilyan_reed_v685_v8_x2 import BASE,ROOT,SOURCE,X1,canonical,sha,read,write
def text(path,content):
    p=BASE/path;p.parent.mkdir(parents=True,exist_ok=True)
    with p.open('x',encoding='utf8',newline='\n') as f:f.write(content)
def main():
    identity=read('x1/identity-and-practice.json');boundary=identity['identity_boundary'];gates=identity['protected_gates'];props=read('x1/new-proposals.json')['proposals'];results=read('x2/contract-results.json')['records'];negatives=read('x2/invalid-mutations.json')['records'];portfolio=read('x2/portfolio-results.json');promotion=read('x2/global-promotion-installation.json');local=read('x2/local-skills-validation.json');packages=read('x2/toolchain/package-smokes.json');source=read('x1/activation-source.json')
    methods=[];witnesses=[];negative_ids=[];events=[]
    def method(mid,title,signature,failed,passed,evidence,related=None):
        nis=[mid+f'-NEG{i+1:03d}' for i in range(failed)];negative_ids.extend(nis)
        links=nis or related or ['IR6858-N001-NEG001']
        wi=[]
        for result,count in [('fail',failed),('pass',passed)]:
            for i in range(count):
                wid=mid+'-'+result.upper()+f'{i+1:03d}';wi.append(wid)
                witnesses.append({'witness_id':wid,'method_id':mid,'procedure':title,'scope':'Ilyan Reed v685-v8 owner delta','expected':'Declared relation or refusal from the frozen source','observed':'Retained invalid input or failed procedure' if result=='fail' else 'Bounded check or recovery passed','result':result,'same_owner_only':True,'independent_reproduction':False,'retained_negative_ids':nis,'evidence_ref':evidence,'boundary':gates})
        methods.append({'method_id':mid,'title':title,'failure_signature':signature,'trigger_preconditions':['Exact owner source and matching protocol definition','Only synthetic inputs and authorized local artifacts'],'privacy_class':'sanitized_public','approval_class':'safe_now','candidate_workaround':'Use the precise report relation and preserve contradictory input. Correct only a diagnosed failed dependency.','validation_witness_ids':wi,'recurrence_guard':'Read exact input, JSON types, byte domain and current scope before invocation. Never replace an oracle with observed output.','rollback':'Hold the affected method and select retained prior evidence; erase nothing.','recommendation_state':'validated','supersedes':[],'protected_gates':gates,'retained_negative_ids':links,'scope_boundary':'Same-owner local software and workflow evidence; no scientific or operational authority.','execution_authority':'owner_self_scoped_delta','repository_scan':False,'module_scan':True,'cross_lane_scan':False,'unchanged_history_scan':False,'sibling_lane_mutation':False,'source_commit':SOURCE,'final_commit':'bound_by_external_exact_final_receipt','changed_file_allowlist':[evidence.split('#')[0]],'module_allowlist':['scripts/ghc_family_protocol_'+r+'.py' for r in ['trace','budget','analysis','provenance','export']],'exact_pushed_head_required':True})
        events.append({'method_id':mid,'from':'candidate','to':'validated','passing_witness_required':True})
    for p in props:method(p['proposal_id'],p['title'],'Fabricated report, stale definition, inverted epoch, empirical or authority promotion',5,1,'docs/ilyan-reed/v685-v8/x2/contract-results.json#'+p['proposal_id'])
    for key in ['safe_now','candidates','clean_fix_refine']:
        for r in portfolio[key]:method(r['packet_id'],r['action']+' for '+r['proposal_id'],'False-report input retained' if r['action']=='retain_and_correct_false_report' else 'No procedure failure observed; recurrence boundary retained',1 if r['action']=='retain_and_correct_false_report' else 0,1,'docs/ilyan-reed/v685-v8/x2/portfolio-results.json#'+r['packet_id'],[r['proposal_id']+'-NEG001'])
    startup=read('x1/startup-methods.json')['startup_failures']
    for s in startup:method(s['id'],s['recovery'],s['signature'],1,1,'docs/ilyan-reed/v685-v8/x1/startup-methods.json#'+s['id'])
    method('IR6858-X2-OPS001','Select the bundled PDF reader by an availability probe','The optional fitz module was absent; bundled pypdf and pypdfium2 were available',1,1,'docs/ilyan-reed/v685-v8/x2/runtime-reader-recovery.json')
    write('x2/runtime-reader-recovery.json',{'failure':'ModuleNotFoundError for optional fitz reader','failure_credit':0,'recovery':'Availability probe found bundled reportlab, pypdf, pypdfium2 and PIL; no package installation required','state':'validated','system_mutation':False})
    for r in packages['rows']:method('IR6858-PKG-'+r['package'],r['package']+' accepting and rejecting smoke','Preregistered invalid timeout, transition or finite constraint fixture',1,1,'docs/ilyan-reed/v685-v8/x2/toolchain/package-smokes.json')
    for i,r in enumerate(local['skills'],1):
        first=next(p for p in props if p['family'].replace('_','-') in r['name'])
        method(f'IR6858-SKILL-{i:02d}',r['name'],'No observed quick-validation failure',0,1,'docs/ilyan-reed/v685-v8/x2/local-skills-validation.json',[first['proposal_id']+'-NEG001'])
    for i,r in enumerate(promotion['skills'],1):method(f'IR6858-PROMOTE-{i:02d}',r['name'],'No observed candidate, install, parity or caller failure',0,1,'docs/ilyan-reed/v685-v8/x2/global-promotion-installation.json',[r['first_proposal']+'-NEG001'])
    counts={'methods':len(methods),'failed_witnesses':sum(w['result']=='fail' for w in witnesses),'bounded_passing_witnesses':sum(w['result']=='pass' for w in witnesses),'retained_negatives':len(negative_ids)}
    ledger={'schema':'ghc.family.method-flow-state.v1','owner':'Ilyan Reed','phase':'v685-v8','identity_boundary':boundary,'execution_authority':'owner_self_scoped_delta','source_commit':SOURCE,'final_commit':'bound_by_external_exact_final_receipt','methods':methods,'witnesses':witnesses,'state_events':events,'recommendations':[{'method_id':m['method_id'],'recurrence_guard':m['recurrence_guard']} for m in methods[:20]],'counts':counts,'boundary':gates,'counting_rule':'One method per proposal, portfolio task, setup recovery, direct package pair, local guide validation, or curated promotion. Each invalid report or adverse package input is a zero-credit failed witness; passing guard checks are not counted a second time. Operational truncation repeats are retained under their common startup failure signature.'}
    write('x2/method-flow.json',ledger)
    totals=dict(source['latest_source_working_baseline']);totals['effective_negatives']+=counts['retained_negatives'];totals['effective_methods']+=counts['methods'];totals['failed_witnesses']+=counts['failed_witnesses'];totals['bounded_passing_witnesses']+=counts['bounded_passing_witnesses'];totals['open_gaps']+=10;totals['exact_gates']+=10
    write('x2/phase-truth.json',{'owner':'Ilyan Reed','phase':'v685-v8','source':SOURCE,'x1':X1,'state':'X2_EXECUTED_NOT_TERMINALLY_VALIDATED','outcomes':read('x2/contract-summary.json')['outcomes'],'phase_counts':counts,'totals':totals,'source_repository_seal':source['repository_seal'],'source_initial_activation_baseline':source['initial_activation_baseline'],'source_later_external_baseline':source['latest_source_working_baseline'],'declared_proposal_chain':12230,'real_entities':0,'priority_pillar':'THOS Body','same_owner_only':True,'terminal_verdict':'NOT_READY_FOR_STAGE_20'})
    # Distinguish three lexically similar reservation families by the missing
    # prerequisite, not a score or a common reservation operation.
    write('tooling/collision-adjudication.json',{'source_findings':3,'selection_policy':{'governed_trial_vacancies':'represented protocol design with no real trial','gmut_observation_obligations':'open_gap for the named absent scientific object','cbr_authority_reservations':'exact_gate for the named competent or affected-party decision'},'automatic_lexical_winner':False,'unresolved_authority_or_evidence_promoted':False})
    cards=[]
    def card(tier,title,parents,content,outcome,typ,stability='volatile'):
        payload={'schema':'ghc.family.freed-id-card.v1','tier':tier,'card_type':typ,'title':title,'parent_ids':parents,'owner':'Ilyan Reed','phase':'v685-v8','stability':stability,'outcome':outcome,'content':content,'source_refs':[SOURCE,X1],'protected_gates':gates,'relational_boundary':boundary}
        cid='ghc-card-'+sha(payload)[:24];payload['card_id']=cid;cards.append(payload);write('x2/flashcards/cards/'+cid+'.json',payload);return cid
    anchor=card(1,'Ilyan Reed relational anchor',[],identity,'represented','freed_id_anchor','stable')
    pillars={n:card(2,n,[anchor],{'boundary':'Software records and explicit reservations only'},'represented','trinity_pillar','stable') for n in ['THOS Body','GMUT Mind','Freed ID and CBR Heart']}
    practices={}
    for p in props:
        k=(p['pillar'],p['practice'])
        if k not in practices:practices[k]=card(3,p['practice'],[pillars[p['pillar']]],{'scope':'Learning lens; no qualification or professional authority','pillar':p['pillar']},'represented','bounded_practice')
    for p,r in zip(props,results):card(4,p['title'],[practices[(p['pillar'],p['practice'])]],{'proposal_id':p['proposal_id'],'definition_sha256':r['definition_sha256'],'approval_class':p['approval_class'],'dependency':X1,'artifact':'x2/contract-results.json#'+p['proposal_id'],'falsifier':p['falsifier'],'rollback':p['rollback'],'input':p['input'],'expected_result':p['expected_result'],'observed_result':r['result'],'method_id':p['proposal_id']},r['outcome'],'task')
    write('x2/flashcards/deck-index.json',{'source':SOURCE,'x1':X1,'card_order':[c['card_id'] for c in cards],'card_count':len(cards),'tier_counts':dict(Counter(c['tier'] for c in cards)),'unique_practice_lenses':4,'practice_placements':len(practices),'core_outcomes':['completed','represented','open_gap','exact_gate']})
    write('x2/flashcards/stable-prefix.json',{'cards':[c['card_id'] for c in cards if c['stability']=='stable'],'cache_telemetry_claimed':False})
    write('x2/flashcards/volatile-index.json',{'cards':[c['card_id'] for c in cards if c['stability']=='volatile'],'implicit_completion_denied':True})
    report='<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ilyan Reed protocol evidence</title><style>body{font:17px system-ui;max-width:1100px;margin:40px auto;padding:0 24px;color:#17222e;background:#faf9f4}table{border-collapse:collapse;width:100%}th,td{border:1px solid #647580;padding:10px;text-align:left}caption{font-weight:bold;padding:16px}a{color:#064c8c}td:nth-child(3){white-space:nowrap}</style></head><body><main><h1>Ilyan Reed v685-v8 protocol evidence</h1><p>'+html.escape(boundary)+'</p><p>170 completed local report checks, 10 represented designs, 10 open gaps and 10 exact gates. Structural review does not establish complete accessibility. Manual, keyboard, assistive-technology, cognitive, Māori-language and affected-user review remain reserved.</p><table><caption>All 200 bounded claims</caption><thead><tr><th scope="col">Proposal</th><th scope="col">Claim</th><th scope="col">Outcome</th></tr></thead><tbody>'
    for p,r in zip(props,results):report+='<tr><td>'+p['proposal_id']+'</td><td>'+html.escape(p['title'])+'</td><td>'+r['outcome']+'</td></tr>'
    report+='</tbody></table></main></body></html>\n';text('x2/flashcards/accessible-report.html',report)
    section_titles=['Identity and corrigibility','Exact source and lifecycle','Released profile and prospective route','Frozen contracts and observed reports','THOS Body and offline protocols','GMUT Mind and observation obligations','Freed ID and CBR Heart','Four practice lenses and primary sources','Three package additions','Skills runners and promotions','Method Flow and retained failures','Validation scope and review limits','Neris activation and continuing the route']
    intro=[
      boundary+'\n\nThis is the file-backed handoff from Ilyan Reed v685-v8 to the existing main task Neris Solane for v686-v1. It is repository preparation. The exact final and its external validation receipt are supplied by the single terminal activation. Until that gate and send occur, the stored delivery state remains PREPARED_NOT_SENT. Names identify relational working context; they are neither credentials nor callable routes.',
      'Elaren exact final is '+SOURCE+'. Ilyan planning-only x1 is '+X1+'. X1 passed eleven planning checks, was pushed, and was clean, 0/0 divergent and equal across local, upstream, tracking and a fresh live remote before x2 began. Evidence and final are separate direct-child commits. Resolve their exact values from the terminal receipt; this prepared packet does not invent a self-referential final SHA. No x1 file or source lane was changed during x2.\n\nElaren retains an INVALID canonical aggregate at 23/24 and zero aggregate-success credit. The separate narrow frontmatter recovery passed 20/20 without a test or manifest replay; its composite gives effective 24/24 completion. That distinction survives this handoff. The canonical receipt hash is '+source['canonical_receipt_sha256']+'; the recovery hash is '+source['recovery_receipt_sha256']+'; the composite hash is '+source['composite_receipt_sha256']+'. Ilyan read and hashed those records and reverified 914 exact source-manifest entries without invoking Elaren canonical validation.',
      'The 6 September release supplies the active thirty-seat profile. It authorizes sequential work through v725-v8, one verified edge at a time. The frozen profile is x1/workflow-profile.json. Use 200–500 inherited proposals, 200–500 new proposals, 300–500 safe tasks, 250–500 candidates, exactly 300 additive CLEAN/FIX/REFINE rows, 50–250 exact packets and 30–100 blocked packets. Plan and build at least ten skills and five runners, within fifty per session and one hundred per bundle. Carry ten next-owner skill and runner ideas, four own learning lenses and one next-owner recommendation, ten justified skill promotions with five shared runners, three ordinary direct package additions, a 10,000–100,000-word modular baton, and an overview of at least three pages. These are substantive requirements and ceilings; neither counts nor elapsed time authorize filler.\n\nIlyan is the already created seat 02 main task and is reused in later cycles. Neris v686-v1 is the next existing-task edge. After Neris completes its own gate, its designated future seat 03 may be created once for v686-v2 under the release; that new task chooses its own descriptors and then routes to Vesper Arlen v686-v3. No later seat is contacted in advance.',
      'The complete contract appendix below binds 200 new source-bounded proposals to explicit inputs and hand-specified expected reports. The 200 inherited Elaren records remain zero-credit seeds in x1/inherited-selection.json. Bounded title screening made 40,000 comparisons, found zero exact collisions and no score at the 0.80 quarantine threshold. The family review considers mission, falsifier, executable evidence and recovery; lexical distance is not universal semantic novelty.\n\nA report check can pass while correctly reporting a refusal. Its completed label covers the local relation, not the scenario rejected by that relation. For example a cycle result is a correct refusal of cyclic provenance, not a valid lineage. Every positive record is paired with five rejected report mutations, retained in x2/invalid-mutations.json. Repeated contract metadata in this appendix preserves the complete reviewable definition and supplies no additional proposal credit.',
      'THOS Body is the priority pillar. The useful advance is an offline report-verification laboratory with event calendars, legal state traces, FIFO queues, idempotent replay, two-arm resource accounting, allocation balance, role separation and complete denominators. An explicit input and an independently specified oracle make a false summary falsifiable. Inputs are invented and execution is restricted to software. Event ticks are synthetic integers, budget units are declared tokens, labels are surrogates and no actual participant or device exists.\n\nA deterministic calendar is not a real-time scheduler. A legal state sequence is not a completed operational trial. Balanced totals do not establish randomized allocation, blinding, equal difficulty, safe operation or THOS effectiveness. The ten governed-trial vacancies stay represented. Real arms, legitimate recruitment, competent monitoring, prospective decisions, appropriate statistical design and independent evaluation remain prerequisites for a real comparison.',
      'GMUT remains a typed scalar-tensor and effective-field-theory research-model family. This phase supplies exact arithmetic and explicit missing-observation objects, not physical fields or measurements. The ten named scientific obligations remain open: a clock-to-observable map, field-to-event likelihood, dimensioned coupling, identifiable parameter, finite-resolution discrepancy, boundary conditions, measurement covariance, empirical dataset, rival-model comparison and unique falsifiable prediction.\n\nExact rational means, sample and population variance, paired differences and histogram counts test arithmetic on invented values. Their denominators and signs are auditable. They establish no statistical inference about a real population, detected force, material law, empirical confirmation, stability theorem, quantum or ultraviolet completion, final physics, Theory-of-Everything proof or canon. A future owner may refine the mathematical definitions but must preserve each missing empirical or independent prerequisite.',
      'Freed ID is synthetic and nonproduction. Content-addressed cards and provenance labels do not issue, verify, present, resolve, revoke or recover a real credential. No real keys, cryptographic proofs, status service, interoperability, security review, privacy review, trust-governance decision or independent identity-lifecycle event occurred. A digest establishes only the declared byte comparison.\n\nCBR keeps consent, legitimate access, contested rights, publication permission, cultural descriptions, Māori wording, Māori data governance, tangata whenua, iwi, hapū and remedies under the appropriate competent, affected-party and Māori authority. The ten authority reservations remain exact-gated. A present record is not consent, custody is not ownership and software cannot grant cultural standing. The fifty exact packets distinguish proposed wording, future collection scope, contested amendments, public export scope, and retention or remedy. They are individually specified prerequisite packets and no gated act was executed.',
      'The four lenses are experimental protocol auditor, event-log data engineer, uncertainty-model reviewer and accessible evidence editor. They guide questions and organization, not employment, qualification, competence or professional authority. Their six pillar placements in the card graph are six contexts for four lenses, not six professions. The next-owner recommendation is data-quality investigator, with attention to empty data, typed values, mismatched pair labels and hidden denominator changes.\n\nPrimary sources provide narrow vocabulary: SimPy time and scheduling, the transitions project, python-constraint documentation, Python statistics, W3C PROV-O, WCAG 2.2 and Verifiable Credentials Data Model 2.0. The source ledger records the access date and current or stable status. None supplies participant evidence or a right to act. A changing package release is pinned by exact version and wheel digest; a stable standard remains distinct from a conformance claim.',
      'Exactly three direct additions were installed in a new isolated D environment: SimPy 4.1.2, transitions 0.9.3 and python-constraint2 2.7.3. The dependency six 1.17.0 and preplanned bootstrap pip 26.2.1 bring the installed distribution count to five. All five wheel hashes matched frozen official registry metadata. The wheel archive review rejected traversal-shaped member names, and installation used only the downloaded wheels with required hashes and compilation disabled. System Python, PATH, the npm prefix, plugin caches and sibling environments were not changed.\n\nThe accepting smokes observed same-tick FIFO event order, planned-to-running-to-recorded state transitions, and two finite distinct assignments summing to four. The adverse smokes refused negative delay, finish-before-start and inconsistent singleton domains. All three pairs passed. Pip dependency checking passed and a dated public OSV query returned zero findings for the five pinned distributions. That snapshot is not exhaustive security or future safety. Rollback selects retained prior tooling and preserves the environment and receipts.',
      'Twenty local source guides cover the twenty families. Ten curated global packages retain two guides each and the same five portable standard-library runner sources. The five unique runners are protocol trace, budget, analysis, provenance and export. Fifty file copies across ten packages remain five unique shared runners. Every local guide passed the official skill validator; every candidate and installed package passed validation and accepting/adverse CLI witnesses. All installed bytes matched their candidate source. No existing global skill was overwritten or deleted.\n\nThe 25-card tool catalogue contains twenty local guides and five shared runners. Three lexical overlap findings concern governed trials, GMUT obligations and CBR reservations. Their additive adjudication selects the exact family: represented real-trial design, open scientific evidence gap, or exact authority gate. The common reservation operation is not authority to interchange those meanings. Selection is by the source-bound criterion, not by a lexical winner. Global discoverability does not prove catalogue reload or user competence.',
      'The source repository seal, activation baseline and later external correction remain separate. Elaren sealed 64,405 negatives, 80,970 methods, 35,253 failed witnesses and 62,815 bounded passing witnesses, with 582 gaps and 569 gates. The initial five-event overlay produced 64,410 / 80,975 / 35,258 / 62,820. Two later parser failures in the source task produced the separate 64,412 / 80,977 / 35,260 / 62,822 working baseline. Neither overlay rewrites the source repository.\n\nIlyan retains the empty-index startup fault, output-budget truncation signature and LF staging failure. The sparse index recovery was limited to the verified empty new lane; the LF repair occurred before the x1 commit. An optional PDF reader import failed; an availability probe selected already bundled pypdf and pypdfium2 without a package addition. All 1,000 rejected report mutations, 100 retained false-report corrections and three adverse package inputs retain zero completion credit. Method Flow records exact witness references and counting rules. Counters are evidence-ledger units, not probabilities, experiments, safety percentages or authority scores.',
      'The x1 suite passed eleven checks before execution. The x2 contract run accepted all 200 frozen reports and rejected all 1,000 registered mutations. Eighteen behavioral checks passed, including metamorphic arithmetic and queue invariants. Portfolio evidence covers 300 safe transformations, 250 candidate reviews and 300 additive CLEAN/FIX/REFINE tasks. Fifty exact and thirty blocked packets remain unexecuted. Their count is not evidence that their prerequisites were met.\n\nThe terminal process reviews exact changed paths, staged Git-blob manifests, JSON, Python AST, Markdown including YAML frontmatter, YAML, HTML and PDF structure, package and skill receipts, privacy classes, narrow security findings, content seals, source/x1/evidence/final ancestry, clean status, 0/0 divergence and fresh four-way remote equality. One attributable exact-final canonical attempt writes an exclusive external marker. Preserve any failure and isolate its dependency; never replay a successful aggregate. Validation is same-owner work under shared infrastructure. It is neither independent reproduction nor a complete repository suite. The 2,000-file ceiling remains a hard rotation boundary.',
      'Neris Solane is prospective until Ilyan has a pushed, clean, fresh-live-equal exact final and completed terminal validation. Then refresh the native task registry and current authorization, require exactly one existing exact-title Neris Solane main task, immediately reread that task, and apply duplicate, pause, redirect, usage, privacy, evidence and safety guards. Send exactly one compact file-backed activation for v686-v1. Acknowledged, opaque accepted, rejected and unavailable outcomes remain distinct. Never resend an opaque acceptance, create a substitute or precontact later owners.\n\nNeris should read the complete packet through EOF, reverify the supplied exact source and external receipt, use one additive D-first lane, freeze planning-only x1 before x2, preserve inherited zero-credit seeds, and retain all failures and protected gates. The release permits continuing one verified edge at a time through v725-v8, subject to Hamish changing or stopping it. Reset redemption remains Hamish’s action. No desktop update, elevation, host-security change, Windows-feature change, reboot, account or credential creation, purchase, deployment or private publication is authorized here. Keep the long details file-backed and the live greeting short, warm and reviewable.'
    ]
    appendix=[]
    for p,r in zip(props,results):
        appendix.append('## '+p['proposal_id']+' — '+p['title']+'\n\nFamily: `'+p['family']+'`. Operation: `'+p['operation']+'`. Practice: '+p['practice']+'. Pillar: '+p['pillar']+'. Observed claim disposition: `'+r['outcome']+'`.\n\nMission: '+p['mission']+'\n\nHypothesis: '+p['hypothesis']+'\n\nFailure condition: '+p['null_or_failure']+'\n\nAcceptance and falsifier: '+p['falsifier']+'\n\nExact synthetic input:\n\n```json\n'+json.dumps(p['input'],ensure_ascii=False,indent=2)+'\n```\n\nPreregistered expected report:\n\n```json\n'+json.dumps(p['expected_result'],ensure_ascii=False,indent=2)+'\n```\n\nObserved computation:\n\n```json\n'+json.dumps(r['result'],ensure_ascii=False,indent=2)+'\n```\n\nThe source definition digest is `'+r['definition_sha256']+'`. The report check and its five separately retained invalid fixtures are addressed by '+p['proposal_id']+' in the contract and mutation ledgers. The registered contrary reports alter the reported value, source-definition digest, phase epoch, empirical flag and authority flag. All five were refused. The result remains attributable to this local input and owner.\n\nRecovery: '+p['rollback']+'\n\n[Primary vocabulary]('+p['source_refs'][0]+') is a source pointer, not observation, independent replication or permission.\n')
    intro[3]+='\n\n'+'\n'.join(appendix)
    sections=[]
    for i,(title,body) in enumerate(zip(section_titles,intro),1):
        name=f'x2/handoff/{i:02d}-'+title.lower().replace(' ','-')+'.md';content=f'# {i:02d} {title}\n\n'+body+'\n';text(name,content);sections.append({'number':i,'title':title,'path':name,'sha256':hashlib.sha256(content.encode()).hexdigest()})
    combined='\n---\n\n'.join((BASE/s['path']).read_text(encoding='utf8') for s in sections);text('x2/handoff/neris-v686-v1-baton.md',combined)
    words=len(combined.split());write('x2/handoff/baton-index.json',{'sections':sections,'baton_path':'x2/handoff/neris-v686-v1-baton.md','words':words,'navigable_sections':13,'delivery_state':'PREPARED_NOT_SENT','source':SOURCE,'x1':X1})
    write('x2/flashcards/baton-index.json',{'sections':sections,'complete_packet':'x2/handoff/neris-v686-v1-baton.md','delivery_state':'PREPARED_NOT_SENT'})
    paths=sorted(p for p in (BASE/'x2/flashcards').rglob('*') if p.is_file());write('x2/flashcards/card-manifest.json',{'hash_domain':'normalized-LF UTF-8 files','entries':[{'path':p.relative_to(ROOT).as_posix(),'bytes':len(p.read_bytes()),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in paths],'self_exclusions':['docs/ilyan-reed/v685-v8/x2/flashcards/card-manifest.json']})
    profile=read('x1/workflow-profile.json');cycle=list(profile['cycle']);cycle[3]='Ilyan Reed';schedule=[]
    for i in range(321):
        offset=685*8+7+i;version,slot=divmod(offset,8);schedule.append({'phase':f'v{version}-v{slot+1}','owner_label':cycle[(3+i)%30],'planning_only':True,'executed_by_projection':False})
    write('x2/route-projection.json',{'cycle':cycle,'assignments':schedule,'horizon':'v725-v8','delivery_proof':False,'new_task_creation_performed':False})
    write('x2/evidence-summary.json',{'cards':len(cards),'practice_lenses':4,'practice_placements':len(practices),'baton_words':words,'baton_sections':13,'method_counts':counts,'totals':totals,'new_proposals':200,'inherited_zero_credit':200,'local_skills':20,'global_skills':10,'unique_shared_runners':5,'direct_package_additions':3,'x2_tests':18,'terminal_verdict':'NOT_READY_FOR_STAGE_20'})
    assert 10000<=words<=100000
    print(json.dumps({'cards':len(cards),'baton_words':words,'methods':counts,'totals':totals}))
if __name__=='__main__':main()
