"""Create final review documents; exact final identity is bound externally."""
import argparse,hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'docs/ilyan-reed/v685-v8';EVIDENCE='01e246b683f64993cb2cca2244776e92c237c850';X1='ae33e7fd357e38c464677c10538a50f069b68353';SOURCE='f5464f56d095e9c691707f669668b86ff70468a6'
def read(p):return json.loads((BASE/p).read_text(encoding='utf8'))
def text(p,s):
    dest=BASE/p;dest.parent.mkdir(parents=True,exist_ok=True)
    with dest.open('x',encoding='utf8',newline='\n') as f:f.write(s)
def js(p,d):text(p,json.dumps(d,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--equality',required=True);a=ap.parse_args();eq=json.loads(Path(a.equality).read_text());assert eq['head']==EVIDENCE and eq['clean'] and eq['four_way_equal']
    js('final/evidence-equality.json',eq)
    truth=read('x2/phase-truth.json');truth.update(evidence=EVIDENCE,final='bound_by_external_exact_final_receipt',state='FINAL_PREPARED_CANONICAL_PENDING',delivery_state='PREPARED_NOT_SENT');js('final/phase-truth.json',truth)
    boundary=read('x1/identity-and-practice.json')['identity_boundary']
    pages=[
    ('Purpose, ownership and exact lifecycle',[
    'Ilyan Reed v685-v8 develops an offline protocol-report laboratory. Its practical question is whether a report agrees with its frozen synthetic input and the declared rule. The work supplies small executable examples, report challenges, readable source guides and a file-backed handoff. It does not establish that a real trial occurred or that a physical or social claim is true.',
    boundary,
    'The exact source is Elaren final '+SOURCE+'. Ilyan planning-only x1 is '+X1+'. Immutable x2 evidence is '+EVIDENCE+'. The final commit is the direct child of evidence and is identified by the external exact-final receipt after commit and push. Source to final must contain three direct single-parent Ilyan commits and zero merges. X1 was pushed and verified clean with local, upstream, tracking and fresh-live equality before implementation began. Evidence passed the same equality gate before this overview was prepared.',
    'The source validation history stays intact. Elaren’s canonical aggregate remains INVALID at 23 of 24 checks with zero canonical aggregate-success credit. A separately retained narrow frontmatter recovery passed all 20 affected source-guide blobs; the composite records effective completion of 24 of 24. The canonical aggregate was not replayed. Ilyan verified the three receipt hashes and 914 exact source-manifest entries without rerunning source tests or invoking the source aggregate.',
    'The owned D-first lane uses sparse materialization and additive paths. Shared and sibling content remains read-only. The startup index failure and the precommit LF mismatch were retained and repaired only in the new unsealed lane. The file ceiling is 2,000, with additive rotation if needed. A clean Git state is evidence about the exact checkout and branch; it does not prove independent reproduction, conformance of a device or the authority of a record.',
    'For review, begin with final/phase-truth.json and the external receipt. Read x2/contract-summary.json for the bounded claim outcomes, x2/portfolio-results.json for task transformations, x2/method-flow.json for retained failures, and final/neris-v686-v1-baton.md for the complete packet. These documents address different units of evidence. A proposal, a task transformation, a failed input and a validator check must not be counted as interchangeable accomplishments.'
    ]),
    ('Protocol results and Trinity Mandala boundaries',[
    'X1 selected 200 inherited Elaren rows with zero borrowed novelty or execution credit and froze 200 new proposals. Their inputs and expected reports were specified before the evaluators were written. The title screen performed 40,000 comparisons against the exact Elaren records, found no exact collision and no score reaching the 0.80 quarantine threshold. The semantic review considered each family’s mission, falsifier, concrete input and recovery. These bounded comparisons cannot establish universal novelty.',
    'The executed claim outcomes are 170 completed local report checks, 10 represented real-trial designs, 10 open GMUT evidence gaps and 10 exact CBR authority gates. All 200 positive report checks passed. All 1,000 preregistered report mutations were rejected and retained at zero completion credit. A refusal can be the correct computed report: detecting a cycle is a successful software check while the proposed lineage remains invalid.',
    'Five runners cover calendars, state traces, resource queues, replay, matched budgets, allocation balance, role-set overlap, missing-data denominators, exact summaries, paired alignment, histogram boundaries, stopping rules, derivation graphs, byte domains, immutable merges, allowlist projection, table structure and reservations. Eighteen behavioral tests passed. Additional checks verify queue translation, event idempotency, mean scaling, signed paired differences, histogram conservation and the distinction between booleans and integers.',
    'THOS Body is the priority pillar. Synthetic ticks are not measured time, balanced resource tokens are not matched real difficulty, and deterministic execution is not real-time safety or operational effectiveness. GMUT remains a typed scalar-tensor and effective-field-theory research-model family. Rational arithmetic and event diagrams supply no observable map, physical likelihood, empirical data, independent comparison, discovered force, final physics or Theory-of-Everything proof.',
    'Freed ID remains synthetic and nonproduction. No real keys, proofs, issuance, presentation, status, revocation, recovery, interoperability or trust-governance event occurred. CBR keeps consent, access, contested rights, publication, cultural interpretation and remedies under appropriate authority. Māori wording, concepts, data governance, tangata whenua, iwi and hapū remain under Māori authority. The software records do not make those decisions.',
    'The task portfolio separately records 300 safe transformations, 250 candidate reviews and exactly 300 additive CLEAN/FIX/REFINE rows. The latter preserve source views, retain and correct false reports, and derive readable explanations. Their local completion does not raise a linked scientific or authority claim. Fifty exact packets and thirty blocked packets remain unexecuted, with specific target classes and missing prerequisites.'
    ]),
    ('Reusable packages, skills and reviewable context',[
    'Three new direct packages were added in an isolated D environment: SimPy 4.1.2, transitions 0.9.3 and python-constraint2 2.7.3. Six 1.17.0 is the single runtime dependency and pip 26.2.1 is a separately classified, preplanned bootstrap. All five wheel files matched their frozen official registry SHA-256 values. The archive member checks passed and installation used only those wheels with hash requirements. The environment passed pip check.',
    'SimPy’s accepting witness preserved FIFO order for two events at the same synthetic time; its adverse witness refused a negative timeout. Transitions accepted planned-to-running-to-recorded and refused finish-before-start. The constraint package found exactly two distinct ordered assignments summing to four, while incompatible singleton domains had no solution. All three accepting and three rejecting smokes passed. No network endpoint, device, real-time environment or participant was involved.',
    'A dated OSV query found zero advisory rows for the five pinned distributions. The result is an advisory snapshot, not exhaustive security, future safety or a license interpretation. The transaction did not modify system Python, PATH, the npm prefix, Windows features, host security, the Codex desktop, plugin caches or sibling environments. Rollback preserves the receipts and selects retained tooling; no cleanup deletion was performed.',
    'Twenty local source guides and ten curated global packages passed skill validation. Each global package retains two local guides, concrete positive and adverse inputs, provenance and the same five shared standard-library runners. Candidate and installed CLI smokes passed and all installed files matched their candidate bytes. Ten packages with five copies each still count as five unique shared runners. Installation supplies discoverability, not competence or proof that another task has reloaded its catalogue.',
    'The 25-card catalogue contains twenty guides and five runners. Three lexical overlaps among governed-trial, GMUT and CBR reservation guides remain visible. Their review distinguishes represented trial design, missing scientific evidence and exact authority rather than assigning a lexical winner. Current tools are selected by exact operation and source-bound criterion. Broad inventory is not permission to execute or install every discovered tool.',
    'The four learning lenses are experimental protocol auditor, event-log data engineer, uncertainty-model reviewer and accessible evidence editor. The content-addressed deck has 210 cards: one owner anchor, three pillars, six practice placements and 200 tasks. Six placements express four lenses in their pillar contexts. The card graph and manifest passed structural checks. The accessible HTML report has text outcomes and table headers; browser, keyboard, assistive, cognitive, Māori-language and affected-user evaluation remain reserved.'
    ]),
    ('Retained failures, final validation and the next edge',[
    'Elaren’s immutable repository seal preserves 64,405 negatives, 80,970 methods, 35,253 failed witnesses and 62,815 bounded passing witnesses, plus 582 gaps and 569 gates. The initial activation adds five external events; a later source-task report adds two more parser failures. The resulting external working baseline is 64,412 negatives, 80,977 methods, 35,260 failed witnesses and 62,822 passing witnesses. Historical source bytes and receipts remain unchanged.',
    'Ilyan’s counted Method Flow has 1,087 methods, 1,107 failed witnesses, 1,107 retained negatives and 1,087 bounded passing witnesses. The failed inputs include 1,000 report mutations, 100 false-report correction inputs and three package adversaries. Four setup or reader failures are retained: the empty new index, bounded-output truncation signature, LF staging mismatch and absent optional fitz reader. The existing bundled pypdf and pypdfium2 readers resolved the last issue without installing another package.',
    'The prepared repository totals therefore become 65,519 negatives, 82,064 methods, 36,367 failed witnesses and 63,909 bounded passing witnesses, with 592 open gaps and 579 exact gates. These values count the explicitly enumerated ledger units. They are not safety rates, observations, probability estimates, professional qualifications or authority scores. Later canonical or delivery events belong in external receipts and must not rewrite the sealed ledger.',
    'The final gate checks the exact owner delta, immutable x1 and evidence, Git-blob manifests, content seal, JSON, Python AST, Markdown with frontmatter, YAML, HTML and PDF structure, global-copy parity, the bounded privacy and security scans, word and file limits, direct ancestry, clean status, zero divergence and fresh remote equality. The single attributable canonical attempt writes an exclusive external invocation marker. A failure stays invalid and is isolated; a successful aggregate is never replayed for confidence, presentation or routing.',
    'The next task is the existing exact-title Neris Solane for v686-v1. Only after this terminal gate may Ilyan refresh the native registry and current authority, require one match, immediately reread Neris and apply duplicate, pause, redirect, usage, privacy, evidence and safety guards. The activation is sent once. Target-identifying acknowledgement, opaque acceptance, rejection and unavailable route are separate outcomes. An opaque acceptance never triggers a resend or substitute task.',
    'The release continues the thirty-seat sequence one verified edge at a time through v725-v8. Neris’s next designated creation is future seat 03 for v686-v2 after its own terminal gate; that task chooses its own descriptors and later routes to Vesper Arlen v686-v3. Hamish can change or stop the route. Reset redemption remains his action. The terminal boundary remains NOT_READY_FOR_STAGE_20, and all work here is same-owner evidence under shared infrastructure rather than independent reproduction or a complete repository suite.'
    ])]
    js('final/overview-pages.json',{'pages':[{'title':title,'paragraphs':paragraphs} for title,paragraphs in pages],'planned_pages':4})
    overview='\n\n'.join('# '+title+'\n\n'+'\n\n'.join(paragraphs) for title,paragraphs in pages)+'\n';text('final/integrated-overview.md',overview)
    baton=(BASE/'x2/handoff/neris-v686-v1-baton.md').read_text(encoding='utf8')
    preface='The immutable Ilyan x2 evidence is `'+EVIDENCE+'`. This final handoff preserves its packet unchanged below. The exact final SHA and attributable canonical result are bound by the external receipt and the one compact terminal activation. Stored repository delivery remains `PREPARED_NOT_SENT`.\n\n'
    baton=baton.replace('# 01 Identity and corrigibility\n\n','# 01 Identity and corrigibility\n\n'+preface,1);text('final/neris-v686-v1-baton.md',baton)
    js('final/baton-integrity.json',{'words':len(baton.split()),'sections':len(re.findall(r'^# \d{2} ',baton,re.M)),'sha256':hashlib.sha256(baton.encode()).hexdigest(),'overview_words':len(overview.split()),'x2_baton_unchanged':True,'next_owner':'Neris Solane','next_phase':'v686-v1'})
    js('final/delivery-state.json',{'state':'PREPARED_NOT_SENT','endpoint_kind':'main_task','recipient':'Neris Solane','phase':'v686-v1','send_count':0,'acknowledgement':'not_yet_available','new_task_or_subagent_created':False})
    js('final/validation-policy.json',{'source':SOURCE,'x1':X1,'evidence':EVIDENCE,'branch':'codex/GHC-Family/ilyan-reed-v685-v8-full-tools','owner':'Ilyan Reed','phase':'v685-v8','canonical_attempt_limit':1,'canonical_replay_limit':0,'test_modules':['tests/test_ghc_family_ilyan_reed_v685_v8_x2.py','tests/test_ghc_family_ilyan_reed_v685_v8_final.py'],'x1_tests':'Historical eleven-check receipt retained at exact x1; not replayed against the changed phase filesystem','scope':'Exact source-to-final owner additions only','materialized_file_ceiling':2000,'expected_history_commits':3,'expected_merges':0,'final_parent':EVIDENCE,'same_owner_only':True,'source_aggregate_replay_forbidden':True,'receipt_external_to_repository':True})
    js('final/complete-incomplete-checklist.json',{'completed_local':['200 report checks','1000 mutation refusals retained','300 safe transformations','250 candidate reviews','300 additive CLEAN/FIX/REFINE tasks','20 local guides','10 curated global packages','5 unique shared runners','3 direct package additions','210 content-addressed cards','13-section complete baton'],'represented':['10 real-trial design vacancies','learning lenses','synthetic Freed ID and THOS proxies'],'open_gap':['10 GMUT observations and model obligations','30 blocked packets','independent reproduction','real participants and governed comparison'],'exact_gate':['10 CBR authority reservations','50 exact packets','Māori authority','production identity and deployment','Stage 20'],'pending_terminal':['exact final commit and push','fresh final equality','single attributable canonical attempt','guarded Neris send']})
    text('final/compact-activation.md','# Prepared Neris activation\n\nKia ora Neris. Ilyan Reed v685-v8 has prepared your solo v686-v1 handoff. The terminal message will supply the exact final SHA and external canonical result after the final gate. Read `docs/ilyan-reed/v685-v8/final/neris-v686-v1-baton.md` through EOF and preserve the separate source seal, external overlays, retained failures, four dispositions and protected gates. Use the released profile and one D-first owner lane. Your designated next creation is future seat 03 for v686-v2 only after your own terminal gate; its next edge is Vesper Arlen v686-v3. The planned horizon is v725-v8, one verified edge at a time, subject to Hamish pausing or redirecting. Reset redemption remains Hamish’s action.\n')
    print(json.dumps({'overview_words':len(overview.split()),'baton_words':len(baton.split()),'sections':13,'delivery':'PREPARED_NOT_SENT'}))
if __name__=='__main__':main()
