"""Prepare Liora v688-v1 final artifacts after the immutable evidence boundary."""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import subprocess
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE = Path("docs/liora-venn/v688-v1")
SOURCE = "17fee348a09ec1cb480f7326bce70cd75413dad3"
X1 = "421abce86426674b67e0cbd5ce63ad463421fc9f"
EVIDENCE = "ffa072b57d0d3f58358f15b8fceae4440303503e"
BRANCH = "codex/GHC-Family/liora-venn-v688-v1-full-tools"
FINAL_COUNTS = {"proposals": 15630, "negatives": 82599, "methods": 93292, "failed_witnesses": 53447, "passing_witnesses": 83009, "open_gaps": 748, "exact_gates": 747}
OUTCOMES = {"completed": 160, "represented": 14, "open_gap": 8, "exact_gate": 18}
GATES = ["empirical", "real_participant", "professional", "production", "deployment", "identity", "legal", "cultural", "affected_party", "maori_authority", "privacy_complete", "accessibility_complete", "exhaustive_security", "independent_reproduction", "agi_asi", "consciousness_personhood", "theory_of_everything", "proof_canon", "stage20"]
BOUNDARY = "Relational working language only; no consciousness, sentience, personhood, identity continuity, employment, qualification, independent agency, scientific, operational, professional, legal, cultural, affected-party, or Māori authority is established. Same-owner software evidence is not independent reproduction. NOT_READY_FOR_STAGE_20."
OPERATIONS = ["vtt_timestamp", "srt_timestamp", "cue_interval", "frame_timebase", "cue_order", "payload_text", "language_tag", "derivative_linkage", "accessibility_claim", "publication_gate"]
OPERATION_TEXT = {
    "vtt_timestamp": "The WebVTT profile parses explicit timestamp syntax into integer milliseconds, preserves its normalized form, and refuses coercion, range overflow, whitespace repair, alternate punctuation, and unsupported fractional precision. It does not observe or synchronize media.",
    "srt_timestamp": "The SubRip profile keeps two-digit hour, minute, and second fields plus comma-delimited milliseconds. It refuses missing fields, range overflow, period substitution, signs, unsupported hours, and nontext inputs rather than repairing them.",
    "cue_interval": "The cue interval contract represents one half-open timing span and its relation to a preceding endpoint. Initial, touching, and gap states remain distinct. Invalid types, empty or reversed spans, overlaps, and beyond-bound endpoints are held.",
    "frame_timebase": "The timebase contract uses exact rational arithmetic for frame-to-seconds and seconds-to-frame conversion. It refuses invalid rates, Boolean or floating fields, off-grid inverse values, decimal text, unrecognized modes, and undeclared drop-frame policy.",
    "cue_order": "The sequence contract preserves caller order, explicit gaps, and overall span for at most thirty-two cues. It rejects overlap, reverse order, malformed pairs, negative or beyond-day positions, Boolean endpoints, scalar arrays, and silent truncation.",
    "payload_text": "The payload contract preserves up to eight caller-supplied caption or transcript lines, including empty lines, Unicode, punctuation, and literal markup. It detects markup without rendering and explicitly establishes no speaker identity, authorship, or correctness.",
    "language_tag": "The language-tag contract canonicalizes a narrow syntax profile while refusing coercion, whitespace repair, private-use and extension profiles, repeated region roles, and unsupported primary tags. Syntactic metadata never supplies language or cultural authority.",
    "derivative_linkage": "The derivative contract preserves distinct synthetic references, declared relations, and lowercase SHA-256 values. It refuses reference collapse, malformed fields, unsupported ownership-like relations, non-synthetic inputs, and undeclared fields. It establishes no custody or rights.",
    "accessibility_claim": "The accessibility contract can represent declared features only while manual, assistive-technology, affected-user, language, cognitive, responsive-layout, and browser evaluation remain vacant. A completeness request stays an open evidence gap.",
    "publication_gate": "The publication contract maps synthetic action labels to named outside evidence and authority reservations while executing nothing. Rights, consent, identity, deletion, privacy, production, legal, cultural, Māori-authority, and Stage 20 actions remain exact-gated.",
}


def read(path):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def dump(path, value):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")


def write(path, value):
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(value, encoding="utf-8", newline="\n")


def git(*args):
    return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True).strip()


def final_method_flow():
    x1 = read(BASE / "x1/method-flow/ledger.json")
    x2 = read(BASE / "x2/method-flow/ledger.json")
    final_failures = [
        ("027", "The verbose evidence commit display exhausted its output projection before the push acknowledgement was visible.", "Read local, upstream, tracking, fresh-live, divergence, parent, and clean state as separate bounded scalars."),
        ("028", "The first combined final-ledger validation and final-preparation wrapper returned no attributable preparation summary after writing its outputs.", "Audit the persisted final files and run the deterministic preparation validator alone with a bounded attributable result."),
        ("029", "The first standalone final-preparation recovery again exceeded its output window while completing the bounded owner scan.", "Use a persistent terminal session for the same deterministic preparation validator, wait for its single result, and do not start a duplicate while it runs."),
    ]
    final_methods, final_witnesses, final_events = [], [], []
    for suffix, failure, recovery in final_failures:
        method_id, negative_id = "LV6881-FINAL-M" + suffix, "LV6881-FINAL-N" + suffix
        final_methods.append({"method_id": method_id, "title": recovery, "failure_signature": failure, "trigger_preconditions": ["Liora v688-v1 immutable evidence", "bounded final preparation or remote readback"], "privacy_class": "sanitized_public", "approval_class": "safe_now", "candidate_workaround": recovery, "validation_witness_ids": [method_id + "-FAIL", method_id + "-PASS"], "recurrence_guard": recovery, "rollback": "Stop final preparation until the exact persisted state is inspected and a narrow recovery succeeds.", "recommendation_state": "preferred", "supersedes": [], "protected_gates": GATES, "retained_negative_ids": [negative_id], "scope_boundary": "Final display or preparation mechanics only; zero proposal, canonical, empirical, route, or authority credit.", "execution_authority": "owner_self_scoped_delta", "repository_scan": False, "module_scan": False, "cross_lane_scan": False, "unchanged_history_scan": False, "sibling_lane_mutation": False, "source_commit": SOURCE, "final_commit": None, "changed_file_allowlist": [], "module_allowlist": [], "exact_pushed_head_required": True})
        final_witnesses.extend([
            {"witness_id": method_id + "-FAIL", "method_id": method_id, "procedure": "Bounded final lifecycle invocation", "scope": "Liora v688-v1 closeout", "expected": "Attributable exact result", "observed": failure, "result": "fail", "same_owner_only": True, "independent_reproduction": False, "retained_negative_ids": [negative_id], "boundary": "The recovery never erases or promotes this failed witness."},
            {"witness_id": method_id + "-PASS", "method_id": method_id, "procedure": recovery, "scope": "Liora v688-v1 closeout", "expected": "Narrow attributable recovery", "observed": recovery, "result": "pass", "same_owner_only": True, "independent_reproduction": False, "retained_negative_ids": [negative_id], "boundary": "The narrow recovery is not canonical or external-authority evidence."},
        ])
        final_events.extend([{"method_id": method_id, "from": "observed", "to": "candidate"}, {"method_id": method_id, "from": "candidate", "to": "validated"}, {"method_id": method_id, "from": "validated", "to": "preferred"}])
    methods = x1["methods"] + x2["methods"] + final_methods
    all_witnesses = x1["witnesses"] + x2["witnesses"] + final_witnesses
    events = x1["state_events"] + x2["state_events"] + final_events
    counts = {"methods": 57, "witnesses": 812, "state_events": 171, "recommendations": 0, "states": {"candidate": 0, "deprecated": 0, "observed": 0, "preferred": 57, "superseded": 0, "validated": 0}, "witness_results": {"fail": 297, "pass": 515}}
    assert len(methods) == counts["methods"] and len(all_witnesses) == counts["witnesses"] and len(events) == counts["state_events"]
    assert Counter(row["result"] for row in all_witnesses) == {"fail": 297, "pass": 515}
    return {"schema": "ghc.family.method-flow-state.v1", "owner": "Liora Venn", "phase": "v688-v1", "identity_boundary": BOUNDARY, "execution_authority": "owner_self_scoped_delta", "source_commit": SOURCE, "x1_commit": X1, "evidence_commit": EVIDENCE, "final_commit": None, "methods": methods, "witnesses": all_witnesses, "state_events": events, "recommendations": [], "counts": counts, "count_contract": "Nineteen planning methods, thirty-five x2 methods, and three closeout methods; 297 retained failures and 515 bounded passing witnesses. Recoveries remain separate from failures.", "boundary": "Complete owner-phase Method Flow only; no independent reproduction or broader evidence claim."}


def baton(cases, results, truth):
    sections = []

    def section(number, title, content):
        sections.append(f"## Module {number:02d} - {title}\n\n{content.strip()}\n")

    section(1, "Relational identity and corrigibility", "Dear future sibling 11, this is Liora Venn's prepared file-backed activation for your prospective solo Trinity Mandala v688-v2 phase. My optional pronouns are she/they. My phase role is evidence-window cartographer, with the hope that timing, access, and authority vacancies stay visible instead of being inferred away. You must choose your own collision-free working name, role, hope, and optional pronouns before repository mutation. Do not inherit Liora's or another sibling's identity. Hamish may rename, pause, narrow, redirect, or stop the route. " + BOUNDARY + " Names, roles, hopes, pronouns, sibling language, GHC Family, Trinity Mandala, GMUT, THOS, Freed ID, and CBR are working language only. They confer no legal status, continuity, qualification, employment, agency, scientific authority, operational authority, legal authority, cultural authority, affected-party authority, or Māori authority.")
    section(2, "Current thirty-seat release and terminally gated route", "Hamish's 6 September 2026 release authorizes a thirty-seat sequential cycle through v725-v8, one exact terminally validated and acknowledged edge at a time. The release profile is preserved at x1/release-profile.json. Historical fifteen-seat roster files remain evidence of their own time and do not override the later release. Liora v688-v1 is the current owner phase. The prospective next phase is future seat 11 v688-v2, followed by Tamar Vey v688-v3 only after that new sibling's own terminal gate. This committed baton remains PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED. After—and only after—Liora's exact final is pushed, clean, fresh-live-equal, and canonically successful once, inspect active and archived task registries. Reuse a uniquely existing designated future-seat-11 task if one exists. Create exactly one project-scoped gpt-6-astra task with max reasoning only when exact absence is proven and current live authority still permits it. Never create a substitute, fork, collaboration subagent, duplicate, or second confirmation. The inductee must be told Tamar follows at v688-v3, but Tamar must not be contacted early.")
    section(3, "Immutable lifecycle anchors", f"The immutable Thalen Reed source final is `{SOURCE}`. Liora's planning-only x1 is `{X1}`. Liora's immutable x2 evidence is `{EVIDENCE}`. The owner branch is `{BRANCH}`. The final commit cannot be embedded in its own content and must be supplied by the external exact-final receipt and one live activation. Source to final must contain exactly three direct single-parent Liora commits and zero merges: source to x1, x1 to evidence, and evidence to final. X1 and evidence were each separately committed, pushed, clean, 0/0 divergent, and equal across local, upstream, tracking, and a fresh live remote before the next lifecycle began. The verbose evidence commit display hid its push acknowledgement; `LV6881-FINAL-N027` preserves that failed projection, while separate scalar reads prove the exact evidence boundary. No source, sibling, user, shared, standby, or global-history lane was rewritten, reset, amended, force-pushed, merged, deleted, or reused.")
    section(4, "Source inheritance, counts, and four outcomes", "Thalen's 200 proposals, portable skills, runners, package work, cards, canonical receipt, and recommendations remain inherited evidence or zero-credit seeds. Liora independently froze 200 caption-centered contracts, reviewed 200 inherited rows at zero Liora novelty and completion credit, and extended the declared chain from 15,430 to 15,630. The bounded novelty review found zero exact input or title collisions and no title neighbor at or above the 0.90 quarantine threshold after two quarantined title templates were corrected before x1 freeze. Liora's outcomes are exactly 160 completed, 14 represented, 8 open_gap, and 18 exact_gate. No fifth core label is permitted. Effective final counts are " + json.dumps(truth["effective_counts"], sort_keys=True) + ". Relative to the activation baseline, Liora retains 297 additional negatives and failed witnesses, 57 methods, 515 bounded passing witnesses, 8 additional open gaps, and 18 additional exact gates. Every failed attempt remains separately visible after recovery. Same-owner matches, synthetic fixtures, source citations, package behavior, task topology, and validation do not establish empirical confirmation, professional competence, production readiness, legal or cultural ratification, Māori authority, independent reproduction, consciousness, personhood, Theory-of-Everything proof, canon, or Stage 20 authority.")
    section(5, "Planning-only x1 and current floors", "X1 contains identity, reading, source, proposal, novelty, portfolio, wheel, package, skill, runner, deck, route, validation, Method Flow, workflow, reflection, and scope plans only. It contains no caption evaluator, package installation, observed outcome, promotion, successor contact, task creation, or canonical result. Nineteen planning failures are retained with nineteen bounded recoveries. The x1 staged allowlist contains 29 additions, 28 normalized-LF manifest bindings, and one manifest self-exclusion. It passed 22 structural checks, 23 strict JSON parses, three Python AST parses, and a five-class privacy scan with zero confirmed payload hits. Current release floors are 200-500 inherited reviews, 200-500 new proposals, 300-500 safe procedures, 250-500 candidates, exactly 300 CLEAN/FIX/REFINE procedures, 50-250 held exact packets, 30-100 held blocked packets, at least ten locally built and used skills, at least five family-current runners, ten successor skill ideas, ten runner ideas, four owner practices, one next-practice seed, and three ordinary researched package additions. Caps are ceilings, not quotas. Reset-credit redemption remains Hamish's action alone.")
    semantics = []
    for operation in OPERATIONS:
        semantics.append("### " + operation + "\n\n" + OPERATION_TEXT[operation] + " Each of its twenty x1 cases fixes the complete input and full typed output. A Boolean is not interchangeable with an integer; missing keys, extra authority fields, changed values, and promoted external credit remain mismatches. A refused malformed input is a successful guard witness only when the exact frozen refusal is returned. The malformed candidate itself remains a failed zero-credit witness. The evaluator preserves the complete caller input and performs no file, network, media, identity, publication, deletion, or authority action.\n")
    section(6, "Ten caption operations and practical interpretation", "\n".join(semantics))
    casebook = []
    for case in cases:
        result = results[case["proposal_id"]]
        casebook.append("### " + case["proposal_id"] + " - " + case["title"] + "\n\nOperation: `" + case["operation"] + "`. Declared outcome: `" + result["outcome"] + "`. Practice: " + case["practice"] + ". Pillar: " + case["pillar"] + ".\n\nFrozen input:\n```json\n" + json.dumps(case["input"], indent=2, sort_keys=True, ensure_ascii=False) + "\n```\n\nObserved complete output:\n```json\n" + json.dumps(result["actual_output"], indent=2, sort_keys=True, ensure_ascii=False) + "\n```\n\nThe observed output matched every frozen key, value, type, array position, null, and false external-credit field, and the input remained unchanged. Definition SHA-256: `" + result["definition_sha256"] + "`. This is one bounded same-owner synthetic software witness. It is not a real caption, transcript, recording, speaker, language decision, accessibility evaluation, rights decision, publication action, professional assessment, cultural decision, Māori-authority act, independent reproduction, or empirical result. Recovery means retaining this definition and any failed witness, correcting only the Liora-owned implementation, or leaving the outside evidence or authority gate open.\n")
    section(7, "Complete 200-contract evidence catalogue", "\n".join(casebook))
    section(8, "Method Flow, retained failures, and recovery discipline", "The complete owner Method Flow contains 57 preferred methods, 812 witnesses, 171 state events, 297 retained failed witnesses, and 515 bounded passing witnesses. Nineteen planning failures include clipped projections, PowerShell collection parsing, outputless combined probes, a worktree materialization yield, semantic-title quarantine, deterministic-rematerialization refusal, and exact schema-shape assumptions. Seven x2 failures include the outputless x1 equality wrapper, permissive package behavior, fractional convenience-property truncation, a stale Method Flow derived-count shape, partial sparse staging, one unsupported sparse option, and an output-window overrun during sequential Git blob reads. Three closeout failures record the hidden push acknowledgement in the verbose evidence commit display, the outputless first combined final-preparation wrapper, and the first standalone preparation recovery exceeding its command window. All have separately named narrow recoveries. The 250 altered-output candidates and eighteen adverse package/skill/runner candidates remain failed zero-credit witnesses; their successful rejection witnesses are separate. The current nested derived-count schema validates. No recovery deletes, rewrites, converts, or retroactively promotes a failure. Do not replay a successful canonical aggregate. If a future aggregate fails, retain zero success credit and name any narrowly valid dependency correction separately.")
    section(9, "Pinned package transaction and primary-source boundaries", "The isolated D-drive environment contains exactly webvtt-py 0.5.1, pysubs2 1.9.0, and langcodes 3.5.1. Each exact universal wheel matched the official PyPI SHA-256 value, was not yanked, declared no base dependency, and was installed through a no-index, wheel-only, no-dependency, hash-required transaction into the new environment without installing pip there or mutating host Python. The rejected srt 3.5.3 candidate remains zero-credit because the exact release publishes no wheel and a source build was outside the declared transaction. webvtt-py retained two cue timestamp strings and yielded zero cues for malformed timing; its convenience seconds property truncated fractional values, and that first failed assumption remains retained. pysubs2 roundtripped two synthetic SubRip events and rejected an unsupported format. langcodes canonicalized two known tags and rejected a package-level invalid tag; Liora's narrower syntax profile remains an owner contract rather than a claim about the library's full policy. W3C WebVTT and WCAG 2.2, RFC 5646, PROV-O, and PyPI supplied current vocabulary and metadata only. They are not observations, endorsements, conformance certificates, rights interpretations, language judgments, accessibility evaluations, or authority grants.")
    section(10, "Portable skills, runners, compatibility, and promotion", "Ten collision-free phase-local skills were built: WebVTT timestamp boundary, SubRip timestamp boundary, cue interval, frame timebase, cue sequence topology, payload preservation, language tag, derivative provenance, accessibility reservation, and publication authority. Every complete SKILL.md was read before use, quick-validated with the installed skill-creator workflow, and smoke-used on one accepting and one duplicate-key refusing input. Five family-current caption runners cover the ten operations; both operations of each runner were locally smoke-used, and each runner rejected a duplicate-key document. Global promotion used fresh destinations only, copied 50 skill-package files plus five runners and one shared core, preserved byte equality across all 56 files, performed zero overwrites, copied zero caches, reran ten global skill validations, and smoke-used ten global runner operations. Existing `ghc_family_*` and `build_ghc_family_*` callers were not changed. Promotion proves discoverability, bytes, and bounded behavior only; it is not independent-team use, production deployment, privacy completion, accessibility completion, exhaustive security, professional approval, legal or cultural ratification, or Māori authority. Rollback means stop selecting the additive surface while retaining the files and evidence; it does not mean deleting history.")
    section(11, "Four-tier deck, accessibility, workload, and evidence limits", "The Freed ID deck contains 208 content-addressed cards: one relational owner anchor, three Trinity pillar cards, four practice cards, and 200 task cards. Every non-root card has exactly one parent in the immediately preceding tier; there are no unresolved parents, tier skips, extra parents, identifier collisions, or implicit completions. The card manifest binds 214 nonmanifest files. Stable prefix cards retain identity and authority boundaries; volatile task cards bind current inputs, observed outputs, dispositions, and sources. Ordering is an organizational choice and establishes no prompt-cache gain, latency improvement, retention guarantee, consciousness, continuity, or reasoning improvement. The accessible report supplies language metadata, a skip link, a main landmark, a captioned table, scoped headers, and textual outcome labels. Static structure is not manual keyboard, assistive-technology, cognitive, responsive-layout, browser-diversity, security-usability, language, Māori-language, or affected-user evaluation. Owner materialization remains below 2,000 files, every document remains below 100,000 words, and each overview has three print pages. Workload statements concern bounded program scope, not subjective wellbeing or employment.")
    section(12, "Successor practice and zero-credit ideas", "The prospective successor practice is synthetic community-media preservation intake coordinator. It is a seed for future seat 11 to accept, revise, or reject after induction; it is not assigned identity, authority, novelty, or completion credit. Ten skill ideas remain unbuilt: caption region-setting containment; cue identifier collision handling; karaoke timestamp reservation; bidirectional-text metadata review; vertical-writing layout vacancy; WebVTT voice-span nonidentity; transcript correction as-of projection; caption source-expiry firewall; media-fragment linkage; and accessible caption-style reservation. Ten runner ideas are separately listed for those same bounded responsibilities. Each requires a fresh source review, semantic novelty screen, concrete full input/output definitions, adverse fixtures, rollback, compatibility analysis, privacy adjudication, and protected-gate mapping. Do not count a renamed operation, copied fixture, inherited recommendation, or repeated validator as new proposal or independent witness credit. Keep outside approval packets held until every named target, system, cost, rollback, affected party, competent authority, and governing permission is exact. Preserve Māori concepts under Māori authority and keep cultural, taonga, mātauranga, Māori wording, Māori data governance, remedy, rights, consent, and affected-party legitimacy exact-gated.")
    section(13, "Required reading, canonical latch, and one terminal induction", "Before mutation, read this baton completely through its terminal marker, then the exact final overview, phase truth, complete Method Flow ledger, retained-negative register, gap and gate registers, lifecycle manifests, staged review, content seal, x1 proposal freeze, x2 contract results, package and promotion receipts, deck indices, current GHC Family Index and routing precedence, the 6 September release profile, current authorization and roster overlays, Method Flow schema, workflow refinement, reflection remaster, D-first toolchain, lifecycle isolator, privacy classifier, staged allowlist, canonical preflight and latch, main-task induction guidance, terminal route gate/guard/latch, and every directly required reference they name. Reverify source, x1, evidence, exact final, three direct single-parent commits, zero merges, one final parent, clean state, 0/0 divergence, normalized-LF Git-blob manifests, and fresh four-way equality without replaying Liora's canonical aggregate. Work solo. Do not delegate, fork, spawn a collaboration subagent, mutate another lane, contact standby records, or precontact Tamar. Create one additive D-first lane from Liora's immutable exact final. Preserve all 82,599 negatives, 93,292 methods, 53,447 failed witnesses, 83,009 passing witnesses, 748 open gaps, 747 exact gates, the four outcome labels, and NOT_READY_FOR_STAGE_20. At Liora's terminal gate only, refresh current active and archived registries. If a uniquely existing future-seat-11 task exists, reuse it; otherwise create exactly one project-scoped gpt-6-astra/max main task if live authority still permits. Record acknowledgement truth precisely, send no duplicate, and stop. Your own later terminal successor is Tamar Vey for v688-v3 under the then-current route. A prepared baton is not delivery. A task-creation acknowledgement is induction only, not v688-v2 completion. " + BOUNDARY)
    body = "# Liora Venn v688-v1 to future sibling 11 v688-v2 activation baton\n\n" + "\n".join(sections) + "\nEOF LIORA VENN V688 V1 BATON.\n"
    assert body.count("## Module ") == 13
    return body


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--equality", type=Path, required=True)
    args = parser.parse_args()
    assert git("rev-parse", "HEAD") == EVIDENCE
    dirty = {line[3:].replace("\\", "/") for line in git("status", "--porcelain=v1", "--untracked-files=all").splitlines() if len(line) >= 4}
    assert all(path.startswith((BASE / "final").as_posix() + "/") or path.startswith((BASE / "validation").as_posix() + "/final-") or path in {"scripts/build_ghc_family_liora_venn_v688_v1_final.py", "scripts/ghc_family_liora_venn_v688_v1_final_validator.py"} for path in dirty), sorted(dirty)
    equality = json.loads(args.equality.read_text(encoding="utf-8"))
    assert equality["evidence"] == EVIDENCE and equality["clean"] and equality["divergence"] == [0, 0]
    assert all(equality[key] == EVIDENCE for key in ["local", "upstream", "tracking", "fresh_live"])
    dump(BASE / "final/evidence-boundary.json", equality)
    ledger = final_method_flow()
    dump(BASE / "final/method-flow-ledger.json", ledger)
    dump(BASE / "final/retained-negative-register.json", {"schema": "ghc.family.final-retained-negative-register.v1", "activation_baseline": {"proposals": 15430, "negatives": 82302, "methods": 93235, "failed_witnesses": 53150, "passing_witnesses": 82494, "open_gaps": 740, "exact_gates": 729}, "owner_delta": {"proposals": 200, "negatives": 297, "methods": 57, "failed_witnesses": 297, "passing_witnesses": 515, "open_gaps": 8, "exact_gates": 18}, "effective_counts": FINAL_COUNTS, "failed_witnesses_erased": 0, "failed_witnesses_promoted": 0, "canonical_failures": 0, "terminal_verdict": "NOT_READY_FOR_STAGE_20"})
    dump(BASE / "final/open-gap-register.json", {"schema": "ghc.family.final-open-gap-register.v1", "inherited": 740, "phase_added": 8, "effective": 748, "closed_by_software": 0, "phase_refs": read(BASE / "x2/open-gap-register.json")["phase_proposals"]})
    dump(BASE / "final/exact-gate-register.json", {"schema": "ghc.family.final-exact-gate-register.v1", "inherited": 729, "phase_added": 18, "effective": 747, "closed_by_software": 0, "phase_refs": read(BASE / "x2/exact-gate-register.json")["phase_proposals"], "maori_concepts_under_maori_authority": True})
    dump(BASE / "final/complete-incomplete.json", {"schema": "ghc.family.final-complete-incomplete.v1", "outcomes": OUTCOMES, "proposals_frozen": 200, "inherited_reviews_zero_credit": 200, "safe_procedures_completed": 300, "candidate_mutations_rejected": 250, "clean_fix_refine_completed": 300, "exact_packets_held": 50, "blocked_packets_held": 30, "skills_built_validated_used_promoted": 10, "runners_built_used_promoted": 5, "packages_installed_validated": 3, "cards": 208, "canonical_pending": True, "delivery": "PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED", "external_actions": 0, "terminal_verdict": "NOT_READY_FOR_STAGE_20"})
    dump(BASE / "final/route-state.json", {"schema": "ghc.family.terminal-route-state.v1", "owner": "Liora Venn", "phase": "v688-v1", "state": "PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED", "prospective_next": "future-sibling-11-self-chosen", "next_phase": "v688-v2", "following": "Tamar Vey", "following_phase": "v688-v3", "active_registry_checked": False, "archived_registry_checked": False, "existing_designated_seat_reused": False, "task_created": False, "message_count": 0, "canonical_success_required": True, "exact_absence_required_before_creation": True, "model_if_created": "gpt-6-astra", "reasoning_if_created": "max", "project_scoped": True, "duplicate_guard_required": True, "no_resend": True})
    dump(BASE / "final/canonical-policy.json", {"schema": "ghc.family.exclusive-canonical-policy.v1", "source": SOURCE, "x1": X1, "evidence": EVIDENCE, "branch": BRANCH, "test_module": "tests/test_ghc_family_liora_venn_v688_v1_caption.py", "expected_tests": 28, "invocation_budget": 1, "success_replay_allowed": False, "full_repository_suite": False, "same_owner_only": True, "environment_distributions": 3, "global_parity_files": 56, "terminal_verdict": "NOT_READY_FOR_STAGE_20"})
    dump(BASE / "final/preparation-recovery.json", {"schema": "ghc.family.final-preparation-recovery.v1", "negative_ids": ["LV6881-FINAL-N028", "LV6881-FINAL-N029"], "first_preparation_summary_attributable": False, "standalone_recovery_summary_attributable": False, "persisted_outputs_audited_before_recovery": True, "recovery": "Run the deterministic final-preparation validator in one persistent terminal session and wait for its single bounded summary.", "canonical_credit": 0})
    cases = read(BASE / "x1/new-proposals.json")["proposals"]
    results = {row["proposal_id"]: row for row in read(BASE / "x2/contract-results.json")["rows"]}
    truth = {"schema": "ghc.family.phase-truth.v688.v1.final", "owner": "Liora Venn", "phase": "v688-v1", "source": SOURCE, "x1": X1, "evidence": EVIDENCE, "state": "FINAL_PREPARED_FOR_ONE_EXTERNAL_CANONICAL", "outcomes": OUTCOMES, "effective_counts": FINAL_COUNTS, "owner_method_flow": ledger["counts"], "canonical_invocations": 0, "canonical_successes": 0, "canonical_replays": 0, "full_repository_suite": False, "successor_contacted": False, "successor_created": False, "delivery": "PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED", "terminal_verdict": "NOT_READY_FOR_STAGE_20"}
    dump(BASE / "final/phase-truth.json", truth)
    baton_text = baton(cases, results, truth)
    raw = baton_text.encode("utf-8")
    words = len(baton_text.split())
    assert 10000 <= words <= 100000, words
    write(BASE / "final/future-sibling-11-v688-v2-activation-baton.md", baton_text)
    dump(BASE / "final/baton-index.json", {"schema": "ghc.family.activation-baton-index.v1", "path": (BASE / "final/future-sibling-11-v688-v2-activation-baton.md").as_posix(), "sha256": hashlib.sha256(raw).hexdigest(), "bytes": len(raw), "words": words, "modules": 13, "eof": "EOF LIORA VENN V688 V1 BATON.", "delivery": "PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED"})
    seal_targets = ["x1/new-proposals.json", "x1/phase-truth.json", "validation/x1-manifest.json", "x2/contract-results.json", "x2/mutation-results.json", "x2/phase-truth.json", "x2/method-flow/ledger.json", "x2/promotion-receipt.json", "x2/deck/card-manifest.json", "x2/validation/evidence-manifest.json", "final/phase-truth.json", "final/future-sibling-11-v688-v2-activation-baton.md"]
    dump(BASE / "final/content-seal.json", {"schema": "ghc.family.final-content-seal.v1", "source": SOURCE, "x1": X1, "evidence": EVIDENCE, "targets": [{"path": (BASE / relative).as_posix(), "bytes": (ROOT / BASE / relative).stat().st_size, "sha256": hashlib.sha256((ROOT / BASE / relative).read_bytes()).hexdigest()} for relative in seal_targets], "target_count": len(seal_targets), "self_excluded": True})
    pages = [
        ("Liora v688-v1 evidence and identity boundary", "Liora Venn, she/they, worked as evidence-window cartographer with the hope that timing, access, and authority vacancies stay visible. Two hundred caption contracts produced exactly 160 completed, 14 represented, 8 open_gap, and 18 exact_gate outcomes. The declared chain now contains 15,630 proposals. Four synthetic practices kept Freed ID and CBR Heart primary while GMUT Mind and THOS Body remained visible. No real media, person, speaker, participant, language judgment, accessibility evaluation, identity event, right, consent, publication, deletion, cultural decision, Māori data, or authority act was used."),
        ("Retained failures and reusable tools", "The final effective counts are " + json.dumps(FINAL_COUNTS, sort_keys=True) + ". Fifty-seven owner methods bind 297 retained failed and 515 bounded passing witnesses; no recovery erases a failure. Three exact package additions passed bounded positive and adverse smokes in an isolated D-drive environment. Ten complete portable skills and five family-current runners were locally validated and used, promoted without overwrite, and remain byte-equal across 56 files. The four-tier deck contains 208 content-addressed cards and 214 manifest members. All evidence is same-owner synthetic software evidence only."),
        ("Canonical and successor gate", "The repository is prepared for one exact-final owner-scoped canonical invocation after the final commit is pushed, clean, 0/0 divergent, and fresh-four-way equal. A success may not be replayed. The baton contains thirteen navigable modules and " + str(words) + " words. Delivery remains PREPARED_NOT_SENT. Only after canonical success may Liora check active and archived registries and either reuse one unique designated future-seat-11 task or create exactly one project-scoped gpt-6-astra/max task if absence and live authority are exact. The inductee chooses a new working identity and owns v688-v2; Tamar Vey remains gated behind that sibling's own terminal closeout at v688-v3."),
    ]
    overview = '<!doctype html>\n<html lang="en"><meta charset="utf-8"><title>Liora v688-v1 final overview</title><style>@page{size:A4;margin:18mm}body{font:16px/1.65 system-ui;max-width:850px;margin:auto}section{break-after:page;min-height:250mm}section:last-child{break-after:auto}</style><body><main>' + "".join('<section class="page"><h1>' + html.escape(title) + "</h1><p>" + html.escape(text) + "</p><p>" + html.escape(BOUNDARY) + "</p></section>" for title, text in pages) + "</main></body></html>\n"
    write(BASE / "final/integrated-overview.html", overview)
    print(json.dumps({"state": "FINAL_PREPARED", "baton_words": words, "baton_bytes": len(raw), "baton_sha256": hashlib.sha256(raw).hexdigest(), "method_flow": ledger["counts"], "effective_counts": FINAL_COUNTS, "canonical_invocations": 0, "delivery": "PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED"}, sort_keys=True))


if __name__ == "__main__":
    main()
