#!/usr/bin/env python3
"""Eiren Kestrel v656-v5 source, proposal, and startup catalogue."""

from __future__ import annotations


def _source(
    source_id: str,
    title: str,
    publisher: str,
    url: str,
    status: str,
    use: str,
) -> dict:
    return {
        "source_id": source_id,
        "title": title,
        "publisher": publisher,
        "url": url,
        "status": status,
        "use": use,
    }


OFFICIAL_SOURCES = [
    _source(
        "ISO-4149-2025",
        "ISO 4149:2025 Green coffee — Olfactory and visual examination and determination of foreign matter and defects",
        "International Organization for Standardization",
        "https://www.iso.org/standard/87699.html",
        "published_2025",
        "green-coffee examination, foreign-matter, and defect-field vocabulary only; no real sample, inspection, grading, conformity, commercial, or arbitration claim",
    ),
    _source(
        "ISO-4150-2011",
        "ISO 4150:2011 Green coffee or raw coffee — Size analysis — Manual and machine sieving",
        "International Organization for Standardization",
        "https://www.iso.org/standard/44602.html",
        "published_under_review_2026",
        "screen, sieve, size-distribution, and presentation vocabulary only; no real sampling, sieving, measurement, conformity, or quality claim",
    ),
    _source(
        "ISO-6668-2008",
        "ISO 6668:2008 Green coffee — Preparation of samples for use in sensory analysis",
        "International Organization for Standardization",
        "https://www.iso.org/standard/44609.html",
        "current_confirmed_2017",
        "sample-preparation, roast, grind, beverage, and comparative-assessment vocabulary only; no standard-text reproduction, real preparation, sensory result, acceptance, or rejection decision",
    ),
    _source(
        "ISO-20481-2008",
        "ISO 20481:2008 Coffee and coffee products — Determination of caffeine content using HPLC",
        "International Organization for Standardization",
        "https://www.iso.org/standard/34185.html",
        "published_under_review_2026",
        "caffeine analyte, method, and claim-reservation vocabulary only; no sample, chromatography, measurement, laboratory, compliance, or health claim",
    ),
    _source(
        "ISO-23134-2022",
        "ISO 23134:2022 Coffee and coffee products — Determination of particle size of ground roasted coffee",
        "International Organization for Standardization",
        "https://www.iso.org/standard/74672.html",
        "published_under_review_2026",
        "particle-size, sieve-motion, apparatus, procedure, unit, and result-presentation vocabulary only; no real grinding, sieving, measurement, conformity, or performance claim",
    ),
    _source(
        "SCA-CVA",
        "Coffee Value Assessment",
        "Specialty Coffee Association",
        "https://sca.coffee/value-assessment",
        "current_documented_surface_2026",
        "physical, descriptive, affective, and extrinsic assessment field separation only; no professional cupping, score, quality, value, market, or certification claim",
    ),
    _source(
        "NZ-MPI-FCP",
        "Food control plans",
        "New Zealand Ministry for Primary Industries",
        "https://www.mpi.govt.nz/food-business/running-a-food-business/food-control-plans",
        "current_2026_context",
        "food-risk, plan, verification, cleaning, training, maintenance, and record-reservation context only; no registration, verification, safe-food, compliance, or legal claim",
    ),
    _source(
        "NZ-WORKSAFE-MACHINERY",
        "Safe use of machinery",
        "WorkSafe New Zealand",
        "https://www.worksafe.govt.nz/topic-and-industry/machinery/safe-use-of-machinery/",
        "current_guidance",
        "hazard, guarding, isolation, competent-assessment, and stop-work reservation only; no machinery operation, risk assessment, control selection, or safety authorization",
    ),
    _source(
        "W3C-PROV-O",
        "PROV-O: The PROV Ontology",
        "W3C",
        "https://www.w3.org/TR/prov-o/",
        "stable_recommendation",
        "entity, activity, derivation, revision, attribution, generation, invalidation, correction, and custody lineage",
    ),
    _source(
        "RFC-3339",
        "RFC 3339: Date and Time on the Internet: Timestamps",
        "RFC Editor",
        "https://www.rfc-editor.org/rfc/rfc3339.html",
        "stable",
        "synthetic UTC lexical timestamps, intervals, observations, revisions, and handovers",
    ),
    _source(
        "RFC-8785",
        "RFC 8785: JSON Canonicalization Scheme",
        "RFC Editor",
        "https://www.rfc-editor.org/rfc/rfc8785.html",
        "stable",
        "deterministic synthetic contract, receipt, statement, and manifest serialization",
    ),
    _source(
        "NIST-SP811",
        "NIST SP 811: Guide for the Use of the International System of Units",
        "National Institute of Standards and Technology",
        "https://www.nist.gov/publications/guide-use-international-system-units-si",
        "stable",
        "quantity, unit, symbol, conversion, temperature, mass, time, pressure, flow, and uncertainty discipline only; no real metrology or calibration",
    ),
    _source(
        "W3C-WCAG-22",
        "Web Content Accessibility Guidelines 2.2",
        "W3C",
        "https://www.w3.org/TR/WCAG22/",
        "current_recommendation",
        "structural accessibility vocabulary with manual, browser, assistive-technology, Māori-language, cognitive, low-vision, and affected-user evaluation reserved",
    ),
    _source(
        "NZ-PRIVACY-PRINCIPLES",
        "Privacy Act 2020 information privacy principles",
        "Office of the Privacy Commissioner New Zealand",
        "https://www.privacy.org.nz/privacy-principles/",
        "current_including_ipp3a_from_2026_05_01",
        "purpose, source, notice, fairness, security, access, correction, retention, use, disclosure, and identifier reservations only; no legal advice",
    ),
    _source(
        "NZ-CONSUMER-CGA",
        "Consumer Guarantees Act",
        "New Zealand Consumer Protection",
        "https://www.consumerprotection.govt.nz/general-help/consumer-laws/consumer-guarantees-act",
        "current_context",
        "description, reasonable-care, disclosure, complaint, and remedy-reservation vocabulary only; no legal advice, liability, customer decision, or remedy authority",
    ),
    _source(
        "W3C-VC-DM-20",
        "Verifiable Credentials Data Model v2.0",
        "W3C",
        "https://www.w3.org/TR/vc-data-model-2.0/",
        "current_recommendation",
        "synthetic credential vocabulary only; no conforming credential, real issuer, holder, verifier, proof, trust decision, or interoperability event",
    ),
    _source(
        "RFC-9943",
        "RFC 9943: An Architecture for Trustworthy and Transparent Digital Supply Chains",
        "IETF / RFC Editor",
        "https://www.rfc-editor.org/rfc/rfc9943.html",
        "current_proposed_standard",
        "signed-statement, transparent-statement, receipt, registration-policy, and transparency-service vocabulary only; no live key, signature, service, audit, trust, or non-equivocation claim",
    ),
    _source(
        "C2PA-2.4",
        "C2PA Content Credentials Technical Specification 2.4",
        "Coalition for Content Provenance and Authenticity",
        "https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html",
        "current_2026",
        "manifest, assertion, ingredient, action, binding, validation-result, and trust-model vocabulary only; no signed manifest, certificate, validation, trust, or authenticity claim",
    ),
    _source(
        "USDA-FDC-API",
        "FoodData Central API Guide",
        "United States Department of Agriculture",
        "https://fdc.nal.usda.gov/api-guide/",
        "current_documented_surface_2026",
        "public food-data API, key, rate-limit, endpoint, field, and attribution vocabulary only; zero keys, requests, rows, nutrient interpretations, or health conclusions",
    ),
    _source(
        "OECD-FAO-AG-SUPPLY",
        "OECD-FAO Guidance for Responsible Agricultural Supply Chains",
        "OECD and Food and Agriculture Organization of the United Nations",
        "https://www.oecd.org/en/publications/oecd-fao-guidance-for-responsible-agricultural-supply-chains_9789264251052-en.html",
        "current_reference",
        "risk-based due-diligence, impact, disclosure, worker, community, producer, indigenous-peoples, and remedy-reservation questions only; no audit, certification, legal conclusion, or affected-party authorization",
    ),
    _source(
        "TMR-PRINCIPLES",
        "Principles of Māori Data Sovereignty",
        "Te Mana Raraunga",
        "https://www.temanararaunga.maori.nz/principles-of-maori-data-sovereignty",
        "current",
        "Māori rights, interests, governance, jurisdiction, language, collective benefit, and authority reservation only; never a substitute for Māori authority",
    ),
    _source(
        "LOCAL-CONTEXTS-TK-BC",
        "Traditional Knowledge and Biocultural Labels Usage and Style Guide",
        "Local Contexts",
        "https://localcontexts.org/wp-content/uploads/2023/08/TK-and-BC-Labels-Usage-and-Style-Guide.pdf",
        "current_reference",
        "community-originated notice and provenance reservation only; no label selection, community decision, cultural authorization, or Māori wording",
    ),
]


# number, title, slug, pillar, disposition, semantic mechanism, source ids
PROPOSAL_ROWS = [
    (
        1,
        "Green-coffee lot intake and custody passport with synthetic batch token, declared origin placeholder, received-state note, bag count, seal state, correction path, and no-real-producer-or-bean claim",
        "coffee-lot-intake-custody",
        "Freed ID and CBR Heart",
        "completed",
        "green-coffee lot intake, synthetic batch token, origin placeholder, received state, bag-count placeholder, seal state, custody, correction, and real-producer and real-bean refusal",
        ["W3C-PROV-O", "RFC-3339", "NZ-PRIVACY-PRINCIPLES", "OECD-FAO-AG-SUPPLY"],
    ),
    (
        2,
        "Green-coffee foreign-matter and defect-observation schema with category placeholder, count and mass units, sample hold, observer-role hold, uncertainty, quarantine, and no-grade-or-acceptance claim",
        "coffee-defect-observation",
        "GMUT Mind",
        "completed",
        "foreign-matter and defect-observation fields, category placeholder, count and mass units, sample and observer holds, uncertainty, quarantine, and grading and acceptance refusal",
        ["ISO-4149-2025", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        3,
        "Green-coffee screen-size distribution envelope with sieve identity placeholder, aperture unit, retained-mass placeholder, closure residual, obstruction cue, instrument hold, and no-size-conformity claim",
        "coffee-screen-size-envelope",
        "GMUT Mind",
        "completed",
        "screen-size distribution, sieve identity placeholder, aperture unit, retained-mass placeholder, closure residual, obstruction cue, instrument hold, and size-conformity refusal",
        ["ISO-4150-2011", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        4,
        "Coffee roaster batch, drum, burner-or-element, fan, damper, probe-placeholder, charge state, exhaust path, interlock hold, revision, and no-machine-operation topology",
        "coffee-roaster-topology",
        "THOS Body and GMUT Mind",
        "completed",
        "roaster batch, drum, heat-source, fan, damper, probe placeholder, charge state, exhaust path, interlock hold, topology revision, and machine-operation refusal",
        ["NZ-WORKSAFE-MACHINERY", "W3C-PROV-O", "RFC-8785"],
    ),
    (
        5,
        "Roast thermal-trace contract with synthetic trace token, charge and environmental temperature placeholders, timestamp interval, sampling cadence, missing segment, uncertainty, and no-profile-performance claim",
        "coffee-roast-thermal-trace",
        "GMUT Mind",
        "completed",
        "synthetic roast thermal trace, charge and environmental temperature placeholders, time interval, cadence, missing segment, uncertainty, provenance, and profile-performance refusal",
        ["NIST-SP811", "RFC-3339", "W3C-PROV-O"],
    ),
    (
        6,
        "Roast heat-input, gas-or-electric source, airflow, pressure-placeholder, fuel-or-energy quantity, damper state, dependency, efficiency hold, and no-consumption-or-emissions claim ledger",
        "coffee-roast-energy-airflow",
        "GMUT Mind and THOS Body",
        "completed",
        "heat-input source, airflow, pressure placeholder, energy quantity, damper state, dependency, efficiency hold, and consumption and emissions refusal",
        ["NIST-SP811", "NZ-WORKSAFE-MACHINERY", "W3C-PROV-O"],
    ),
    (
        7,
        "Roast event-state chart with turning-point, colour-change, first-crack-placeholder, development interval, drop state, cooling start, ambiguous cue, correction, and no-sensory-or-doneness conclusion",
        "coffee-roast-event-state",
        "GMUT Mind",
        "completed",
        "roast event-state chart, turning point, colour-change and first-crack placeholders, development interval, drop and cooling states, ambiguity, correction, and doneness refusal",
        ["ISO-6668-2008", "RFC-3339", "W3C-PROV-O"],
    ),
    (
        8,
        "Green-to-roasted coffee mass-balance record with input, output, retained-sample, chaff-placeholder, loss fraction, unit, closure residual, uncertainty, and no-yield-or-quality conclusion",
        "coffee-roast-mass-balance",
        "GMUT Mind",
        "completed",
        "green-to-roasted mass balance, input and output placeholders, retained sample, chaff placeholder, loss fraction, unit, closure residual, uncertainty, and yield and quality refusal",
        ["NIST-SP811", "W3C-PROV-O", "RFC-8785"],
    ),
    (
        9,
        "Roasted-coffee colour and development observation board with device-or-visual method placeholder, scale hold, replicate, lighting context, uncertainty, calibration absence, and no-roast-degree classification",
        "coffee-colour-development-observation",
        "GMUT Mind",
        "completed",
        "roasted-coffee colour and development observation, method placeholder, scale hold, replicate, lighting context, uncertainty, calibration absence, and roast-degree classification refusal",
        ["ISO-6668-2008", "SCA-CVA", "W3C-PROV-O"],
    ),
    (
        10,
        "Coffee grinding and particle-distribution ledger with grinder and burr placeholders, setting token, dose, sieve-range, fines cue, retention, static cue, instrument hold, and no-grind-performance claim",
        "coffee-grind-particle-ledger",
        "GMUT Mind and THOS Body",
        "completed",
        "grinder and burr placeholders, setting token, dose, particle and sieve range, fines cue, retention, static cue, instrument hold, and grind-performance refusal",
        ["ISO-23134-2022", "NIST-SP811", "NZ-WORKSAFE-MACHINERY"],
    ),
    (
        11,
        "Coffee brew-water composition and temperature envelope with source placeholder, treatment state, hardness and alkalinity placeholders, pH hold, temperature interval, uncertainty, and no-potability-or-suitability claim",
        "coffee-brew-water-envelope",
        "GMUT Mind and CBR Heart",
        "completed",
        "brew-water source placeholder, treatment state, composition placeholders, pH hold, temperature interval, uncertainty, provenance, and potability and suitability refusal",
        ["NIST-SP811", "NZ-MPI-FCP", "W3C-PROV-O"],
    ),
    (
        12,
        "Coffee recipe ratio and contact-time contract with coffee-mass placeholder, water-mass placeholder, ratio, dose sequence, bloom-or-preinfusion state, interval, amendment, and no-taste-or-extraction promise",
        "coffee-recipe-ratio-time",
        "GMUT Mind",
        "completed",
        "coffee and water mass placeholders, ratio, dose sequence, bloom or preinfusion state, contact interval, amendment, provenance, and taste and extraction-promise refusal",
        ["NIST-SP811", "RFC-3339", "ISO-6668-2008"],
    ),
    (
        13,
        "Coffee filter-bed flow and pressure relation graph with vessel placeholder, filter medium, bed depth placeholder, flow interval, pressure placeholder, channel cue, bypass cue, and no-equipment-setting instruction",
        "coffee-filter-bed-flow",
        "GMUT Mind and THOS Body",
        "completed",
        "filter-bed vessel placeholder, filter medium, bed-depth placeholder, flow interval, pressure placeholder, channel and bypass cues, relation graph, and equipment-setting refusal",
        ["NIST-SP811", "W3C-PROV-O", "NZ-WORKSAFE-MACHINERY"],
    ),
    (
        14,
        "Coffee beverage concentration and extraction-yield observation envelope with beverage-mass placeholder, concentration-placeholder, calculation lineage, replicate, uncertainty, instrument hold, and no-optimality conclusion",
        "coffee-extraction-observation",
        "GMUT Mind",
        "completed",
        "beverage-mass and concentration placeholders, extraction calculation lineage, replicate, uncertainty, instrument hold, correction, and optimality refusal",
        ["NIST-SP811", "ISO-6668-2008", "W3C-PROV-O"],
    ),
    (
        15,
        "Synthetic coffee sensory-sample preparation and blinding docket with sample token, roast-and-grind placeholders, vessel order, randomization hold, assessor-role hold, palate-state refusal, and no-cupping-score claim",
        "coffee-sensory-sample-docket",
        "CBR Heart and GMUT Mind",
        "completed",
        "synthetic sensory-sample preparation, sample token, roast and grind placeholders, vessel order, randomization and assessor-role holds, palate-state refusal, and cupping-score refusal",
        ["ISO-6668-2008", "SCA-CVA", "W3C-PROV-O"],
    ),
    (
        16,
        "Coffee descriptive-vocabulary and uncertainty record with aroma, flavour, texture, aftertaste, intensity-placeholder, assessor-context hold, disagreement, language, accessibility, and no-quality-or-market-value claim",
        "coffee-sensory-language-boundary",
        "CBR Heart",
        "completed",
        "descriptive sensory vocabulary, intensity placeholder, assessor-context hold, disagreement, language, accessibility, uncertainty, and quality and market-value refusal",
        ["SCA-CVA", "W3C-WCAG-22", "NZ-PRIVACY-PRINCIPLES"],
    ),
    (
        17,
        "Coffee caffeine, acrylamide, contaminant, nutrition, dose, laboratory-method, sample, uncertainty, competent-review, and no-health-or-compliance claim firewall",
        "coffee-chemical-claim-firewall",
        "CBR Heart and GMUT Mind",
        "completed",
        "caffeine, acrylamide, contaminant, nutrition, dose, laboratory-method, sample, uncertainty, competent-review, and health and compliance claim refusal",
        ["ISO-20481-2008", "NZ-MPI-FCP", "USDA-FDC-API"],
    ),
    (
        18,
        "Coffee roaster, grinder, brewer, steam, pressure, heat, electrical, guarding, isolation, competent-person, emergency, and no-operation safety reservation board",
        "coffee-machinery-safety-reserve",
        "THOS Body and CBR Heart",
        "completed",
        "coffee machinery, grinder, brewer, steam, pressure, heat, electrical, guarding, isolation, competent-person, emergency, and operation-safety reservation",
        ["NZ-WORKSAFE-MACHINERY", "NZ-MPI-FCP", "W3C-PROV-O"],
    ),
    (
        19,
        "Coffee equipment cleaning, chemical-placeholder, potable-water hold, residue cue, allergen-and-milk cross-contact possibility, waste, training, verification, and no-food-safety release contract",
        "coffee-cleaning-cross-contact",
        "THOS Body and CBR Heart",
        "completed",
        "equipment cleaning, chemical placeholder, potable-water hold, residue cue, allergen and milk cross-contact possibility, waste, training, verification, and food-safety release refusal",
        ["NZ-MPI-FCP", "NZ-WORKSAFE-MACHINERY", "W3C-PROV-O"],
    ),
    (
        20,
        "Roasted-coffee packaging, valve-placeholder, seal, lot, pack timestamp, storage condition, degassing placeholder, shelf-life hold, recall path, and no-freshness-or-fitness claim",
        "coffee-packaging-shelf-life",
        "Freed ID and CBR Heart",
        "completed",
        "roasted-coffee packaging, valve placeholder, seal, lot, timestamp, storage condition, degassing placeholder, shelf-life hold, recall path, and freshness and fitness refusal",
        ["RFC-3339", "NZ-MPI-FCP", "W3C-PROV-O"],
    ),
    (
        21,
        "Coffee origin, farm-or-cooperative placeholder, processor, exporter, importer, certification-claim placeholder, chain-of-custody gap, substitution, due-diligence hold, and no-ethical-or-sustainability assurance",
        "coffee-supply-chain-declarations",
        "Freed ID and CBR Heart",
        "completed",
        "coffee origin and farm or cooperative placeholders, processing and trade roles, certification-claim placeholder, custody gap, substitution, due-diligence hold, and ethical and sustainability assurance refusal",
        ["OECD-FAO-AG-SUPPLY", "W3C-PROV-O", "RFC-8785"],
    ),
    (
        22,
        "Accessible coffee product notice with roast and preparation description placeholders, caffeine-and-allergen warning holds, price and quantity fields, correction, complaint, remedy path, and affected-user evaluation reservation",
        "accessible-coffee-product-notice",
        "CBR Heart and THOS Body",
        "completed",
        "accessible product notice, roast and preparation placeholders, caffeine and allergen warning holds, price and quantity fields, correction, complaint, remedy, and affected-user evaluation reservation",
        ["W3C-WCAG-22", "NZ-CONSUMER-CGA", "NZ-PRIVACY-PRINCIPLES"],
    ),
    (
        23,
        "Coffee production and service queue handover with hot-equipment state, open batch, cleaning hold, unresolved decision, workload limit, interruption, custody readback, correction acknowledgement, and shift docket",
        "coffee-workload-handover",
        "THOS Body and CBR Heart",
        "completed",
        "production and service queue, hot-equipment state, open batch, cleaning hold, unresolved decision, workload limit, interruption, custody readback, correction, and shift handover",
        ["NZ-WORKSAFE-MACHINERY", "NZ-MPI-FCP", "RFC-3339"],
    ),
    (
        24,
        "GMUT synthetic coffee-roast coupled heat-and-mass-transfer proxy with typed bean and gas states, boundary flux placeholders, evaporation term, reaction-source hold, units, identifiability hold, and zero empirical fit",
        "gmut-coffee-roast-transport-proxy",
        "GMUT Mind",
        "represented",
        "typed synthetic coffee-roast heat and mass transfer proxy, bean and gas states, boundary flux placeholders, evaporation term, reaction-source hold, units, identifiability hold, and empirical-fit refusal",
        ["NIST-SP811", "RFC-3339"],
    ),
    (
        25,
        "GMUT synthetic coffee-bed porous-flow and extraction proxy with pressure and concentration fields, permeability-placeholder, dispersion-placeholder, boundary obligations, residual, stability hold, and zero predictive claim",
        "gmut-coffee-bed-flow-proxy",
        "GMUT Mind",
        "represented",
        "typed synthetic porous-bed flow and extraction proxy, pressure and concentration fields, permeability and dispersion placeholders, boundary obligations, residual, stability hold, and prediction refusal",
        ["NIST-SP811", "W3C-PROV-O"],
    ),
    (
        26,
        "THOS roast-loss incident choreography with concealed fixture identity, equal-resource comparison hold, batch quarantine, decision readback, escalation ladder, safe resumption, workload ceiling, and zero operational-benefit conclusion",
        "thos-coffee-recovery-proxy",
        "THOS Body",
        "represented",
        "synthetic coffee-batch discrepancy and recovery protocol, blind and matched-budget reservations, quarantine, readback, escalation, resumption, workload, outcome hold, and effectiveness refusal",
        ["W3C-PROV-O", "RFC-3339", "W3C-WCAG-22"],
    ),
    (
        27,
        "Freed ID canonical coffee-batch disclosure capsule linking a subject placeholder, declared predicate, content digest, policy-state placeholder, inclusion absence, supersession, and revocation reservation without operational trust",
        "freed-id-coffee-scitt-envelope",
        "Freed ID",
        "represented",
        "synthetic coffee-lot statement and transparent-supply-chain envelope, subject placeholder, predicate, digest, policy placeholder, receipt absence, revocation hold, and live-identity refusal",
        ["RFC-9943", "RFC-8785", "W3C-VC-DM-20"],
    ),
    (
        28,
        "Freed ID roast-and-pack image lineage plan with synthetic asset token, source ingredient, transformation action, declared assertion, binding and signer holds, absent validation result, and authenticity refusal",
        "freed-id-coffee-c2pa-profile",
        "Freed ID",
        "represented",
        "synthetic coffee roast-and-pack media provenance profile, asset placeholder, ingredient, action, assertion, binding and signer placeholders, validation absence, trust hold, and authenticity refusal",
        ["C2PA-2.4", "W3C-PROV-O", "NZ-PRIVACY-PRINCIPLES"],
    ),
    (
        29,
        "USDA FoodData Central coffee discovery adapter readiness packet with query-purpose placeholder, API-key gate, endpoint allowlist, nutrient-field quarantine, pagination budget, attribution, cache hold, and zero-row execution",
        "usda-coffee-zero-row-adapter",
        "Freed ID and GMUT Mind",
        "open_gap",
        "public food-data coffee discovery readiness, query-purpose placeholder, API-key gate, endpoint allowlist, nutrient-field quarantine, pagination budget, attribution, cache hold, and zero-row execution",
        ["USDA-FDC-API", "NZ-PRIVACY-PRINCIPLES", "W3C-PROV-O"],
    ),
    (
        30,
        "CBR coffee producer, worker, farm and cooperative, origin and place, indigenous and traditional-knowledge possibility, living-income, privacy, benefit, remedy, legal, cultural, data-governance, and Māori-authority reservation matrix",
        "cbr-coffee-authority-matrix",
        "CBR Heart",
        "exact_gate",
        "coffee producer, worker, farm and cooperative, origin and place, indigenous and traditional-knowledge possibilities, living-income, privacy, benefit, remedy, legal, cultural, data-governance, and Māori-authority reservation",
        ["OECD-FAO-AG-SUPPLY", "TMR-PRINCIPLES", "LOCAL-CONTEXTS-TK-BC", "NZ-PRIVACY-PRINCIPLES"],
    ),
]


CLEAN_SURFACES = [
    "proposal and official-source ledgers",
    "semantic novelty and frozen-chain indexes",
    "coffee lot, roast, grind, brew, packaging, and handover schemas",
    "GMUT synthetic thermal and porous-flow boundaries",
    "THOS synthetic discrepancy-recovery protocol",
    "Freed ID synthetic statement and media envelopes",
    "CBR producer, worker, origin, and authority reservations",
    "Method Flow and retained-negative provenance",
    "privacy, accessibility, food, machinery, and workload boundaries",
    "commit-local manifests and exact-final receipts",
]

SKILL_IDEAS = [
    "ghc-family-coffee-lot-provenance-boundary",
    "ghc-family-coffee-roast-trace-nonpromotion",
    "ghc-family-coffee-grind-claim-firewall",
    "ghc-family-coffee-brew-evidence-boundary",
    "ghc-family-coffee-sensory-authority-reserve",
    "ghc-family-coffee-machinery-food-safety-reserve",
    "ghc-family-coffee-accessibility-handover",
    "ghc-family-coffee-supply-privacy-cultural-reserve",
    "ghc-family-gmut-coffee-transport-firewall",
    "ghc-family-coffee-evidence-nonpromotion",
]

RUNNER_IDEAS = [
    "ghc_family_coffee_lot_provenance_boundary.py",
    "ghc_family_coffee_roast_trace_nonpromotion.py",
    "ghc_family_coffee_grind_claim_firewall.py",
    "ghc_family_coffee_brew_evidence_boundary.py",
    "ghc_family_coffee_sensory_authority_reserve.py",
    "ghc_family_coffee_machinery_food_safety_reserve.py",
    "ghc_family_coffee_accessibility_handover.py",
    "ghc_family_coffee_supply_privacy_cultural_reserve.py",
    "ghc_family_gmut_coffee_transport_firewall.py",
    "ghc_family_v656_v5_suite.py",
]


def _negative(
    number: int,
    signature: str,
    observed: str,
    recovery: str,
    guard: str,
    scope: str = "startup",
) -> dict:
    return {
        "negative_id": f"V6565-NEG-X1-{number:03d}",
        "scope": scope,
        "signature": signature,
        "observed": observed,
        "credit": 0,
        "retained": True,
        "recovery": recovery,
        "recurrence_guard": guard,
        "same_owner_only": True,
        "independent_reproduction": False,
    }


X1_OPERATIONAL_NEGATIVES = [
    _negative(
        1,
        "combined-tool-discovery-timeout",
        "The initial combined deferred-tool discovery call exceeded its bounded timeout.",
        "Proceed with the already available local tools and discover only an exact missing capability when required.",
        "Do not bundle unrelated tool discovery into one cold call.",
    ),
    _negative(
        2,
        "broad-drive-and-worktree-probe-timeout",
        "A broad D-drive and worktree discovery probe exceeded its bounded timeout.",
        "Use the exact source and intended D-first target paths from the verified activation.",
        "Prefer exact literal paths over drive-wide discovery.",
    ),
    _negative(
        3,
        "powershell-skill-inventory-foreach-pipeline-parser-fault",
        "PowerShell rejected a direct foreach block piped to JSON serialization.",
        "Materialize the foreach results into an array before piping.",
        "Never pipe directly from a PowerShell foreach statement in this host.",
    ),
    _negative(
        4,
        "powershell-provider-metadata-expansion",
        "A Get-Content first-and-last projection serialized provider metadata instead of the intended scalar lines.",
        "Use System.IO.File.ReadAllLines and explicit scalar indexing.",
        "Use .NET scalar file APIs for bounded Windows text projections.",
    ),
    _negative(
        5,
        "activation-baton-chunk-output-truncation",
        "Oversized parallel baton chunks exceeded the readable tool-output envelope.",
        "Verify the complete file by byte hash, structural section counts, first and last lines, and the already delivered live content.",
        "Keep file-display chunks small even when the underlying file read succeeds.",
    ),
    _negative(
        6,
        "broad-agents-file-search-timeout",
        "A recursive AGENTS.md filesystem search exceeded its bounded timeout.",
        "Use the committed Git index to resolve applicable AGENTS.md files.",
        "Prefer Git's exact tracked-file index to a recursive archive walk.",
    ),
    _negative(
        7,
        "receipt-projection-foreach-pipeline-parser-fault",
        "A receipt projection repeated the direct foreach-to-pipeline PowerShell syntax fault.",
        "Materialize receipt rows before JSON serialization.",
        "Apply the known foreach materialization recurrence guard consistently.",
    ),
    _negative(
        8,
        "script-inventory-foreach-pipeline-parser-fault",
        "A script inventory repeated the direct foreach-to-pipeline PowerShell syntax fault.",
        "Materialize script inventory rows before JSON serialization.",
        "Treat parser recurrence as retained evidence rather than erasing the repeated witness.",
    ),
    _negative(
        9,
        "dotnet-sha256-hashdata-unavailable",
        "The installed .NET runtime did not expose SHA256.HashData.",
        "Use the supported Get-FileHash SHA-256 implementation.",
        "Probe runtime-supported hashing surfaces before using newer static methods.",
    ),
    _negative(
        10,
        "committed-agents-index-wrapper-timeout",
        "A thirty-second committed-file lookup returned the no-AGENTS result but crossed the wrapper deadline.",
        "Repeat the exact tracked-file lookup with a bounded longer envelope and preserve the first attempt at zero credit.",
        "Separate returned partial evidence from command completion credit.",
    ),
    _negative(
        11,
        "minified-method-flow-search-output-overflow",
        "A broad text search matched a minified Method Flow ledger and produced unusably expansive output.",
        "Parse exact JSON properties or query exact files instead of matching minified ledgers.",
        "Never use free-text search over compact single-line evidence ledgers.",
    ),
    _negative(
        12,
        "source-receipt-property-projection-assumption",
        "The first source-receipt projection requested nonexistent generic phase and head keys and returned null values.",
        "Enumerate each receipt's declared properties before projecting its phase-specific fields.",
        "Treat each receipt schema as explicit rather than assuming cross-phase property names.",
    ),
    _negative(
        13,
        "frozen-index-property-shape-assumption",
        "The first frozen-index projection assumed proposals or entries instead of prior_proposals and new_proposals.",
        "Join the two declared proposal arrays after property discovery.",
        "Inspect JSON property names before count or semantic projections.",
    ),
    _negative(
        14,
        "worktree-add-wrapper-timeout-after-live-continuation",
        "The worktree-add wrapper timed out while its exact Git process continued an initializing checkout.",
        "Do not retry; inspect the exact administrative lock, process tree, target marker, branch, and index until the original process completes.",
        "A wrapper timeout never proves a worktree mutation failed or stopped.",
    ),
    _negative(
        15,
        "combined-post-worktree-target-audit-timeout",
        "A combined target-path, Git-head, branch, and full status audit timed out during the active checkout.",
        "Split filesystem marker, head, branch, index, process, and cleanliness checks.",
        "Do not run full status while an initializing worktree process is active.",
    ),
    _negative(
        16,
        "worktree-list-porcelain-audit-timeout",
        "A full repository worktree-list audit timed out during the active checkout.",
        "Read the exact worktree administrative directory derived from the target .git marker.",
        "Use exact administrative records instead of enumerating all archive worktrees.",
    ),
    _negative(
        17,
        "semantic-novelty-threshold-failure",
        "The first x1 build found the THOS, SCITT, and C2PA proposal titles too similar to Caelen's corresponding frozen templates and stopped before artifact generation.",
        "Retitle the three proposals around their coffee-specific mechanisms while preserving approval classes, evidence lanes, falsifiers, rollbacks, and protected gates.",
        "Treat domain substitution alone as insufficient novelty for reusable framework proposal titles.",
    ),
    _negative(
        18,
        "system-text-json-document-unavailable",
        "The first independent PowerShell JSON parse attempted to use System.Text.Json.JsonDocument, which is unavailable in this host runtime.",
        "Use ConvertFrom-Json for the independent PowerShell parse and retain Python's exact JSON parsing as the phase-native validator.",
        "Probe PowerShell runtime types before choosing a secondary JSON parser.",
    ),
    _negative(
        19,
        "python-codex-launcher-access-denied",
        "The x1 builder's Python subprocess could not execute the Windows Codex launcher and returned WinError 5 after a separate PowerShell version probe had succeeded.",
        "Bind the sanitized PowerShell-observed Codex CLI version into the environment receipt without launching Codex from Python.",
        "Verify Windows command shims from their working host surface and pass only the sanitized observation to builders.",
    ),
    _negative(
        20,
        "staged-manifest-line-ending-hash-mismatch",
        "The first exact staged-blob audit found two Python files whose CRLF working bytes differed from Git's LF-cleaned index bytes.",
        "Hash the exact Git-clean candidate blob for every manifest entry and keep working-tree line endings outside the immutable content assertion.",
        "A commit manifest must bind the bytes Git will store, not an unfiltered working-tree representation.",
    ),
    _negative(
        21,
        "complex-line-ending-diagnostic-policy-rejection",
        "The first compound PowerShell line-ending diagnostic was rejected by the command policy before execution.",
        "Replace it with small read-only Git attribute, index, raw-hash, and filtered-hash probes.",
        "Prefer narrowly composed diagnostic commands over temporary-file or deeply nested shell projections.",
    ),
    _negative(
        22,
        "x1-unstage-wrapper-timeout-after-success",
        "The scoped x1 unstage command completed, but the appended broad status count crossed the wrapper deadline.",
        "Verify the exact staged and untracked path subsets independently and do not replay the completed index mutation.",
        "Separate index mutation from large-worktree status enumeration and audit completion before retry.",
    ),
    _negative(
        23,
        "git-clean-blob-read-before-object-materialization",
        "The first Git-clean manifest rebuild computed a filtered object identifier without writing the object, so cat-file could not read the candidate bytes and the build stopped.",
        "Materialize each exact filtered blob with hash-object write mode before reading its bytes; staging will reference the same immutable object.",
        "Do not assume a hash-object identifier is already present in the object database unless it was written or otherwise reachable.",
    ),
]
