"""Finite mathematical witnesses, explicit counterexamples and source metadata."""
import hashlib,itertools,json,math
from fractions import Fraction
from ghc_family_ilyan_v689_v8_io import BASE,read,write
def main():
    tuples=[];compression=[];remainder=[]
    for i,(m,s,k) in enumerate([(4,0,1),(4,1,1),(4,2,2),(4,3,2),(4,4,3),(5,2,3),(7,3,2),(8,1,3),(1,1,2),(8,0,2)]):
        all_rows=list(itertools.product(range(m),repeat=k));hits=sum(all(x<s for x in r) for r in all_rows);p=Fraction(s**k,m**k);tuples.append({'width':m,'occupied':s,'probes':k,'enumerated_positive':hits,'enumerated_total':len(all_rows),'fraction':str(p),'passed':p==Fraction(hits,len(all_rows)),'scope':'conditional finite model only'})
        n=6+i;size=2+i%3;bits=1+i%4;sets=math.comb(n,size);states=2**bits;compression.append({'universe':n,'set_size':size,'summary_bits':bits,'source_sets':sets,'summary_states':states,'collision_forced':sets>states,'argument':'pigeonhole; not a probability estimate'})
        F=Fraction(i+1,3);M2=Fraction(i+2,2);Tm=Fraction(i-3,5);Tphi=Fraction(i+4,7);D=Fraction(i-2,9);alpha=Fraction(i+2,11);kappa=1/M2;G=(kappa*(Tm+Tphi)+D)/F;omega=(kappa*(1/F-1)*Tm+kappa*Tphi/F+D/F)/alpha;residual=G-kappa*Tm-alpha*omega;remainder.append({'F':str(F),'M_squared':str(M2),'alpha':str(alpha),'T_m':str(Tm),'T_phi':str(Tphi),'D':str(D),'residual':str(residual),'passed':residual==0,'scope':'exact scalar-component substitutions of a defined algebraic remainder, not a tensor variation proof'})
    failed=[{'id':'IR6898-RESEARCH-N001','claim':'Known-member deletion remains safe after counter saturation','counterexample':{'cap':1,'members':['a','b'],'shared_position':0,'true_multiplicity':2,'stored_counter':1,'after_deleting_a':0,'remaining_member_b_is_false_negative':True},'claim_result':'refuted_in_declared_finite_example','original_success_credit':0},{'id':'IR6898-RESEARCH-N002','claim':'An arbitrary independently specified Omega can accompany conserved matter without a conservation check','counterexample':{'metric':'diag(-1,1,1,1)','Omega_00':'t','other_Omega_components':0,'divergence_nu_0':-1},'claim_result':'refuted_for_constant_alpha_and_conserved_matter','original_success_credit':0}]
    write('x2/research/mathematical-witnesses.json',{'conditional_probability':tuples,'compression_counts':compression,'gmut_remainder_substitutions':remainder,'retained_failed_claims':failed,'empirical_rows':0,'new_fundamental_laws':0,'independent_reproduction':False})
    write('x2/research/source-metadata.json',{'records':[{'title':'Equivalence between Scalar-Tensor theories and f(R)-gravity','arxiv':'1808.05615v4','arxiv_doi':'10.48550/arXiv.1808.05615','related_journal_doi':'10.1088/2399-6528/ab902f','source':'https://arxiv.org/abs/1808.05615','status':'stable','scope':'variational comparison, not empirical support for GMUT'},{'title':'Local energy-momentum conservation in scalar-tensor-like gravity with generic curvature invariants','arxiv':'1507.07448v2','arxiv_doi':'10.48550/arXiv.1507.07448','related_journal_doi':'10.1007/s10714-016-2106-6','source':'https://arxiv.org/abs/1507.07448','status':'stable','scope':'consistency-condition comparison'},{'title':'Network Applications of Bloom Filters: A Survey, shortened preliminary copy','source':'https://www.cs.cornell.edu/courses/cs619/2004fa/documents/BloomFilterSurvey.pdf','status':'stable','scope':'established approximate-membership assumptions'},{'title':'MassGameplay Overview','source':'https://dev.epicgames.com/documentation/en-us/unreal-engine/overview-of-mass-gameplay-in-unreal-engine','status':'current','scope':'official engine vocabulary; some features experimental'},{'title':'DGX Spark hardware','source':'https://docs.nvidia.com/dgx/dgx-spark/hardware.html','status':'current','scope':'manufacturer specifications; no workload benchmark or purchase recommendation'},{'title':'User-linked X demo','source':'https://x.com/mattshumer_/status/2095596175705399482','status':'watch','scope':'initial primary open failed; no direct video or run-log inspection'}],'checked_on':'2026-09-10'})
    image=BASE/'x2/assets/finite-membership-editorial.png';write('x2/image-provenance.json',{'task':'IR6898-EXTRA-04','mode':'built_in_image_generation','prompt_file':'x2/image-request.json','project_path':'x2/assets/finite-membership-editorial.png','sha256':hashlib.sha256(image.read_bytes()).hexdigest(),'bytes':len(image.read_bytes()),'source_copy_parity':True,'visual_review':'Archive records, compact translucent summaries and connecting threads; no readable data labels or people.','evidence_role':'non_evidentiary_editorial_illustration'})
    print(json.dumps({'conditional_witnesses':10,'counting_arguments':10,'algebraic_substitutions':10,'failed_broad_claims_retained':2,'all_algebraic_residuals_zero':all(r['passed'] for r in remainder)}))
if __name__=='__main__':main()
