#!/usr/bin/env python3
"""Closeout lifecycle constants for Vesper v656-v8."""

from __future__ import annotations


SOURCE_COMMIT = "c885a4533b2a73343990039e21d74979acb79c00"
X1_COMMIT = "25c840c4e16a2b414dc6b51f5c529379eb244d1c"
EVIDENCE_COMMIT = "a721ae1ca74f3a0d5adc9149af5bb78fe9fc57bb"
EVIDENCE_EFFECTIVE_NEGATIVES = 15060
EVIDENCE_EFFECTIVE_METHODS = 1345
EVIDENCE_OPEN_GAPS = 104
EVIDENCE_EXACT_GATES = 103

# Failures discovered after the evidence packet was generated. Some occurred
# during pre-evidence scaffolding but were not present in the immutable
# evidence ledger; they are therefore carried forward additively here without
# retroactive evidence credit.
CLOSEOUT_DISCOVERED_NEGATIVES: list[dict[str, str]] = [
    {
        "negative_id": "V6568-LIFECYCLE-N16",
        "slug": "powershell-case-insensitive-rewrite-map-collision",
        "observed_lifecycle": "pre_evidence_scaffolding_disclosed_at_closeout",
        "failure_signature": "A PowerShell hashtable rejected replacement keys that differed only by case.",
        "candidate_workaround": "Use an ordered array of exact old/new pairs and apply each literal replacement independently.",
        "recurrence_guard": "Never represent case-distinct replacement tokens as keys in a PowerShell hashtable.",
        "fail_procedure": "Construct the mechanical scaffold rewrite as a PowerShell hashtable containing case-distinct keys.",
        "fail_observed": "PowerShell stopped on a duplicate case-insensitive key; no rewrite credit was granted.",
        "pass_procedure": "Re-express the same exact replacements as ordered two-element arrays and audit the resulting files.",
        "pass_observed": "The bounded pairwise rewrite completed and every intended token was inspected.",
        "scope_boundary": "Owner-local scaffold transformation recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N17",
        "slug": "overbroad-ash-substring-replacement",
        "observed_lifecycle": "pre_evidence_scaffolding_disclosed_at_closeout",
        "failure_signature": "An unbounded replacement of the token ash also changed unrelated hash text.",
        "candidate_workaround": "Revert the candidate immediately and replace only exact names or complete literals.",
        "recurrence_guard": "Require token-boundary or exact-literal review before any global name substitution.",
        "fail_procedure": "Apply the broad substring replacement across copied lifecycle scaffolding.",
        "fail_observed": "Inspection found unintended hash-token corruption; the candidate earned zero transformation credit.",
        "pass_procedure": "Restore the untouched scaffold and apply exact full-string replacements only.",
        "pass_observed": "The corrected scaffold preserved hash terminology and changed only intended names.",
        "scope_boundary": "Owner-local text-transformation recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N18",
        "slug": "runner-directory-assumed-before-generation",
        "observed_lifecycle": "pre_evidence_scaffolding_disclosed_at_closeout",
        "failure_signature": "A read probe targeted a runners directory before that directory existed.",
        "candidate_workaround": "Inspect the repository script inventory first and create runner receipts only through the declared builder.",
        "recurrence_guard": "Test literal-path existence before enumerating optional generated directories.",
        "fail_procedure": "Enumerate the expected runner directory before x2 generated it.",
        "fail_observed": "The path-not-found probe returned no runner inventory and earned zero inspection credit.",
        "pass_procedure": "Enumerate family-current scripts from the repository root, then inspect generated receipts after x2.",
        "pass_observed": "All ten runner wrappers and receipts were found in their declared locations.",
        "scope_boundary": "Owner-local path-discovery recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N19",
        "slug": "patch-context-drift",
        "observed_lifecycle": "pre_evidence_scaffolding_disclosed_at_closeout",
        "failure_signature": "One or more exact-context patch attempts did not match the copied scaffold after prior bounded edits.",
        "candidate_workaround": "Reread the exact UTF-8 file slice and apply a smaller context-specific patch.",
        "recurrence_guard": "Refresh source context immediately before a dependent patch and avoid stale copied snippets.",
        "fail_procedure": "Apply a patch using stale or encoding-rendered context.",
        "fail_observed": "Patch verification failed and changed no file; the attempts retained zero edit credit.",
        "pass_procedure": "Reread the literal UTF-8 file and apply only the smallest exact matching hunks.",
        "pass_observed": "The intended edits applied and subsequent diff inspection bounded the changed regions.",
        "scope_boundary": "Owner-local patch-context recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N20",
        "slug": "repeated-windows-rg-wildcard-path",
        "observed_lifecycle": "pre_evidence_scaffolding_disclosed_at_closeout",
        "failure_signature": "A repeated Windows rg invocation supplied a wildcard as a path instead of using a glob option.",
        "candidate_workaround": "Use rg -g filters with literal directory roots.",
        "recurrence_guard": "On Windows, reserve wildcard matching for rg -g and keep path operands literal.",
        "fail_procedure": "Pass a wildcard-bearing filename as an rg path operand.",
        "fail_observed": "rg rejected the path form; the repeated occurrence earned zero search credit.",
        "pass_procedure": "Run rg with literal roots and explicit -g include patterns.",
        "pass_observed": "The bounded search returned the intended lifecycle files.",
        "scope_boundary": "Owner-local search-syntax recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N21",
        "slug": "powershell-direct-mojibake-pattern-parse-one",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "A direct PowerShell string containing terminal-rendered mojibake failed with a missing string terminator.",
        "candidate_workaround": "Avoid copying terminal-rendered mojibake into shell literals and query UTF-8 source with stable text or ASCII-safe patterns.",
        "recurrence_guard": "Treat PowerShell display decoding as presentation only; use rg UTF-8 matching or code-point-safe construction.",
        "fail_procedure": "Embed terminal-rendered mojibake directly in the first PowerShell pattern query.",
        "fail_observed": "PowerShell failed during parsing and performed no scan.",
        "pass_procedure": "Query the exact UTF-8 Māori, dash, and arrow strings with rg against bounded files.",
        "pass_observed": "rg confirmed the source files contained correct UTF-8 text rather than corrupted repository bytes.",
        "scope_boundary": "Read-only encoding-diagnosis recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N22",
        "slug": "powershell-direct-mojibake-pattern-parse-two",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "A second direct PowerShell pattern-array attempt repeated the missing-terminator parse failure.",
        "candidate_workaround": "Stop retrying direct rendered strings and switch to bounded rg UTF-8 literals.",
        "recurrence_guard": "After one shell-literal encoding parse failure, change representation rather than repeat it.",
        "fail_procedure": "Retry the rendered mojibake as a PowerShell pattern array.",
        "fail_observed": "PowerShell again failed before execution and earned zero scan credit.",
        "pass_procedure": "Use literal UTF-8 rg probes and verify the exact expected glyphs.",
        "pass_observed": "The bounded probes succeeded without modifying repository content.",
        "scope_boundary": "Read-only encoding-diagnosis recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N23",
        "slug": "broad-encoding-rg-scan-timeout",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "A broad recursive rg encoding audit exceeded its thirty-second outer bound.",
        "candidate_workaround": "Constrain the scan with phase-specific globs and a longer bounded timeout.",
        "recurrence_guard": "Scope recursive scans to owner and lifecycle file families before increasing the time bound.",
        "fail_procedure": "Search broad scripts, tests, and phase roots with a composite regex under thirty seconds.",
        "fail_observed": "The wrapper timed out and returned no complete scan result.",
        "pass_procedure": "Repeat with phase-specific -g filters and a sixty-second bound.",
        "pass_observed": "The constrained scan completed and the subsequent exact UTF-8 probes resolved the display concern.",
        "scope_boundary": "Read-only bounded scan recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N24",
        "slug": "guessed-permission-state-reference-path",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "A read probe guessed a current permission-state path that was not present.",
        "candidate_workaround": "Use the already-read skill routing reference or enumerate the skill's declared references before selecting a file.",
        "recurrence_guard": "Never infer a reference filename from a neighboring skill; use the selected SKILL.md declarations.",
        "fail_procedure": "Read a guessed current-permission-state.json path beside the valid roster state.",
        "fail_observed": "The literal path was absent and received zero permission-state evidence credit.",
        "pass_procedure": "Retain the earlier complete skill/schema read and use only its declared reference names.",
        "pass_observed": "No permission expansion was inferred from the missing path; the phase remained within the verified baton.",
        "scope_boundary": "Read-only skill-reference recovery only.",
    },
    {
        "negative_id": "V6568-LIFECYCLE-N25",
        "slug": "closeout-audit-repeated-windows-wildcard-path",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "A closeout audit again supplied test_ghc_family_v656_v8*.py as an rg path operand on Windows.",
        "candidate_workaround": "Use a literal tests root with rg -g test_ghc_family_v656_v8*.py.",
        "recurrence_guard": "Encode the Windows wildcard rule directly in lifecycle audit commands rather than relying on recollection.",
        "fail_procedure": "Run the composite closeout audit with the wildcard-bearing test path.",
        "fail_observed": "rg returned the Windows invalid-path error; the occurrence earned zero audit credit.",
        "pass_procedure": "Repeat with a literal tests root and an explicit -g include pattern.",
        "pass_observed": "The bounded audit completed and exposed the exact stale class reference for correction.",
        "scope_boundary": "Read-only closeout search-syntax recovery only.",
    },
    {
        "negative_id": "V6568-CLOSEOUT-N26",
        "slug": "future-tests-staged-in-closeout-delta",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "The first closeout staged review found two final-only test modules outside its exact allowlist.",
        "candidate_workaround": "Retain the failed review, unstage and park only the future tests, rebuild all affected receipts, and rerun the closeout review.",
        "recurrence_guard": "Resolve each lifecycle allowlist before staging scaffolding shared with a later commit.",
        "fail_procedure": "Stage all restored lifecycle scaffolding and run the exact closeout staged review.",
        "fail_observed": "The review reported the final and successor test modules as out of scope and granted zero closeout-review credit.",
        "pass_procedure": "Park the two final-only tests, regenerate closeout truth and manifests, stage the bounded closeout set, and rerun the same review.",
        "pass_observed": "The corrected closeout candidate contains only its declared owner scope; the failed review remains retained.",
        "scope_boundary": "Owner-local lifecycle staging recovery only.",
    },
    {
        "negative_id": "V6568-CLOSEOUT-N27",
        "slug": "future-test-parking-wrapper-timeout-after-completion",
        "observed_lifecycle": "post_evidence_closeout",
        "failure_signature": "The bounded unstage-and-park wrapper timed out after both final-only files had already moved to scratch.",
        "candidate_workaround": "Audit both repository and scratch paths plus index state before any retry.",
        "recurrence_guard": "After a mutating wrapper timeout, inspect durable path and index state and never repeat the move blindly.",
        "fail_procedure": "Unstage and move the two final-only tests in one bounded PowerShell wrapper.",
        "fail_observed": "The outer wrapper timed out and earned zero move-credit despite possible durable completion.",
        "pass_procedure": "Probe each literal repository path, scratch path, and staged state without mutation.",
        "pass_observed": "Both files were present only in scratch and absent from the index; no retry or duplicate move occurred.",
        "scope_boundary": "Owner-local post-timeout state-audit recovery only.",
    },
]
