"""Mutable-by-addition v648-v7 x2 operational-negative register source."""

X1_COMMIT = "5ab7e85107f92dd8f6f21af66244c6dc9791b39d"
X2_OPERATIONAL_NEGATIVES = [
    {"negative_id":"V6487-X2-N01","category":"powershell_upstream_expression_parse","failed":"An unquoted upstream divergence expression was mangled by PowerShell after x1 push, while the four exact commit values and clean state still matched.","recovery":"Quote the complete revision expression and test the returned zero-zero divergence separately.","passing":"The corrected read-only probe returned exact x1 head, upstream equality, zero-zero divergence, and a clean lane.","recurrence_guard":"Quote revision expressions containing braces in PowerShell."},
    {"negative_id":"V6487-X2-N02","category":"inherited_skill_name_assumption","failed":"A read-only compatibility probe requested a plausible but absent inherited skill package after the exact directory listing had already exposed the real names.","recovery":"Select an exact discovered package name before reading its files.","passing":"The exact inherited package was read without repository mutation.","recurrence_guard":"Resolve package names from bounded discovery output rather than reconstructing them."},
    {"negative_id":"V6487-X2-N03","category":"skill_validator_locale_decode","failed":"The first quick validator used the Windows locale default and stopped decoding a valid UTF-8 skill before schema validation.","recovery":"Set the child Python UTF-8 mode explicitly and rerun validation for the complete 20-skill set.","passing":"All 20 phase-local skills passed the official quick validator under explicit UTF-8.","recurrence_guard":"Set explicit UTF-8 for every skill-creator validation subprocess on Windows."},
    {"negative_id":"V6487-X2-N04","category":"portfolio_receipt_path_domain_mismatch","failed":"The first evidence aggregate completed 28 bounded child invocations, then looked for the portfolio receipt in the x2-ledger domain although the runner had written it in the runner-use domain.","recovery":"Write the detailed portfolio receipt to its declared x2 path, emit a separate runner-use summary, and rerun idempotently with zero duplicate completion credit.","passing":"The corrected aggregate consumed the x2 portfolio receipt, retained the first attempt, and assembled all ledgers without duplicate credit.","recurrence_guard":"Declare runner-use and domain-ledger paths separately before any evidence-producing child command runs."},
    {"negative_id":"V6487-X2-N05","category":"x1_test_read_mutable_successor_ledger","failed":"The first combined development run failed because an x1 count assertion read the live Method Flow ledger after legitimate x2 witnesses were added.","recovery":"Read the immutable x1 commit's ledger for frozen x1 counts while leaving live-ledger growth to x2 tests.","passing":"The corrected combined development selection preserved x1 truth and accepted additive x2 Method Flow evidence.","recurrence_guard":"Bind frozen-phase assertions to their commit object rather than a successor-mutated working-tree ledger."},
    {"negative_id":"V6487-X2-N06","category":"untracked_directory_manifest_collapse","failed":"Evidence preflight found that the status collector collapsed untracked skill directories, so the manifest omitted individual phase-local skill files.","recovery":"Request all untracked files explicitly, rebuild the evidence manifest, and require staged path parity.","passing":"The rebuilt manifest enumerated every individual evidence path and the exact staged reviewer reported zero missing or unexpected paths.","recurrence_guard":"Use the all-untracked status mode for manifests whenever generated directories may be new."},
    {"negative_id":"V6487-X2-N07","category":"inherited_postpass_lifecycle_assertions","failed":"The first canonical attempt ran 69 tests and failed two inherited v648-v6 closeout assertions that still expected Orin's pre-pass candidate state although Orin's sealed source truth records one successful pass.","recovery":"Exclude only those two source-local pre-pass assertions, retain the other eight source closeout tests, and require the corrected selection to contain exactly 67 cases.","passing":"The corrected canonical selection ran exactly 67 tests and passed without replay or full-suite credit.","recurrence_guard":"Successor scopes must distinguish immutable source evidence tests from source-local assertions intentionally changed by that source's own post-pass seal."},
    {"negative_id":"V6487-X2-N08","category":"validator_repository_root_import_path","failed":"The second canonical attempt ran zero tests because file execution placed the scripts directory, not the repository root, on the import path and the loader counted six import-failure placeholders.","recovery":"Insert the exact repository root before loading named test modules and preserve the zero-test attempt separately.","passing":"The corrected wrapper selected and ran exactly 67 real cases; the zero-test attempt received no pass credit.","recurrence_guard":"Every file-executed in-process unittest loader must place the repository root on the import path before discovery."},
    {"negative_id":"V6487-X2-N09","category":"atomic_patch_context_miss","failed":"The first additive recovery patch was rejected atomically because its long closeout-plan context did not exactly match the generated one-line source.","recovery":"Inspect exact lines and apply the state, validator, plan, and test edits in smaller bounded patches.","passing":"The smaller exact patches applied and the source compiled without changing unrelated bytes.","recurrence_guard":"Split patches around long generated one-line literals and verify exact context first."},
    {"negative_id":"V6487-X2-N10","category":"atomic_patch_context_recurrence","failed":"A second multi-file recovery patch repeated the same long-line context mismatch and was rejected atomically.","recovery":"Remove the generated plan line from every multi-file patch and replace it only in a standalone full-line patch.","passing":"The isolated short patches and standalone plan replacement applied cleanly.","recurrence_guard":"After one generated-line context miss, never include that line in another multi-file patch."},
    {"negative_id":"V6487-X2-N11","category":"postpass_boundary_vocabulary_false_positive","failed":"The first post-pass incremental seal treated protected Method Flow boundary vocabulary as secret payload and refused sealing after the canonical pass.","recovery":"Apply the previously proven strict secret-assignment distinction to Method Flow files while preserving all five pattern classes and scan every post-canonical change.","passing":"The corrected incremental scan retained boundary vocabulary and reported zero confirmed payload hits without rerunning tests or the canonical scan.","recurrence_guard":"Reuse the proven boundary-vocabulary classifier in every incremental scanner that covers Method Flow artifacts."},
]
