#!/usr/bin/env python3
"""Frozen v649-v4 proposal, source, portfolio, and x1-negative data."""

from __future__ import annotations


PROPOSALS = [
    {
        "proposal_id": "V6494-P01",
        "title": "Method Flow future single-assignment, completion-cancellation race, exception propagation, callback ordering, waiter notification, executor shutdown, and evidence-credit tribunal",
        "pillar": "THOS Body",
        "hypothesis": "A bounded future-state tribunal can enforce single settlement, distinguish cancellation before execution from failed cancellation after start, preserve exception propagation and callback order, notify waiters once, and refuse duplicate evidence credit.",
        "null_or_failure_condition": "The tribunal permits a second settlement, reports successful cancellation after running begins, loses an exception, reorders callbacks, leaves a waiter unnotified, runs callbacks twice, or counts repeated completion as independent evidence.",
        "approval_class": "safe_now_owner_scoped_concurrency_fixture",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-PY-FUTURE"],
        "artifacts": ["method-flow/future-completion-contract.json", "method-flow/future-completion-mutations.json"],
        "falsifier_or_acceptance_gate": "Every synthetic trace has one terminal state, legal cancellation semantics, ordered callbacks, one waiter notification, bounded teardown, and no duplicate evidence credit.",
        "rollback_or_recovery": "Stop the fixture, retain the failed trace, and fall back to a sequential inert state table.",
        "protected_gates": ["production_concurrency", "independent_reproduction", "exhaustive_security", "sibling_state"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6494-P02",
        "title": "GMUT operator-product-expansion short-distance domain, coefficient distribution, scaling degree, associativity, microlocal spectrum, renormalization, gauge, EFT, unit, and observation-firewall obligation board",
        "pillar": "GMUT Mind",
        "hypothesis": "A typed OPE obligation board can separate short-distance coefficient and consistency obligations from empirical GMUT evidence.",
        "null_or_failure_condition": "The board omits the coincidence domain, distributional coefficient, scaling degree, associativity domain, microlocal spectrum, renormalization ambiguity, gauge scope, EFT truncation, units, or converts a formal expansion into observed physics.",
        "approval_class": "safe_now_symbolic_research_only",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-OPE-PRIMARY"],
        "artifacts": ["gmut/operator-product-expansion-obligations.json", "gmut/operator-product-expansion-mutations.json"],
        "falsifier_or_acceptance_gate": "Every accepted row names its short-distance, distribution, scaling, associativity, microlocal, renormalization, gauge, EFT, unit, and observation-firewall obligations.",
        "rollback_or_recovery": "Withdraw the formal board, retain the missing obligation, and make no force, prediction, likelihood, constraint, confirmation, completion, or Theory-of-Everything claim.",
        "protected_gates": ["real_data", "physical_prediction", "empirical_confirmation", "quantum_completion", "theory_of_everything"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6494-P03",
        "title": "GMUT Einstein Toolkit thorn-interface, evolved-variable, gauge, hyperbolicity, initial-boundary condition, discretization, refinement, constraint-propagation, convergence, environment, and zero-solver-run protocol",
        "pillar": "GMUT Mind",
        "hypothesis": "An official-toolkit implementation contract can expose equation, interface, gauge, hyperbolicity, initial-boundary, discretization, refinement, constraint, convergence, environment, and independent-review prerequisites without treating documentation or a planned thorn as a numerical result.",
        "null_or_failure_condition": "No frozen executable equations, variable map, thorn implementation, parameter file, solver run, refinement triplet, constraint trace, convergence estimate, environment lock, benchmark comparison, or independent review is present.",
        "approval_class": "real_numerical_implementation_compute_and_independent_review_required",
        "execution_lane": "x2_open_gap",
        "source_needs": ["SRC-ET-DOCS", "SRC-ET-TESTS"],
        "artifacts": ["empirical/einstein-toolkit-study-contract.json", "empirical/einstein-toolkit-zero-solver-run-receipt.json"],
        "falsifier_or_acceptance_gate": "Remain open_gap while there is no toolkit checkout, GMUT thorn, parameter file, solver run, constraint trace, refinement triplet, measured convergence order, reproducible environment, benchmark comparison, or independent review.",
        "rollback_or_recovery": "Retain the zero-solver-run refusal and make no numerical-stability, convergence, force, prediction, likelihood, constraint, confirmation, or Theory-of-Everything claim.",
        "protected_gates": ["real_numerical_implementation", "compute_execution", "convergence_evidence", "independent_review", "physical_prediction"],
        "expected_disposition": "open_gap",
    },
    {
        "proposal_id": "V6494-P04",
        "title": "THOS community seed-library germination-assay sample draw, replicate tray, count window, dormancy note, censored result, viability calculation, retest, stock-depletion budget, amendment, and custody-handoff proxy",
        "pillar": "THOS Body",
        "hypothesis": "A synthetic seed-library assay ledger can represent a bounded sample draw, replicate trays, count window, dormancy note, censored outcome, viability calculation, retest trigger, stock-depletion budget, result amendment, and custody handoff without real seed operations or people.",
        "null_or_failure_condition": "The proxy omits accession reservation, sample quantity, replicate identity, count window, dormancy status, censoring reason, calculation basis, retest rule, depletion limit, amendment lineage, or receiving custodian.",
        "approval_class": "safe_now_proxy_protocol_no_people_or_real_seed_operations",
        "execution_lane": "x2_proxy_protocol",
        "source_needs": ["SRC-FAO-GENEBANK", "SRC-WCAG22"],
        "artifacts": ["thos/seed-germination-assay-contract.json", "thos/seed-germination-assay-vectors.json"],
        "falsifier_or_acceptance_gate": "Represented only when synthetic traces preserve sampling, replicate, count, censoring, calculation, retest, depletion, amendment, and custody lineage and every real donor, custodian, seed lot, assay, biological result, distribution, safety outcome, and effectiveness claim remains false.",
        "rollback_or_recovery": "Revert to a design-only assay checklist, retain the failed trace, and issue no real sample, viability, retest, depletion, amendment, custody, or distribution decision.",
        "protected_gates": ["real_operations", "professional_authority", "participant_effectiveness", "biological_material"],
        "expected_disposition": "represented",
    },
    {
        "proposal_id": "V6494-P05",
        "title": "Freed ID RFC 7592 client-configuration endpoint, registration-access-token, read, full-update, delete, metadata replacement, credential rotation, deprovisioning, replay, experimental-status, and minimization profile",
        "pillar": "Freed ID / CBR Heart",
        "hypothesis": "Synthetic RFC 7592 vectors can test configuration-endpoint binding, registration-token confinement, complete metadata replacement, rotation, deletion, deprovisioning, replay refusal, status disclosure, and minimization without production identity operations.",
        "null_or_failure_condition": "The profile accepts an unbound endpoint, wrong registration token, partial update disguised as complete replacement, silent credential retention, stale token after deletion, replay, status inflation, or treats an Experimental RFC as production assurance.",
        "approval_class": "safe_now_synthetic_nonproduction",
        "execution_lane": "x2_proxy_protocol",
        "source_needs": ["SRC-RFC7592", "SRC-RFC7591"],
        "artifacts": ["freed-id/registration-management-profile.json", "freed-id/registration-management-mutations.json"],
        "falsifier_or_acceptance_gate": "Represented only; synthetic messages, Experimental status, absent real keys and services, absent interoperability, absent privacy and security review, and absent trust governance remain explicit.",
        "rollback_or_recovery": "Reject the vector, retain the negative, and leave registration, identity, credentials, accounts, tokens, and trust decisions unmade.",
        "protected_gates": ["real_keys", "production_identity", "interoperability", "privacy_review", "independent_security_review", "trust_governance"],
        "expected_disposition": "represented",
    },
    {
        "proposal_id": "V6494-P06",
        "title": "CBR seed-accession passport, collection-site geolocation, land-relationship, digital-sequence linkage, reidentification, purpose, disclosure, retention, material-transfer, benefit-sharing, affected-party, and Māori-data-governance authority gate",
        "pillar": "Freed ID / CBR Heart",
        "hypothesis": "A reservation gate can expose how passport metadata, collection-site detail, land relationships, digital-sequence linkage, reidentification, purpose, disclosure, retention, material transfer, and benefit-sharing depend on affected people and competent Māori, privacy, biological, legal, and data-governance authority.",
        "null_or_failure_condition": "Any real passport release, geolocation precision, land-relationship statement, sequence linkage, reidentification risk decision, purpose authorization, disclosure, retention, material transfer, benefit-sharing, legal interpretation, cultural decision, or Māori-data-governance decision is marked completed by software evidence.",
        "approval_class": "authorized_affected_parties_and_competent_authority_required",
        "execution_lane": "x2_exact_gate",
        "source_needs": ["SRC-FAO-GENEBANK", "SRC-CBD-DSI", "SRC-NZ-PRIVACY", "SRC-TE-MANA-RARAUNGA"],
        "artifacts": ["cbr/seed-passport-dsi-risk-gate.json", "cbr/seed-passport-authority-reservation.json"],
        "falsifier_or_acceptance_gate": "Remain exact_gate until affected donors and communities, relevant land relationships, tangata whenua, iwi, hapū, Māori authorities, and competent biological, privacy, legal, cultural, digital-sequence, material-transfer, benefit-sharing, and data-governance authorities decide within scope.",
        "rollback_or_recovery": "Remove any accidental release or authority claim, retain the assumption failure, and preserve passport, geolocation, land-relationship, sequence, donor, community, cultural, and linkage privacy.",
        "protected_gates": ["affected_party_legitimacy", "maori_data_governance", "digital_sequence_governance", "legal_interpretation", "cultural_ratification", "benefit_sharing_authority", "biological_material_authority"],
        "expected_disposition": "exact_gate",
    },
    {
        "proposal_id": "V6494-P07",
        "title": "NetCDF classic CDF-1, CDF-2, CDF-5 magic, dimensions, attributes, variables, padding, offsets, record variables, size arithmetic, external-data, resource-budget, and refusal tribunal",
        "pillar": "THOS Body",
        "hypothesis": "A bounded netCDF classic-family tribunal can reject invalid signatures, counts, names, types, padding, offsets, record layouts, arithmetic overflow, external retrieval, and resource exhaustion in synthetic fixtures.",
        "null_or_failure_condition": "The tribunal accepts an invalid CDF signature, malformed dimension or attribute list, unsupported type, misaligned padding, escaping offset, inconsistent record variable, overflowing size, external retrieval, or unbounded allocation.",
        "approval_class": "safe_now_owner_scoped_parser_fixture",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-NETCDF-NUG"],
        "artifacts": ["formats/netcdf-classic-contract.json", "formats/netcdf-classic-mutations.json"],
        "falsifier_or_acceptance_gate": "All declared malformed fixtures are rejected, offsets and arithmetic remain bounded, external retrieval is disabled, and no production-conformance or exhaustive-security claim is made.",
        "rollback_or_recovery": "Disable the wrapper, retain the failed fixture, and fall back to inert byte metadata without decoding.",
        "protected_gates": ["external_payloads", "exhaustive_security", "production_decoder", "user_files"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6494-P08",
        "title": "Accessible form error-summary heading, live status, focus target, error links, field association, persistent text, non-colour cue, correction confirmation, zoom, fallback, and manual-reservation audit",
        "pillar": "THOS Body",
        "hypothesis": "A structural audit can verify an identifiable error summary, deterministic focus target, links to associated fields, persistent textual errors, non-colour cues, correction confirmation, zoom resilience, and a linear fallback while reserving manual evaluation.",
        "null_or_failure_condition": "The surface lacks a heading or status, deterministic target, working field links, programmatic association, persistent text, non-colour indication, correction confirmation, zoom guard, fallback, or honest manual reservation.",
        "approval_class": "safe_now_structural_only",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-W3C-ERRORS", "SRC-W3C-G139", "SRC-WCAG22"],
        "artifacts": ["accessibility/error-summary-contract.json", "accessibility/error-summary-mutations.json"],
        "falsifier_or_acceptance_gate": "Pass only structural fixtures; reserve keyboard, browser, responsive, assistive-technology, cognitive, Māori-language, security-usability, and affected-user evaluation.",
        "rollback_or_recovery": "Publish an inert sequential error list and retain every structural failure.",
        "protected_gates": ["complete_accessibility", "manual_evaluation", "affected_user_acceptance", "language_authority"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6494-P09",
        "title": "Thermo-Psyche Lippmann electrocapillary interfacial-tension, electrode-potential, reference-electrode, chemical-potential constraint, surface-excess, sign, unit, equilibrium-domain, and agency-nonconversion classifier",
        "pillar": "Trinity Mandala bridge",
        "hypothesis": "A typed classifier can preserve the Lippmann electrocapillary derivative domain and its reference and constraint obligations while refusing conversion of electrical or interfacial quantities into psyche, agency, worth, or consciousness.",
        "null_or_failure_condition": "The reference electrode or fixed variables are omitted, sign or units drift, surface excess is misidentified as localized physical charge, equilibrium assumptions are absent, or the relation is converted into a law of mind or value.",
        "approval_class": "safe_now_formal_domain_guard",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-IUPAC-LIPPMANN"],
        "artifacts": ["thermo-psyche/lippmann-electrocapillary-contract.json", "thermo-psyche/lippmann-electrocapillary-mutations.json"],
        "falsifier_or_acceptance_gate": "Every accepted row states derivative, fixed variables, reference electrode, sign, units, surface-excess interpretation, equilibrium domain, and agency nonconversion.",
        "rollback_or_recovery": "Remove the analogy, retain only the physical statement, and preserve the rejected conversion.",
        "protected_gates": ["psyche_conversion", "consciousness", "personhood", "moral_value", "agency_measure"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6494-P10",
        "title": "Stage 20 pattern-mixture, reference-based multiple-imputation, delta-adjustment, missingness, tipping-point, estimand-alignment, combination-rule, multiplicity, sensitivity, and nonpromotion board",
        "pillar": "Trinity Mandala bridge",
        "hypothesis": "A pattern-mixture sensitivity board can expose missing-data and reference-based imputation assumptions without converting zero-participant fixtures into treatment effects or Stage 20 evidence.",
        "null_or_failure_condition": "The board omits missingness pattern, reference basis, delta provenance, tipping-point range, estimand alignment, combination rule, multiplicity, uncertainty, sensitivity interpretation, or promotes software as an effect.",
        "approval_class": "safe_now_structural_nonpromotion",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-ICH-E9R1", "SRC-EMA-MISSING"],
        "artifacts": ["stage20/pattern-mixture-contract.json", "stage20/pattern-mixture-mutations.json"],
        "falsifier_or_acceptance_gate": "Pass only structural protocol fixtures; real outcomes, credible missingness assumptions, safety monitoring, value authority, and independent review remain absent.",
        "rollback_or_recovery": "Retain the failed fixture and keep treatment-effect, participant-effect, and Stage 20 claims false.",
        "protected_gates": ["real_participants", "causal_effect", "value_authority", "independent_review", "stage20"],
        "expected_disposition": "completed",
    },
]


SOURCES = [
    {"source_id": "SRC-LIVE-REQUEST", "title": "Hamish current v649-v4 activation from Sable Rook", "url": None, "status": "current", "kind": "live_authority", "implication": "Controls solo ownership, x1-before-x2, four-commit cap, one scoped pass, no replay, platform exclusions, privacy, authority, and terminal route."},
    {"source_id": "SRC-PY-FUTURE", "title": "Python 3.12 concurrent.futures Future documentation", "url": "https://docs.python.org/3.12/library/concurrent.futures.html", "status": "current", "kind": "official_documentation", "implication": "Supplies Future state, cancellation, callback, and exception semantics for synthetic traces only."},
    {"source_id": "SRC-OPE-PRIMARY", "title": "Holland and Hollands, Operator product expansion algebra", "url": "https://arxiv.org/abs/1205.4904", "status": "stable", "kind": "primary_research", "implication": "Supports formal OPE consistency and coefficient obligations only, never empirical GMUT evidence."},
    {"source_id": "SRC-ET-DOCS", "title": "Einstein Toolkit official documentation", "url": "https://www.einsteintoolkit.org/documentation.html", "status": "current", "kind": "official_documentation", "implication": "Supplies thorn, Cactus, user-guide, and component-documentation context; this phase performs no checkout, build, or solver run."},
    {"source_id": "SRC-ET-TESTS", "title": "Einstein Toolkit guidance for adding a Cactus test case", "url": "https://docs.einsteintoolkit.org/et-docs/Adding_a_test_case", "status": "current", "kind": "official_documentation", "implication": "Distinguishes bounded regression tests from convergence and physics-correctness evidence; no test or convergence run occurs here."},
    {"source_id": "SRC-FAO-GENEBANK", "title": "FAO practical guides for application of genebank standards", "url": "https://www.fao.org/cgrfa/topics/plant-genetic-resources/practical-guides/en", "status": "current", "kind": "official_guidance", "implication": "Supplies accession, viability, documentation, distribution, and conservation context; it does not authorize community seed decisions here."},
    {"source_id": "SRC-CBD-DSI", "title": "Convention on Biological Diversity digital sequence information on genetic resources", "url": "https://www.cbd.int/dsi-gr", "status": "current", "kind": "official_authority", "implication": "Supplies current DSI and multilateral benefit-sharing context; repository authors make no legal interpretation, allocation, database, beneficiary, or authority decision."},
    {"source_id": "SRC-RFC7592", "title": "RFC 7592 OAuth 2.0 Dynamic Client Registration Management Protocol", "url": "https://www.rfc-editor.org/info/rfc7592/", "status": "stable", "kind": "official_experimental_specification", "implication": "Defines read, update, delete, registration-token, rotation, and deprovisioning behavior and remains Experimental."},
    {"source_id": "SRC-RFC7591", "title": "RFC 7591 OAuth 2.0 Dynamic Client Registration Protocol", "url": "https://www.rfc-editor.org/info/rfc7591/", "status": "stable", "kind": "official_standard", "implication": "Provides the adjacent registration metadata contract; synthetic vectors are not production registration evidence."},
    {"source_id": "SRC-NETCDF-NUG", "title": "Unidata netCDF-3 File Format Specifications", "url": "https://docs.unidata.ucar.edu/nug/2.0-draft/nc3_file_formats.html", "status": "draft", "kind": "official_format_specification", "implication": "Defines a draft documentation surface for CDF-1, CDF-2, and CDF-5 structural grammar; bounded fixtures do not promote the page to a final standard."},
    {"source_id": "SRC-WCAG22", "title": "Web Content Accessibility Guidelines 2.2", "url": "https://www.w3.org/TR/WCAG22/", "status": "stable", "kind": "official_standard", "implication": "Structural checks cover only declared obligations and cannot close manual or affected-user evaluation."},
    {"source_id": "SRC-W3C-ERRORS", "title": "W3C Understanding Error Identification", "url": "https://www.w3.org/WAI/WCAG22/Understanding/error-identification", "status": "current", "kind": "official_guidance", "implication": "Supports textual error identification; manual and assistive-technology evaluation remain reserved."},
    {"source_id": "SRC-W3C-G139", "title": "W3C G139 mechanism to jump to errors", "url": "https://www.w3.org/WAI/WCAG22/Techniques/general/G139", "status": "current", "kind": "official_technique", "implication": "Supplies an example error-summary and linking pattern, not a complete conformance method."},
    {"source_id": "SRC-IUPAC-LIPPMANN", "title": "IUPAC Gold Book Lippmann equation entry", "url": "https://goldbook.iupac.org/terms/view/L03577", "status": "current", "kind": "official_terminology", "implication": "Supports the electrocapillary derivative, fixed-variable, reference, sign, and surface-excess obligations only."},
    {"source_id": "SRC-ICH-E9R1", "title": "ICH E9(R1) Estimands and Sensitivity Analysis guideline", "url": "https://database.ich.org/sites/default/files/E9-R1_Step4_Guideline_2019_1203.pdf", "status": "stable", "kind": "official_guideline", "implication": "Supports estimand and sensitivity-analysis obligations without participant or Stage 20 evidence."},
    {"source_id": "SRC-EMA-MISSING", "title": "EMA guideline on missing data in confirmatory clinical trials", "url": "https://www.ema.europa.eu/en/missing-data-confirmatory-clinical-trials-scientific-guideline", "status": "current", "kind": "official_guideline", "implication": "Supplies missingness and pattern-mixture context; no trial or effect is evaluated here."},
    {"source_id": "SRC-NZ-PRIVACY", "title": "New Zealand Privacy Commissioner obligations guidance", "url": "https://www.privacy.org.nz/responsibilities/your-obligations/", "status": "current", "kind": "official_authority", "implication": "Real privacy, correction, disclosure, and remedy decisions require competent human authority and affected-person consideration."},
    {"source_id": "SRC-TE-MANA-RARAUNGA", "title": "Te Mana Raraunga principles of Māori data sovereignty", "url": "https://www.temanararaunga.maori.nz/principles-of-maori-data-sovereignty", "status": "stable", "kind": "primary_authority_source", "implication": "Māori data and concepts remain under Māori governance; software and citation confer no Māori authority."},
    {"source_id": "SRC-OPENAI-CODEX", "title": "OpenAI Codex official repository", "url": "https://github.com/openai/codex", "status": "watch", "kind": "official_package", "implication": "CLI version status may be observed; this phase performs no desktop application update."},
]


SAFE_TASKS = [
    "Verify Sable source, x1, evidence, parent-count, zero-merge, clean, and live-remote anchors",
    "Replay Sable x1, evidence, and final manifests from immutable Git blobs",
    "Carry five external Sable post-seal negatives without rewriting Sable's sealed count",
    "Record D-first capacity and fast-forward-only Orin lane continuity",
    "Audit all 670 frozen proposal titles and substantive neighbors with collision reasons",
    "Build the current, stable, draft, and watch source ledger without status flattening",
    "Freeze exactly ten proposals without x2 outcomes or completion claims",
    "Build immutable x1 Git-blob separation and staged-path receipts",
    "Run five-class privacy scanning with scanner-definition quarantine",
    "Record every tooling fault, false assumption, recovery, and passing witness",
    "Build and validate Method Flow fail-pass witness parity",
    "Refresh the phase-scoped GHC Family Index without global churn",
    "Run Reflection Remaster additively and preserve every compatibility surface",
    "Freeze the future completion-state tribunal plan",
    "Freeze the operator-product-expansion obligation plan",
    "Freeze the Einstein Toolkit zero-solver-run protocol",
    "Freeze the community seed-library germination-assay proxy plan",
    "Freeze the RFC 7592 registration-management profile plan",
    "Freeze the seed-passport and digital-sequence authority reservation plan",
    "Freeze the netCDF bounded parser tribunal plan",
    "Freeze the error-summary structural accessibility plan",
    "Freeze the Lippmann electrocapillary domain classifier plan",
    "Freeze the pattern-mixture nonpromotion board plan",
    "Freeze 70 proposal-linked synthetic mutations without executing them",
    "Preserve inherited exact-approval and blocked packets as unexecuted",
    "Measure owner-generated growth independently from inherited baseline",
    "Verify local and official Codex versions without updating desktop software",
    "Record Sandbox and Hyper-V as excluded and untouched",
    "Reserve one successful canonical scoped pass and prohibit replay",
    "Keep the Tamar route prepared but unsent until exact final proof",
]


CANDIDATE_TASKS = [
    "Future single-settlement and cancellation-race prototype",
    "Future callback-order and waiter-notification prototype",
    "OPE short-distance and scaling-degree obligation prototype",
    "OPE associativity and observation-firewall prototype",
    "Einstein Toolkit thorn-interface and variable-map prerequisite prototype",
    "Einstein Toolkit zero-solver-run and convergence-refusal prototype",
    "Seed germination sample and replicate-count prototype",
    "Seed censoring, retest, depletion-budget, amendment, and custody prototype",
    "RFC 7592 endpoint and registration-token binding prototype",
    "RFC 7592 full-update, rotation, deletion, and replay prototype",
    "Seed passport, geolocation, digital-sequence, and reidentification reservation prototype",
    "NetCDF signature, list, and padding prototype",
    "NetCDF offset, record-variable, and resource-budget prototype",
    "Error-summary heading, focus, and link prototype",
    "Error-summary association, correction, zoom, and fallback prototype",
    "Lippmann reference and fixed-variable domain prototype",
    "Lippmann agency-nonconversion prototype",
    "Pattern-mixture missingness and reference-imputation prototype",
    "Pattern-mixture tipping-point and uncertainty prototype",
    "Stage 20 pattern-mixture nonpromotion prototype",
]


SKILL_IDEAS = [
    "ghc-family-v649-v4-future-completion",
    "ghc-family-v649-v4-future-callback-order",
    "ghc-family-v649-v4-ope-obligations",
    "ghc-family-v649-v4-ope-observation-firewall",
    "ghc-family-v649-v4-einstein-toolkit-zero-run",
    "ghc-family-v649-v4-seed-germination-sampling",
    "ghc-family-v649-v4-seed-germination-custody",
    "ghc-family-v649-v4-registration-management",
    "ghc-family-v649-v4-registration-token-minimization",
    "ghc-family-v649-v4-seed-passport-dsi-reservation",
    "ghc-family-v649-v4-netcdf-tribunal",
    "ghc-family-v649-v4-netcdf-budget",
    "ghc-family-v649-v4-error-summary-association",
    "ghc-family-v649-v4-error-summary-fallback",
    "ghc-family-v649-v4-lippmann-domain",
    "ghc-family-v649-v4-lippmann-nonconversion",
    "ghc-family-v649-v4-pattern-mixture",
    "ghc-family-v649-v4-stage20-nonpromotion",
    "ghc-family-v649-v4-method-flow-recovery",
    "ghc-family-v649-v4-terminal-proof",
]


RUNNER_IDEAS = [
    "ghc_family_v649_v4_future_completion.py",
    "ghc_family_v649_v4_ope_obligations.py",
    "ghc_family_v649_v4_einstein_toolkit_refusal.py",
    "ghc_family_v649_v4_seed_germination_assay.py",
    "ghc_family_v649_v4_registration_management.py",
    "ghc_family_v649_v4_netcdf_tribunal.py",
    "ghc_family_v649_v4_accessibility_audit.py",
    "ghc_family_v649_v4_domain_guards.py",
    "ghc_family_v649_v4_portfolio.py",
    "build_ghc_family_v649_v4_closeout.py",
]


CLEANUP_TASKS = [
    "Normalize v649-v4 JSON ordering and UTF-8 output only",
    "Add explicit outcome vocabulary validation",
    "Add explicit source-status vocabulary validation",
    "Add exact proposal-count assertion",
    "Add exact frozen-chain count assertion",
    "Add source and lifecycle ancestry assertions",
    "Add zero-merge and final-parent assertions",
    "Add x1 and x2 contamination guards",
    "Add Git-blob versus checkout-byte domain labels",
    "Add five privacy class labels",
    "Add scanner-definition disposition",
    "Add document word-cap checks",
    "Add owner-file threshold measurement",
    "Add citation-not-observation flags",
    "Add same-owner and independent-reproduction separation",
    "Add Sandbox and Hyper-V no-action receipts",
    "Add desktop no-update receipt",
    "Add no-cross-platform-send receipt",
    "Add no-task and no-subagent receipt",
    "Add terminal route prepared-not-sent state",
    "Add accessibility manual-evaluation reservation",
    "Add Māori-language and authority reservation",
    "Add real-data and likelihood refusal fields",
    "Add participant and operator absence fields",
    "Add production identity absence fields",
    "Add exhaustive-security nonclaim fields",
    "Add rollback and recovery fields to every prototype",
    "Add protected-gate parity checks",
    "Add exact staged-path allowlist checks",
    "Add final remote-equality proof fields",
]


X1_OPERATIONAL_NEGATIVES = [
    {"negative_id": "V6494-X1-N01", "category": "windows_wildcard_path_fault", "failed": "Ripgrep rejected literal shell-style wildcard path arguments on Windows before searching.", "recovery": "Pass explicit directories and constrain filenames with -g include patterns.", "passing": "The corrected read-only search exited zero and returned matching predecessor tokens.", "recurrence_guard": "Use explicit directories with ripgrep -g patterns on Windows."},
    {"negative_id": "V6494-X1-N02", "category": "method_flow_redundant_transition", "failed": "A redundant explicit validated transition was rejected after the passing witness had already auto-promoted the method.", "recovery": "Inspect current ledger state after each witness and request only the next legal transition.", "passing": "The state was confirmed as validated and the validated-to-preferred transition passed.", "recurrence_guard": "Inspect method state after every witness operation before issuing a transition."},
    {"negative_id": "V6494-X1-N03", "category": "memory_registry_no_current_match", "failed": "The current memory registry had no exact v649-v3 or v649-v4 continuity entry.", "recovery": "Retain the no-match and use the live activation plus exact Git evidence as current authority.", "passing": "No continuity credit was inferred from memory silence; the live baton and Git evidence controlled.", "recurrence_guard": "Treat exact-current memory absence as absence, not proof or contradiction."},
    {"negative_id": "V6494-X1-N04", "category": "overbroad_worktree_inventory", "failed": "The first repository worktree inventory emitted a very large historical surface that obscured the current lane proof.", "recovery": "Use compact exact-repository probes for named owner and source worktrees after locating them.", "passing": "Compact source and owner probes established exact heads, clean states, ancestry, and live equality.", "recurrence_guard": "Use the global worktree list only for discovery, then switch to exact named probes."},
    {"negative_id": "V6494-X1-N05", "category": "schema_probe_overoutput", "failed": "A frozen-index schema probe also serialized the full 670-proposal corpus and produced truncated output.", "recovery": "Query only top-level keys, counts, targeted titles, or exact semantic-neighbor terms.", "passing": "Targeted searches returned attributable collision and no-collision evidence without flattening the corpus.", "recurrence_guard": "Never serialize the full frozen index when only schema fields or neighbors are needed."},
    {"negative_id": "V6494-X1-N06", "category": "semantic_seed_collisions", "failed": "Initial seeds collided with frozen backpressure, Epstein-Glaser, Gaia, museum, DPoP, treegrid, Gibbs-Duhem, and target-trial proposals.", "recovery": "Reject collided seeds and form a provisional candidate set for the aggregate frozen-corpus screen.", "passing": "Narrow searches produced a provisional ten-candidate set; later aggregate guards separately rejected and replaced three candidates before freeze.", "recurrence_guard": "Treat plausible novelty as a hypothesis until the aggregate lexical and substantive neighbor checks pass."},
    {"negative_id": "V6494-X1-N07", "category": "fast_forward_summary_truncation", "failed": "The successful inherited fast-forward emitted an oversized change summary that was truncated and earned no compact proof credit.", "recovery": "Run exact head, branch, clean, divergence, tracking, and live-remote probes after the fast-forward.", "passing": "The compact proof established the Orin branch at Sable's exact final with a clean four-way-equal state.", "recurrence_guard": "Validate a large fast-forward with separate compact exact probes."},
    {"negative_id": "V6494-X1-N08", "category": "token_inventory_output_truncation", "failed": "The corrected broad token inventory returned matches but its display was truncated before a complete manual inventory could be credited.", "recovery": "Use narrower exact-token and file-specific searches for each substantive replacement.", "passing": "Narrow proposal and source searches supplied bounded attributable evidence for each selected mechanism.", "recurrence_guard": "Use broad searches only for discovery and narrow them before awarding completeness credit."},
    {"negative_id": "V6494-X1-N09", "category": "native_output_split_precedence", "failed": "A compact equality probe applied PowerShell -split inside the native git expression and reduced the live hash to one character.", "recovery": "Capture git ls-remote output in a separate variable, verify the native exit status, then split the captured line.", "passing": "The corrected probe recovered the complete live hash and proved four-way source equality before x1 freeze.", "recurrence_guard": "Evaluate native commands and parse their captured output in separate statements."},
    {"negative_id": "V6494-X1-N10", "category": "grouped_login_shell_timeout", "failed": "A grouped status, inventory, and help probe timed out during login-shell startup before returning usable evidence.", "recovery": "Retry the read-only checks as isolated commands with login-shell initialization disabled.", "passing": "The isolated status and Method Flow help probes completed within their bounded timeouts.", "recurrence_guard": "Use no-profile isolated probes for bounded Windows lifecycle checks instead of grouping unrelated startup-sensitive commands."},
    {"negative_id": "V6494-X1-N11", "category": "combined_live_remote_timeout", "failed": "The corrected four-way probe grouped local checks with the live network lookup and timed out before returning a result.", "recovery": "Run local, upstream, tracking, and dirty-state checks separately from a longer bounded live-remote lookup, then compare the captured hashes.", "passing": "The split probes returned complete hashes and established exact equality without repeating the parsing fault.", "recurrence_guard": "Isolate live network lookups from local Git checks and assign them an explicit bounded network timeout."},
    {"negative_id": "V6494-X1-N12", "category": "local_status_timeout", "failed": "The first split local equality probe still timed out because full repository status enumeration exceeded the ten-second bound.", "recovery": "Retain the timeout and rerun the same read-only local checks under a measured longer bound without changing their evidence criteria.", "passing": "The longer bounded local probe returned exact local, upstream, tracking, branch, and phase-owned dirty-state evidence.", "recurrence_guard": "Budget status enumeration separately for inherited large checkouts and do not infer cleanliness from a timed-out probe."},
    {"negative_id": "V6494-X1-N13", "category": "frozen_proposal_collision", "failed": "The first preregistration build rejected the proposed 4XMM-DR14 catalogue adapter at Jaccard 0.5357 against the frozen Chandra catalogue adapter V6485-P03.", "recovery": "Withdraw the catalogue-adapter seed and substitute a substantively distinct Einstein Toolkit numerical-implementation and zero-solver-run protocol without relaxing the novelty threshold.", "passing": "The revised ten-proposal set passed the unchanged lexical threshold and manual substantive-neighbor review across all 670 frozen proposals.", "recurrence_guard": "Treat a different instrument or catalogue as insufficient novelty when the evidence mechanism and prerequisite shape collide."},
    {"negative_id": "V6494-X1-N14", "category": "practice_proxy_collision", "failed": "The second preregistration build rejected the seed-library intake and handover proxy at Jaccard 0.5000 against Sable's immediately prior community food-bank intake and handover proxy V6493-P04.", "recovery": "Withdraw the generic intake-hold-notice-workload pattern and replace it with a germination-assay sampling, replicate, censoring, retest, depletion-budget, amendment, and custody mechanism.", "passing": "The assay-specific proxy passed the unchanged lexical threshold and substantive-neighbor review without inheriting completion credit.", "recurrence_guard": "A new practice domain does not make a repeated intake-hold-handover mechanism novel; change the operational hypothesis and falsifier."},
    {"negative_id": "V6494-X1-N15", "category": "authority_matrix_collision", "failed": "The third preregistration build rejected the initial seed-stewardship authority matrix at Jaccard 0.5862 against Sable's immediately prior food-access authority matrix V6493-P06.", "recovery": "Withdraw the generic access-privacy-remedy matrix and substitute a seed-passport, collection-site, digital-sequence linkage, reidentification, material-transfer, and benefit-sharing authority gate after frozen-neighbor review.", "passing": "The replacement exact-gate mechanism passed the unchanged lexical threshold and substantive-neighbor review.", "recurrence_guard": "Do not treat a new beneficiary domain as novelty when the authority-matrix fields and completion gate are inherited."},
    {"negative_id": "V6494-X1-N16", "category": "unicode_diagnostic_stream_fault", "failed": "A targeted frozen-title diagnostic emitted Māori text through the default CP1252 stream and failed before printing the requested row.", "recovery": "Pin PYTHONUTF8=1 for the same read-only diagnostic and keep the failed stream attempt as evidence.", "passing": "The UTF-8-pinned diagnostic returned the exact frozen neighbor without repository mutation.", "recurrence_guard": "Pin UTF-8 before any diagnostic that may emit Māori or other non-CP1252 text."},
    {"negative_id": "V6494-X1-N17", "category": "x1_builder_rerun_allowlist_fault", "failed": "The idempotent x1 rebuild rejected its own previously generated x1 documents because the startup allowlist covered only seed inputs.", "recovery": "Permit phase-owned generated x1 paths on rerun while explicitly rejecting x2, evidence, report, runtime, closeout, seal, final, and observed-outcome markers.", "passing": "The narrowed rerun guard accepted only the existing x1 surface and rebuilt receipts without admitting x2 implementation or outcomes.", "recurrence_guard": "Separate first-run seed allowlists from idempotent x1-output allowlists and keep explicit x2 marker rejection in both."},
]
