#!/usr/bin/env python3
"""Frozen definitions for Eiren Kestrel's v648-v3 repeat-phase x1 packet."""

from __future__ import annotations

SOURCE_COMMIT = "f3a90b0280ff8f3504353da3b6a37ef0540e3296"
SOURCE_PHASE = "v648-gmut-thos-v3-x1-x2"
PHASE = "v648-gmut-thos-v3-x1-x2-r2"
PHASE_SLUG = "v648-v3-2"
OWNER = "Eiren Kestrel"
BRANCH = "codex/GHC-Family/eiren-kestrel-v648-v3-2-full-tools"
PRIMARY_FOCUS = "THOS Body"
BOUNDED_PRACTICE = (
    "software maintenance, configuration management, release engineering, and incident handover "
    "as a learning and design lens only"
)
OUTCOME_CLASSES = ["completed", "represented", "open_gap", "exact_gate"]

PROPOSALS = [
    {
        "proposal_id": "V6483R2-P01",
        "title": "GHC Family Reflection-Remaster dependency, trigger-collision, caller-compatibility, consolidation, deprecation, rollback, and evidence-credit tribunal",
        "pillar": "THOS Body",
        "hypothesis": "A bounded dependency and caller audit can identify safe additive remasters while preserving historical compatibility and failed evidence.",
        "null_or_failure_condition": "The audit lacks callers, trigger overlap, rollback, or evidence for a proposed merge or deprecation.",
        "approval_class": "safe_now_owner_scoped_additive",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-GIT-CAT", "SRC-GIT-HASH", "SRC-SEMVER"],
        "artifacts": ["reflection-remaster/assessment.json", "reflection-remaster/issues.json", "reflection-remaster/remaster-receipt.json"],
        "falsifier_or_acceptance_gate": "Accept only remasters with an explicit caller inventory, compatibility plan, bounded witness, rollback, and no destructive deletion.",
        "rollback_or_recovery": "Keep the prior family-current surface active and retain the proposed remaster as unpromoted.",
        "protected_gates": ["identity_records", "historical_evidence", "sibling_lanes", "destructive_cleanup"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6483R2-P02",
        "title": "GMUT Epstein-Glaser causal-factorization, distribution-splitting, scaling-degree, locality, counterterm, renormalization-ambiguity, EFT, unit, and observation-firewall board",
        "pillar": "GMUT Mind",
        "hypothesis": "A typed obligation board can distinguish formal causal-perturbation constraints from empirical GMUT support.",
        "null_or_failure_condition": "The board collapses formal distribution-extension obligations into observed physics or omits domains and units.",
        "approval_class": "safe_now_symbolic_research_only",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-EPSTEIN-GLASER"],
        "artifacts": ["gmut/epstein-glaser-obligations.json", "gmut/epstein-glaser-mutations.json"],
        "falsifier_or_acceptance_gate": "Every formal row must preserve locality, scaling and ambiguity obligations and keep empirical confirmation false.",
        "rollback_or_recovery": "Withdraw the formal adapter and retain the mismatch as a negative.",
        "protected_gates": ["empirical_confirmation", "theory_of_everything", "proof_or_canon"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6483R2-P03",
        "title": "GMUT LVK O4 public-alert superevent, preferred-event, false-alarm-rate, classification, skymap-version, selection, calibration, waveform-systematic, and zero-row likelihood-refusal adapter",
        "pillar": "GMUT Mind",
        "hypothesis": "An official-format adapter can expose the exact data and likelihood prerequisites without treating an alert schema as a measurement result.",
        "null_or_failure_condition": "The adapter ingests no real rows or lacks selection, calibration, covariance, or likelihood evidence.",
        "approval_class": "real_data_and_independent_review_required",
        "execution_lane": "x2_open_gap",
        "source_needs": ["SRC-LVK-SUPEREVENT", "SRC-LVK-CONTENT"],
        "artifacts": ["empirical/lvk-o4-study-contract.json", "empirical/lvk-o4-zero-row-receipt.json"],
        "falsifier_or_acceptance_gate": "Remain open_gap while real rows, a preregistered likelihood, systematics, and independent review are absent.",
        "rollback_or_recovery": "Retain the zero-row refusal and make no likelihood, force, prediction, or confirmation claim.",
        "protected_gates": ["real_data", "empirical_likelihood", "independent_review", "physical_prediction"],
        "expected_disposition": "open_gap",
    },
    {
        "proposal_id": "V6483R2-P04",
        "title": "THOS release-baseline, change-control, build-provenance, compatibility, dual-review, rollback, workload-budget, readback, and next-maintainer handover proxy",
        "pillar": "THOS Body",
        "hypothesis": "A synthetic configuration-management handover can represent bounded operational obligations without real maintainers or deployment.",
        "null_or_failure_condition": "The proxy omits baseline identity, change authority, provenance, rollback, workload, or readback.",
        "approval_class": "safe_now_proxy_protocol_no_people_or_operations",
        "execution_lane": "x2_proxy_protocol",
        "source_needs": ["SRC-NIST-SSDF", "SRC-GIT-CAT"],
        "artifacts": ["thos/release-handover-contract.json", "thos/release-handover-vectors.json"],
        "falsifier_or_acceptance_gate": "Represented only when every synthetic vector is bounded and all real deployment and worker claims remain false.",
        "rollback_or_recovery": "Revert to a design-only checklist and retain any failed vector.",
        "protected_gates": ["deployment", "professional_authority", "real_workers", "production_readiness"],
        "expected_disposition": "represented",
    },
    {
        "proposal_id": "V6483R2-P05",
        "title": "Freed ID OAuth attestation-based client-authentication, client-instance-key, attestation-JWT, proof-of-possession, challenge, replay, rotation, trust-resolution, privacy, and draft-watch profile",
        "pillar": "Freed ID / CBR Heart",
        "hypothesis": "A synthetic draft-watch profile can test key binding and refusal logic without production credentials or trust claims.",
        "null_or_failure_condition": "The profile accepts missing binding, stale challenge, replay, unsafe algorithm, or ungoverned trust resolution.",
        "approval_class": "safe_now_synthetic_draft_watch_nonproduction",
        "execution_lane": "x2_proxy_protocol",
        "source_needs": ["SRC-IETF-ATTESTATION"],
        "artifacts": ["freed-id/client-attestation-profile.json", "freed-id/client-attestation-mutations.json"],
        "falsifier_or_acceptance_gate": "Represented only; draft status, synthetic keys, absent live resolution and absent governance stay explicit.",
        "rollback_or_recovery": "Reject the fixture, preserve the negative, and wait for a current standards-conformant production design.",
        "protected_gates": ["real_keys", "production_identity", "trust_governance", "privacy_review"],
        "expected_disposition": "represented",
    },
    {
        "proposal_id": "V6483R2-P06",
        "title": "CBR software-maintenance automation regression, maintainer-labour and diagnostic privacy, accessible notice, rollback appeal, restorative remedy, affected-party co-design, legal, cultural, and Maori data-governance authority matrix",
        "pillar": "Freed ID / CBR Heart",
        "hypothesis": "A reservation matrix can make remedy and authority dependencies explicit without pretending repository authors can decide them.",
        "null_or_failure_condition": "Any legal, cultural, Maori-authority, employment, privacy-remedy, or affected-party decision is marked completed by software evidence.",
        "approval_class": "authorized_affected_parties_and_competent_authority_required",
        "execution_lane": "x2_exact_gate",
        "source_needs": ["SRC-NZ-PRIVACY", "SRC-TE-MANA-RARAUNGA"],
        "artifacts": ["cbr/maintenance-incident-remedy-matrix.json", "cbr/maintenance-authority-reservation.json"],
        "falsifier_or_acceptance_gate": "Remain exact_gate until affected parties, Maori authorities, and competent legal or cultural authorities decide within their scope.",
        "rollback_or_recovery": "Remove any accidental authority claim and retain the incident as a failed assumption.",
        "protected_gates": ["affected_party_legitimacy", "maori_authority", "legal_interpretation", "cultural_ratification"],
        "expected_disposition": "exact_gate",
    },
    {
        "proposal_id": "V6483R2-P07",
        "title": "Deterministic CBOR and COSE major-type, shortest-form, map-order, duplicate-key, tag, indefinite-length, algorithm, nesting, output-budget, and refusal tribunal",
        "pillar": "THOS Body",
        "hypothesis": "A bounded parser tribunal can reject ambiguous or resource-exhausting synthetic encodings while preserving protocol-specific exceptions.",
        "null_or_failure_condition": "The tribunal accepts duplicate keys, non-deterministic encodings, unsupported algorithms, or unbounded nesting/output.",
        "approval_class": "safe_now_owner_scoped_parser_fixture",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-RFC8949", "SRC-RFC9053"],
        "artifacts": ["formats/cbor-cose-contract.json", "formats/cbor-cose-mutations.json"],
        "falsifier_or_acceptance_gate": "All declared malformed fixtures must be rejected and no exhaustive-security claim may be made.",
        "rollback_or_recovery": "Disable the parser wrapper and retain the failing fixture.",
        "protected_gates": ["exhaustive_security", "production_parser", "external_payloads"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6483R2-P08",
        "title": "Accessible change-diff insertion, deletion, non-colour cue, line-context, keyboard-order, focus, copy, print, and manual-evaluation reservation audit",
        "pillar": "THOS Body",
        "hypothesis": "A structural audit can verify redundant change semantics and navigation without claiming complete accessibility.",
        "null_or_failure_condition": "Additions or deletions rely on colour alone, reading order is ambiguous, or manual and affected-user evaluation are claimed complete.",
        "approval_class": "safe_now_structural_only",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-WCAG22", "SRC-WHATWG-EDITS"],
        "artifacts": ["accessibility/change-diff-contract.json", "accessibility/change-diff-mutations.json"],
        "falsifier_or_acceptance_gate": "Pass only bounded structural fixtures; reserve keyboard, browser, assistive-technology, Maori-language, and affected-user evaluation.",
        "rollback_or_recovery": "Restore plain sequential text and retain the structural failure.",
        "protected_gates": ["complete_accessibility", "manual_evaluation", "affected_user_acceptance"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6483R2-P09",
        "title": "Thermo-Psyche temporal Fisher-information, statistical-distance, entropy-production, activity, state-transform speed-limit, unit, domain, and urgency-agency nonconversion classifier",
        "pillar": "Trinity Mandala bridge",
        "hypothesis": "A typed classifier can preserve physical speed-limit assumptions while refusing conversion into psychological urgency, value, agency, or moral worth.",
        "null_or_failure_condition": "Physical information geometry is used as a measure of human urgency, agency, consciousness, or value.",
        "approval_class": "safe_now_formal_domain_guard",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-THERMO-SPEED"],
        "artifacts": ["thermo-psyche/fisher-speed-contract.json", "thermo-psyche/fisher-speed-mutations.json"],
        "falsifier_or_acceptance_gate": "Every accepted row states dynamics, metric, cost, units and domain; all psyche conversions are rejected.",
        "rollback_or_recovery": "Remove the analogy and retain only the physical statement.",
        "protected_gates": ["psyche_conversion", "consciousness", "personhood", "moral_value"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6483R2-P10",
        "title": "Stage 20 marginal-structural-model time-varying treatment, treatment-confounder feedback, stabilized-weight, positivity, censoring, model-diagnostic, sensitivity, and nonpromotion board",
        "pillar": "Trinity Mandala bridge",
        "hypothesis": "A marginal-structural-model board can expose longitudinal causal assumptions without turning zero-participant software fixtures into effectiveness evidence.",
        "null_or_failure_condition": "Treatment-confounder feedback, weighting, positivity, censoring, model diagnostics, or sensitivity obligations are absent or software results are promoted as participant evidence.",
        "approval_class": "safe_now_structural_nonpromotion",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-MSM"],
        "artifacts": ["stage20/marginal-structural-contract.json", "stage20/marginal-structural-mutations.json"],
        "falsifier_or_acceptance_gate": "Pass only structural protocol fixtures; real participants, outcomes, safety monitoring and independent review remain absent.",
        "rollback_or_recovery": "Retain the failed fixture and keep effectiveness and Stage 20 claims false.",
        "protected_gates": ["real_participants", "causal_effect", "independent_review", "stage20"],
        "expected_disposition": "completed",
    },
]

SOURCES = [
    {"source_id": "SRC-LIVE-REQUEST", "title": "Hamish current v648-v3 repeat-phase instruction", "url": None, "status": "current", "kind": "live_authority", "implication": "Controls phase scope, no-replay rule, cross-platform exclusion, document caps, commit cap, and exact Ilyra route."},
    {"source_id": "SRC-GIT-HASH", "title": "Git hash-object documentation", "url": "https://git-scm.com/docs/git-hash-object", "status": "current", "kind": "official", "implication": "Use the Git filtered blob domain when content identity matters."},
    {"source_id": "SRC-GIT-CAT", "title": "Git cat-file documentation", "url": "https://git-scm.com/docs/git-cat-file.html", "status": "current", "kind": "official", "implication": "Batch object reads avoid per-object process overhead and preserve committed-byte truth."},
    {"source_id": "SRC-SEMVER", "title": "Semantic Versioning 2.0.0", "url": "https://semver.org/", "status": "stable", "kind": "official", "implication": "Compatibility and deprecation decisions need explicit public contract boundaries."},
    {"source_id": "SRC-NIST-SSDF", "title": "NIST SP 800-218 Secure Software Development Framework", "url": "https://csrc.nist.gov/pubs/sp/800/218/final", "status": "stable", "kind": "official", "implication": "Release provenance, protected integrity, and retained artifacts support bounded configuration-management controls."},
    {"source_id": "SRC-EPSTEIN-GLASER", "title": "Connes-Kreimer-Epstein-Glaser Renormalization", "url": "https://arxiv.org/abs/hep-th/0006106", "status": "stable", "kind": "primary_research", "implication": "Causal perturbation extends time-ordered distributions and leaves renormalization obligations; it is not empirical GMUT confirmation."},
    {"source_id": "SRC-LVK-SUPEREVENT", "title": "IGWN Public Alerts User Guide: Superevents", "url": "https://emfollow.docs.ligo.org/userguide/analysis/superevents.html", "status": "current", "kind": "official", "implication": "Superevents unify candidates and inherit preferred-event significance, localization and classification."},
    {"source_id": "SRC-LVK-CONTENT", "title": "IGWN Public Alerts User Guide: Alert Contents", "url": "https://emfollow.docs.ligo.org/userguide/content.html", "status": "current", "kind": "official", "implication": "Official alert fields define a format contract, not a GMUT likelihood or physical result."},
    {"source_id": "SRC-IETF-ATTESTATION", "title": "OAuth 2.0 Attestation-Based Client Authentication draft-09", "url": "https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/", "status": "draft", "kind": "official_draft", "implication": "Client attestation and proof of possession are key-bound; trust resolution and parts of attester interaction remain out of scope."},
    {"source_id": "SRC-RFC8949", "title": "RFC 8949 Concise Binary Object Representation", "url": "https://www.rfc-editor.org/rfc/rfc8949.html", "status": "stable", "kind": "official_standard", "implication": "Deterministic encoding, unique map keys and application-level validity need explicit handling."},
    {"source_id": "SRC-RFC9053", "title": "RFC 9053 COSE Initial Algorithms", "url": "https://www.rfc-editor.org/rfc/rfc9053.html", "status": "stable", "kind": "official_standard", "implication": "COSE algorithm and duplicate-label processing need fail-closed policy."},
    {"source_id": "SRC-WCAG22", "title": "Web Content Accessibility Guidelines 2.2", "url": "https://www.w3.org/TR/WCAG22/", "status": "stable", "kind": "official_standard", "implication": "Change meaning must not rely on colour alone and structural checks cannot replace user evaluation."},
    {"source_id": "SRC-WHATWG-EDITS", "title": "WHATWG HTML Standard: Edits", "url": "https://html.spec.whatwg.org/multipage/edits.html", "status": "current", "kind": "official_standard", "implication": "ins and del represent additions and deletions with structural constraints."},
    {"source_id": "SRC-THERMO-SPEED", "title": "Time-information uncertainty relations in thermodynamics", "url": "https://arxiv.org/abs/2001.05418", "status": "stable", "kind": "primary_research", "implication": "Fisher-information bounds concern physical or stochastic dynamics and do not measure psyche, urgency or agency."},
    {"source_id": "SRC-THERMO-SPEED-WATCH", "title": "Unified speed limits via temporal Fisher information", "url": "https://journals.aps.org/pre/accepted/10.1103/x95d-fhpq", "status": "watch", "kind": "primary_research_accepted", "implication": "A 2026 accepted result is useful watch material but remains domain-specific and non-convertible to personhood claims."},
    {"source_id": "SRC-MSM", "title": "Marginal structural models and causal inference in epidemiology", "url": "https://pubmed.ncbi.nlm.nih.gov/10955408/", "status": "stable", "kind": "primary_method", "implication": "Longitudinal causal estimation with treatment-confounder feedback requires explicit identifying assumptions, weighting, diagnostics and positivity; a software fixture is not participant evidence."},
    {"source_id": "SRC-NZ-PRIVACY", "title": "New Zealand Privacy Commissioner breach guidance", "url": "https://www.privacy.org.nz/responsibilities/privacy-breaches/", "status": "current", "kind": "official_authority", "implication": "Serious-harm assessment, notification and affected-person duties require competent real-world decisions; repository software cannot make them."},
    {"source_id": "SRC-TE-MANA-RARAUNGA", "title": "Te Mana Raraunga principles of Maori data sovereignty", "url": "https://www.temanararaunga.maori.nz/principles-of-maori-data-sovereignty", "status": "stable", "kind": "primary_authority_source", "implication": "Maori data should remain under Maori governance; software artifacts confer no Maori authority."},
    {"source_id": "SRC-CODEX-CLI", "title": "OpenAI Codex CLI stable npm channel", "url": "https://www.npmjs.com/package/@openai/codex", "status": "watch", "kind": "official_package", "implication": "The CLI may be updated after a stable-channel check; the desktop package remains status-only in this phase."},
]

SAFE_TASKS = [
    "Build a family-tool dependency and caller inventory",
    "Classify trigger collisions and overlapping responsibilities",
    "Draft the Reflection-Remaster issue and decision schema",
    "Bind file-based baton metadata to committed repository-relative artifacts",
    "Generate a single-pass validation and no-replay credit plan",
    "Refresh the family index with current and compatibility surfaces",
    "Record the current CLI and desktop version boundary",
    "Record D-first storage and C-drive headroom without cleanup",
    "Audit the 580-title core-proposal corpus for semantic novelty",
    "Build the official and primary source ledger with four status classes",
    "Build a five-class privacy pattern set",
    "Build an x1-to-x2 byte-separation contract",
    "Build a document-cap and file-baton word-count contract",
    "Prepare the exact-title Ilyra route as PREPARED_NOT_SENT",
    "Record Sandbox, Hyper-V, and cross-platform messaging as user-deferred",
]

CANDIDATE_TASKS = [
    "Reflection-Remaster dependency graph prototype",
    "Reflection-Remaster merge-versus-wrapper decision prototype",
    "Reflection-Remaster deprecation and rollback prototype",
    "Epstein-Glaser obligation classifier prototype",
    "LVK alert zero-row contract prototype",
    "Release configuration handover proxy",
    "Client-attestation draft-watch profile",
    "Maintenance incident authority reservation matrix",
    "Deterministic CBOR refusal engine",
    "Accessible change-diff structural audit",
    "Fisher speed-limit domain classifier",
    "Marginal-structural-model nonpromotion board",
    "File-baton commit and word-count manifest",
    "Single-pass evidence noncompensation gate",
    "Family-current caller-compatibility wrapper map",
    "Method Flow issue-to-witness crosslinker",
    "Official-source status drift ledger",
    "Document-cap validator",
    "Five-class privacy adjudicator",
    "Exact route acknowledgement recorder",
]

SKILL_IDEAS = [
    "ghc-family-reflection-remaster",
    "ghc-family-dependency-caller-inventory",
    "ghc-family-trigger-collision-audit",
    "ghc-family-compatibility-wrapper-planner",
    "ghc-family-deprecation-rollback-guard",
    "ghc-family-file-baton-manifest",
    "ghc-family-single-pass-validation-credit",
    "ghc-family-epstein-glaser-obligations",
    "ghc-family-lvk-o4-zero-row",
    "ghc-family-release-handover-proxy",
    "ghc-family-client-attestation-draft-watch",
    "ghc-family-maintenance-authority-reservation",
    "ghc-family-deterministic-cbor-tribunal",
    "ghc-family-accessible-change-diff",
    "ghc-family-fisher-speed-domain",
    "ghc-family-marginal-structural-nonpromotion",
    "ghc-family-document-cap-guard",
    "ghc-family-five-class-privacy-guard-v2",
    "ghc-family-method-issue-crosslink",
    "ghc-family-exact-route-pointer",
]

RUNNER_IDEAS = [
    "ghc_family_reflection_remaster.py",
    "ghc_family_epstein_glaser_obligations.py",
    "ghc_family_lvk_o4_zero_row.py",
    "ghc_family_release_handover.py",
    "ghc_family_client_attestation_profile.py",
    "ghc_family_maintenance_authority.py",
    "ghc_family_deterministic_cbor.py",
    "ghc_family_accessible_change_diff.py",
    "ghc_family_fisher_speed_domain.py",
    "ghc_family_marginal_structural_board.py",
]

CLEANUP_TASKS = [
    "Inventory version-named runners without deleting them",
    "Classify family-current versus compatibility runners",
    "Identify duplicate trigger language across GHC skills",
    "Identify unresolved caller references before any deprecation",
    "Normalize new repository-relative artifact pointers",
    "Normalize LF endings for new phase artifacts",
    "Remove only generated placeholders created by this phase",
    "Check new JSON schema names for phase consistency",
    "Check new Markdown documents against the 6000-word cap",
    "Check the baton draft against the 4000-to-10000-word range",
    "Check x1 artifacts for accidental x2 outcomes",
    "Check every proposal has a null or failure condition",
    "Check every proposal has rollback and protected gates",
    "Check source rows use current stable draft or watch",
    "Check no citation is promoted to experimental evidence",
    "Check no Sandbox or Hyper-V activation claim exists",
    "Check no cross-platform ChatGPT send claim exists",
    "Check no raw task or thread identifiers exist",
    "Check no private absolute paths exist",
    "Check no credential or callable identifier exists",
    "Check no real participant or beneficiary data exists",
    "Check no production key or token exists",
    "Check no legal or cultural authority claim exists",
    "Check no Maori authority claim exists",
    "Check no AGI ASI consciousness or personhood claim exists",
    "Check no Theory-of-Everything confirmation claim exists",
    "Check no independent-reproduction claim exists",
    "Check no replay credit is planned",
    "Check commit-count plan remains at three and below four",
    "Check terminal route remains PREPARED_NOT_SENT",
]

X1_OPERATIONAL_NEGATIVES = [
    {
        "negative_id": "V6483R2-X1-N01",
        "failure": "A combined preflight wrapper treated ripgrep's expected no-match exit for AGENTS.md as fatal and discarded drive and worktree results.",
        "recovery": "Run instruction, drive, and worktree probes independently and normalize the expected no-match exit.",
    },
    {
        "negative_id": "V6483R2-X1-N02",
        "failure": "A PowerShell JSON-shape foreach pipeline produced EmptyPipeElement and aborted an aggregate inspection.",
        "recovery": "Assign foreach output to an array before piping it to ConvertTo-Json.",
    },
    {
        "negative_id": "V6483R2-X1-N03",
        "failure": "A second portfolio-shape command repeated the foreach pipeline parser fault.",
        "recovery": "Use a pre-materialized result array and refuse direct foreach-to-pipeline composition.",
    },
    {
        "negative_id": "V6483R2-X1-N04",
        "failure": "A novelty-term probe repeated the same direct foreach pipeline parser fault.",
        "recovery": "Adopt the array-before-pipeline pattern as the preferred Windows PowerShell recurrence guard.",
    },
    {
        "negative_id": "V6483R2-X1-N05",
        "failure": "The first x1 builder correctly rejected a target-trial proposal title at the conservative lexical collision threshold.",
        "recovery": "Replace the colliding proposal with a genuinely different marginal-structural-model surface; do not relax the threshold.",
    },
    {
        "negative_id": "V6483R2-X1-N06",
        "failure": "A collision-diagnostic max operation tried to compare proposal dictionaries when two scores tied.",
        "recovery": "Select maxima with an explicit numeric score key so payload objects are never tie-break comparands.",
    },
    {
        "negative_id": "V6483R2-X1-N07",
        "failure": "The corrected collision diagnostic reached a Maori macron and failed while printing through the Windows cp1252 console encoder.",
        "recovery": "Pin PYTHONUTF8 before process launch and preserve the unchanged Unicode text.",
    },
    {
        "negative_id": "V6483R2-X1-N08",
        "failure": "The x1 builder requested the IANA Pacific/Auckland zone from Python, but the optional tzdata package was absent on this Windows host.",
        "recovery": "Use the configured Windows local timezone and fail closed unless its UTC offset is valid for New Zealand standard or daylight time.",
    },
    {
        "negative_id": "V6483R2-X1-N09",
        "failure": "The first x1 contract review expected a route-mode synonym instead of the exact frozen short-file-pointer enum and returned 32 of 33 checks.",
        "recovery": "Bind the review to the exact serialized route enum; do not rewrite a valid frozen packet to satisfy an unfrozen synonym.",
    },
    {
        "negative_id": "V6483R2-X1-N10",
        "failure": "The retained-negative register used a stale hard-coded projected total after new x1 failures were appended.",
        "recovery": "Derive the projected total from inherited plus current operational plus frozen synthetic counts and assert the arithmetic dynamically.",
    },
    {
        "negative_id": "V6483R2-X1-N11",
        "failure": "The first Git-index privacy review treated the x1 builder's own route-pattern definition as a confirmed payload hit.",
        "recovery": "Classify the exact builder path as a scanner definition while preserving confirmed-hit treatment for every non-scanner path.",
    },
]
