#!/usr/bin/env python3
"""Frozen proposal, source, and portfolio data for Sable Rook v649-v3 x1."""

from __future__ import annotations

from typing import Any


def proposal(number: int, **fields: Any) -> dict[str, Any]:
    return {"proposal_id": f"V6493-P{number:02d}", **fields}


PROPOSALS = [
    proposal(
        1,
        title="RO-Crate 1.3 root-data, contextual-entity, hasPart, checksum, external-reference, source-independence, duplicate-credit, and orphan quarantine tribunal",
        pillar="cross_pillar_provenance",
        mission_surface="RO-Crate 1.3 JSON-LD context, metadata descriptor, root data entity, data and contextual entities, hasPart reachability, checksums, external references, source-independence labels, duplicate-credit refusal, and orphan quarantine",
        hypothesis="A bounded structural tribunal can preserve RO-Crate entity roles and reject orphan, duplicate-credit, checksum, and external-reference ambiguities without claiming complete provenance or independent reproduction.",
        null_or_failure_condition="A fixture lacks its metadata or root entity, confuses contextual and data entities, leaves a local entity unreachable, accepts a checksum mismatch, counts one source twice, treats an external reference as locally preserved, or promotes a crate to independent evidence.",
        approval_class="safe_now_bounded_structural",
        execution_lane="x2_synthetic_metadata_fixtures",
        official_or_primary_source_needs=["RO-CRATE-1.3"],
        concrete_artifacts=["provenance/ro-crate-contract.json", "provenance/ro-crate-mutations.json", "scripts/ghc_family_v649_v3_ro_crate.py"],
        test_falsifier_or_acceptance_gate="Accept one bounded synthetic crate and reject seven root, role, reachability, checksum, external-reference, source-independence, duplicate-credit, or promotion mutations.",
        rollback_or_recovery="Quarantine the malformed crate, retain the failed edge or credit claim, rebuild only the owner-local fixture, and grant no provenance-completeness or independent-reproduction credit.",
        protected_gates=["provenance_complete", "source_independence", "independent_reproduction", "external_content_retrieval"],
        expected_disposition="completed",
        novelty_against_prior_frozen_proposals="The frozen chain includes W3C PROV, evidence DAGs, manifests, transparency logs, SLSA, in-toto, and archive lineage, but no RO-Crate 1.3 root/contextual/data entity roles with hasPart reachability, external-reference isolation, and duplicate-credit refusal.",
    ),
    proposal(
        2,
        title="GMUT Haag-Kastler local-net isotony, locality, covariance, spectrum, vacuum, additivity, time-slice, gauge, EFT, unit, and observation-firewall obligation board",
        pillar="GMUT Mind",
        mission_surface="bounded-region algebra assignment, isotony, spacelike locality, covariance representation, spectrum condition, vacuum scope, additivity, time-slice assumptions, gauge-observable restriction, EFT truncation, units, and observation firewall",
        hypothesis="Typed symbolic obligations can expose missing Haag-Kastler local-net assumptions while blocking conversion of axiomatic bookkeeping into a physical state, force, prediction, likelihood, or quantum completion.",
        null_or_failure_condition="A fixture reverses isotony, accepts noncommuting spacelike observables, omits covariance or spectrum scope, assumes a vacuum without declaration, confuses field and observable algebras, erases EFT or unit limits, or asserts empirical completion.",
        approval_class="safe_now_symbolic_only",
        execution_lane="x2_typed_symbolic_mutation",
        official_or_primary_source_needs=["HAAG-KASTLER-1964", "BFV-2003"],
        concrete_artifacts=["gmut/haag-kastler-contract.json", "gmut/haag-kastler-mutations.json", "scripts/ghc_family_v649_v3_haag_kastler.py"],
        test_falsifier_or_acceptance_gate="Preserve all typed local-net prerequisites and reject seven isotony, locality, covariance, spectrum, vacuum, gauge/EFT/unit, or forbidden-claim mutations.",
        rollback_or_recovery="Restore the omitted formal obligation, retain the rejected statement, and make no state, force, likelihood, prediction, constraint, quantum-completion, empirical-confirmation, or Theory-of-Everything claim.",
        protected_gates=["physical_prediction", "empirical_confirmation", "quantum_completion", "theory_of_everything"],
        expected_disposition="completed",
        novelty_against_prior_frozen_proposals="Prior GMUT boards cover Reeh-Schlieder, Tomita-Takesaki, KMS, Haag-Ruelle, local commutator support, covariant phase space, and many QFT formalisms; none freezes the Haag-Kastler local-net axiom bundle itself with time-slice, additivity, gauge/EFT, unit, and observation firewalls.",
    ),
    proposal(
        3,
        title="GMUT ATNF Pulsar Catalogue release, parameter-reference, uncertainty, selection, binary-state, epoch, checksum, covariance, and zero-row likelihood-refusal adapter",
        pillar="GMUT Mind",
        mission_surface="ATNF PSRCAT release identity, archived-version pin, pulsar identifier, parameter value and uncertainty, reference provenance, binary state, coordinate and epoch conventions, selection, checksum, covariance obligation, row count, and likelihood lock",
        hypothesis="A zero-row adapter can freeze current official ATNF catalogue obligations while refusing to convert availability into a GMUT likelihood, posterior, constraint, force, or confirmation.",
        null_or_failure_condition="Any catalogue query, download, real pulsar row, parameter value, timing record, covariance row, likelihood call, posterior sample, constraint, force, or empirical GMUT claim occurs without a separately authorized evidence phase.",
        approval_class="external_evidence_and_independent_review_required",
        execution_lane="x2_zero_row_contract_only",
        official_or_primary_source_needs=["ATNF-PSRCAT", "ATNF-CATALOGUE-2005"],
        concrete_artifacts=["empirical/atnf-psrcat-contract.json", "empirical/atnf-psrcat-zero-row-receipt.json", "scripts/ghc_family_v649_v3_atnf_refusal.py"],
        test_falsifier_or_acceptance_gate="Receipt preserves zero queries, downloads, catalogue rows, timing rows, covariance rows, likelihood calls, posterior samples, constraints, forces, and empirical claims.",
        rollback_or_recovery="Stop before network or fit activity and require separate authorization with a frozen release, checksums, selection, reference lineage, uncertainty and covariance model, nuisance treatment, and independent review.",
        protected_gates=["network_download", "real_data", "likelihood", "parameter_constraint", "force_detection", "independent_review"],
        expected_disposition="open_gap",
        novelty_against_prior_frozen_proposals="The chain covers binary-pulsar studies, NANOGrav, CHIME, and many official astronomy products, but no release-pinned ATNF PSRCAT parameter-reference, uncertainty, binary-state, epoch, selection, checksum, covariance, and zero-row likelihood-refusal adapter.",
    ),
    proposal(
        4,
        title="THOS community food-bank lot-intake, allergen-hold, recall, correction-readback, accessible-notice, workload, and shift-handover proxy",
        pillar="THOS Body",
        mission_surface="synthetic donor and lot aliases, product and allergen flags, intake state, date and location lineage, precautionary hold, recall scope, correction, accessible notice, workload ceiling, readback, and next-shift acceptance",
        hypothesis="Synthetic traces can represent fail-closed food-bank lot and recall handover obligations without claiming food-safety competence, service effectiveness, recipient safety, professional authority, or real operational outcomes.",
        null_or_failure_condition="A trace loses lot lineage, silently clears an allergen or recall hold, distributes after an unresolved hold, omits correction readback or next owner, exceeds the workload ceiling, exposes recipient information, or claims a real safety outcome.",
        approval_class="synthetic_proxy_only_real_arms_and_food_safety_authority_required",
        execution_lane="x2_synthetic_protocol",
        official_or_primary_source_needs=["MPI-FOOD-RECALL", "MPI-SIMULATED-RECALL"],
        concrete_artifacts=["thos/food-bank-handover-contract.json", "thos/food-bank-handover-mutations.json", "scripts/ghc_family_v649_v3_food_bank_handover.py"],
        test_falsifier_or_acceptance_gate="Synthetic vectors preserve lot lineage, holds, recall scope, corrections, accessible notice, workload, readback, and next owner with zero real people, food, distributions, decisions, or outcomes.",
        rollback_or_recovery="Quarantine the synthetic case, restore its last accepted state, retain every unresolved hold, and defer all real food-safety or service action to qualified and authorized people and institutions.",
        protected_gates=["food_safety_competence", "recipient_safety", "participant_evidence", "real_operational_effectiveness", "blind_matched_budget_arms"],
        expected_disposition="represented",
        novelty_against_prior_frozen_proposals="Earlier THOS proxies cover medicine, transfusion, postal, aviation, rail, water, archives, libraries, and other handovers; none covers community food-bank lot intake, allergen hold, recall, accessible distribution notice, correction readback, workload, and shift acceptance.",
    ),
    proposal(
        5,
        title="Freed ID DID Resolution v0.3 input, option, result-metadata, version, query-normalization, duplicate-parameter, dereferencing, cache, error, draft-watch, and privacy profile",
        pillar="Freed ID/CBR Heart",
        mission_surface="DID and DID URL syntax, resolution and dereferencing options, result metadata, content type, versionId and versionTime, query normalization, duplicate parameters, relative references, cache boundaries, errors, feature-at-risk status, and requester privacy",
        hypothesis="Synthetic vectors can enforce bounded DID Resolution draft obligations and draft-watch refusal without asserting live resolution, real keys, proofs, interoperability, privacy review, security review, recovery, or trust governance.",
        null_or_failure_condition="A vector accepts an invalid DID, ambiguous duplicate parameter, unsafe relative reference, cache-key collision, missing metadata or error, silent draft-feature promotion, requester profiling, or a production-completion claim.",
        approval_class="synthetic_nonproduction_draft_watch_real_resolution_and_governance_required",
        execution_lane="x2_synthetic_protocol",
        official_or_primary_source_needs=["W3C-DID-RESOLUTION-0.3", "W3C-DID-CORE-1.0"],
        concrete_artifacts=["freed-id/did-resolution-contract.json", "freed-id/did-resolution-mutations.json", "scripts/ghc_family_v649_v3_did_resolution.py"],
        test_falsifier_or_acceptance_gate="Accept one bounded synthetic result and reject seven input, option, metadata, version, normalization, duplicate-parameter, dereferencing, cache, error, privacy, draft-promotion, or production mutations.",
        rollback_or_recovery="Reject the vector, restore bounded synthetic state, keep the Working Draft and feature-at-risk labels visible, and require live methods, keys, proofs, interoperability, independent reviews, recovery, and trust governance for production.",
        protected_gates=["real_keys", "live_resolution", "status_or_revocation", "interoperability", "privacy_review", "independent_security_review", "trust_governance"],
        expected_disposition="represented",
        novelty_against_prior_frozen_proposals="The chain covers DID conformance and many OAuth, VC, wallet, status, and trust-chain profiles, but no DID Resolution v0.3 input/result metadata, query normalization, duplicate parameters, dereferencing, cache, error, feature-at-risk, and requester-privacy profile.",
    ),
    proposal(
        6,
        title="CBR community food access, dignity, disability, dietary and cultural need, recipient privacy, correction, recall remedy, affected-party, legal, data-governance, and Māori-authority matrix",
        pillar="Freed ID/CBR Heart",
        mission_surface="synthetic food-access questions, dignity and eligibility, disability access, dietary and cultural need, recipient confidentiality, correction, recall communication and remedy, data governance, affected people, tangata whenua, iwi, hapū, and Māori authority",
        hypothesis="A fail-closed matrix can expose where repository software must stop without deciding real eligibility, allocation, disclosure, remedy, law, culture, data governance, affected-party legitimacy, or Māori authority.",
        null_or_failure_condition="Software grants or denies food access, ranks need, discloses recipient information, prescribes a cultural response, allocates remedy, interprets law, or claims affected-party or Māori legitimacy.",
        approval_class="competent_affected_party_and_maori_authority_required",
        execution_lane="x2_exact_gate_matrix_only",
        official_or_primary_source_needs=["MPI-FOOD-RECALL", "NZ-PRIVACY-PRINCIPLES", "TE-MANA-RARAUNGA"],
        concrete_artifacts=["cbr/food-access-authority-matrix.json", "cbr/food-access-authority-reservation.json"],
        test_falsifier_or_acceptance_gate="Every authority-dependent cell remains unknown or reserved; software makes zero real access, allocation, disclosure, correction, remedy, legal, cultural, governance, or authority decisions.",
        rollback_or_recovery="Reopen any silently closed cell, quarantine disclosures or allocations, preserve contestability, and defer to competent authorities, affected people, tangata whenua, iwi, hapū, and Māori authorities.",
        protected_gates=["food_access_authority", "recipient_privacy", "remedy_allocation", "legal_interpretation", "cultural_legitimacy", "maori_authority"],
        expected_disposition="exact_gate",
        novelty_against_prior_frozen_proposals="Prior CBR matrices cover utilities, medicine, transfusion, transport, libraries, archives, and other services, but not community food access, dignity, disability, dietary and cultural need, recipient privacy, correction, recall remedy, and Māori data and cultural authority.",
    ),
    proposal(
        7,
        title="FITS primary-HDU card, END, block-padding, BITPIX, NAXIS, data-size, extension, checksum, truncation, resource-budget, and refusal tribunal",
        pillar="cross_pillar_format_safety",
        mission_surface="FITS 80-character header cards, SIMPLE, BITPIX, NAXIS and dimensions, END card, 2880-byte padding, primary and extension HDUs, calculated data size, checksum field shape, truncation, trailing bytes, and bounded resource refusal",
        hypothesis="A bounded structural tribunal can accept one contract-shaped synthetic FITS primary HDU and reject malformed header, dimension, size, padding, extension, checksum, truncation, and resource-budget states without opening real astronomy data.",
        null_or_failure_condition="A malformed, truncated, conflicting, trailing, or over-budget fixture is accepted, any real FITS product is opened, or structural success is promoted to complete FITS conformance, production parsing, privacy assurance, or exhaustive security.",
        approval_class="safe_now_disposable_synthetic",
        execution_lane="x2_structural_byte_fixtures",
        official_or_primary_source_needs=["FITS-STANDARD-4.0"],
        concrete_artifacts=["formats/fits-contract.json", "formats/fits-mutations.json", "scripts/ghc_family_v649_v3_fits_tribunal.py"],
        test_falsifier_or_acceptance_gate="Accept one bounded contract-shaped synthetic header and reject seven card, END, padding, type, dimension, size, extension, checksum, truncation, trailing-data, or budget mutation classes.",
        rollback_or_recovery="Refuse the fixture, retain the mutation class, reset disposable state, and make no full-conformance, production parser, supply-chain, privacy-complete, or exhaustive-security claim.",
        protected_gates=["real_astronomy_data", "standard_conformance_complete", "production_parsing", "privacy_complete", "exhaustive_security"],
        expected_disposition="completed",
        novelty_against_prior_frozen_proposals="The format corpus covers WARC, TAR/PAX, ZIP, CPIO, PCAPNG, EBML, PNG, TIFF, MIME, CBOR/COSE, Brotli, and others, but no FITS primary-HDU card, END, block-padding, BITPIX, NAXIS, data-size, extension, checksum, and resource-budget refusal tribunal.",
    ),
    proposal(
        8,
        title="Accessible risk-matrix row, column, numeric-cell, legend, non-colour encoding, summary, focus-order, data-table, print, and manual-reservation audit",
        pillar="cross_pillar_accessibility",
        mission_surface="risk-matrix title and summary, row and column headers, numeric or textual cell values, legend, non-colour encoding, reading and focus order, equivalent data table, responsive overflow, print fallback, and manual evaluation reservation",
        hypothesis="A structural audit can detect a visually encoded matrix with missing relationships or alternatives while reserving manual keyboard, touch, browser, assistive-technology, cognitive, Māori-language, security-usability, and affected-user evaluation.",
        null_or_failure_condition="A fixture passes with missing headers, colour-only meaning, unlabeled cells, an absent legend or summary, illogical focus order, no equivalent table or print fallback, or a missing manual-evaluation reservation.",
        approval_class="safe_now_structural_manual_evaluation_reserved",
        execution_lane="x2_structural_fixture_audit",
        official_or_primary_source_needs=["WCAG-2.2", "WCAG-COLOR", "WCAG-FOCUS-ORDER"],
        concrete_artifacts=["accessibility/risk-matrix-contract.json", "accessibility/risk-matrix-mutations.json", "scripts/ghc_family_v649_v3_risk_matrix.py"],
        test_falsifier_or_acceptance_gate="Reject seven header, cell, legend, colour, summary, focus, table, print, responsive, or reservation mutation classes.",
        rollback_or_recovery="Restore the missing structural alternative, retain the rejected fixture, and do not claim complete accessibility conformance from structural checks.",
        protected_gates=["manual_browser_evaluation", "assistive_technology_evaluation", "cognitive_evaluation", "maori_language_evaluation", "affected_user_evaluation", "accessibility_complete"],
        expected_disposition="completed",
        novelty_against_prior_frozen_proposals="The accessibility chain covers maps, timelines, charts, carousels, treegrids, forms, meters, switches, and many widgets, but no risk matrix with explicit row/column/numeric relationships, legend, non-colour encoding, equivalent data table, and print reservation.",
    ),
    proposal(
        9,
        title="Thermo-Psyche Stefan-Boltzmann radiant-exitance, area, emissivity, absolute-temperature, spectral-total, view-factor, unit, domain, and agency-nonconversion classifier",
        pillar="THOS Body",
        mission_surface="blackbody radiant exitance, surface area, total power, emissivity scope, absolute temperature, spectral versus total quantities, enclosure and view-factor scope, SI units, and category firewall",
        hypothesis="Typed formal fixtures can preserve the Stefan-Boltzmann law and radiative-domain conditions while rejecting conversion into psyche, worth, agency, justice, capability, consciousness, personhood, or a fundamental law of mind.",
        null_or_failure_condition="A fixture drops absolute temperature, fourth-power dependence, area or quantity distinction, emissivity scope, spectral-total distinction, geometry or view-factor boundary, SI unit, radiative domain, or category barrier, or asserts a human interpretation.",
        approval_class="safe_now_typed_formal_only",
        execution_lane="x2_typed_formal_mutation",
        official_or_primary_source_needs=["NIST-RADIATION-NOTE", "BIPM-SI-2026"],
        concrete_artifacts=["thermo-psyche/stefan-boltzmann-contract.json", "thermo-psyche/stefan-boltzmann-mutations.json", "scripts/ghc_family_v649_v3_stefan_boltzmann.py"],
        test_falsifier_or_acceptance_gate="Preserve the fourth-power relation, quantity distinctions, conditions, geometry scope, units, physical domain, and category barrier and reject seven mutation classes.",
        rollback_or_recovery="Restore the missing radiative restriction, retain the rejected statement, and make no participant, psyche, worth, agency, justice, consciousness, personhood, or universal-law claim.",
        protected_gates=["participant_evidence", "psyche_or_agency_claim", "morality_or_justice_claim", "consciousness", "personhood", "fundamental_law"],
        expected_disposition="completed",
        novelty_against_prior_frozen_proposals="The thermodynamic chain includes Planck radiance, Clausius, Gibbs, Maxwell, Nernst, transport laws, fluctuation relations, and many classifiers, but no Stefan-Boltzmann radiant-exitance, area, emissivity, spectral-total, view-factor, unit, and agency-nonconversion classifier.",
    ),
    proposal(
        10,
        title="Stage 20 equivalence-test smallest-effect, dual-one-sided-test, margin-provenance, multiplicity, missingness, switching, sensitivity, and nonpromotion board",
        pillar="cross_pillar_stage20",
        mission_surface="smallest effect size of interest, lower and upper equivalence bounds, two one-sided hypotheses, alpha allocation, confidence interval correspondence, margin provenance, multiplicity, missingness, outcome switching, sensitivity, negative retention, and nonpromotion",
        hypothesis="A fail-closed structural board can expose invalid equivalence claims without participant data, fitted statistics, effect estimates, or promotion into Stage 20 readiness.",
        null_or_failure_condition="A fixture selects a margin after outcomes, uses one-sided evidence incompletely, confuses nonsignificance with equivalence, omits multiplicity, missingness, switching, sensitivity, or negative retention, or emits a participant, deployment, proof, or Stage 20 claim.",
        approval_class="safe_now_structural_nonpromotion_only",
        execution_lane="x2_structural_mutation",
        official_or_primary_source_needs=["SCHUIRMANN-1987", "FDA-EQUIVALENCE-GUIDANCE"],
        concrete_artifacts=["stage20/equivalence-contract.json", "stage20/equivalence-mutations.json", "scripts/ghc_family_v649_v3_equivalence_board.py"],
        test_falsifier_or_acceptance_gate="Reject seven margin, hypothesis, alpha, interval, multiplicity, missingness, switching, sensitivity, retention, or promotion mutations and accept only a zero-participant nonpromotion fixture.",
        rollback_or_recovery="Remove the invalid claim, retain the failed fixture, preserve zero participant rows and zero fitted statistics, and keep Stage 20 closed.",
        protected_gates=["participant_effect", "equivalence_conclusion", "deployment", "proof_or_canon", "stage20"],
        expected_disposition="completed",
        novelty_against_prior_frozen_proposals="The Stage 20 chain covers synthetic controls, negative controls, registered reports, multiplicity, optional stopping, noninferiority references, and many causal designs, but no dual-one-sided equivalence board tying smallest-effect margin provenance to confidence intervals, switching, missingness, sensitivity, and nonpromotion.",
    ),
]


SOURCES = [
    {"source_id": "RO-CRATE-1.3", "title": "RO-Crate Metadata Specification 1.3", "authority": "researchobject.org community", "url": "https://www.researchobject.org/ro-crate/specification/1.3/index.html", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Root, data, contextual, external-reference, and provenance structure only; no provenance-completeness claim."},
    {"source_id": "HAAG-KASTLER-1964", "title": "An Algebraic Approach to Quantum Field Theory", "authority": "Haag and Kastler, primary literature", "url": "https://doi.org/10.1063/1.1704187", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Local-observable algebra obligations only; no physical or empirical GMUT result."},
    {"source_id": "BFV-2003", "title": "The generally covariant locality principle", "authority": "Brunetti, Fredenhagen, and Verch, primary literature", "url": "https://doi.org/10.1007/s00220-002-0729-0", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Local covariance and time-slice context only; no quantum-completion claim."},
    {"source_id": "ATNF-PSRCAT", "title": "ATNF Pulsar Catalogue v2.7.0 documentation and release history", "authority": "CSIRO Australia Telescope National Facility", "url": "https://www.atnf.csiro.au/research/pulsar/psrcat/psrcat_help.html", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Product, parameter, uncertainty, and reference obligations only; zero query, download, ingestion, or fit."},
    {"source_id": "ATNF-CATALOGUE-2005", "title": "The Australia Telescope National Facility Pulsar Catalogue", "authority": "Manchester et al., primary catalogue paper", "url": "https://doi.org/10.1086/428488", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Catalogue design and reference lineage only; no observational row is used."},
    {"source_id": "MPI-FOOD-RECALL", "title": "Food recall guidance for businesses", "authority": "New Zealand Food Safety, Ministry for Primary Industries", "url": "https://www.mpi.govt.nz/food-business/food-recalls/food-recall-guidance-for-businesses", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Synthetic hold, recall, communication, and audit vocabulary only; no food-safety or legal interpretation."},
    {"source_id": "MPI-SIMULATED-RECALL", "title": "Simulated recall guidance for food businesses", "authority": "New Zealand Food Safety, Ministry for Primary Industries", "url": "https://www.mpi.govt.nz/dmsdocument/50630/direct", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Mock-recall and traceability context only; no real food operation or competence claim."},
    {"source_id": "W3C-DID-RESOLUTION-0.3", "title": "Decentralized Identifier Resolution v0.3", "authority": "W3C Decentralized Identifier Working Group", "url": "https://www.w3.org/TR/did-resolution/", "status": "draft", "retrieved_utc": "2026-07-19", "use_boundary": "Working-Draft input, result, error, security, and privacy obligations only; dereferencing feature-at-risk remains visible."},
    {"source_id": "W3C-DID-CORE-1.0", "title": "Decentralized Identifiers v1.0", "authority": "W3C", "url": "https://www.w3.org/TR/did-core/", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "DID syntax and data-model context only; no live DID, key, proof, or trust claim."},
    {"source_id": "NZ-PRIVACY-PRINCIPLES", "title": "New Zealand information privacy principles", "authority": "Office of the Privacy Commissioner", "url": "https://www.privacy.org.nz/privacy-act-2020/privacy-principles/", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Privacy issue spotting only; no legal interpretation."},
    {"source_id": "TE-MANA-RARAUNGA", "title": "Te Mana Raraunga Māori Data Sovereignty Network", "authority": "Te Mana Raraunga", "url": "https://www.temanararaunga.maori.nz/", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Authority reservation only; Māori concepts remain under tangata whenua, iwi, hapū, and Māori authority."},
    {"source_id": "FITS-STANDARD-4.0", "title": "Definition of the Flexible Image Transport System, Version 4.0", "authority": "IAU FITS Working Group and NASA GSFC", "url": "https://fits.gsfc.nasa.gov/fits_standard.html", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Bounded primary-HDU structural requirements only; no complete conformance or production parser claim."},
    {"source_id": "WCAG-2.2", "title": "Web Content Accessibility Guidelines 2.2", "authority": "W3C", "url": "https://www.w3.org/TR/WCAG22/", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Structural accessibility requirements only; manual and affected-user evaluation remain reserved."},
    {"source_id": "WCAG-COLOR", "title": "Understanding Success Criterion 1.4.1: Use of Color", "authority": "W3C Web Accessibility Initiative", "url": "https://www.w3.org/WAI/WCAG22/Understanding/use-of-color", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Non-colour structural cues only; not a complete conformance evaluation."},
    {"source_id": "WCAG-FOCUS-ORDER", "title": "Understanding Success Criterion 2.4.3: Focus Order", "authority": "W3C Web Accessibility Initiative", "url": "https://www.w3.org/WAI/WCAG22/Understanding/focus-order.html", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "Logical structural focus order only; manual keyboard and assistive-technology evaluation remain reserved."},
    {"source_id": "NIST-RADIATION-NOTE", "title": "Self-study manual on optical radiation measurements, Part I, Chapter 12", "authority": "National Institute of Standards and Technology", "url": "https://nvlpubs.nist.gov/nistpubs/Legacy/TN/nbstechnicalnote910-8.pdf", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Radiant exitance, absolute temperature, area, and unit context only; no psyche conversion."},
    {"source_id": "BIPM-SI-2026", "title": "The International System of Units, 9th edition, updated 2026", "authority": "Bureau International des Poids et Mesures", "url": "https://www.bipm.org/en/publications/si-brochure/", "status": "current", "retrieved_utc": "2026-07-19", "use_boundary": "SI unit definitions only; no empirical or human-domain claim."},
    {"source_id": "SCHUIRMANN-1987", "title": "A comparison of the Two One-Sided Tests Procedure and the Power Approach for assessing equivalence", "authority": "Schuirmann, primary methods paper", "url": "https://doi.org/10.1007/BF01068419", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Dual-one-sided-test and interval-hypothesis structure only; zero participant estimation."},
    {"source_id": "FDA-EQUIVALENCE-GUIDANCE", "title": "Statistical Approaches to Establishing Bioequivalence", "authority": "United States Food and Drug Administration", "url": "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/statistical-approaches-establishing-bioequivalence", "status": "stable", "retrieved_utc": "2026-07-19", "use_boundary": "Margin and analysis-plan context only; no clinical, regulatory, or participant conclusion."},
]


SAFE_TASK_TITLES = [
    "Freeze RO-Crate metadata descriptor and root-data roles", "Freeze RO-Crate entity reachability and checksum rules", "Freeze source-independence and duplicate-credit refusals",
    "Freeze Haag-Kastler isotony and locality obligations", "Freeze covariance spectrum vacuum and time-slice scope", "Freeze gauge EFT unit and observation firewalls",
    "Freeze ATNF release parameter and reference identity", "Freeze ATNF uncertainty selection checksum and covariance duties", "Freeze ATNF zero-query zero-row likelihood counters",
    "Freeze food-bank lot and allergen lineage", "Freeze recall hold correction and accessible-notice transitions", "Freeze workload readback and handover ownership",
    "Freeze DID resolution input option and result metadata", "Freeze DID URL normalization duplicate and cache refusals", "Freeze draft and feature-at-risk watch without promotion",
    "Freeze food-access authority reservation cells", "Freeze privacy correction remedy and dignity nondecision matrix", "Freeze Māori-authority and affected-party reservations",
    "Freeze FITS cards END and padding schema", "Freeze FITS type dimension data-size and budget refusals", "Freeze risk-matrix headers cells and legend schema",
    "Freeze risk-matrix non-colour focus table and manual reservations", "Freeze Stefan-Boltzmann typed quantities and domain", "Freeze Stefan-Boltzmann category-barrier mutations",
    "Freeze equivalence margins dual hypotheses and alpha rules", "Freeze equivalence multiplicity missingness switching and nonpromotion", "Build four-status official-source ledger",
    "Build 660-proposal exact collision audit", "Build five-class privacy and exact Git-blob manifest plan", "Build sanitized Orin terminal-route hold plan",
]

CANDIDATE_TITLES = [
    "RO-Crate root and entity-role validator", "RO-Crate orphan and duplicate-credit quarantine", "Haag-Kastler local-net obligation linter", "GMUT observation-firewall mutation board",
    "ATNF release and reference contract", "ATNF zero-row receipt emitter", "Food-bank lot and hold state machine", "Food-bank recall correction and handover board",
    "DID Resolution input and result checker", "DID URL normalization cache and privacy matrix", "Food-access authority stop matrix", "Māori and affected-party reservation checker",
    "FITS bounded primary-HDU inspector", "FITS size padding and budget checker", "Accessible risk-matrix semantics linter", "Accessible table and reservation checker",
    "Stefan-Boltzmann unit and domain checker", "Thermodynamic category firewall", "Equivalence-margin nonpromotion board", "Single-pass commit-manifest verifier",
]

SKILL_SPECS = [
    ("ghc-family-ro-crate-credit-guard", "Audit RO-Crate source independence and duplicate credit."),
    ("ghc-family-ro-crate-orphan-quarantine", "Quarantine unreachable or role-confused crate entities."),
    ("ghc-family-haag-kastler-obligations", "Type local-net axioms without physical promotion."),
    ("ghc-family-gmut-observation-firewall", "Block symbolic GMUT obligations from empirical promotion."),
    ("ghc-family-atnf-zero-row", "Preserve a zero-row ATNF catalogue evidence boundary."),
    ("ghc-family-atnf-release-watch", "Keep ATNF release and reference lineage explicit."),
    ("ghc-family-food-bank-lot-lineage", "Check synthetic food-bank lot and hold lineage."),
    ("ghc-family-food-bank-recall-handover", "Check synthetic recall correction and handover."),
    ("ghc-family-did-resolution-profile", "Audit synthetic DID resolution inputs and results."),
    ("ghc-family-did-dereference-privacy", "Audit DID URL cache and requester privacy boundaries."),
    ("ghc-family-food-access-authority", "Reserve access allocation privacy and remedy decisions."),
    ("ghc-family-maori-authority-reservation", "Keep Māori data and cultural authority exact-gated."),
    ("ghc-family-fits-refusal", "Reject malformed bounded FITS fixtures."),
    ("ghc-family-fits-resource-budget", "Enforce FITS dimension padding and resource budgets."),
    ("ghc-family-risk-matrix-audit", "Audit risk-matrix structural alternatives."),
    ("ghc-family-accessibility-reservation", "Reserve manual and affected-user accessibility review."),
    ("ghc-family-stefan-boltzmann-domain", "Guard Stefan-Boltzmann quantities and units."),
    ("ghc-family-thermo-psyche-nonconversion", "Reject thermodynamic-to-psyche category conversion."),
    ("ghc-family-equivalence-margin-board", "Audit equivalence margins without participant inference."),
    ("ghc-family-single-pass-terminal-gate", "Enforce one successful canonical pass before routing."),
]

RUNNER_TITLES = [
    "v649_v3_ro_crate", "v649_v3_haag_kastler", "v649_v3_atnf_refusal", "v649_v3_food_bank_handover", "v649_v3_did_resolution",
    "v649_v3_food_access_authority", "v649_v3_fits_tribunal", "v649_v3_risk_matrix", "v649_v3_stefan_boltzmann", "v649_v3_equivalence_board",
]

CLEAN_TASK_TITLES = [
    "CLEAN normalize x1 JSON ordering", "FIX reject x2 fields in x1", "REFINE required proposal fields",
    "CLEAN deduplicate source identifiers", "FIX restrict source status vocabulary", "REFINE draft and watch explanations",
    "CLEAN normalize portfolio identifiers", "FIX reject inherited completion credit", "REFINE exact and blocked packet visibility",
    "CLEAN normalize mutation identifiers", "FIX preserve zero-query and zero-row counters", "REFINE GMUT observation-firewall wording",
    "CLEAN normalize food-bank synthetic states", "FIX require unresolved hold and recall ownership", "REFINE competence and service-effectiveness reservations",
    "CLEAN normalize DID Resolution vectors", "FIX reject ambiguous query and draft-feature promotion", "REFINE cache privacy and nonproduction wording",
    "CLEAN normalize authority matrix cells", "FIX prevent access allocation disclosure or remedy action", "REFINE Māori-authority reservation wording",
    "CLEAN normalize FITS byte fixtures", "FIX enforce card block and data-size budgets", "REFINE complete-conformance refusal wording",
    "CLEAN normalize risk-matrix alternatives", "FIX preserve manual and affected-user evaluation reservations", "REFINE Stefan-Boltzmann unit typing",
    "CLEAN normalize equivalence obligations", "FIX preserve Stage 20 nonpromotion", "REFINE terminal-route sanitation and hold checks",
]
