#!/usr/bin/env python3
"""Frozen definitions for Tamar Vey's v648-v7 x1 packet."""

from __future__ import annotations

SOURCE_COMMIT = "38e3fe7bc710239337f831617ced97bec51d7d7a"
SOURCE_PHASE = "v648-gmut-thos-v6-x1-x2"
SOURCE_BRANCH = "codex/GHC-Family/orin-thale-v642-v6-full-tools"
SOURCE_X1_COMMIT = "3f6a64d239bdde1c38fea166db5eff0f2f3e1d89"
SOURCE_EVIDENCE_COMMIT = "c13afb2e2753e820d4fc55735d51fa172f332483"
PHASE = "v648-gmut-thos-v7-x1-x2"
PHASE_SLUG = "v648-v7"
OWNER = "Tamar Vey"
PRONOUNS = "they/them"
ROLE = "relational evidence-systems cartographer and boundary keeper"
HOPE = "keep decisions legible, failures recoverable, and authority boundaries intact"
BRANCH = "codex/GHC-Family/tamar-vey-full-tools"
PRIMARY_FOCUS = "Freed ID / CBR Heart"
BOUNDED_PRACTICE = (
    "postal-depot registered-item intake, mis-sort quarantine, damaged-item hold, "
    "address privacy, accessible notice, workload, and shift handover as a learning "
    "and synthetic-design lens only"
)
OUTCOME_CLASSES = ["completed", "represented", "open_gap", "exact_gate"]
SOURCE_STATUS_CLASSES = ["current", "stable", "draft", "watch"]
INHERITED_NEGATIVES = 4482
INHERITED_OPEN_GAPS = 32
INHERITED_EXACT_GATES = 33
PREREGISTERED_SYNTHETIC_NEGATIVES = 70

PROPOSALS = [
    {
        "proposal_id": "V6487-P01",
        "title": "Method Flow Retry-After parsing, exponential-backoff cap, deterministic-jitter seed, idempotency precondition, circuit-breaker state, dead-letter quarantine, and evidence-credit tribunal",
        "pillar": "THOS Body",
        "hypothesis": "A bounded retry tribunal can parse declared Retry-After forms, cap backoff, make synthetic jitter reproducible, require an idempotency precondition, expose circuit state, quarantine terminal failures, and prevent repeated attempts from receiving duplicate evidence credit.",
        "null_or_failure_condition": "The tribunal accepts an invalid or negative delay, unbounded backoff, hidden nondeterminism, a retry without an idempotency precondition, an illegal circuit transition, a dropped dead-letter record, or duplicate evidence credit.",
        "approval_class": "safe_now_owner_scoped_workflow_fixture",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-RFC9110", "SRC-RFC9773"],
        "artifacts": ["method-flow/retry-policy-contract.json", "method-flow/retry-policy-mutations.json"],
        "falsifier_or_acceptance_gate": "Every invalid delay, cap, idempotency, transition, quarantine, and duplicate-credit mutation is rejected while no external request is sent.",
        "rollback_or_recovery": "Disable automatic retry, preserve the failed attempt and payload digest, and require explicit owner review.",
        "protected_gates": ["external_side_effects", "idempotency", "evidence_credit", "production_orchestration"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6487-P02",
        "title": "GMUT Reeh-Schlieder cyclic-vector, separating-vector, local-algebra, spectrum, analyticity, domain, locality, no-signalling, gauge, EFT, unit, and observation-firewall obligation board",
        "pillar": "GMUT Mind",
        "hypothesis": "A typed Reeh-Schlieder obligation board can distinguish cyclicity, separating properties, local algebra, spectrum and analyticity assumptions, domain and locality, and no-signalling limits from empirical GMUT evidence.",
        "null_or_failure_condition": "The board omits a cyclic or separating domain, local-algebra scope, spectrum or analyticity premise, locality, gauge and EFT scope, units, or converts formal state-density language into signalling, preparation power, physical prediction, or observed physics.",
        "approval_class": "safe_now_symbolic_research_only",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-REEH-SCHLIEDER-PRIMARY"],
        "artifacts": ["gmut/reeh-schlieder-obligations.json", "gmut/reeh-schlieder-mutations.json"],
        "falsifier_or_acceptance_gate": "Every accepted row names its algebra, region, state/vector, spectrum, analyticity, domain, locality, gauge, EFT, unit, and non-observation obligations; operational signalling and empirical promotion stay false.",
        "rollback_or_recovery": "Withdraw the formal board, retain the missing premise as a negative, and make no state-preparation, force, likelihood, stability, or completeness claim.",
        "protected_gates": ["empirical_confirmation", "operational_signalling", "physical_prediction", "theory_of_everything"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6487-P03",
        "title": "GMUT TESS MAST light-curve cadence, quality-bit, crowding, dilution, detrending, sector-selection, covariance, checksum, and zero-row likelihood-refusal adapter",
        "pillar": "GMUT Mind",
        "hypothesis": "An official TESS/MAST product contract can expose cadence, quality, crowding, dilution, detrending, selection, covariance, checksum, and frozen-analysis prerequisites without treating archive availability as a GMUT likelihood.",
        "null_or_failure_condition": "No real rows, frozen target/sector selection, calibrated light curves, quality policy, crowding and dilution treatment, detrending, covariance, preregistered likelihood, uncertainty analysis, or independent review are present.",
        "approval_class": "real_data_and_independent_review_required",
        "execution_lane": "x2_open_gap",
        "source_needs": ["SRC-MAST-TESS"],
        "artifacts": ["empirical/tess-study-contract.json", "empirical/tess-zero-row-receipt.json"],
        "falsifier_or_acceptance_gate": "Remain open_gap while zero real rows and zero likelihood evaluations exist and selection, calibration, systematics, covariance, falsifiers, and independent review remain absent.",
        "rollback_or_recovery": "Retain the zero-row refusal and make no light-curve anomaly, force, parameter, posterior, constraint, or confirmation claim.",
        "protected_gates": ["real_data", "empirical_likelihood", "independent_review", "physical_prediction"],
        "expected_disposition": "open_gap",
    },
    {
        "proposal_id": "V6487-P04",
        "title": "THOS postal-depot registered-item intake, barcode-event, mis-sort quarantine, damaged-item hold, reroute, address-privacy, accessible-notice, workload, and shift-handover proxy",
        "pillar": "THOS Body",
        "hypothesis": "A synthetic postal-depot event ledger can represent registered-item lineage, barcode events, mis-sort quarantine, damage holds, reroute requests, address privacy, accessible notices, workload limits, and handover without real mail or workers.",
        "null_or_failure_condition": "The proxy omits item/event lineage, duplicate scan handling, quarantine, damage state, reroute authorization reservation, address minimization, accessible alternative, workload bound, correction, or next owner.",
        "approval_class": "safe_now_proxy_protocol_no_people_or_operations",
        "execution_lane": "x2_proxy_protocol",
        "source_needs": ["SRC-NZPOST-LOSS", "SRC-NZPOST-PRIVACY", "SRC-WCAG22"],
        "artifacts": ["thos/postal-handover-contract.json", "thos/postal-handover-vectors.json"],
        "falsifier_or_acceptance_gate": "Represented only when synthetic vectors preserve state and privacy boundaries and every real item, worker, route, delivery, incident, customer outcome, and effectiveness claim remains absent.",
        "rollback_or_recovery": "Return to a design-only checklist, retain the failed vector, and issue no real scan, hold, reroute, notice, or handover.",
        "protected_gates": ["real_operations", "professional_authority", "participant_effectiveness", "address_privacy"],
        "expected_disposition": "represented",
    },
    {
        "proposal_id": "V6487-P05",
        "title": "Freed ID SCIM core-schema, mutability, uniqueness, PATCH-path, ETag-version, bulk-failOnErrors, deprovisioning, minimization, and privacy profile",
        "pillar": "Freed ID / CBR Heart",
        "hypothesis": "Synthetic SCIM vectors can test schema declaration, mutability and uniqueness, PATCH paths, version preconditions, bounded bulk failure, deprovisioning state, minimization, and privacy refusals without live identity operations.",
        "null_or_failure_condition": "The profile accepts an undeclared schema, writes readOnly data, violates uniqueness, accepts an ambiguous PATCH path, ignores a stale version, exceeds failOnErrors, equates deletion with safe deprovisioning, overdiscloses attributes, or treats provisioning as authentication or trust.",
        "approval_class": "safe_now_synthetic_nonproduction",
        "execution_lane": "x2_proxy_protocol",
        "source_needs": ["SRC-RFC7643", "SRC-RFC7644"],
        "artifacts": ["freed-id/scim-profile.json", "freed-id/scim-mutations.json"],
        "falsifier_or_acceptance_gate": "Represented only; synthetic resources, zero real directories or accounts, zero live lifecycle events, zero interoperability, zero privacy or independent security review, and zero trust-governance decisions remain explicit.",
        "rollback_or_recovery": "Reject the vector, retain the negative, and leave every production account, identity, deprovisioning, privacy, and trust decision unmade.",
        "protected_gates": ["production_identity", "live_accounts", "interoperability", "privacy_review", "trust_governance"],
        "expected_disposition": "represented",
    },
    {
        "proposal_id": "V6487-P06",
        "title": "CBR postal loss and misdirection, address and household privacy, accessible redress, remedy, place-name stewardship, affected-party, legal, cultural, data-governance, and Māori-authority matrix",
        "pillar": "Freed ID / CBR Heart",
        "hypothesis": "A reservation matrix can expose postal-loss, misdirection, privacy, accessibility, redress, remedy, place-name, collective-data, legal, cultural, and authority dependencies without substituting repository authors for affected people or competent authorities.",
        "null_or_failure_condition": "Any real delivery, disclosure, recovery, compensation, address correction, place-name, legal, cultural, data-governance, remedy, affected-party, or Māori-authority decision is marked completed by software evidence.",
        "approval_class": "authorized_affected_parties_and_competent_authority_required",
        "execution_lane": "x2_exact_gate",
        "source_needs": ["SRC-NZPOST-LOSS", "SRC-NZPOST-PRIVACY", "SRC-NZ-PRIVACY", "SRC-TE-MANA-RARAUNGA", "SRC-WCAG22"],
        "artifacts": ["cbr/postal-remedy-matrix.json", "cbr/postal-authority-reservation.json"],
        "falsifier_or_acceptance_gate": "Remain exact_gate until affected senders, recipients and households, disabled people, workers, tangata whenua, iwi, hapū, Māori authorities, and competent postal, privacy, consumer, legal, cultural, data-governance, and remedy authorities decide within scope.",
        "rollback_or_recovery": "Remove any accidental authority claim, retain the assumption failure, and preserve household, address, worker, complainant, beneficiary, and cultural privacy.",
        "protected_gates": ["affected_party_legitimacy", "maori_authority", "legal_interpretation", "cultural_ratification", "remedy_authority"],
        "expected_disposition": "exact_gate",
    },
    {
        "proposal_id": "V6487-P07",
        "title": "EBML element-ID, variable-integer width, unknown-size, nesting-level, child-boundary, CRC, version, external-data, and resource-budget tribunal",
        "pillar": "THOS Body",
        "hypothesis": "A bounded EBML tribunal can reject invalid element identifiers, variable-integer widths, unknown-size placement, nesting and child-boundary escapes, CRC mismatch, unsupported versions, external retrieval, and resource exhaustion in synthetic fixtures.",
        "null_or_failure_condition": "The tribunal accepts an invalid identifier or VINT, illegal unknown size, excessive nesting, child data outside its parent, CRC mismatch, unsupported read version, external fetch, or unbounded element and byte growth.",
        "approval_class": "safe_now_owner_scoped_parser_fixture",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-RFC8794"],
        "artifacts": ["formats/ebml-contract.json", "formats/ebml-mutations.json"],
        "falsifier_or_acceptance_gate": "All declared malformed fixtures are rejected, structural arithmetic stays bounded, external retrieval is disabled, and no production-decoder or exhaustive-security claim is made.",
        "rollback_or_recovery": "Disable the parser wrapper, retain the failing bytes, and fall back to inert byte metadata without decoding.",
        "protected_gates": ["external_payloads", "exhaustive_security", "production_decoder", "user_files"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6487-P08",
        "title": "Accessible combobox name, input-value, popup relationship, expanded-state, active-option, keyboard, selection, escape, focus, and fallback structural audit",
        "pillar": "THOS Body",
        "hypothesis": "A structural audit can verify combobox naming, value, popup relationship, expanded state, active-option reference, keyboard behavior, selection, escape cancellation, focus continuity, and a native fallback while reserving manual and affected-user evaluation.",
        "null_or_failure_condition": "The combobox lacks a distinct name and value, valid popup relationship, state parity, active option, documented keyboard path, reversible escape, focus continuity, or fallback and honest reservation.",
        "approval_class": "safe_now_structural_only",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-WAI-ARIA12", "SRC-WAI-COMBOBOX", "SRC-WCAG22"],
        "artifacts": ["accessibility/combobox-contract.json", "accessibility/combobox-mutations.json"],
        "falsifier_or_acceptance_gate": "Pass only structural fixtures; reserve browser, keyboard, responsive, assistive-technology, cognitive, Māori-language, security-usability, and affected-user evaluation.",
        "rollback_or_recovery": "Publish a native select or labelled text-input fallback and retain every structural failure.",
        "protected_gates": ["complete_accessibility", "manual_evaluation", "affected_user_acceptance", "language_authority"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6487-P09",
        "title": "Thermo-Psyche Fick diffusion flux, concentration-gradient, diffusivity-tensor, boundary-condition, initial-condition, unit, conservation, and psyche-influence nonconversion classifier",
        "pillar": "Trinity Mandala bridge",
        "hypothesis": "A typed classifier can preserve declared diffusion flux, concentration gradient, diffusivity tensor, boundary and initial conditions, units, and conservation while refusing conversion into psyche influence, social spread, agency, value, or consciousness.",
        "null_or_failure_condition": "Flux sign, tensor positivity or domain, boundary/initial condition, units, or conservation is omitted, or a physical diffusion model is converted into a claim about thought, culture, agency, morality, or personhood.",
        "approval_class": "safe_now_formal_domain_guard",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-FICK-PRIMARY", "SRC-IUPAC-DIFFUSION"],
        "artifacts": ["thermo-psyche/fick-diffusion-contract.json", "thermo-psyche/fick-diffusion-mutations.json"],
        "falsifier_or_acceptance_gate": "Every accepted row states flux, gradient, coefficient or tensor, domain, conditions, units, and conservation; every psyche, agency, culture, value, and consciousness conversion is rejected.",
        "rollback_or_recovery": "Remove the analogy, retain only the physical statement and its domain, and preserve the rejected conversion.",
        "protected_gates": ["psyche_conversion", "consciousness", "personhood", "cultural_claim"],
        "expected_disposition": "completed",
    },
    {
        "proposal_id": "V6487-P10",
        "title": "Stage 20 interrupted-time-series intervention-time, level, slope, autocorrelation, seasonality, concurrent-event, pretrend, uncertainty, and nonpromotion board",
        "pillar": "Trinity Mandala bridge",
        "hypothesis": "An interrupted-time-series board can expose intervention timing, level and slope, autocorrelation, seasonality, concurrent events, pretrend, uncertainty, and interpretation obligations without converting a zero-row fixture into an effect or Stage 20 evidence.",
        "null_or_failure_condition": "The board omits time-zero definition, baseline trend, level or slope estimand, dependence, seasonality, concurrent-event threats, pretrend, uncertainty, multiplicity, value authority, or promotes software structure as an effect.",
        "approval_class": "safe_now_structural_nonpromotion",
        "execution_lane": "x2_build_task",
        "source_needs": ["SRC-COCHRANE-ITS"],
        "artifacts": ["stage20/interrupted-time-series-contract.json", "stage20/interrupted-time-series-mutations.json"],
        "falsifier_or_acceptance_gate": "Pass only structural protocol fixtures; real observations, credible counterfactual assumptions, effect estimates, safety monitoring, value authority, and independent review remain absent.",
        "rollback_or_recovery": "Retain the failed fixture and keep causal-effect, participant-effect, intervention-effect, and Stage 20 claims false.",
        "protected_gates": ["real_participants", "causal_effect", "value_authority", "independent_review", "stage20"],
        "expected_disposition": "completed",
    },
]

SOURCES = [
    {"source_id": "SRC-LIVE-REQUEST", "title": "Hamish current v648-v7 activation and committed Orin baton", "url": None, "status": "current", "kind": "live_authority", "implication": "Controls solo ownership, x1-before-x2, one successful canonical pass, no replay, privacy, authority, and terminal route."},
    {"source_id": "SRC-RFC9110", "title": "RFC 9110 HTTP Semantics", "url": "https://www.rfc-editor.org/info/rfc9110/", "status": "stable", "kind": "official_standard", "implication": "Defines Retry-After syntax and semantics; it does not authorize retrying unsafe or non-idempotent actions."},
    {"source_id": "SRC-RFC9773", "title": "RFC 9773 ACME Renewal Information", "url": "https://www.rfc-editor.org/info/rfc9773/", "status": "stable", "kind": "official_standard", "implication": "Provides a bounded capped-backoff example; it is not a universal retry policy."},
    {"source_id": "SRC-REEH-SCHLIEDER-PRIMARY", "title": "Strohmaier, Verch, and Wollenberg on analytic microlocal spectrum and Reeh-Schlieder", "url": "https://arxiv.org/abs/math-ph/0202003", "status": "stable", "kind": "primary_research", "implication": "Supports formal theorem obligations only, not an empirical GMUT result or operational state-preparation claim."},
    {"source_id": "SRC-MAST-TESS", "title": "MAST TESS Data Products", "url": "https://archive.stsci.edu/missions-and-data/tess/data-products", "status": "current", "kind": "official_data_archive", "implication": "Describes official TESS products and quality context; this phase downloads and analyzes no real observation."},
    {"source_id": "SRC-NZPOST-LOSS", "title": "NZ Post cover for loss or damage", "url": "https://www.nzpost.co.nz/personal/sending-in-nz/cover-loss-damage", "status": "current", "kind": "primary_operator_source", "implication": "Provides operator context for loss and damage processes without delegating any real delivery or remedy authority."},
    {"source_id": "SRC-NZPOST-PRIVACY", "title": "NZ Post Privacy Centre", "url": "https://www.nzpost.co.nz/about-us/privacy-centre", "status": "current", "kind": "primary_operator_source", "implication": "Confirms address and delivery data are personal information; software fixtures make no real disclosure decision."},
    {"source_id": "SRC-RFC7643", "title": "RFC 7643 SCIM Core Schema", "url": "https://www.rfc-editor.org/info/rfc7643/", "status": "stable", "kind": "official_standard", "implication": "Defines SCIM resource and attribute characteristics; synthetic conformance is not live identity assurance."},
    {"source_id": "SRC-RFC7644", "title": "RFC 7644 SCIM Protocol", "url": "https://www.rfc-editor.org/info/rfc7644/", "status": "stable", "kind": "official_standard", "implication": "Defines SCIM HTTP operations, PATCH, versioning and bulk behavior without proving interoperability or safe production deprovisioning."},
    {"source_id": "SRC-RFC8794", "title": "RFC 8794 Extensible Binary Meta Language", "url": "https://www.rfc-editor.org/info/rfc8794/", "status": "stable", "kind": "official_standard", "implication": "Defines EBML structure for bounded fixtures; it is not exhaustive decoder security assurance."},
    {"source_id": "SRC-WAI-ARIA12", "title": "WAI-ARIA 1.2", "url": "https://www.w3.org/TR/wai-aria/", "status": "stable", "kind": "official_standard", "implication": "Defines combobox roles and state relationships while implementation and user evaluation remain separate."},
    {"source_id": "SRC-WAI-ARIA13-DRAFT", "title": "WAI-ARIA 1.3 Working Draft", "url": "https://www.w3.org/TR/wai-aria-1.3/", "status": "draft", "kind": "official_draft", "implication": "Watched as draft only and not flattened into the stable 1.2 contract."},
    {"source_id": "SRC-WAI-COMBOBOX", "title": "WAI-ARIA Authoring Practices Combobox Pattern", "url": "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/", "status": "current", "kind": "official_guidance", "implication": "Supports structural and keyboard design checks; APG examples are not complete accessibility conformance."},
    {"source_id": "SRC-WCAG22", "title": "Web Content Accessibility Guidelines 2.2", "url": "https://www.w3.org/TR/WCAG22/", "status": "stable", "kind": "official_standard", "implication": "Supports declared structural obligations while manual and affected-user evaluation remain reserved."},
    {"source_id": "SRC-FICK-PRIMARY", "title": "Adolf Fick, On Liquid Diffusion", "url": "https://doi.org/10.1080/14786445508641925", "status": "stable", "kind": "primary_research", "implication": "Supports the physical diffusion relationship only, never a psyche, agency, cultural, or value conversion."},
    {"source_id": "SRC-IUPAC-DIFFUSION", "title": "IUPAC Gold Book diffusion definition", "url": "https://goldbook.iupac.org/terms/view/D01716", "status": "stable", "kind": "official_terminology", "implication": "Supplies domain terminology without establishing any new physical or psychological law."},
    {"source_id": "SRC-COCHRANE-ITS", "title": "Cochrane interrupted time-series analysis training", "url": "https://training.cochrane.org/sites/training.cochrane.org/files/public/uploads/Introduction%20to%20analysis%20and%20meta-analysis%20of%20ITS%20studies%20with%20continuous%20outcomes.pdf", "status": "current", "kind": "official_method_guidance", "implication": "Identifies dependence and seasonality obligations; it is not participant evidence or Stage 20 authority."},
    {"source_id": "SRC-NZ-PRIVACY", "title": "New Zealand Privacy Commissioner Privacy Act principles", "url": "https://www.privacy.org.nz/privacy-principles/", "status": "current", "kind": "official_authority", "implication": "Real address, household, correction, disclosure, and remedy decisions require competent human authority and affected-person consideration."},
    {"source_id": "SRC-TE-MANA-RARAUNGA", "title": "Te Mana Raraunga principles of Māori data sovereignty", "url": "https://www.temanararaunga.maori.nz/principles-of-maori-data-sovereignty", "status": "stable", "kind": "primary_authority_source", "implication": "Māori data and concepts remain under Māori governance; software confers no Māori authority."},
    {"source_id": "SRC-OPENAI-CODEX", "title": "OpenAI Codex CLI getting started", "url": "https://help.openai.com/en/articles/11096431", "status": "watch", "kind": "official_product_channel", "implication": "Supports version-channel observation only; this phase performs no CLI or desktop update."},
    {"source_id": "SRC-OPENAI-DESKTOP", "title": "OpenAI Codex app announcement", "url": "https://openai.com/index/introducing-the-codex-app/", "status": "current", "kind": "official_product", "implication": "Confirms the Windows app surface; the installed build is observed locally and not updated."},
]

SAFE_TASKS = [
    "Verify Orin source, x1, evidence, parent-count, zero-merge, clean, and live-remote anchors",
    "Verify all three inherited commit-local Git-blob manifests and final checkout-byte parity",
    "Record D-first capacity and fast-forward-only Tamar lane continuity",
    "Audit all 620 frozen proposal titles and substantive neighbors with collision reasons",
    "Build the four-state official and primary source ledger without status flattening",
    "Freeze exactly ten proposals without x2 implementation or outcome claims",
    "Build immutable x1 Git-blob separation and staged-path receipts",
    "Run five-class privacy scanning with scanner-definition quarantine",
    "Retain every parser, encoding, output, search, and manifest-domain fault",
    "Build and validate Method Flow failed and passing witnesses",
    "Refresh the phase-scoped GHC Family Index without global churn",
    "Run Reflection Remaster as an additive audit with compatibility preserved",
    "Freeze the retry-policy and duplicate-credit tribunal plan",
    "Freeze the Reeh-Schlieder symbolic obligation plan",
    "Freeze the TESS zero-row likelihood-refusal plan",
    "Freeze the postal-depot handover proxy plan",
    "Freeze the SCIM synthetic lifecycle profile plan",
    "Freeze the postal CBR authority-reservation plan",
    "Freeze the EBML bounded parser tribunal plan",
    "Freeze the combobox structural accessibility plan",
    "Freeze the Fick diffusion nonconversion plan",
    "Freeze the interrupted-time-series nonpromotion plan",
    "Freeze 70 proposal-linked synthetic mutations without executing them",
    "Preserve inherited exact-approval and blocked packets as unexecuted",
    "Measure Tamar-generated file growth independently from inherited baseline",
    "Verify local and official Codex surfaces without updating software",
    "Record Sandbox, Hyper-V, elevation, and cross-platform send as untouched",
    "Reserve one successful canonical scoped pass and prohibit replay",
    "Preserve family-current callers and all historical compatibility surfaces",
    "Keep terminal Sylven route prepared but unsent until exact final proof",
]

CANDIDATE_TASKS = [
    "Retry-After and bounded-backoff prototype", "Circuit-state and duplicate-credit prototype",
    "Reeh-Schlieder algebra-domain prototype", "Reeh-Schlieder observation-firewall prototype",
    "TESS product-prerequisite prototype", "TESS zero-row likelihood-refusal prototype",
    "Postal event-lineage and quarantine prototype", "Postal privacy and handover prototype",
    "SCIM schema and mutability prototype", "SCIM PATCH, version, bulk, and deprovisioning prototype",
    "Postal redress and authority-reservation prototype", "Postal place-name and data-governance reservation prototype",
    "EBML VINT and element-boundary prototype", "EBML nesting and resource-budget prototype",
    "Combobox relationship and active-option prototype", "Combobox keyboard, escape, and fallback prototype",
    "Fick diffusion domain prototype", "Fick psyche-influence nonconversion prototype",
    "Interrupted-time-series assumption prototype", "Stage 20 interrupted-time-series nonpromotion prototype",
]

SKILL_IDEAS = [
    "ghc-family-v648-v7-retry-tribunal", "ghc-family-v648-v7-retry-credit-guard",
    "ghc-family-v648-v7-reeh-obligations", "ghc-family-v648-v7-reeh-firewall",
    "ghc-family-v648-v7-tess-refusal", "ghc-family-v648-v7-tess-provenance",
    "ghc-family-v648-v7-postal-lineage", "ghc-family-v648-v7-postal-handover",
    "ghc-family-v648-v7-scim-profile", "ghc-family-v648-v7-scim-minimization",
    "ghc-family-v648-v7-postal-reservation", "ghc-family-v648-v7-address-privacy",
    "ghc-family-v648-v7-ebml-tribunal", "ghc-family-v648-v7-ebml-budget",
    "ghc-family-v648-v7-combobox-structure", "ghc-family-v648-v7-combobox-fallback",
    "ghc-family-v648-v7-fick-domain", "ghc-family-v648-v7-fick-nonconversion",
    "ghc-family-v648-v7-its-board", "ghc-family-v648-v7-terminal-proof",
]

RUNNER_IDEAS = [
    "ghc_family_v648_v7_retry_policy.py", "ghc_family_v648_v7_reeh_obligations.py",
    "ghc_family_v648_v7_tess_refusal.py", "ghc_family_v648_v7_postal_handover.py",
    "ghc_family_v648_v7_scim_profile.py", "ghc_family_v648_v7_ebml_tribunal.py",
    "ghc_family_v648_v7_accessibility_audit.py", "ghc_family_v648_v7_domain_guards.py",
    "ghc_family_v648_v7_portfolio.py", "build_ghc_family_v648_v7_closeout.py",
]

CLEANUP_TASKS = [
    "Normalize v648-v7 JSON ordering and UTF-8 output only",
    "Add explicit four-outcome vocabulary validation",
    "Add explicit four-source-status vocabulary validation",
    "Add exact proposal-count assertion",
    "Add exact frozen-chain count assertion",
    "Add source and lifecycle ancestry assertions",
    "Add zero-merge and final-parent assertions",
    "Add x1 and x2 contamination guards",
    "Add Git-blob versus checkout-byte domain labels",
    "Add five privacy pattern class labels",
    "Add scanner-definition disposition",
    "Add document word-cap checks",
    "Add owner-file threshold measurement",
    "Add source citation not-observation flags",
    "Add same-owner and independent-reproduction separation",
    "Add Sandbox and Hyper-V no-action receipts",
    "Add desktop and CLI no-update receipts",
    "Add no-cross-platform-send receipt",
    "Add no-task and no-subagent receipt",
    "Add terminal route prepared-not-sent state",
    "Add accessibility manual-evaluation reservation",
    "Add Māori-language and authority reservation",
    "Add real-data and likelihood refusal fields",
    "Add participant, worker, and operator absence fields",
    "Add production identity and live-account absence fields",
    "Add exhaustive-security nonclaim fields",
    "Add rollback and recovery fields to every prototype",
    "Add protected-gate parity checks",
    "Add exact staged-path allowlist checks",
    "Add final remote-equality proof fields",
]

X1_OPERATIONAL_NEGATIVES = [
    {"negative_id": "V6487-X1-N01", "category": "memory_registry_no_match", "failed": "An exact current-memory registry search returned zero matches with a nonzero search exit and was initially surfaced as a tool failure.", "recovery": "Normalize the no-match exit and use the live committed baton plus exact Git evidence as current authority.", "passing": "The normalized probe returned zero matches, inferred no continuity, and preserved live baton and Git precedence.", "recurrence_guard": "Distinguish zero matches from execution errors and never infer continuity from silence."},
    {"negative_id": "V6487-X1-N02", "category": "foreach_pipeline_parse_fault", "failed": "A PowerShell foreach statement was piped directly and failed at parse time before reading receipts.", "recovery": "Materialize loop results in an array before piping to JSON conversion.", "passing": "The corrected array-first wrapper read and summarized the requested receipts.", "recurrence_guard": "Never pipe a PowerShell foreach statement directly."},
    {"negative_id": "V6487-X1-N03", "category": "untyped_receipt_summary", "failed": "A broad receipt wrapper indexed entries on non-manifest JSON and returned warnings plus truncated output.", "recovery": "Inspect schema and keys first and emit compact type-specific summaries.", "passing": "Exact metadata reads returned bounded manifest and receipt fields without null indexing.", "recurrence_guard": "Branch on schema before indexing optional arrays."},
    {"negative_id": "V6487-X1-N04", "category": "manifest_domain_mix", "failed": "The first manifest verifier compared checkout-byte declarations with raw Git blob sizes and falsely reported four mismatches.", "recovery": "Verify Git blob identity and checkout bytes in their separately declared domains.", "passing": "All inherited paths and blob identities matched, and the exact final checkout matched all 66 declared byte counts.", "recurrence_guard": "Read hash and byte domain metadata before comparison."},
    {"negative_id": "V6487-X1-N05", "category": "cat_file_checkout_assumption", "failed": "A cat-file filters probe was assumed to reproduce historical checkout bytes and mismatched every entry.", "recovery": "Use immutable objects for historical blob proof and the exact checked-out final worktree for checkout-byte proof without a replay lane.", "passing": "The exact final checkout matched 66 of 66 declared byte counts with no replay or temporary validation lane.", "recurrence_guard": "Do not use cat-file filters as a historical checkout-byte reconstruction contract."},
    {"negative_id": "V6487-X1-N06", "category": "fast_forward_output_truncation", "failed": "The successful fast-forward emitted an overlarge inherited change summary that the tool display truncated.", "recovery": "Use a compact exact postflight without repeating the fast-forward.", "passing": "The compact postflight showed the exact inherited head, zero divergence, four-way equality, and only intended x1 paths after mutation began.", "recurrence_guard": "Separate lifecycle mutation from compact state proof."},
    {"negative_id": "V6487-X1-N07", "category": "console_encoding_fault", "failed": "A proposal-term scan stopped on non-ASCII text under the default console encoder.", "recovery": "Configure child stdout explicitly as UTF-8 before emitting repository titles.", "passing": "The corrected scan emitted all 41 requested term rows over all 620 proposals.", "recurrence_guard": "Set explicit UTF-8 for repository-text output."},
    {"negative_id": "V6487-X1-N08", "category": "semantic_seed_collision", "failed": "The first proposal seed batch collided with frozen food cold-chain, Gibbs phase-rule, and target-trial mechanisms and exposed two close substantive neighbours.", "recovery": "Reject the collided titles, inspect exact neighbours, and replace them with absent mechanisms and practice domains.", "passing": "All ten replacement titles stayed below the 0.50 lexical threshold and passed manual substantive-neighbour review against 620 proposals.", "recurrence_guard": "Treat plausible novelty as a hypothesis until lexical and substantive audits pass."},
    {"negative_id": "V6487-X1-N09", "category": "foreach_pipeline_recurrence", "failed": "The direct foreach-to-pipeline parser fault recurred in a read-only skill-file existence check after the guard was known.", "recovery": "Materialize the existence rows before JSON conversion and retain the recurrence separately.", "passing": "The corrected wrapper found both skill files and reported their bounded line counts.", "recurrence_guard": "Use an array assignment for every PowerShell loop feeding a pipeline."},
    {"negative_id": "V6487-X1-N10", "category": "privacy_boundary_vocabulary_false_positive", "failed": "The first x1 privacy gate classified a protected credential and API-key approval label as a confirmed secret payload hit.", "recovery": "Quarantine the exact approval register as protected-gate vocabulary while preserving the candidate and rerun the same five pattern classes.", "passing": "The corrected scan retained the boundary-vocabulary candidate and reported zero confirmed payload hits.", "recurrence_guard": "Distinguish protected-gate vocabulary from credential assignment or secret material without weakening the pattern set."},
    {"negative_id": "V6487-X1-N11", "category": "premature_privacy_promotion", "failed": "A privacy recovery was promoted before all generated x1 definition surfaces existed; the subsequent complete-surface scan found five propagated boundary-definition candidates.", "recovery": "Demote the method, classify exact retained-definition surfaces, run a complete generated-surface preview, and promote only before a final manifest scan that includes the resulting Method Flow files.", "passing": "The complete preview and final manifest scan retained definition candidates and reported zero confirmed payload hits.", "recurrence_guard": "Never promote a privacy method before the full generated surface exists and a post-promotion final scan can cover the new evidence files."},
    {"negative_id": "V6487-X1-N12", "category": "patch_scope_misplacement", "failed": "A patch-context match placed the staged-review receipt write inside the post-scan promotion function with out-of-scope manifest locals.", "recovery": "Move the receipt write back into the manifest function and inspect the function boundaries plus AST before execution.", "passing": "The corrected source parsed and the staged-review write used only locals defined by the manifest function.", "recurrence_guard": "After context-based patches, inspect enclosing function boundaries rather than relying on syntax alone."},
    {"negative_id": "V6487-X1-N13", "category": "method_state_demotion_refused", "failed": "The Method Flow runner rejected a preferred-to-candidate demotion requested after a later scan narrowed the earlier passing witness.", "recovery": "Preserve the immutable preferred history, add a stricter complete-surface ordering method, and withhold terminal privacy credit until that additive method passes.", "passing": "The earlier state and witness remained intact while the additive M10 method carried the complete-surface gate.", "recurrence_guard": "Treat Method Flow promotion as monotonic; correct later scope with an additive method and witness rather than demotion."},
    {"negative_id": "V6487-X1-N14", "category": "scanner_output_recursion_and_premature_witness", "failed": "The final x1 scan treated two privacy class labels inside its own preview receipt as payload, and the M10 witness had already described that final scan as passed.", "recovery": "Classify the preview as scanner output, run a complete pre-promotion scan, record additive recovery witnesses, then run a second post-promotion scan and rebuild the current manifest with no later Method Flow mutation.", "passing": "The post-promotion scan covered the new witnesses and current ledger with zero confirmed payload hits.", "recurrence_guard": "Quarantine scanner-output receipts explicitly and never describe a later scan as passed before it executes."},
    {"negative_id": "V6487-X1-N15", "category": "method_flow_witness_filename_assumption", "failed": "A read-only probe assumed a Method Flow failed-witness filename omitted the required witness suffix and reported a missing path.", "recovery": "Enumerate the bounded Method Flow directory, resolve the exact schema-produced filename, and read the existing artifact without changing it.", "passing": "The exact suffixed failed-witness artifact was found and read, and the ledger state was summarized separately.", "recurrence_guard": "Discover schema-produced artifact names from the bounded directory or receipt before constructing a path."},
    {"negative_id": "V6487-X1-N16", "category": "method_flow_cli_argument_assumption", "failed": "The first Method Flow record call used an unverified method-file option and the CLI rejected it before changing the ledger.", "recovery": "Use the command-specific help-reported record-file option and preserve the rejected call as a failed witness.", "passing": "The corrected record-file call added the method once and the validator accepted the resulting ledger.", "recurrence_guard": "Read command-specific CLI usage before constructing a Method Flow mutation call."},
    {"negative_id": "V6487-X1-N17", "category": "verbose_staged_status_output_truncation", "failed": "A successful exact staged review was followed by a verbose status and line-ending warning stream that the tool display truncated.", "recovery": "Preserve the successful review receipt, retain the display fault separately, and use compact count and digest summaries for later staged postflight.", "passing": "A compact postflight reported exact staged counts and hashes without repeating the overlarge status stream.", "recurrence_guard": "Keep exact review mutation separate from bounded postflight summaries on large staged packets."},
]
