#!/usr/bin/env python3
"""Caelen Morrow v656-v4 source, proposal, and startup catalogue."""

from __future__ import annotations


def _source(
    source_id: str,
    title: str,
    publisher: str,
    url: str,
    status: str,
    use: str,
) -> dict:
    return {
        "source_id": source_id,
        "title": title,
        "publisher": publisher,
        "url": url,
        "status": status,
        "use": use,
    }


OFFICIAL_SOURCES = [
    _source(
        "ISO-3764-2016",
        "ISO 3764:2016 Timekeeping instruments — Movements — Types, dimensions and nomenclature",
        "International Organization for Standardization",
        "https://www.iso.org/standard/59931.html",
        "current_under_systematic_review_2026",
        "movement-type, dimension, and nomenclature vocabulary only; no standard-text reproduction, inspection, repair, interchangeability, or compliance claim",
    ),
    _source(
        "ISO-3159-2009",
        "ISO 3159:2009 Timekeeping instruments — Wrist-chronometers with spring balance oscillator",
        "International Organization for Standardization",
        "https://www.iso.org/standard/54804.html",
        "current_under_systematic_review_2026",
        "chronometer, rate, position, temperature, duration, and observation vocabulary only; no timing test, certification, accuracy, or chronometer claim",
    ),
    _source(
        "ISO-22810-2010",
        "ISO 22810:2010 Horology — Water-resistant watches",
        "International Organization for Standardization",
        "https://www.iso.org/standard/45334.html",
        "current_under_systematic_review_2026",
        "water-resistance claim-boundary vocabulary only; no pressure test, seal assessment, depth, use-condition, conformity, or safety claim",
    ),
    _source(
        "ISO-764-2020",
        "ISO 764:2020 Horology — Magnetic resistant watches",
        "International Organization for Standardization",
        "https://www.iso.org/standard/70610.html",
        "current_confirmed_2025",
        "magnetic-resistance vocabulary only; no exposure, demagnetization, test, conformity, rate, or safety claim",
    ),
    _source(
        "ISO-1413-2016",
        "ISO 1413:2016 Horology — Shock-resistant wrist watches",
        "International Organization for Standardization",
        "https://www.iso.org/standard/62753.html",
        "current_under_systematic_review_2026",
        "shock-resistance vocabulary only; no impact, test, damage, conformity, fitness, or safety claim",
    ),
    _source(
        "ISO-6425-2018",
        "ISO 6425:2018 Divers' watches",
        "International Organization for Standardization",
        "https://www.iso.org/standard/66517.html",
        "current_confirmed_2024",
        "divers-watch claim-reservation vocabulary only; no test, depth, diving, water-resistance, safety, conformity, or fitness claim",
    ),
    _source(
        "ISO-16359-2025",
        "ISO 16359:2025 Horology — Wrist-watches — Chemical regulatory compliance",
        "International Organization for Standardization",
        "https://www.iso.org/standard/84549.html",
        "current_2025",
        "chemical-regulatory field and evidence-reservation vocabulary only; no material test, declaration, conformity, legal advice, or market-access claim",
    ),
    _source(
        "IEC-60086-3-2016",
        "IEC 60086-3:2016 Primary batteries — Part 3: Watch batteries",
        "International Electrotechnical Commission",
        "https://webstore.iec.ch/en/publication/24941",
        "current_reference",
        "watch-cell designation, polarity, handling-field, and replacement-record vocabulary only; no battery selection, installation, safety, transport, recycling, or conformity claim",
    ),
    _source(
        "NZ-WORKSAFE-ORGANIC-SOLVENTS",
        "Organic solvents",
        "WorkSafe New Zealand",
        "https://www.worksafe.govt.nz/topic-and-industry/hazardous-substances/guidance/substances/organic-solvents/",
        "current_context",
        "hazard, exposure, ventilation, competent-assessment, control, and emergency-reservation context only; no solvent choice, workplace control, exposure assessment, or safety authorization",
    ),
    _source(
        "NZ-CONSUMER-CGA",
        "Consumer Guarantees Act",
        "New Zealand Consumer Protection",
        "https://www.consumerprotection.govt.nz/general-help/consumer-laws/consumer-guarantees-act",
        "current_context",
        "service-description, reasonable-care, remedy, disclosure, and complaint-reservation vocabulary only; no legal advice, liability finding, customer decision, or remedy authority",
    ),
    _source(
        "NZ-CONSUMER-FAULTY-SERVICES",
        "Providing remedies for faulty services",
        "New Zealand Consumer Protection",
        "https://www.consumerprotection.govt.nz/guidance-for-businesses/customer-returns-and-complaints/providing-remedies-for-faulty-services",
        "current_context",
        "remedy-path and service-complaint reservation vocabulary only; no legal determination, admission, settlement, or customer outcome",
    ),
    _source(
        "W3C-PROV-O",
        "PROV-O: The PROV Ontology",
        "W3C",
        "https://www.w3.org/TR/prov-o/",
        "stable_recommendation",
        "entity, activity, derivation, revision, attribution, generation, invalidation, correction, and custody lineage",
    ),
    _source(
        "RFC-3339",
        "RFC 3339: Date and Time on the Internet: Timestamps",
        "RFC Editor",
        "https://www.rfc-editor.org/rfc/rfc3339.html",
        "stable",
        "synthetic UTC lexical timestamps, intervals, observations, revisions, and handovers",
    ),
    _source(
        "RFC-8785",
        "RFC 8785: JSON Canonicalization Scheme",
        "RFC Editor",
        "https://www.rfc-editor.org/rfc/rfc8785.html",
        "stable",
        "deterministic synthetic contract, receipt, statement, and manifest serialization",
    ),
    _source(
        "NIST-SP811",
        "NIST SP 811: Guide for the Use of the International System of Units",
        "National Institute of Standards and Technology",
        "https://www.nist.gov/publications/guide-use-international-system-units-si",
        "stable",
        "quantity, unit, symbol, conversion, time, angle, temperature, pressure, torque, and uncertainty discipline only; no real metrology or calibration",
    ),
    _source(
        "W3C-WCAG-22",
        "Web Content Accessibility Guidelines 2.2",
        "W3C",
        "https://www.w3.org/TR/WCAG22/",
        "current_recommendation",
        "structural accessibility vocabulary with manual, browser, assistive-technology, Māori-language, cognitive, low-vision, and affected-user evaluation reserved",
    ),
    _source(
        "NZ-PRIVACY-PRINCIPLES",
        "Privacy Act 2020 information privacy principles",
        "Office of the Privacy Commissioner New Zealand",
        "https://www.privacy.org.nz/privacy-principles/",
        "current_including_ipp3a_from_2026_05_01",
        "purpose, source, direct and indirect collection notice, fairness, security, access, correction, accuracy, retention, use, disclosure, and identifier reservations only; no legal advice",
    ),
    _source(
        "W3C-VC-DM-20",
        "Verifiable Credentials Data Model v2.0",
        "W3C",
        "https://www.w3.org/TR/vc-data-model-2.0/",
        "current_recommendation",
        "synthetic credential vocabulary only; no conforming credential, real issuer, holder, verifier, proof, trust decision, or interoperability event",
    ),
    _source(
        "RFC-9943",
        "RFC 9943: An Architecture for Trustworthy and Transparent Digital Supply Chains",
        "IETF / RFC Editor",
        "https://www.rfc-editor.org/rfc/rfc9943.html",
        "current_proposed_standard",
        "signed-statement, transparent-statement, receipt, registration-policy, and transparency-service vocabulary only; no live key, signature, service, registration, audit, trust, or non-equivocation claim",
    ),
    _source(
        "C2PA-2.4",
        "C2PA Content Credentials Technical Specification 2.4",
        "Coalition for Content Provenance and Authenticity",
        "https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html",
        "current_2026",
        "manifest, assertion, ingredient, action, binding, validation-result, and trust-model vocabulary only; no signed manifest, certificate, timestamp, revocation, validation, trust, or authenticity claim",
    ),
    _source(
        "SMITHSONIAN-OPEN-ACCESS",
        "Smithsonian Open Access",
        "Smithsonian Institution",
        "https://www.si.edu/openaccess",
        "current_documented_surface",
        "public collection metadata and API-readiness vocabulary only; zero keys, requests, downloads, objects, images, rows, interpretations, or likelihoods",
    ),
    _source(
        "TMR-PRINCIPLES",
        "Principles of Māori Data Sovereignty",
        "Te Mana Raraunga",
        "https://www.temanararaunga.maori.nz/principles-of-maori-data-sovereignty",
        "current",
        "Māori rights, interests, governance, jurisdiction, language, collective benefit, and authority reservation only; never a substitute for Māori authority",
    ),
    _source(
        "LOCAL-CONTEXTS-TK-BC",
        "Traditional Knowledge and Biocultural Labels Usage and Style Guide",
        "Local Contexts",
        "https://localcontexts.org/wp-content/uploads/2023/08/TK-and-BC-Labels-Usage-and-Style-Guide.pdf",
        "current_reference",
        "community-originated notice and provenance reservation only; no label selection, community decision, cultural authorization, or Māori wording",
    ),
]


# number, title, slug, pillar, disposition, semantic mechanism, source ids
PROPOSAL_ROWS = [
    (
        1,
        "Timepiece service intake and custody passport with synthetic job token, declared scope, received-state note, accessory inventory, approval boundary, correction path, and no-real-customer-or-watch claim",
        "timepiece-intake-custody-passport",
        "Freed ID and CBR Heart",
        "completed",
        "service intake, synthetic job token, declared scope, received state, accessory inventory, custody, approval boundary, correction, and real-customer and real-watch refusal",
        ["W3C-PROV-O", "RFC-3339", "NZ-PRIVACY-PRINCIPLES", "NZ-CONSUMER-CGA"],
    ),
    (
        2,
        "Movement, calibre-family, plate, bridge, train, oscillator, escapement, winding, calendar, and complication component-topology graph with orphan quarantine and no-assembly instruction",
        "timepiece-component-topology",
        "GMUT Mind and Freed ID",
        "completed",
        "movement and calibre-family component topology, parent-child relation, train membership, orphan quarantine, revision, and assembly refusal",
        ["ISO-3764-2016", "W3C-PROV-O", "RFC-8785"],
    ),
    (
        3,
        "Dial, index, hand, subdial, calendar aperture, chapter ring, rotation sense, zero datum, indication interval, occlusion, and ambiguity coordinate-frame contract",
        "timepiece-indication-frame",
        "GMUT Mind",
        "completed",
        "dial, hand, calendar, indication, rotation, datum, interval, occlusion, ambiguity, and coordinate-frame obligations",
        ["ISO-3764-2016", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        4,
        "Case, bezel, crystal, crown, stem, tube, pusher, back, gasket-seat, seal-placeholder, access state, and no-water-resistance release interface ledger",
        "timepiece-case-seal-interface",
        "GMUT Mind and THOS Body",
        "completed",
        "case, bezel, crystal, crown, tube, pusher, back, gasket seat, seal placeholder, access state, and water-resistance release refusal",
        ["ISO-22810-2010", "ISO-6425-2018", "W3C-PROV-O"],
    ),
    (
        5,
        "Barrel, centre, third, fourth, escape, motion-work, calendar-drive, wheel, pinion, mesh, direction, ratio-placeholder, backlash cue, and no-performance prediction graph",
        "timepiece-gear-train-graph",
        "GMUT Mind",
        "completed",
        "gear train, wheel, pinion, mesh, direction, ratio placeholder, backlash cue, dependency, and performance-prediction refusal",
        ["ISO-3764-2016", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        6,
        "Escape wheel, pallet fork, entry and exit pallet, guard pin, banking, impulse face, lock placeholder, drop placeholder, clearance cue, and no-adjustment command board",
        "timepiece-escapement-relation",
        "GMUT Mind and THOS Body",
        "completed",
        "escapement components, impulse, lock, drop, clearance, relation, uncertainty, and adjustment-command refusal",
        ["ISO-3764-2016", "W3C-PROV-O"],
    ),
    (
        7,
        "Balance, hairspring, collet, stud, regulator-placeholder, beat relation, amplitude-placeholder, position, temperature, interval, uncertainty, and no-rate conclusion envelope",
        "timepiece-oscillator-state",
        "GMUT Mind",
        "completed",
        "balance oscillator, hairspring, beat relation, amplitude placeholder, position, temperature, interval, uncertainty, and rate-conclusion refusal",
        ["ISO-3159-2009", "NIST-SP811", "RFC-3339"],
    ),
    (
        8,
        "Mainspring, barrel arbor, bridle, ratchet, crown wheel, click, reverser, rotor, automatic train, wind-state placeholder, torque quantity, and no-power-reserve claim ledger",
        "timepiece-winding-energy-ledger",
        "GMUT Mind and THOS Body",
        "completed",
        "mainspring, barrel, manual and automatic winding, wind-state placeholder, torque quantity, dependency, and power-reserve refusal",
        ["ISO-3764-2016", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        9,
        "Pivot, hole jewel, cap jewel, endshake-placeholder, sideshake-placeholder, bushing, bearing surface, wear cue, uncertainty, substitution hold, and no-condition determination inventory",
        "timepiece-pivot-jewel-inventory",
        "GMUT Mind",
        "completed",
        "pivot, jewel, bushing, bearing, clearance placeholders, wear cue, uncertainty, substitution hold, and condition-determination refusal",
        ["ISO-3764-2016", "W3C-PROV-O"],
    ),
    (
        10,
        "Lubrication point, contact mode, lubricant-placeholder, batch-placeholder, expiry, compatibility hold, application-state placeholder, contamination cue, supersession, and no-material instruction ledger",
        "timepiece-lubrication-ledger",
        "THOS Body and GMUT Mind",
        "completed",
        "lubrication point, contact mode, material placeholder, batch, expiry, compatibility, contamination, supersession, and material-instruction refusal",
        ["ISO-16359-2025", "W3C-PROV-O", "RFC-3339"],
    ),
    (
        11,
        "Screw, spring, jumper, click, lever, wheel, pinion, jewel, washer, shim, tray-cell, transfer count, duplicate quarantine, loss hold, and small-part custody map",
        "timepiece-small-part-custody",
        "Freed ID and THOS Body",
        "completed",
        "small-part identity placeholder, tray cell, transfer count, duplicate quarantine, loss hold, readback, correction, and custody",
        ["W3C-PROV-O", "RFC-3339", "RFC-8785"],
    ),
    (
        12,
        "Timepiece condition-image lineage with synthetic asset token, viewpoint, lighting mode, scale cue, rights, redaction, ingredient, action, revision, and no-diagnostic-or-authenticity claim",
        "timepiece-condition-image-lineage",
        "Freed ID and CBR Heart",
        "completed",
        "condition image, synthetic asset token, capture context, rights, redaction, provenance, revision, and diagnostic and authenticity refusal",
        ["C2PA-2.4", "W3C-PROV-O", "NZ-PRIVACY-PRINCIPLES"],
    ),
    (
        13,
        "Pre-service, proposed-service, approved-scope-placeholder, post-service-placeholder, affected component, dependency, supersession, discrepancy, rollback, and no-completed-repair delta graph",
        "timepiece-service-delta-graph",
        "Freed ID and CBR Heart",
        "completed",
        "baseline, proposed service, approval placeholder, post-state placeholder, affected component, dependency, supersession, discrepancy, rollback, and completed-repair refusal",
        ["W3C-PROV-O", "RFC-3339", "NZ-CONSUMER-CGA"],
    ),
    (
        14,
        "Timing-observation envelope with synthetic trace token, dial position, temperature-placeholder, interval, rate-placeholder, beat-error-placeholder, amplitude-placeholder, unit, uncertainty, instrument-state hold, and no-accuracy claim",
        "timepiece-timing-observation-envelope",
        "GMUT Mind",
        "completed",
        "timing observation schema, position, temperature placeholder, interval, rate placeholder, beat-error placeholder, amplitude placeholder, unit, uncertainty, instrument-state hold, and accuracy refusal",
        ["ISO-3159-2009", "NIST-SP811", "RFC-3339"],
    ),
    (
        15,
        "Watch-cell designation, chemistry-placeholder, dimensions-placeholder, polarity, lot-placeholder, expiry, received voltage-placeholder, replacement approval, isolation, disposal hold, and no-battery-selection contract",
        "timepiece-cell-replacement-boundary",
        "THOS Body and CBR Heart",
        "completed",
        "watch cell, chemistry placeholder, dimensions placeholder, polarity, batch, expiry, voltage placeholder, approval, isolation, disposal hold, and battery-selection refusal",
        ["IEC-60086-3-2016", "ISO-16359-2025", "W3C-PROV-O"],
    ),
    (
        16,
        "Cleaning solvent, bath, basket, ultrasonic-placeholder, rinse, drying, ventilation, exposure, competent-person, isolation, waste, emergency, and no-cleaning-procedure board",
        "timepiece-cleaning-safety-reserve",
        "THOS Body and CBR Heart",
        "completed",
        "solvent and cleaning-equipment state, exposure, ventilation, competent person, isolation, waste, emergency, and cleaning-procedure refusal",
        ["NZ-WORKSAFE-ORGANIC-SOLVENTS", "ISO-16359-2025", "W3C-PROV-O"],
    ),
    (
        17,
        "Water-resistance evidence firewall with case-state placeholder, gasket-state placeholder, crown-state placeholder, pressure-instrument hold, test-protocol hold, result absence, expiry, use warning, and no-depth-or-diving claim",
        "timepiece-water-resistance-firewall",
        "THOS Body and CBR Heart",
        "completed",
        "water-resistance evidence fields, seal and instrument holds, test absence, expiry, use warning, and depth, diving, conformity, fitness, and safety refusal",
        ["ISO-22810-2010", "ISO-6425-2018", "W3C-PROV-O"],
    ),
    (
        18,
        "Magnetic-exposure and demagnetization evidence firewall with field-placeholder, orientation, duration-placeholder, instrument hold, before-after rate placeholders, residual uncertainty, and no-magnetic-resistance claim",
        "timepiece-magnetic-resistance-firewall",
        "GMUT Mind and THOS Body",
        "completed",
        "magnetic exposure and demagnetization placeholders, orientation, duration, instrument hold, before-after observation, uncertainty, and resistance-claim refusal",
        ["ISO-764-2020", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        19,
        "Shock-event and shock-test evidence firewall with impact absence, orientation placeholder, instrument hold, before-after observation placeholders, damage uncertainty, quarantine, and no-shock-resistance claim",
        "timepiece-shock-resistance-firewall",
        "THOS Body and GMUT Mind",
        "completed",
        "shock event and test placeholders, orientation, instrument hold, before-after observation, damage uncertainty, quarantine, and shock-resistance refusal",
        ["ISO-1413-2016", "NIST-SP811", "W3C-PROV-O"],
    ),
    (
        20,
        "Timepiece component provenance, declared-source, manufacturer-claim-placeholder, reference compatibility, interchangeability hold, substitution approval, counterfeit uncertainty, return path, and no-authentication ledger",
        "timepiece-parts-provenance",
        "Freed ID and CBR Heart",
        "completed",
        "component provenance, declared source, manufacturer-claim placeholder, compatibility, interchangeability hold, substitution, counterfeit uncertainty, return, and authentication refusal",
        ["W3C-PROV-O", "NZ-CONSUMER-CGA", "RFC-8785"],
    ),
    (
        21,
        "Accessible service estimate, scope choice, excluded-work notice, approval placeholder, cost and time placeholder, status, interruption, correction, complaint, remedy path, and reserved affected-user evaluation",
        "accessible-timepiece-service-notice",
        "CBR Heart and THOS Body",
        "completed",
        "accessible estimate, scope choice, exclusions, approval placeholder, cost and time placeholders, status, correction, complaint, remedy, and affected-user evaluation reservation",
        ["W3C-WCAG-22", "NZ-CONSUMER-CGA", "NZ-CONSUMER-FAULTY-SERVICES", "NZ-PRIVACY-PRINCIPLES"],
    ),
    (
        22,
        "Service queue, open-movement state, exposed-part cue, active-solvent cue, interruption, workload limit, unresolved decision, custody readback, correction acknowledgement, and shift-handover docket",
        "timepiece-workload-handover",
        "THOS Body and CBR Heart",
        "completed",
        "queue, open movement, exposed parts, solvent cue, interruption, workload limit, unresolved decision, custody readback, correction, and handover",
        ["NZ-WORKSAFE-ORGANIC-SOLVENTS", "W3C-PROV-O", "RFC-3339"],
    ),
    (
        23,
        "Timepiece return package, movement immobilization-placeholder, dial and hand clearance hold, accessory reconciliation, moisture-control placeholder, seal, transfer readback, discrepancy, and no-transport-or-fitness authorization docket",
        "timepiece-return-custody-docket",
        "THOS Body and Freed ID",
        "completed",
        "return packaging, immobilization placeholder, clearance hold, accessory reconciliation, moisture placeholder, seal, transfer, discrepancy, and transport and fitness refusal",
        ["W3C-PROV-O", "RFC-3339", "NZ-CONSUMER-CGA"],
    ),
    (
        24,
        "GMUT coupled balance-hairspring synthetic oscillator proxy with typed state, phase chart, damping-placeholder, drive-placeholder, position field, unit, initial and boundary obligations, identifiability hold, and zero empirical fit",
        "gmut-timepiece-oscillator-proxy",
        "GMUT Mind",
        "represented",
        "typed coupled oscillator proxy, phase chart, damping and drive placeholders, position field, units, initial and boundary obligations, identifiability hold, and empirical-fit refusal",
        ["ISO-3159-2009", "NIST-SP811"],
    ),
    (
        25,
        "GMUT timepiece gear-train graph energy proxy with wheel-node state, mesh-edge state, incidence orientation, torque-placeholder, loss-placeholder, residual, unit, stability hold, and zero predictive claim",
        "gmut-timepiece-gear-energy-proxy",
        "GMUT Mind",
        "represented",
        "typed gear-train graph energy proxy, node and edge states, incidence orientation, torque and loss placeholders, residual, units, stability hold, and prediction refusal",
        ["ISO-3764-2016", "NIST-SP811"],
    ),
    (
        26,
        "THOS synthetic timepiece service discrepancy and recovery protocol with blinded-scenario placeholder, matched-budget reservation, readback, quarantine, escalation, resumption, workload, outcome-field hold, and no-effectiveness claim",
        "thos-timepiece-recovery-proxy",
        "THOS Body",
        "represented",
        "synthetic service discrepancy and recovery protocol, blind and matched-budget reservations, readback, quarantine, escalation, resumption, workload, outcome hold, and effectiveness refusal",
        ["W3C-PROV-O", "RFC-3339", "W3C-WCAG-22"],
    ),
    (
        27,
        "Freed ID synthetic timepiece service statement and SCITT-style envelope with subject placeholder, predicate, content digest, registration-policy placeholder, transparent-statement placeholder, receipt absence, revocation hold, and no-live-identity claim",
        "freed-id-timepiece-scitt-envelope",
        "Freed ID",
        "represented",
        "synthetic service statement and transparent-supply-chain envelope, subject placeholder, predicate, digest, policy placeholder, receipt absence, revocation hold, and live-identity refusal",
        ["RFC-9943", "RFC-8785", "W3C-VC-DM-20"],
    ),
    (
        28,
        "Freed ID synthetic timepiece condition-media C2PA profile with asset placeholder, ingredient, action, assertion, binding-placeholder, signer-placeholder, validation-result absence, trust hold, and no-authenticity claim",
        "freed-id-timepiece-c2pa-profile",
        "Freed ID",
        "represented",
        "synthetic condition-media provenance profile, asset placeholder, ingredient, action, assertion, binding placeholder, signer placeholder, validation absence, trust hold, and authenticity refusal",
        ["C2PA-2.4", "W3C-PROV-O", "NZ-PRIVACY-PRINCIPLES"],
    ),
    (
        29,
        "Smithsonian Open Access horology discovery adapter readiness packet with query-purpose placeholder, API-key gate, rights filter, object and image field quarantine, pagination budget, attribution, caching hold, and zero-row execution",
        "smithsonian-horology-zero-row-adapter",
        "Freed ID and GMUT Mind",
        "open_gap",
        "public museum horology discovery readiness, query-purpose placeholder, API-key gate, rights filter, object and image quarantine, pagination budget, attribution, cache hold, and zero-row execution",
        ["SMITHSONIAN-OPEN-ACCESS", "NZ-PRIVACY-PRINCIPLES", "W3C-PROV-O"],
    ),
    (
        30,
        "CBR heirloom, memorial, sacred-object possibility, taonga possibility, donor, family, whānau, collective-interest, provenance, image, access, repair, return, remedy, legal, cultural, and Māori-authority reservation matrix",
        "cbr-timepiece-authority-matrix",
        "CBR Heart",
        "exact_gate",
        "heirloom, memorial, sacred-object and taonga possibilities, donor, family, whānau, collective interest, provenance, image, access, repair, return, remedy, legal, cultural, and Māori-authority reservation",
        ["TMR-PRINCIPLES", "LOCAL-CONTEXTS-TK-BC", "NZ-PRIVACY-PRINCIPLES", "W3C-PROV-O"],
    ),
]


CLEAN_SURFACES = [
    "proposal and source ledgers",
    "semantic novelty and frozen-chain indexes",
    "timepiece component and relation schemas",
    "GMUT typed oscillator and gear-graph boundaries",
    "THOS synthetic recovery protocol",
    "Freed ID synthetic statement and media envelopes",
    "CBR authority reservation matrix",
    "Method Flow and retained-negative provenance",
    "privacy, accessibility, and workload boundaries",
    "commit-local manifests and exact-final receipts",
]

SKILL_IDEAS = [
    "ghc-family-timepiece-custody-boundary",
    "ghc-family-timepiece-topology-integrity",
    "ghc-family-timepiece-timing-nonpromotion",
    "ghc-family-timepiece-water-magnetic-shock-reserve",
    "ghc-family-timepiece-material-safety-reserve",
    "ghc-family-timepiece-image-provenance-boundary",
    "ghc-family-timepiece-accessibility-handover",
    "ghc-family-timepiece-privacy-cultural-reserve",
    "ghc-family-gmut-timepiece-interface-firewall",
    "ghc-family-timepiece-evidence-nonpromotion",
]

RUNNER_IDEAS = [
    "ghc_family_timepiece_custody_boundary.py",
    "ghc_family_timepiece_topology_integrity.py",
    "ghc_family_timepiece_timing_nonpromotion.py",
    "ghc_family_timepiece_water_magnetic_shock_reserve.py",
    "ghc_family_timepiece_material_safety_reserve.py",
    "ghc_family_timepiece_image_provenance_boundary.py",
    "ghc_family_timepiece_accessibility_handover.py",
    "ghc_family_timepiece_privacy_cultural_reserve.py",
    "ghc_family_gmut_timepiece_interface_firewall.py",
    "ghc_family_v656_v4_suite.py",
]


def _negative(
    number: int,
    signature: str,
    observed: str,
    recovery: str,
    guard: str,
    scope: str = "startup",
) -> dict:
    return {
        "negative_id": f"V6564-NEG-X1-{number:03d}",
        "scope": scope,
        "signature": signature,
        "observed": observed,
        "credit": 0,
        "retained": True,
        "recovery": recovery,
        "recurrence_guard": guard,
        "same_owner_only": True,
        "independent_reproduction": False,
    }


X1_OPERATIONAL_NEGATIVES = [
    _negative(
        1,
        "combined-memory-skill-discovery-timeout",
        "The first combined memory and skill discovery command exceeded its bounded timeout.",
        "Split memory lookup from skill discovery and use bounded literal-path probes.",
        "Keep read-first discovery scalar and time-bounded before repository mutation.",
    ),
    _negative(
        2,
        "powershell-login-profile-memory-probe-timeout",
        "A PowerShell login-profile Get-Item and memory search exceeded its bounded timeout.",
        "Rerun the bounded read-only probes with login-profile loading disabled.",
        "Use login=false for deterministic repository and memory probes.",
    ),
    _negative(
        3,
        "grouped-source-git-verification-timeout",
        "A grouped source Git verification command exceeded its bounded timeout.",
        "Audit path, branch, head, status, ancestry, and remote equality with scalar probes.",
        "Separate local Git checks from live-remote checks and materialize each result.",
    ),
    _negative(
        4,
        "auth-schema-extension-assumption",
        "The first read targeted a nonexistent JSON auth schema instead of the current Markdown schema.",
        "Resolve the schema filename from the selected skill and read the Markdown schema through EOF.",
        "Enumerate exact referenced resources before reading a schema.",
    ),
    _negative(
        5,
        "manifest-replay-inline-python-quoting-fault",
        "The first inline Python manifest replay had a command-quoting syntax error.",
        "Pass the bounded script through standard input and replay the manifest without changing source.",
        "Avoid nested shell quoting for structured manifest checks.",
    ),
    _negative(
        6,
        "source-validation-receipt-schema-assumption",
        "The first receipt projection assumed an older attempts-array shape and returned null fields.",
        "Inspect the flat receipt keys and project the actual canonical aggregate fields.",
        "Inspect receipt schema before projecting validation truth.",
    ),
    _negative(
        7,
        "worktree-preflight-powershell-expression-fault",
        "The first branch and path existence preflight embedded native commands in an invalid PowerShell expression.",
        "Run scalar native commands and capture explicit exit status values.",
        "Keep PowerShell conditionals separate from native command invocations.",
    ),
    _negative(
        8,
        "grouped-post-worktree-audit-timeout",
        "The first grouped post-creation worktree audit exceeded its bounded timeout.",
        "Split registration, branch, head, status, and process checks into scalar probes.",
        "Use small bounded worktree audits after long checkout operations.",
    ),
    _negative(
        9,
        "frozen-index-property-shape-assumption",
        "The first frozen proposal projection assumed proposals or entries rather than prior_proposals and new_proposals.",
        "Enumerate the index properties and join the two declared proposal arrays.",
        "Inspect JSON property names before count or semantic projections.",
    ),
    _negative(
        10,
        "source-evidence-exclusion-set-mismatch",
        "The inherited evidence manifest declares one lifecycle exclusion for a path absent from the evidence commit; all committed evidence paths remain covered and the final owner and delta manifests are exact.",
        "Retain the source audit mismatch at zero credit, use exact set-equality checks for Caelen manifests, and do not rewrite Sylven history.",
        "Require declared exclusions plus entries to equal actual commit-local paths in every Caelen manifest.",
        scope="inherited-source-audit",
    ),
    _negative(
        11,
        "method-flow-projection-console-encoding-fault",
        "The first inherited Method Flow projection reached a Windows console encoding error while printing Māori text.",
        "Set Python UTF-8 input and output encoding and rerun the read-only projection.",
        "Set PYTHONUTF8 and PYTHONIOENCODING for all structured Python probes.",
    ),
    _negative(
        12,
        "mixed-method-flow-state-event-shape",
        "The first x1 build assumed every inherited Method Flow state event used an after field, but retained older events use a to field.",
        "Preserve both inherited event shapes and count the normalized after-or-to state.",
        "Normalize mixed historical Method Flow event shapes only at read time; never rewrite inherited events.",
    ),
    _negative(
        13,
        "repeated-large-git-candidate-discovery-timeout",
        "The second x1 build exceeded its bounded timeout while repeatedly asking Git to rediscover the same large untracked candidate set.",
        "Enumerate the bounded Caelen phase root plus the three phase scripts and x1 test deterministically.",
        "Use one owner-path inventory for build, review, privacy, and manifest generation.",
    ),
    _negative(
        14,
        "grouped-post-build-timeout-audit-timeout",
        "The first grouped process and Git-status audit after the x1 build timeout also exceeded its bounded timeout.",
        "Separate process inspection from repository status and avoid a full untracked status walk.",
        "Audit timeout aftermath with small scalar probes and bounded owner-path enumeration.",
    ),
    _negative(
        15,
        "scalar-process-audit-timeout",
        "A scalar PowerShell process audit exceeded its bounded timeout during temporary host load.",
        "Treat the build invocation as terminated by the command boundary and continue only with deterministic owner-local reads.",
        "Do not retry expensive host-wide process enumeration when bounded repository checks suffice.",
    ),
    _negative(
        16,
        "native-tasklist-process-audit-timeout",
        "A native read-only task-list filter also exceeded its bounded timeout during temporary host load.",
        "Stop host-wide process probing and rely on the next bounded builder exit plus later Git lock and exact-state checks.",
        "Escalate to process inspection only if a concrete Git lock or mutation conflict appears.",
    ),
    _negative(
        17,
        "post-stage-manifest-blob-hash-mismatch",
        "The first exact staged-blob replay found the privacy-scan blob had changed after the manifest entry was computed.",
        "Audit the producing process, stop concurrent writes, rebuild from frozen inputs, and replay every staged blob hash.",
        "Require a zero-writer check and exact staged-blob replay before committing x1.",
    ),
    _negative(
        18,
        "timed-out-x1-builder-survived-command-boundary",
        "The timed-out x1 builder remained live and continued owner-local Git discovery and file rewrites after its command boundary.",
        "Resolve its exact PID and command line, stop only that stale builder and its confirmed Git child, then rebuild once.",
        "After any timeout, audit the exact command-line process before accepting generated artifacts.",
    ),
    _negative(
        19,
        "grouped-post-stage-diff-and-process-audit-timeout",
        "A grouped unstaged-diff and exact-process audit exceeded its bounded timeout after the staged hash replay.",
        "Use git diff-files and an exact Python command-line process filter as separate scalar probes.",
        "Keep large-worktree index checks separate from host process inspection.",
    ),
    _negative(
        20,
        "combined-diff-files-and-untracked-probe-timeout",
        "A combined large-worktree diff-files and untracked probe exceeded its bounded timeout after the exact staged replay.",
        "Rely on the exact staged manifest now and perform clean-state checks as separate long-timeout probes after commit.",
        "Never combine large-worktree cleanliness and untracked enumeration in one bounded command.",
    ),
]
