"""Materialize planning evidence only; refuses an x2 tree."""
from __future__ import annotations
import collections, hashlib, html, importlib.util, json, os, pathlib, re, subprocess
from ghc_family_svg_contract_plan import literal_contracts, SKILL_PAIRS

ROOT=pathlib.Path(__file__).resolve().parents[2]
BASE=ROOT/'docs/orren-pike/v688-v2'
BANK=pathlib.Path(os.environ['GHC_OWNER_BANK'])
SOURCE='2eb2198a9f2b15279bbc1300d857fab440c53be3'
OWNER='Orren Pike'
GATES=['empirical','real_participants','professional','production','deployment','identity','legal','cultural','affected_party','maori_authority','privacy_complete','accessibility_complete','exhaustive_security','independent_reproduction','agi_asi','consciousness_personhood','theory_of_everything','proof_canon','stage20']
BOUNDARY='Relational working language only; no consciousness, personhood, continuity, qualification, employment, independent agency, or authority claim. Synthetic same-owner software evidence is not independent reproduction. NOT_READY_FOR_STAGE_20. Maori concepts remain under Maori authority.'
BASELINE={'proposals':15630,'negatives':82599,'methods':93292,'failed_witnesses':53447,'passing_witnesses':83009,'open_gaps':748,'exact_gates':747}

def canonical(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=True,allow_nan=False).encode('ascii')
def sha(v):return hashlib.sha256(canonical(v)).hexdigest()
def write(rel,value):
 p=BASE/rel;p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text(json.dumps(value,indent=2,sort_keys=True,ensure_ascii=True,allow_nan=False)+'\n',encoding='utf-8',newline='\n')
def git(*a):return subprocess.check_output(['git','-C',str(ROOT),*a],timeout=45)
def pairs(seq):
 d={}
 for k,v in seq:
  if k in d:raise ValueError('DUPLICATE_KEY')
  d[k]=v
 return d
def strict(raw):return json.loads(raw,object_pairs_hook=pairs,parse_constant=lambda x:(_ for _ in ()).throw(ValueError('NONFINITE')))
def ledger(failures):
 result={'schema':'ghc.family.method-flow-state.v1','owner':OWNER,'phase':'v688-v2','identity_boundary':BOUNDARY,'boundary':BOUNDARY,'execution_authority':'owner_self_scoped_delta','source_commit':SOURCE,'final_commit':None,'methods':[],'witnesses':[],'state_events':[],'recommendations':[]}
 for i,r in enumerate(failures,1):
  mid=f'OP6882-START-M{i:03}';nid=r['negative_id'];fail=mid+'-FAIL';pas=mid+'-PASS'
  result['methods'].append({'method_id':mid,'title':r['failure_signature'],'failure_signature':r['failure_signature'],'trigger_preconditions':['Orren Pike v688-v2 source and planning read'],'privacy_class':'sanitized_public','approval_class':'safe_now','candidate_workaround':r['candidate_workaround'],'validation_witness_ids':[fail,pas],'recurrence_guard':r['candidate_workaround'],'rollback':'Stop the bounded procedure and retain source, failure, and correction.','recommendation_state':'preferred','supersedes':[],'protected_gates':GATES,'retained_negative_ids':[nid],'scope_boundary':'Startup and planning only; zero x2 proposal execution credit.'})
  for wid,state,obs in [(fail,'fail',r['failure_signature']),(pas,'pass',r['candidate_workaround'])]:
   result['witnesses'].append({'witness_id':wid,'method_id':mid,'procedure':'Bounded source read and narrow recovery','scope':'Orren Pike startup','expected':'Attributable complete read within declared source scope','observed':obs,'result':state,'same_owner_only':True,'independent_reproduction':False,'retained_negative_ids':[nid] if state=='fail' else [],'boundary':BOUNDARY})
  for a,b in [('observed','candidate'),('candidate','validated'),('validated','preferred')]:result['state_events'].append({'method_id':mid,'from':a,'to':b,'note':'Separate retained failure and bounded recovery witnesses.'})
 result['counts']={'methods':len(failures),'witnesses':2*len(failures),'state_events':3*len(failures),'recommendations':0,'states':{x:(len(failures) if x=='preferred' else 0) for x in ['observed','candidate','validated','preferred','superseded','deprecated']},'witness_results':{'fail':len(failures),'pass':len(failures)}}
 return result

def main():
 assert git('rev-parse','HEAD').decode().strip()==SOURCE
 assert not (BASE/'x2').exists()
 sourcebase='docs/liora-venn/v688-v1/'
 inherited=strict(git('show',SOURCE+':'+sourcebase+'x1/new-proposals.json'))['proposals']
 index=strict((BANK/'reachable-proposal-title-index.json').read_bytes())
 proposals=literal_contracts();assert len(proposals)==200
 skills=dict(SKILL_PAIRS)
 practice_names=['synthetic vector-drawing intake clerk','exact SVG path-state recorder','synthetic stroke and paint catalogue reviewer','vector-reference and access-reservation reviewer']
 pract={op:practice_names[0 if i<6 else 1 if i<14 else 2 if i<18 else 3] for i,op in enumerate(dict.fromkeys(p['operation'] for p in proposals))}
 pillars={practice_names[0]:'THOS Body',practice_names[1]:'GMUT Mind',practice_names[2]:'THOS Body',practice_names[3]:'Freed ID and CBR Heart'}
 for p in proposals:
  op=p['operation'];disp='completed'
  if op=='local_href' and p['expected_output']['accepted'] and not p['expected_output']['value']['resolved']:disp='open_gap'
  if p['expected_output']['error']=='EXTERNAL_REFERENCE':disp='exact_gate'
  if op in ['fill_rule','stroke_style','marker_orientation'] and p['expected_output']['accepted']:disp='represented'
  p.update({'schema':'ghc.family.frozen-svg-contract.v1','source_status':'draft','source_kind':'synthetic','approval_class':'safe_now','execution_lane':'x2_only','expected_execution_disposition':disp,'hypothesis':p['title'],'null_or_failure_condition':'Any complete typed-output mismatch, input mutation, or promotion beyond the named SVG metadata profile fails.','falsifier_or_acceptance_gate':'Compare every key, value, type and array position with the literal frozen output; separately reject the preregistered altered output.','concrete_artifact':'docs/orren-pike/v688-v2/x2/contract-results.json','rollback_or_recovery':'Retain the frozen contract and failed output; change only the owner implementation or leave the named outside gate open.','practice':pract[op],'pillar':pillars[pract[op]],'skill':next(n for n,ops in SKILL_PAIRS if op in ops),'protected_gates':GATES,'external_credit':False})
 unique={r['title']:r for r in index['rows']};tokens=[(set(re.findall('[a-z0-9]+',t.lower())),r) for t,r in unique.items()]
 reviews=[];input_hashes={r['input_sha256'] for r in index['rows'] if r['input_sha256']}
 for p in proposals:
  t=set(re.findall('[a-z0-9]+',p['title'].lower()))
  score,neighbor=max(((len(t&old)/len(t|old),r) for old,r in tokens),key=lambda x:x[0])
  reviews.append({'proposal_id':p['proposal_id'],'nearest_title':neighbor['title'],'nearest_path':neighbor['path'],'token_jaccard':round(score,6),'exact_title_collision':p['title'] in unique,'exact_input_collision':sha(p['input']) in input_hashes,'review':'SVG grammar/state contract is distinct from the inherited general evidence or affine-transform claim; no copied implementation credit.'})
 assert not any(r['exact_title_collision'] or r['exact_input_collision'] or r['token_jaccard']>=.78 for r in reviews)
 assert len({sha(p['input']) for p in proposals})==200 and len({p['title'] for p in proposals})==200
 release=strict((pathlib.Path.home()/'.codex/skills/ghc-family-owned-bundle-rotation/references/workflow-profile-20260906.json').read_bytes())
 package=strict((BANK/'package-metadata.json').read_bytes())
 failures=strict((BANK/'startup-failures.json').read_bytes())['rows']
 failures.append({'negative_id':'OP6882-START-N014','failure_signature':'A historical chain-audit detail projection exceeded the display budget.','candidate_workaround':'Use its already fully parsed proposal-file inventory and project only audit_scope and declared-chain scalars.','success_credit':0})
 write('x1/identity.json',{'name':OWNER,'pronouns':'they/them','role':'keeper of reversible records','hope':'That each useful transformation leaves its sources, uncertainties, and limits easy to inspect.','primary_pillar':'GMUT Mind','practices':[{'name':n,'pillar':pillars[n]} for n in practice_names],'next_practice':'synthetic font-outline and glyph-metadata registrar','boundary':BOUNDARY,'corrigibility':['pause','rename','narrow','redirect','stop']})
 write('x1/new-proposals.json',{'schema':'ghc.family.proposal-freeze.v1','planning_only':True,'count':200,'chain_before':15630,'chain_after':15830,'proposals':proposals})
 write('x1/inherited-review.json',{'schema':'ghc.family.zero-credit-inherited-review.v1','source':SOURCE,'count':200,'novelty_credit':0,'execution_credit':0,'rows':[{'source_proposal':p,'review':'Retain full input, complete output expectation, declared source status, provenance and gates. Caption-specific behavior is inherited; SVG-specific behavior must receive its own contract.','novelty_credit':0,'completion_credit':0} for p in inherited]})
 write('x1/novelty-review.json',{'schema':'ghc.family.source-bounded-semantic-audit.v1','source':SOURCE,'declared_chain_rows':15630,'reachable_proposal_json_files':len(index['files']),'reachable_title_records':len(index['rows']),'distinct_titles':len(unique),'distinct_public_labels':len({r['public_proposal_label'] for r in index['rows'] if r['public_proposal_label']}),'comparison_hash_domain':index['comparison_hash_domain'],'parse_issues':index['issues'],'scope_limit':'Read every proposal-labelled JSON blob in the exact source tree. The declared historical chain count is retained separately from reachable labels; inaccessible or differently named evidence is not certified by this lexical inventory.','universal_novelty_claimed':False,'quarantine_threshold':.78,'reviews':reviews,'conceptual_exclusions':['Generic affine transforms, chart accessibility checklists, inherited caption operations and generic publication gates are zero-credit context.']})
 write('x1/proposal-source-manifest.json',{'schema':'ghc.family.read-only-source-inventory.v1','source':SOURCE,'files':index['files'],'count':len(index['files']),'no_historical_tests_executed':True})
 write('x1/release-profile.json',release)
 write('x1/package-plan.json',{'schema':'ghc.family.pinned-package-plan.v1','packages':package['packages'],'plan_only':True,'base_dependencies':0,'extras_selected':[],'installation':'New isolated D-drive environment; wheel-only no-index no-deps require-hashes; no pip bootstrap in environment.','rollback':'Stop selecting the owner environment and retain it, its lock, and receipts.','uses':{'svg.path':'Parse synthetic path segments and compare exact endpoints; record malformed path behavior.','svgelements':'Compare a synthetic path/point transformation and reject a malformed shape; shared ancestry with svg.path means non-independent evidence.','svgwrite':'Serialize a synthetic line drawing, read back geometry, and reject an invalid attribute in validation mode.'},'advisory_scope':'Official exact-release PyPI vulnerabilities and yanked metadata; bounded snapshot only.','protected_gates':GATES})
 write('x1/skill-runner-plan.json',{'schema':'ghc.family.svg-tool-plan.v1','skills':[{'name':n,'operations':ops,'state':'planned_unbuilt'} for n,ops in SKILL_PAIRS],'runners':[{'name':f'ghc_family_svg_group_{i+1}.py','operations':SKILL_PAIRS[2*i][1]+SKILL_PAIRS[2*i+1][1],'state':'planned_unbuilt'} for i in range(5)],'global_overwrites_allowed':False,'compatibility':'Preserve all ghc_family_* and build_ghc_family_* callers. New commands use collision-free destinations.'})
 safe=[{'procedure_id':f'OP6882-S{i+1:03}','kind':'full_contract','proposal_id':p['proposal_id']} for i,p in enumerate(proposals)]
 modes=['compact_object','indented_object','reversed_key_order','duplicate_operation_refusal','nonfinite_value_refusal']
 for j,op in enumerate(dict.fromkeys(p['operation'] for p in proposals)):
  p=next(p for p in proposals if p['operation']==op)
  for mode in modes:safe.append({'procedure_id':f'OP6882-S{len(safe)+1:03}','kind':'json_interface','proposal_id':p['proposal_id'],'mode':mode,'success_claim':'Bounded interface handling only; no additional proposal or reproduction credit.'})
 candidates=[{'candidate_id':f'OP6882-C{i+1:03}','proposal_id':proposals[i%200]['proposal_id'],'mutation':'flip_accepted' if i<200 else 'remove_value','expected':'reject_complete_output_mismatch','state':'preregistered_unexecuted'} for i in range(250)]
 cfr=[{'procedure_id':f'OP6882-CFR{i+1:03}','kind':['CLEAN','FIX','REFINE'][i//100],'proposal_id':proposals[i%200]['proposal_id'],'purpose':['Preserve the frozen record through deterministic JSON normalization.','Repair a synthetic dropped output field from its immutable definition without deleting the failed candidate.','Build a source-bound field explanation for the literal input and expected output.'][i//100]} for i in range(300)]
 exact=[{'packet_id':f'OP6882-E{i+1:03}','skill':SKILL_PAIRS[i%10][0],'action':['Publish a real drawing','Embed a third-party drawing','Release a rendering into production','Certify drawing accessibility','Use culturally governed artwork'][i//10],'state':'held_unexecuted','missing':['exact target','competent and affected authority','scope and rollback evidence'],'executed':False} for i in range(50)]
 blocked=[{'packet_id':f'OP6882-B{i+1:03}','skill':SKILL_PAIRS[i%10][0],'action':['Promote synthetic SVG metadata into empirical or Stage 20 proof','Replace a distinct owner identity with this drawing record','Erase inherited failed evidence to simplify the catalogue'][i//10],'state':'held_blocked_unexecuted','executed':False} for i in range(30)]
 write('x1/portfolio-plan.json',{'schema':'ghc.family.svg-portfolio-plan.v1','planning_only':True,'safe':safe,'candidates':candidates,'clean_fix_refine':cfr,'exact_packets':exact,'blocked_packets':blocked,'counts':{'safe':300,'candidates':250,'clean_fix_refine':300,'exact_packets':50,'blocked_packets':30},'count_boundary':'Procedure counts are distinct procedural records; they do not multiply proposal novelty, independent reproduction, or empirical credit.'})
 ideas=['SVG clipping-unit declaration','SVG pattern-unit declaration','SVG gradient-stop ordering','SVG filter-region bounds','SVG text-path offset metadata','SVG font-outline provenance','SVG symbol-use dependency','SVG transform-list order grammar','SVG viewport nesting context','SVG alternate-text correction lineage']
 write('x1/successor-ideas.json',{'skill_ideas':[{'idea':x,'state':'unbuilt_zero_credit'} for x in ideas],'runner_ideas':[{'idea':x+' runner','state':'unbuilt_zero_credit'} for x in ideas],'practice':'synthetic font-outline and glyph-metadata registrar','boundary':BOUNDARY})
 write('x1/source-ledger.json',{'schema':'ghc.family.primary-source-ledger.v1','entries':[{'source_id':'SVG2-PATHS','status':'draft','url':'https://www.w3.org/TR/SVG2/paths.html','use':'Path grammar, current-point changes, curve controls, arc degeneracies; no full-conformance or empirical claim.'},{'source_id':'SVG2-COORDS','status':'draft','url':'https://www.w3.org/TR/SVG2/coords.html','use':'Viewport and aspect-ratio vocabulary.'},{'source_id':'SVG2-PAINT','status':'draft','url':'https://www.w3.org/TR/SVG2/painting.html','use':'Stroke, marker and paint-order vocabulary.'},{'source_id':'SVG2-LINK','status':'draft','url':'https://www.w3.org/TR/SVG2/linking.html','use':'Local fragment vocabulary; no external reference fetch.'}]+[{'source_id':p['name'],'status':'current','url':f"https://pypi.org/project/{p['name']}/{p['version']}/",'use':'Exact wheel/version/dependency/advisory metadata.'} for p in package['packages']],'citations_are_observations':False,'real_rows':0})
 write('x1/method-flow/ledger.json',ledger(failures))
 write('x1/retained-negative-register.json',{'activation_baseline':BASELINE,'startup_negatives':failures,'failures_erased':0,'failures_promoted':0})
 write('x1/reading-receipt.json',{'source':SOURCE,'baton_sha256':'b4af315d47eb94bf74e17765159dc38509ec714b159b76e5402c79d590ffb181','baton_bytes':288857,'baton_words':32251,'baton_lines':6642,'baton_eof':'EOF LIORA VENN V688 V1 BATON.','baton_read':'Complete contiguous reads through EOF','source_manifests':{'bindings_verified':710,'exclusions':6,'mismatches':0},'source_content_seal_targets_verified':12,'source_method_flow':{'methods':57,'witnesses':812,'failed':297,'passing':515,'state_events':171},'source_canonical_receipt_sha256':'d71727fe299c7a026efe32c29cd9e614270d732bb7332dfa5864498b77f6e99d','source_canonical_replayed':False,'large_json_read_policy':'Complete strict parse and exact blob verification; bounded semantic projections do not claim line-by-line prose reading.','current_auth_and_roster_read_through_eof':True,'current_release_overrides_stale_v667_cursor':True,'portable_source_skills_read':10})
 write('x1/route-plan.json',{'owner':OWNER,'phase':'v688-v2','future_seat':11,'endpoint_kind':'main_task','source':SOURCE,'next_owner':'Tamar Vey','next_phase':'v688-v3','state':'PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED','send_count':0,'new_task_authority':False,'terminal_conditions':['clean pushed final','fresh four-way equality','one successful non-replayed canonical','current release and registry','unique exact title','immediate guard reread','no duplicate pause redirect rename usage privacy evidence safety or authority block'],'no_post_send_monitoring':True})
 write('x1/scope-budget.json',{'owner_file_ceiling':1999,'document_word_ceiling':100000,'baton_word_range':[10000,100000],'baton_modules':13,'overview_pages_min':3,'commit_cap':{'x1':1,'evidence':1,'final':1,'total':3},'canonical_invocation_budget':1,'canonical_replay':False,'primary_drive':'D','c_free_bytes_at_start':20127227904,'d_free_bytes_at_start':499721158656,'sparse_before_materialization':True,'execution_authority':'owner_self_scoped_delta','sibling_lane_mutation':False,'full_repository_suite':False})
 write('x1/validation-contract.json',{'source':SOURCE,'scope':['docs/orren-pike/v688-v2/','scripts/orren_pike_v688_v2/','tests/test_ghc_family_orren_pike_v688_v2.py'],'hash_domain':'normalized LF Git blobs','required':['strict JSON duplicate/nonfinite refusal','type-sensitive complete outputs','input immutability','all preregistered candidates','source and x1 immutability','exact manifests and exclusions','five-class privacy adjudication','bounded changed-code review','exact staged allowlists','direct single-parent ancestry','zero merges','clean typed zero divergence fresh four-way equality'],'canonical':'Exclusive external invocation marker after final push. Existing marker or success blocks replay.','full_repository_suite':False})
 write('x1/reflection-plan.json',{'disposition':'remaster_additive','kept_current':['GHC Family Index precedence','Method Flow schema','release profile','skill-creator validation'],'kept_compatibility':['ghc-family-svg-chart-audit','all inherited caption tools'],'new_scope':'Twenty SVG command and attribute profiles with literal complete outputs, no generic affine-transform novelty claim.','known_callers':'No existing caller is changed; new skill and runner fixtures will supply bounded caller evidence in x2.','rollback':'Stop selecting the additive tools; preserve all history.','protected_gates':GATES})
 write('x1/workflow-refinement.json',{'submitted_current':'Orren Pike v688-v2','submitted_next':'Tamar Vey v688-v3','normalization_changes_ownership':False,'requires_user_confirmation':False,'current_profile':'Hamish release 6 September 2026','historical_cursors_preserved':True,'planning_only':True,'strict_x1_before_x2':True,'budget_counts':{'inherited':200,'new':200,'safe':300,'candidates':250,'cfr':300,'exact':50,'blocked':30,'skills':10,'runners':5,'packages':3},'boundary':BOUNDARY})
 write('x1/deck-plan.json',{'tiers':['freed_id_anchor','trinity_pillar','bounded_practice','task'],'counts':{'owner':1,'pillar':3,'practice':4,'task':200},'each_nonroot_one_parent_in_previous_tier':True,'build_after_x1_equality_only':True,'cache_or_identity_gain_claimed':False})
 write('x1/phase-truth.json',{'owner':OWNER,'phase':'v688-v2','state':'PLANNING_ONLY_NOT_FROZEN','source':SOURCE,'activation_baseline':BASELINE,'planned_proposal_chain':15830,'x2_execution_count':0,'package_installations':0,'promotions':0,'canonical_invocations':0,'successor_contacts':0,'terminal_verdict':'NOT_READY_FOR_STAGE_20'})
 print(json.dumps({'planning_contracts':len(proposals),'maximum_title_neighbor':max(r['token_jaccard'] for r in reviews),'x2_implementation':False,'packages_installed':0,'startup_negatives':len(failures)}))

if __name__=='__main__':main()
