"""Planning-only literal SVG contracts. No evaluator or package execution."""
from __future__ import annotations

def ok(value):
    return {"accepted": True, "error": None, "value": value, "external_credit": False}

def bad(error):
    return {"accepted": False, "error": error, "value": None, "external_credit": False}

# Each row declares a different acceptance or refusal rule. Expected values are
# authored literals; they are never obtained by running the future evaluator.
GROUPS = {
"number_token": [
 ("SVG numeric zero keeps a rational zero", {"token":"0"}, ok({"rational":"0","negative_zero":False})),
 ("SVG signed zero retains its lexical sign", {"token":"-0.00"}, ok({"rational":"0","negative_zero":True})),
 ("SVG leading plus is a sign rather than an operator", {"token":"+12"}, ok({"rational":"12","negative_zero":False})),
 ("SVG leading decimal point denotes a fraction", {"token":".125"}, ok({"rational":"1/8","negative_zero":False})),
 ("SVG trailing decimal point is accepted explicitly", {"token":"12."}, ok({"rational":"12","negative_zero":False})),
 ("SVG positive exponent expands without float rounding", {"token":"1.25e2"}, ok({"rational":"125","negative_zero":False})),
 ("SVG negative exponent retains an exact denominator", {"token":"2E-3"}, ok({"rational":"1/500","negative_zero":False})),
 ("SVG comma is not a decimal separator", {"token":"1,5"}, bad("NUMBER_SYNTAX")),
 ("SVG number token cannot be a JSON Boolean", {"token":True}, bad("TEXT_TYPE")),
 ("SVG infinity token is outside the finite profile", {"token":"Infinity"}, bad("NUMBER_SYNTAX")),
],
"length_token": [
 ("SVG unitless length stays in user units", {"token":"12"}, ok({"amount":"12","unit":"user","context_required":False})),
 ("SVG pixel length keeps its CSS unit label", {"token":"2.5px"}, ok({"amount":"5/2","unit":"px","context_required":False})),
 ("SVG centimetres are retained without physical calibration", {"token":"1cm"}, ok({"amount":"1","unit":"cm","context_required":False})),
 ("SVG percentage length requires viewport context", {"token":"50%"}, ok({"amount":"50","unit":"%","context_required":True})),
 ("SVG em length requires font context", {"token":"1.5em"}, ok({"amount":"3/2","unit":"em","context_required":True})),
 ("SVG ex length preserves its separate font metric", {"token":"2ex"}, ok({"amount":"2","unit":"ex","context_required":True})),
 ("SVG negative length metadata remains signed", {"token":"-3mm"}, ok({"amount":"-3","unit":"mm","context_required":False})),
 ("SVG length unit case is not silently repaired", {"token":"2PX"}, bad("LENGTH_SYNTAX")),
 ("SVG calculation expression is outside the literal length profile", {"token":"calc(1px + 2px)"}, bad("LENGTH_SYNTAX")),
 ("SVG length token rejects a separated unit suffix", {"token":"2 px"}, bad("LENGTH_SYNTAX")),
],
"viewbox": [
 ("SVG viewBox records an origin and positive extents", {"values":["0","0","100","50"]}, ok({"minimum":["0","0"],"extent":["100","50"],"rendering_enabled":True})),
 ("SVG viewBox permits a negative minimum coordinate", {"values":["-10","-20","30","40"]}, ok({"minimum":["-10","-20"],"extent":["30","40"],"rendering_enabled":True})),
 ("SVG zero viewBox width disables its rendering representation", {"values":["1","2","0","9"]}, ok({"minimum":["1","2"],"extent":["0","9"],"rendering_enabled":False})),
 ("SVG zero viewBox height is distinct from a negative height", {"values":["1","2","9","0"]}, ok({"minimum":["1","2"],"extent":["9","0"],"rendering_enabled":False})),
 ("SVG viewBox preserves fractional bounds exactly", {"values":[".5","-.5","2.5","1.25"]}, ok({"minimum":["1/2","-1/2"],"extent":["5/2","5/4"],"rendering_enabled":True})),
 ("SVG viewBox refuses a negative width", {"values":["0","0","-1","2"]}, bad("NEGATIVE_EXTENT")),
 ("SVG viewBox refuses a negative height", {"values":["0","0","1","-2"]}, bad("NEGATIVE_EXTENT")),
 ("SVG viewBox requires all four fields", {"values":["0","0","1"]}, bad("VIEWBOX_ARITY")),
 ("SVG viewBox does not discard a fifth field", {"values":["0","0","1","2","3"]}, bad("VIEWBOX_ARITY")),
 ("SVG viewBox coordinate types remain textual numbers", {"values":["0",False,"1","2"]}, bad("TEXT_TYPE")),
],
"aspect_ratio": [
 ("SVG none alignment suppresses meet-slice mode", {"value":"none"}, ok({"align":"none","mode":None})),
 ("SVG centred aspect alignment defaults to meet", {"value":"xMidYMid"}, ok({"align":"xMidYMid","mode":"meet"})),
 ("SVG minimum alignment preserves explicit meet", {"value":"xMinYMin meet"}, ok({"align":"xMinYMin","mode":"meet"})),
 ("SVG maximum alignment retains slice", {"value":"xMaxYMax slice"}, ok({"align":"xMaxYMax","mode":"slice"})),
 ("SVG mixed-axis alignment retains independent axes", {"value":"xMinYMax slice"}, ok({"align":"xMinYMax","mode":"slice"})),
 ("SVG none with an explicit meet token preserves ignored-mode meaning", {"value":"none meet"}, ok({"align":"none","mode":None})),
 ("SVG aspect ratio refuses an unknown alignment", {"value":"center"}, bad("ASPECT_SYNTAX")),
 ("SVG aspect ratio refuses an unknown fitting mode", {"value":"xMidYMid stretch"}, bad("ASPECT_SYNTAX")),
 ("SVG aspect ratio rejects obsolete defer in this profile", {"value":"defer xMidYMid"}, bad("ASPECT_SYNTAX")),
 ("SVG aspect ratio does not infer a value from null", {"value":None}, bad("TEXT_TYPE")),
],
"point_pairs": [
 ("SVG empty points list remains empty", {"text":""}, ok({"points":[]})),
 ("SVG comma separates coordinates inside a pair", {"text":"1,2"}, ok({"points":[["1","2"]]})),
 ("SVG whitespace separates successive point pairs", {"text":"1 2 3 4"}, ok({"points":[["1","2"],["3","4"]]})),
 ("SVG mixed comma and whitespace delimiters preserve pair order", {"text":"1,2 3,4"}, ok({"points":[["1","2"],["3","4"]]})),
 ("SVG point-pair decimals retain exact fractions", {"text":".5,-.25"}, ok({"points":[["1/2","-1/4"]]})),
 ("SVG repeated points are not deduplicated", {"text":"1,1 1,1"}, ok({"points":[["1","1"],["1","1"]]})),
 ("SVG odd coordinate count leaves no implicit partner", {"text":"1 2 3"}, bad("POINT_PAIR_ARITY")),
 ("SVG doubled comma is not an empty coordinate", {"text":"1,,2"}, bad("POINT_SEPARATOR")),
 ("SVG trailing comma is refused by the complete-list profile", {"text":"1,2,"}, bad("POINT_SEPARATOR")),
 ("SVG points collection is not coerced from a JSON array", {"text":[1,2]}, bad("TEXT_TYPE")),
],
"command_arity": [
 ("SVG moveto coordinate groups imply later lineto groups", {"command":"M","parameters":["0","0","1","2"]}, ok({"groups":[["0","0"],["1","2"]],"followup_command":"L"})),
 ("SVG relative moveto retains relative followup command", {"command":"m","parameters":["1","2"]}, ok({"groups":[["1","2"]],"followup_command":"l"})),
 ("SVG horizontal line accepts repeated single coordinates", {"command":"H","parameters":["1","2","3"]}, ok({"groups":[["1"],["2"],["3"]],"followup_command":"H"})),
 ("SVG cubic command requires six values per group", {"command":"C","parameters":["0","1","2","3","4","5"]}, ok({"groups":[["0","1","2","3","4","5"]],"followup_command":"C"})),
 ("SVG arc command retains seven-value groups", {"command":"A","parameters":["1","2","0","0","1","3","4"]}, ok({"groups":[["1","2","0","0","1","3","4"]],"followup_command":"A"})),
 ("SVG closepath command has no parameter group", {"command":"z","parameters":[]}, ok({"groups":[],"followup_command":None})),
 ("SVG closepath refuses an unexpected parameter", {"command":"Z","parameters":["0"]}, bad("COMMAND_ARITY")),
 ("SVG lineto refuses an incomplete coordinate pair", {"command":"L","parameters":["1"]}, bad("COMMAND_ARITY")),
 ("SVG command alphabet excludes a custom R command", {"command":"R","parameters":["1","2"]}, bad("COMMAND_NAME")),
 ("SVG required parameter group cannot be empty", {"command":"Q","parameters":[]}, bad("COMMAND_ARITY")),
],
"moveto": [
 ("SVG absolute moveto replaces the current point", {"command":"M","current":["9","9"],"points":[["2","3"]],"first":False}, ok({"subpath_start":["2","3"],"current_point":["2","3"],"implicit_lines":[]})),
 ("SVG subsequent relative moveto offsets the current point", {"command":"m","current":["9","9"],"points":[["2","3"]],"first":False}, ok({"subpath_start":["11","12"],"current_point":["11","12"],"implicit_lines":[]})),
 ("SVG first relative moveto starts from the initial origin", {"command":"m","current":["0","0"],"points":[["2","3"]],"first":True}, ok({"subpath_start":["2","3"],"current_point":["2","3"],"implicit_lines":[]})),
 ("SVG extra absolute moveto pairs become absolute line endpoints", {"command":"M","current":["0","0"],"points":[["1","2"],["3","4"]],"first":True}, ok({"subpath_start":["1","2"],"current_point":["3","4"],"implicit_lines":[["3","4"]]})),
 ("SVG extra relative moveto pairs accumulate after the initial pair", {"command":"m","current":["0","0"],"points":[["1","2"],["3","4"],["-1","0"]],"first":True}, ok({"subpath_start":["1","2"],"current_point":["3","6"],"implicit_lines":[["4","6"],["3","6"]]})),
 ("SVG zero relative moveto still starts a subpath", {"command":"m","current":["5","6"],"points":[["0","0"]],"first":False}, ok({"subpath_start":["5","6"],"current_point":["5","6"],"implicit_lines":[]})),
 ("SVG moveto profile refuses a line command", {"command":"L","current":["0","0"],"points":[["1","2"]],"first":True}, bad("MOVE_COMMAND")),
 ("SVG moveto requires at least one pair", {"command":"M","current":["0","0"],"points":[],"first":True}, bad("MOVE_POINTS")),
 ("SVG moveto pair cannot have three coordinates", {"command":"M","current":["0","0"],"points":[["1","2","3"]],"first":True}, bad("POINT_SHAPE")),
 ("SVG first-move marker must be Boolean", {"command":"M","current":["0","0"],"points":[["1","2"]],"first":1}, bad("FIRST_TYPE")),
],
"lineto": [
 ("SVG absolute line endpoints replace both coordinates", {"command":"L","current":["1","2"],"parameters":["3","4"]}, ok({"endpoints":[["3","4"]],"current_point":["3","4"]})),
 ("SVG relative line endpoints accumulate both offsets", {"command":"l","current":["1","2"],"parameters":["3","4","-1","-2"]}, ok({"endpoints":[["4","6"],["3","4"]],"current_point":["3","4"]})),
 ("SVG absolute horizontal lines preserve current y", {"command":"H","current":["1","2"],"parameters":["3","4"]}, ok({"endpoints":[["3","2"],["4","2"]],"current_point":["4","2"]})),
 ("SVG relative horizontal lines accumulate x only", {"command":"h","current":["1","2"],"parameters":["3","4"]}, ok({"endpoints":[["4","2"],["8","2"]],"current_point":["8","2"]})),
 ("SVG absolute vertical lines preserve current x", {"command":"V","current":["1","2"],"parameters":["3","4"]}, ok({"endpoints":[["1","3"],["1","4"]],"current_point":["1","4"]})),
 ("SVG relative vertical lines accumulate y only", {"command":"v","current":["1","2"],"parameters":["3","4"]}, ok({"endpoints":[["1","5"],["1","9"]],"current_point":["1","9"]})),
 ("SVG zero-length lineto remains an explicit segment", {"command":"L","current":["1","2"],"parameters":["1","2"]}, ok({"endpoints":[["1","2"]],"current_point":["1","2"]})),
 ("SVG lineto profile refuses a curve command", {"command":"C","current":["1","2"],"parameters":["1","2"]}, bad("LINE_COMMAND")),
 ("SVG lineto refuses an odd relative pair stream", {"command":"l","current":["1","2"],"parameters":["1","2","3"]}, bad("COMMAND_ARITY")),
 ("SVG lineto does not infer missing current coordinates", {"command":"L","current":None,"parameters":["1","2"]}, bad("POINT_SHAPE")),
],
"closepath": [
 ("SVG closepath returns to the declared subpath origin", {"start":["1","2"],"current":["4","6"]}, ok({"endpoint":["1","2"],"delta":["-3","-4"],"closed":True})),
 ("SVG closepath retains a zero-length closing segment", {"start":["1","2"],"current":["1","2"]}, ok({"endpoint":["1","2"],"delta":["0","0"],"closed":True})),
 ("SVG closepath can close across negative coordinates", {"start":["-2","-3"],"current":["-5","-7"]}, ok({"endpoint":["-2","-3"],"delta":["3","4"],"closed":True})),
 ("SVG fractional closepath delta remains exact", {"start":[".5",".25"],"current":["1","1"]}, ok({"endpoint":["1/2","1/4"],"delta":["-1/2","-3/4"],"closed":True})),
 ("SVG closepath with no active subpath is refused", {"start":None,"current":["0","0"]}, bad("NO_SUBPATH")),
 ("SVG closepath refuses a one-coordinate origin", {"start":["1"],"current":["0","0"]}, bad("POINT_SHAPE")),
 ("SVG closepath refuses a third current coordinate", {"start":["0","0"],"current":["0","0","0"]}, bad("POINT_SHAPE")),
 ("SVG closepath refuses a Boolean coordinate", {"start":[True,"0"],"current":["0","0"]}, bad("TEXT_TYPE")),
 ("SVG closepath refuses an unbounded exponent", {"start":["1e999","0"],"current":["0","0"]}, bad("NUMBER_BOUND")),
 ("SVG closepath does not accept a render side effect field", {"start":["0","0"],"current":["1","1"],"render":True}, bad("FIELD_SET")),
],
"cubic_controls": [
 ("SVG explicit cubic controls preserve absolute coordinates", {"command":"C","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4","5","6","7","8"]}, ok({"control1":["3","4"],"control2":["5","6"],"endpoint":["7","8"]})),
 ("SVG relative cubic controls share the segment starting point", {"command":"c","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4","5","6","7","8"]}, ok({"control1":["4","6"],"control2":["6","8"],"endpoint":["8","10"]})),
 ("SVG smooth cubic reflects the previous cubic second control", {"command":"S","current":["10","10"],"previous_command":"C","previous_control":["8","6"],"parameters":["20","20","30","30"]}, ok({"control1":["12","14"],"control2":["20","20"],"endpoint":["30","30"]})),
 ("SVG relative smooth cubic offsets only supplied control and endpoint", {"command":"s","current":["10","10"],"previous_command":"s","previous_control":["8","6"],"parameters":["2","3","4","5"]}, ok({"control1":["12","14"],"control2":["12","13"],"endpoint":["14","15"]})),
 ("SVG smooth cubic after a line uses the current point as first control", {"command":"S","current":["1","2"],"previous_command":"L","previous_control":None,"parameters":["3","4","5","6"]}, ok({"control1":["1","2"],"control2":["3","4"],"endpoint":["5","6"]})),
 ("SVG smooth cubic does not reflect a preceding quadratic control", {"command":"S","current":["1","2"],"previous_command":"Q","previous_control":["9","9"],"parameters":["3","4","5","6"]}, ok({"control1":["1","2"],"control2":["3","4"],"endpoint":["5","6"]})),
 ("SVG smooth cubic refuses missing declared cubic control state", {"command":"S","current":["1","2"],"previous_command":"C","previous_control":None,"parameters":["3","4","5","6"]}, bad("PREVIOUS_CONTROL")),
 ("SVG cubic profile rejects a quadratic command", {"command":"Q","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4","5","6"]}, bad("CUBIC_COMMAND")),
 ("SVG cubic endpoint cannot be omitted", {"command":"C","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4","5","6"]}, bad("COMMAND_ARITY")),
 ("SVG smooth cubic does not coerce a numeric control token", {"command":"S","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":[3,"4","5","6"]}, bad("TEXT_TYPE")),
],
"quadratic_controls": [
 ("SVG explicit quadratic control preserves absolute coordinates", {"command":"Q","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4","5","6"]}, ok({"control":["3","4"],"endpoint":["5","6"]})),
 ("SVG relative quadratic control shares the starting-point offset", {"command":"q","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4","5","6"]}, ok({"control":["4","6"],"endpoint":["6","8"]})),
 ("SVG smooth quadratic reflects a prior Q control", {"command":"T","current":["10","10"],"previous_command":"Q","previous_control":["8","6"],"parameters":["20","30"]}, ok({"control":["12","14"],"endpoint":["20","30"]})),
 ("SVG relative smooth quadratic preserves reflection and endpoint offset", {"command":"t","current":["10","10"],"previous_command":"t","previous_control":["8","6"],"parameters":["2","3"]}, ok({"control":["12","14"],"endpoint":["12","13"]})),
 ("SVG smooth quadratic after a line starts with a coincident control", {"command":"T","current":["1","2"],"previous_command":"L","previous_control":None,"parameters":["3","4"]}, ok({"control":["1","2"],"endpoint":["3","4"]})),
 ("SVG smooth quadratic ignores a preceding cubic control", {"command":"T","current":["1","2"],"previous_command":"C","previous_control":["9","9"],"parameters":["3","4"]}, ok({"control":["1","2"],"endpoint":["3","4"]})),
 ("SVG smooth quadratic refuses missing declared quadratic control state", {"command":"T","current":["1","2"],"previous_command":"Q","previous_control":None,"parameters":["3","4"]}, bad("PREVIOUS_CONTROL")),
 ("SVG quadratic profile excludes cubic shorthand", {"command":"S","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4"]}, bad("QUADRATIC_COMMAND")),
 ("SVG quadratic requires both control and endpoint pairs", {"command":"Q","current":["1","2"],"previous_command":None,"previous_control":None,"parameters":["3","4"]}, bad("COMMAND_ARITY")),
 ("SVG quadratic reflection refuses malformed prior point shape", {"command":"T","current":["1","2"],"previous_command":"Q","previous_control":["9"],"parameters":["3","4"]}, bad("POINT_SHAPE")),
],
"arc_parameters": [
 ("SVG arc preserves the small clockwise branch flags", {"current":["0","0"],"radii":["2","3"],"rotation":"0","flags":[0,1],"endpoint":["4","5"]}, ok({"radii":["2","3"],"rotation":"0","large_arc":False,"sweep":True,"endpoint":["4","5"],"kind":"arc"})),
 ("SVG arc preserves the large counterclockwise branch flags", {"current":["0","0"],"radii":["2","3"],"rotation":"45","flags":[1,0],"endpoint":["4","5"]}, ok({"radii":["2","3"],"rotation":"45","large_arc":True,"sweep":False,"endpoint":["4","5"],"kind":"arc"})),
 ("SVG negative arc radii normalize to magnitudes", {"current":["0","0"],"radii":["-2","-3"],"rotation":"-45","flags":[0,0],"endpoint":["4","5"]}, ok({"radii":["2","3"],"rotation":"-45","large_arc":False,"sweep":False,"endpoint":["4","5"],"kind":"arc"})),
 ("SVG zero horizontal arc radius becomes a line representation", {"current":["0","0"],"radii":["0","3"],"rotation":"0","flags":[0,1],"endpoint":["4","5"]}, ok({"radii":["0","3"],"rotation":"0","large_arc":False,"sweep":True,"endpoint":["4","5"],"kind":"line"})),
 ("SVG zero vertical arc radius becomes a line representation", {"current":["0","0"],"radii":["2","0"],"rotation":"0","flags":[0,1],"endpoint":["4","5"]}, ok({"radii":["2","0"],"rotation":"0","large_arc":False,"sweep":True,"endpoint":["4","5"],"kind":"line"})),
 ("SVG coincident arc endpoints omit the arc even with zero radii", {"current":["1","2"],"radii":["0","0"],"rotation":"0","flags":[1,1],"endpoint":["1","2"]}, ok({"radii":["0","0"],"rotation":"0","large_arc":True,"sweep":True,"endpoint":["1","2"],"kind":"omitted"})),
 ("SVG arc flags refuse integers outside zero and one", {"current":["0","0"],"radii":["2","3"],"rotation":"0","flags":[2,0],"endpoint":["4","5"]}, bad("ARC_FLAGS")),
 ("SVG arc Boolean flags are not integer grammar tokens", {"current":["0","0"],"radii":["2","3"],"rotation":"0","flags":[True,0],"endpoint":["4","5"]}, bad("ARC_FLAGS")),
 ("SVG arc needs exactly two radii", {"current":["0","0"],"radii":["2"],"rotation":"0","flags":[0,1],"endpoint":["4","5"]}, bad("POINT_SHAPE")),
 ("SVG arc rotation excludes angle-unit suffixes in path data", {"current":["0","0"],"radii":["2","3"],"rotation":"45deg","flags":[0,1],"endpoint":["4","5"]}, bad("NUMBER_SYNTAX")),
],
"subpath_partition": [
 ("SVG empty command topology contains no subpath", {"commands":[]}, ok({"subpaths":[]})),
 ("SVG initial moveto creates an open subpath", {"commands":["M"]}, ok({"subpaths":[{"commands":["M"],"closed":False,"implicit_start":False}]})),
 ("SVG closepath marks its command group closed", {"commands":["M","L","Z"]}, ok({"subpaths":[{"commands":["M","L","Z"],"closed":True,"implicit_start":False}]})),
 ("SVG later moveto partitions an open path without closing it", {"commands":["M","L","m","l"]}, ok({"subpaths":[{"commands":["M","L"],"closed":False,"implicit_start":False},{"commands":["m","l"],"closed":False,"implicit_start":False}]})),
 ("SVG drawing after close begins an implicit subpath at the same origin", {"commands":["M","Z","L"]}, ok({"subpaths":[{"commands":["M","Z"],"closed":True,"implicit_start":False},{"commands":["L"],"closed":False,"implicit_start":True}]})),
 ("SVG lowercase close retains its literal command spelling", {"commands":["m","q","z"]}, ok({"subpaths":[{"commands":["m","q","z"],"closed":True,"implicit_start":False}]})),
 ("SVG topology cannot begin with a drawing command", {"commands":["L","M"]}, bad("INITIAL_MOVETO")),
 ("SVG topology cannot begin with closepath", {"commands":["Z"]}, bad("INITIAL_MOVETO")),
 ("SVG repeated close is refused by the bounded topology profile", {"commands":["M","Z","Z"]}, bad("REDUNDANT_CLOSE")),
 ("SVG topology refuses an unknown command token", {"commands":["M","R"]}, bad("COMMAND_NAME")),
],
"path_length": [
 ("SVG absent pathLength metadata leaves calibration unspecified", {"token":None}, ok({"declared_length":None,"positive_scale_reference":False})),
 ("SVG positive pathLength metadata is a declared scale reference", {"token":"100"}, ok({"declared_length":"100","positive_scale_reference":True})),
 ("SVG zero pathLength is distinct from an absent value", {"token":"0"}, ok({"declared_length":"0","positive_scale_reference":False})),
 ("SVG fractional pathLength preserves exact decimal meaning", {"token":"2.5"}, ok({"declared_length":"5/2","positive_scale_reference":True})),
 ("SVG scientific pathLength syntax stays finite", {"token":"1e3"}, ok({"declared_length":"1000","positive_scale_reference":True})),
 ("SVG signed zero pathLength normalizes without positive scale credit", {"token":"-0"}, ok({"declared_length":"0","positive_scale_reference":False})),
 ("SVG negative pathLength is refused", {"token":"-1"}, bad("NEGATIVE_PATH_LENGTH")),
 ("SVG pathLength excludes unit suffixes", {"token":"1px"}, bad("NUMBER_SYNTAX")),
 ("SVG pathLength excludes percent calibration", {"token":"50%"}, bad("NUMBER_SYNTAX")),
 ("SVG pathLength does not coerce a numeric JSON value", {"token":100}, bad("TEXT_TYPE")),
],
"fill_rule": [
 ("SVG nonzero fill rule remains winding metadata", {"rule":"nonzero"}, ok({"rule":"nonzero","computed_fill":False})),
 ("SVG evenodd fill rule remains parity metadata", {"rule":"evenodd"}, ok({"rule":"evenodd","computed_fill":False})),
 ("SVG fill rule does not repair case", {"rule":"EvenOdd"}, bad("FILL_RULE")),
 ("SVG fill rule does not trim leading whitespace", {"rule":" nonzero"}, bad("FILL_RULE")),
 ("SVG fill rule refuses a mixed pair of policies", {"rule":"nonzero evenodd"}, bad("FILL_RULE")),
 ("SVG fill rule refuses an empty policy", {"rule":""}, bad("FILL_RULE")),
 ("SVG fill rule does not resolve CSS inherit without a cascade", {"rule":"inherit"}, bad("CASCADE_REQUIRED")),
 ("SVG fill rule does not resolve CSS initial in a literal profile", {"rule":"initial"}, bad("CASCADE_REQUIRED")),
 ("SVG fill rule does not resolve CSS unset without a cascade", {"rule":"unset"}, bad("CASCADE_REQUIRED")),
 ("SVG fill rule refuses a Boolean policy", {"rule":False}, bad("TEXT_TYPE")),
],
"dash_array": [
 ("SVG none dash pattern remains solid", {"values":"none"}, ok({"pattern":[],"period":"0","solid":True})),
 ("SVG empty bounded dash vector remains no pattern", {"values":[]}, ok({"pattern":[],"period":"0","solid":True})),
 ("SVG even dash vector is preserved once", {"values":["2","3"]}, ok({"pattern":["2","3"],"period":"5","solid":False})),
 ("SVG odd dash vector is duplicated before interpretation", {"values":["1","2","3"]}, ok({"pattern":["1","2","3","1","2","3"],"period":"12","solid":False})),
 ("SVG single dash value doubles into dash and gap", {"values":["4"]}, ok({"pattern":["4","4"],"period":"8","solid":False})),
 ("SVG all-zero dash vector produces a solid representation", {"values":["0","0"]}, ok({"pattern":["0","0"],"period":"0","solid":True})),
 ("SVG zero dash beside a positive gap remains patterned", {"values":["0","2"]}, ok({"pattern":["0","2"],"period":"2","solid":False})),
 ("SVG fractional dash period uses exact addition", {"values":[".5",".25"]}, ok({"pattern":["1/2","1/4"],"period":"3/4","solid":False})),
 ("SVG negative dash value is refused", {"values":["1","-1"]}, bad("NEGATIVE_DASH")),
 ("SVG dash token types are not coerced", {"values":[True,"1"]}, bad("TEXT_TYPE")),
],
"stroke_style": [
 ("SVG butt and miter retain the declared miter limit", {"linecap":"butt","linejoin":"miter","miterlimit":"4"}, ok({"linecap":"butt","linejoin":"miter","miterlimit":"4","rendered":False})),
 ("SVG round caps and joins remain separate properties", {"linecap":"round","linejoin":"round","miterlimit":"4"}, ok({"linecap":"round","linejoin":"round","miterlimit":"4","rendered":False})),
 ("SVG square caps can combine with bevel joins", {"linecap":"square","linejoin":"bevel","miterlimit":"4"}, ok({"linecap":"square","linejoin":"bevel","miterlimit":"4","rendered":False})),
 ("SVG miter-clip join remains distinct from miter", {"linecap":"butt","linejoin":"miter-clip","miterlimit":"2"}, ok({"linecap":"butt","linejoin":"miter-clip","miterlimit":"2","rendered":False})),
 ("SVG arcs join is preserved as an SVG2 token", {"linecap":"round","linejoin":"arcs","miterlimit":"3"}, ok({"linecap":"round","linejoin":"arcs","miterlimit":"3","rendered":False})),
 ("SVG miter limit one meets the lower bound", {"linecap":"butt","linejoin":"miter","miterlimit":"1"}, ok({"linecap":"butt","linejoin":"miter","miterlimit":"1","rendered":False})),
 ("SVG fractional miter limit above one remains exact", {"linecap":"square","linejoin":"miter","miterlimit":"1.5"}, ok({"linecap":"square","linejoin":"miter","miterlimit":"3/2","rendered":False})),
 ("SVG miter limit below one is refused", {"linecap":"butt","linejoin":"miter","miterlimit":".5"}, bad("MITER_LIMIT")),
 ("SVG stroke style refuses an unknown cap", {"linecap":"flat","linejoin":"miter","miterlimit":"4"}, bad("LINECAP")),
 ("SVG stroke style refuses an unknown join", {"linecap":"butt","linejoin":"sharp","miterlimit":"4"}, bad("LINEJOIN")),
],
"marker_orientation": [
 ("SVG automatic marker orientation remains unresolved without a tangent", {"value":"auto"}, ok({"mode":"auto","angle":None,"unit":None})),
 ("SVG auto-start-reverse keeps its start-marker distinction", {"value":"auto-start-reverse"}, ok({"mode":"auto-start-reverse","angle":None,"unit":None})),
 ("SVG bare marker angle uses degrees", {"value":"90"}, ok({"mode":"angle","angle":"90","unit":"deg"})),
 ("SVG explicit marker degrees retain their unit", {"value":"45deg"}, ok({"mode":"angle","angle":"45","unit":"deg"})),
 ("SVG marker radians stay unconverted exact metadata", {"value":"1.5rad"}, ok({"mode":"angle","angle":"3/2","unit":"rad"})),
 ("SVG marker gradians remain distinguishable from degrees", {"value":"100grad"}, ok({"mode":"angle","angle":"100","unit":"grad"})),
 ("SVG marker turns retain their fractional amount", {"value":".25turn"}, ok({"mode":"angle","angle":"1/4","unit":"turn"})),
 ("SVG negative marker angle remains signed", {"value":"-90deg"}, ok({"mode":"angle","angle":"-90","unit":"deg"})),
 ("SVG marker orientation refuses unrelated length units", {"value":"2px"}, bad("ORIENT_SYNTAX")),
 ("SVG marker orientation requires a textual token", {"value":90}, bad("TEXT_TYPE")),
],
"local_href": [
 ("SVG local fragment binds only an explicitly available synthetic target", {"href":"#synthetic-path","available_ids":["synthetic-path"]}, ok({"fragment":"synthetic-path","resolved":True,"external_fetch":False})),
 ("SVG unavailable local fragment stays unresolved", {"href":"#synthetic-missing","available_ids":["synthetic-path"]}, ok({"fragment":"synthetic-missing","resolved":False,"external_fetch":False})),
 ("SVG fragment matching preserves identifier case", {"href":"#Synthetic","available_ids":["synthetic"]}, ok({"fragment":"Synthetic","resolved":False,"external_fetch":False})),
 ("SVG fragment identifiers may include an underscore", {"href":"#synthetic_a","available_ids":["synthetic_a"]}, ok({"fragment":"synthetic_a","resolved":True,"external_fetch":False})),
 ("SVG empty fragment is not a target", {"href":"#","available_ids":[]}, bad("FRAGMENT_SYNTAX")),
 ("SVG network href requires separate external authority", {"href":"https://example.invalid/drawing.svg#p","available_ids":[]}, bad("EXTERNAL_REFERENCE")),
 ("SVG relative document href is not a local fragment", {"href":"other.svg#p","available_ids":[]}, bad("EXTERNAL_REFERENCE")),
 ("SVG data href is excluded from the local reference profile", {"href":"data:image/svg+xml,synthetic","available_ids":[]}, bad("EXTERNAL_REFERENCE")),
 ("SVG duplicate available identifiers leave reference resolution ambiguous", {"href":"#synthetic","available_ids":["synthetic","synthetic"]}, bad("DUPLICATE_TARGET")),
 ("SVG local reference does not decode percent escapes implicitly", {"href":"#synthetic%20a","available_ids":["synthetic a"]}, bad("FRAGMENT_SYNTAX")),
],
"paint_order": [
 ("SVG normal paint order expands to fill stroke markers", {"value":"normal"}, ok({"order":["fill","stroke","markers"]})),
 ("SVG stroke-first paint order appends omitted components canonically", {"value":"stroke"}, ok({"order":["stroke","fill","markers"]})),
 ("SVG markers-first paint order retains marker precedence", {"value":"markers"}, ok({"order":["markers","fill","stroke"]})),
 ("SVG partial fill-marker order appends stroke last", {"value":"fill markers"}, ok({"order":["fill","markers","stroke"]})),
 ("SVG partial marker-stroke order appends fill last", {"value":"markers stroke"}, ok({"order":["markers","stroke","fill"]})),
 ("SVG complete reversed paint order remains literal", {"value":"markers stroke fill"}, ok({"order":["markers","stroke","fill"]})),
 ("SVG explicit normal component order matches its keyword", {"value":"fill stroke markers"}, ok({"order":["fill","stroke","markers"]})),
 ("SVG paint order refuses duplicate components", {"value":"fill fill"}, bad("PAINT_ORDER")),
 ("SVG normal paint keyword cannot mix with component names", {"value":"normal stroke"}, bad("PAINT_ORDER")),
 ("SVG paint order refuses an unknown component", {"value":"background fill"}, bad("PAINT_ORDER")),
],
}

SKILL_PAIRS = [
 ("ghc-family-svg-numeric-tokens", ["number_token","length_token"]),
 ("ghc-family-svg-viewport-declarations", ["viewbox","aspect_ratio"]),
 ("ghc-family-svg-coordinate-streams", ["point_pairs","command_arity"]),
 ("ghc-family-svg-pen-transitions", ["moveto","lineto"]),
 ("ghc-family-svg-subpath-closure", ["closepath","subpath_partition"]),
 ("ghc-family-svg-curve-controls", ["cubic_controls","quadratic_controls"]),
 ("ghc-family-svg-arc-length-declarations", ["arc_parameters","path_length"]),
 ("ghc-family-svg-fill-dash-policies", ["fill_rule","dash_array"]),
 ("ghc-family-svg-stroke-marker-policies", ["stroke_style","marker_orientation"]),
 ("ghc-family-svg-reference-paint-policies", ["local_href","paint_order"]),
]

def literal_contracts():
    rows=[]
    for operation,cases in GROUPS.items():
        if len(cases)!=10:
            raise ValueError("Each operation has ten declared distinct rules")
        for title,fields,expected in cases:
            rows.append({"proposal_id":f"OP6882-N{len(rows)+1:03}","operation":operation,"title":title,
                         "input":{"operation":operation,**fields},"expected_output":expected})
    return rows
