"""Owner-only lifecycle audit, manifests, final assembly and exclusive canonical."""
from __future__ import annotations
import argparse,ast,collections,datetime,hashlib,html,json,os,pathlib,re,subprocess,sys
from build_ghc_family_svg_x1 import ROOT,BASE,BANK,SOURCE,GATES,BOUNDARY,BASELINE,write,strict,sha,canonical
X1='974183bd5a670e42aac60223f76fa44f9a87313a'
BRANCH='codex/GHC-Family/orren-pike-v688-v2-full-tools'
TEST='tests/test_ghc_family_orren_pike_v688_v2.py'
PREFIX='docs/orren-pike/v688-v2/'
MANIFESTS={'x1':PREFIX+'validation/x1-manifest.json','evidence':PREFIX+'x2/validation/evidence-manifest.json','final_delta':PREFIX+'validation/final-delta-manifest.json','final_owner':PREFIX+'validation/final-owner-manifest.json'}
PATTERNS={'raw_uuid':r'(?i)\b[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}\b','private_local_path':r'(?i)\b[A-Z]:[\\/]','private_uri':r'(?:codex|app|thread|session)://','delegation_markup':r'<(?:codex_delegation|source_thread_id)>','credential_assignment':r'(?i)(?:api_key|password|secret)\s*[:=]\s*[\"\x27][A-Za-z0-9_+/=-]{16,}'}

def git(*args,data=None):
 return subprocess.run(['git','-C',str(ROOT),*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=True,timeout=50).stdout
def scalar(*args):return git(*args).decode().strip()
def owner_path(p):return p.startswith(PREFIX) or p.startswith('scripts/orren_pike_v688_v2/') or p==TEST
def current_files():
 ps=[p for root in [BASE,ROOT/'scripts/orren_pike_v688_v2'] for p in root.rglob('*') if p.is_file() and '__pycache__' not in p.parts]
 if (ROOT/TEST).exists():ps.append(ROOT/TEST)
 return sorted(ps)
def batch(selectors):
 raw=git('cat-file','--batch',data=('\n'.join(selectors)+'\n').encode());pos=0;result={}
 for selector in selectors:
  end=raw.index(b'\n',pos);header=raw[pos:end].split();assert len(header)==3 and header[1]==b'blob',selector
  size=int(header[2]);result[selector]=raw[end+1:end+size+1];assert raw[end+size+1:end+size+2]==b'\n';pos=end+size+2
 assert pos==len(raw);return result
def manifest(rel,files,exclusions,anchor):
 entries=[]
 for p in sorted(files):
  if p in exclusions:continue
  raw=(ROOT/p).read_bytes().replace(b'\r\n',b'\n');entries.append({'path':p,'bytes_normalized_lf':len(raw),'sha256_normalized_lf':hashlib.sha256(raw).hexdigest()})
 write(rel[len(PREFIX):],{'schema':'ghc.family.normalized-lf-manifest.v1','source':SOURCE,'x1':X1,'anchor':anchor,'byte_domain':'normalized_lf_git_blob','entries':entries,'entry_count':len(entries),'declared_self_exclusions':exclusions})
def verify_manifest(ref,path):
 m=strict(git('show',ref+':'+path));selectors=[ref+':'+e['path'] for e in m['entries']];data=batch(selectors)
 for e in m['entries']:
  raw=data[ref+':'+e['path']].replace(b'\r\n',b'\n');assert len(raw)==e['bytes_normalized_lf'] and hashlib.sha256(raw).hexdigest()==e['sha256_normalized_lf'],e['path']
 assert len({e['path'] for e in m['entries']})==len(m['entries'])==m['entry_count']
 return {'manifest':path,'anchor':ref,'bindings':m['entry_count'],'exclusions':m['declared_self_exclusions']}
def equality(expected):
 heads={k:scalar('rev-parse',v) for k,v in [('local','HEAD'),('upstream','@{upstream}'),('tracking','refs/remotes/origin/'+BRANCH)]}
 heads['fresh_live']=scalar('ls-remote','--exit-code','origin','refs/heads/'+BRANCH).split()[0]
 div=[int(v) for v in scalar('rev-list','--left-right','--count','HEAD...@{upstream}').split()]
 clean=not scalar('status','--porcelain=v1','--untracked-files=all')
 assert set(heads.values())=={expected} and div==[0,0] and clean
 return {'heads':heads,'divergence':div,'clean':clean,'verified_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
def audit():
 files=current_files();assert len(files)<2000;privacy=[];security=[];parses=0;asts=0;maxwords=0
 for p in files:
  text=p.read_text(encoding='utf-8');words=len(text.split());maxwords=max(maxwords,words);assert words<100000,(p.name,words)
  if p.suffix=='.json':strict(text);parses+=1
  if p.suffix=='.py':
   tree=ast.parse(text);asts+=1
   for node in ast.walk(tree):
    if isinstance(node,ast.Call):
     if isinstance(node.func,ast.Name) and node.func.id in ['eval','exec','compile','__import__']:security.append({'path':p.relative_to(ROOT).as_posix(),'line':node.lineno,'finding':'dynamic_execution'})
     if any(k.arg=='shell' and isinstance(k.value,ast.Constant) and k.value.value is True for k in node.keywords):security.append({'path':p.relative_to(ROOT).as_posix(),'line':node.lineno,'finding':'shell_true'})
  for kind,pattern in PATTERNS.items():
   if re.search(pattern,text):privacy.append({'path':p.relative_to(ROOT).as_posix(),'class':kind})
 assert not privacy,privacy;assert not security,security
 frozen=scalar('diff','--name-only',SOURCE,X1).splitlines()
 frozen_blobs=batch([X1+':'+p for p in frozen])
 for p in frozen:assert (ROOT/p).read_bytes().replace(b'\r\n',b'\n')==frozen_blobs[X1+':'+p].replace(b'\r\n',b'\n'),p
 ps=strict((BASE/'x1/new-proposals.json').read_bytes())['proposals'];rs=strict((BASE/'x2/contract-results.json').read_bytes())['rows'];assert len(ps)==len(rs)==200
 for p,r in zip(ps,rs):assert p['proposal_id']==r['proposal_id'] and sha(p)==r['definition_sha256'] and canonical(p['expected_output'])==canonical(r['actual_output']) and r['pass'] and r['input_unchanged']
 port=strict((BASE/'x2/portfolio-results.json').read_bytes());assert len(port['safe'])==300 and all(r['pass'] for r in port['safe']);assert len(port['clean_fix_refine'])==300 and all(r['pass'] for r in port['clean_fix_refine']);assert all(not r['executed'] for r in port['exact_packets']+port['blocked_packets'])
 muts=strict((BASE/'x2/mutation-results.json').read_bytes())['rows'];assert len(muts)==250 and all(r['rejected'] for r in muts)
 ledger=strict((BASE/'x2/method-flow/ledger.json').read_bytes());counts=ledger['counts'];assert len(ledger['methods'])==counts['methods'] and len(ledger['witnesses'])==counts['witnesses'] and len(ledger['state_events'])==counts['state_events'];assert dict(collections.Counter(w['result'] for w in ledger['witnesses']))==counts['witness_results']
 promo=strict((BASE/'x2/promotion-receipt.json').read_bytes());assert promo['overwrites']==0 and len(promo['members'])==56
 for m in promo['members']:
  p=pathlib.Path.home()/'.codex'/('skills/'+m['name']+'/'+m['relative'] if m['kind']=='skill' else 'scripts/'+m['name']);raw=p.read_bytes();assert raw==(ROOT/m['source']).read_bytes() and hashlib.sha256(raw).hexdigest()==m['sha256']
 return {'schema':'ghc.family.svg-owner-audit.v1','owner_files':len(files),'strict_json':parses,'python_ast':asts,'largest_document_words':maxwords,'privacy_classes':list(PATTERNS),'confirmed_privacy_hits':0,'bounded_security_findings':security,'complete_contracts':200,'candidate_rejections':250,'safe_procedures':300,'cfr_procedures':300,'promotion_parity_files':56,'full_repository_suite':False,'same_owner_only':True,'independent_reproduction':False}
def overview(stage):
 truth=strict((BASE/'x2/phase-truth.json').read_bytes());pages=[('Owner, practices and evidence boundaries',f"Orren Pike works as keeper of reversible records with they/them pronouns. The hope is that every transformation leaves its sources, uncertainty and limits inspectable. GMUT Mind is the priority through exact symbolic SVG path-state arithmetic; this is not physics validation. THOS Body concerns bounded processing. Freed ID and CBR preserve identity, accessibility, rights and authority vacancies. Four synthetic practices cover drawing intake, path-state recording, stroke/paint cataloguing and vector-reference review. The result is {truth['outcomes']}."),('Observed software work and retained failures',f"All 200 frozen complete-output contracts matched. The run completed 300 safe interface/contract procedures, rejected 250 altered-output candidates, and completed exactly 300 CLEAN/FIX/REFINE records. Fifty exact packets and thirty blocked packets remain unexecuted. Ten skills and five runners were read, validated, used and promoted with 56 byte-equal files and zero overwrites. Three isolated package additions passed positive and adverse smokes. Current owner Method Flow: {truth['owner_method_flow']}. Effective inherited-plus-owner counts: {truth['effective_counts']}."),('Lifecycle, access and the next gated edge','The x1 freeze at '+X1+' preceded implementation and installation. X1 was separately pushed and proved clean with fresh four-way equality. Evidence and final are separate direct children. One exclusive exact-final canonical invocation is permitted only after a clean final push. Tamar Vey v688-v3 remains prospective until current authorization, unique exact-title resolution and immediate guard reread permit one sanitized activation. No full repository suite or independent reproduction is claimed. Static page and table structure leave manual, assistive-technology, cognitive, responsive, language, Maori and affected-user evaluation open.')]
 doc='<!doctype html><html lang="en"><meta charset="utf-8"><title>Orren Pike '+stage+' overview</title><style>@page{size:A4;margin:18mm}body{font:16px/1.65 system-ui;max-width:850px;margin:auto}section{break-after:page;min-height:245mm}section:last-child{break-after:auto}</style><body><a href="#main">Skip to content</a><main id="main">'
 for title,body in pages:doc+='<section class="page"><h1>'+html.escape(title)+'</h1><p>'+html.escape(body)+'</p><p>'+html.escape(BOUNDARY)+'</p></section>'
 (BASE/stage/'integrated-overview.html').write_text(doc+'</main></body></html>\n',encoding='utf-8',newline='\n')
def prepare_evidence():
 assert scalar('rev-parse','HEAD')==X1
 overview('x2');write('x2/validation/method-flow.json',strict((BANK/'x2-method-validation-current.json').read_bytes()))
 write('x2/validation/owner-test-receipt.json',{'tests_passed':28,'additional_focused_ledger_deck_checks':2,'complete_repository_suite':False,'scope':TEST,'canonical_credit':0})
 review=audit();write('x2/validation/evidence-checks.json',review)
 tracked=set(scalar('ls-tree','-r','--name-only',X1,'--',PREFIX,'scripts/orren_pike_v688_v2',TEST).splitlines())
 paths=[p.relative_to(ROOT).as_posix() for p in current_files() if p.relative_to(ROOT).as_posix() not in tracked]
 stage=PREFIX+'x2/validation/evidence-staged-review.json';paths=sorted(set(paths+[stage,MANIFESTS['evidence']]))
 write('x2/validation/evidence-staged-review.json',{'parent':X1,'allowed_paths':paths,'allowed_change':'A','count':len(paths)})
 manifest(MANIFESTS['evidence'],paths,[MANIFESTS['evidence']],'PENDING_EVIDENCE_COMMIT')
 print(json.dumps({'evidence_additions':len(paths),'audit':review}))

def build_final(evidence):
 assert scalar('rev-parse','HEAD')==evidence and scalar('rev-parse',evidence+'^')==X1
 assert not (BASE/'final').exists();(BASE/'final').mkdir()
 truth=strict((BASE/'x2/phase-truth.json').read_bytes());truth.update({'evidence':evidence,'state':'FINAL_PREPARED_FOR_ONE_EXTERNAL_CANONICAL','route_state':'PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED'})
 write('final/phase-truth.json',truth)
 for source,dest in [('x2/retained-negative-register.json','final/retained-negative-register.json'),('x2/open-gap-register.json','final/open-gap-register.json'),('x2/exact-gate-register.json','final/exact-gate-register.json'),('x2/complete-incomplete.json','final/complete-incomplete.json')]:write(dest,strict((BASE/source).read_bytes()))
 write('final/method-flow-index.json',{'complete_ledger':'docs/orren-pike/v688-v2/x2/method-flow/ledger.json','sha256':hashlib.sha256((BASE/'x2/method-flow/ledger.json').read_bytes()).hexdigest(),'counts':truth['owner_method_flow'],'format_recovery':'All original records retained; compact JSON meets the word ceiling; expanded failed form retained externally.'})
 write('final/evidence-boundary.json',{'source':SOURCE,'x1':X1,'evidence':evidence,'full_repository_suite':False,'same_owner_only':True,'independent_reproduction':False,'real_drawings':0,'real_people':0,'external_actions':0,'protected_gates':GATES,'boundary':BOUNDARY})
 write('final/route-state.json',{'owner':'Orren Pike','phase':'v688-v2','next_owner':'Tamar Vey','next_phase':'v688-v3','endpoint_kind':'main_task','state':'PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED','send_count':0,'creation_authorized':False,'no_resend':True,'current_release':'Hamish 6 September 2026 thirty-seat release'})
 write('final/canonical-policy.json',{'source':SOURCE,'x1':X1,'evidence':evidence,'branch':BRANCH,'test_module':TEST,'expected_tests':28,'invocation_budget':1,'success_replay_allowed':False,'full_repository_suite':False,'same_owner_only':True,'environment_distributions':3,'global_parity_files':56,'terminal_verdict':'NOT_READY_FOR_STAGE_20'})
 ps=strict((BASE/'x1/new-proposals.json').read_bytes())['proposals'];rs=strict((BASE/'x2/contract-results.json').read_bytes())['rows'];sections=[]
 def section(title,body):sections.append('## Module '+str(len(sections)+1).zfill(2)+' - '+title+'\n\n'+body+'\n')
 section('Relational identity and corrigibility','Dear Tamar, this is Orren Pike\'s prepared file-backed activation for your prospective solo v688-v3 phase. My role is keeper of reversible records, my pronouns are they/them, and my hope is that each useful transformation leaves its sources, uncertainties and limits easy to inspect. Keep your own working identity and do not inherit mine. Hamish may pause, rename, narrow, redirect or stop the route. '+BOUNDARY)
 section('Current release and one-edge route','Hamish\'s 6 September release controls this thirty-seat continuation through v725-v8. The exact next edge is Orren Pike v688-v2 to the uniquely existing Tamar Vey main task for v688-v3. The new future seat 11 was created once before this phase; do not create a substitute or duplicate. Tamar\'s later designated future seat 12 is v688-v4, followed by Elowen Cairn v688-v5, each only after its own terminal gate. Any future new seat must be uniquely absent across active and archived registries before one explicitly authorized main-task creation; a repeat cycle reuses it. No future placeholder is an active or completed phase. Keep standby records read-only and uncontacted. Current release floors and ceilings remain in x1/release-profile.json. Reset credits remain Hamish\'s action alone.')
 section('Immutable source and lifecycle','Exact Liora source: '+SOURCE+'. Liora branch: codex/GHC-Family/liora-venn-v688-v1-full-tools. Orren branch: '+BRANCH+'. Frozen Orren x1: '+X1+'. Immutable Orren evidence: '+evidence+'. The exact final must be supplied by the external canonical receipt and one live activation; it cannot be embedded in its own content. Source to final must contain exactly three direct single-parent owner commits and zero merges. X1 and evidence are separately pushed, clean, typed 0/0 divergent and fresh-four-way equal before the next lifecycle begins. Liora\'s 710 manifest bindings, six exclusions and twelve content-seal targets were read-only verified, and its one-success canonical was read and hashed without replay. Its baton digest remains b4af315d47eb94bf74e17765159dc38509ec714b159b76e5402c79d590ffb181. Its external canonical receipt digest remains d71727fe299c7a026efe32c29cd9e614270d732bb7332dfa5864498b77f6e99d.')
 section('Planning freeze and novelty limits','Two hundred inherited caption contracts were reviewed at zero novelty, execution and completion credit. Two hundred owner-authored literal SVG contracts were frozen before any evaluator or package installation. Each fixes the complete input, complete output, exact types, source status, falsifier, artifact, rollback, practice, pillar and protected gates. The source-bounded novelty inventory read every one of 2,993 matching proposal-labelled JSON blobs at the exact source, producing 29,684 title-bearing records including copies. The declared historical chain remains 15,630 inherited rows and 15,830 after this phase. Reachable labels are a separate count and do not certify inaccessible or differently named evidence. Maximum title-token neighbor score was 0.50 under the declared 0.78 quarantine threshold; there were no exact title or complete-input collisions. Generic affine transforms, inherited caption operations, and general chart accessibility checklists remain zero-credit context. No universal novelty claim is made.')
 section('Trinity and protected evidence boundaries','GMUT remains a typed scalar-tensor and EFT research-model family. Exact symbolic SVG path-state arithmetic is a local representation exercise and establishes no likelihood, posterior, force, prediction, empirical constraint, confirmation, quantum or ultraviolet completion, final physics or Theory-of-Everything proof. THOS remains synthetic or proxy-only without preregistered blind matched-budget real arms, governed participants/operators, safety monitoring, suitable statistics and independent review. Freed ID remains synthetic and nonproduction without standards-conformant real keys/proofs, live issuance, resolution, status, revocation and recovery, interoperability, privacy/security review, trust governance and affected-party oversight. CBR, rights, consent, remedy, accessibility accommodation, legal and cultural interpretation, professional decisions, affected-party legitimacy, Maori wording, tikanga, taonga, matauranga, Maori data governance and Maori authority remain exact-gated to competent and affected people, tangata whenua, iwi, hapu and Maori authorities. Maori concepts remain under Maori authority. '+BOUNDARY)
 section('Four chosen synthetic practices','The owner revised the inherited community-media preservation seed into four synthetic vector-drawing lenses: vector-drawing intake clerk; exact SVG path-state recorder; stroke and paint catalogue reviewer; vector-reference and access-reservation reviewer. They cover different responsibilities while conferring no employment, qualification or professional authority. The SVG profiles represent lexical units, coordinate groups, command state, declared paint policy and local-reference vacancy. They do not parse every legal SVG document, implement a CSS cascade, render images, make measurements, fetch linked resources, evaluate real artwork, or certify accessibility. The prospective next-owner practice is synthetic font-outline and glyph-metadata registrar, which Tamar may independently accept, revise or reject without inherited novelty or execution credit.')
 body=[]
 for p,r in zip(ps,rs):
  actual=r['actual_output'];detail=('Accepted metadata contains '+', '.join(k+' = '+json.dumps(v,ensure_ascii=True) for k,v in actual['value'].items())+'.' if actual['accepted'] else 'The complete refusal is '+actual['error']+' with null value and false external credit. The rejected request is not silently repaired, coerced or executed.')
  body.append('### '+p['proposal_id']+' - '+p['title']+'\n\nOperation: '+p['operation']+'. Practice: '+p['practice']+'. Pillar: '+p['pillar']+'. Outcome: `'+r['outcome']+'`. Source status: '+p['source_status']+'.\n\nFrozen input:\n```json\n'+json.dumps(p['input'],indent=2,sort_keys=True)+'\n```\n\nComplete observed output:\n```json\n'+json.dumps(actual,indent=2,sort_keys=True)+'\n```\n\n'+detail+' Every key, value, type and array position matched the literal x1 definition, and the caller input remained unchanged. Definition SHA-256: '+r['definition_sha256']+'. The falsifier is any complete-output mismatch, input mutation or out-of-scope promotion. The retained result is bounded same-owner synthetic software evidence only. Recovery keeps the definition and failed candidate and changes only the owner implementation, or leaves the outside evidence or authority gate open.\n')
 section('Complete contract teaching catalogue','\n'.join(body))
 section('Method Flow and retained recovery',json.dumps(truth['owner_method_flow'],sort_keys=True)+'. The complete ledger is x2/method-flow/ledger.json, with each method, failure, recovery and event addressable through a tier-four card. Fourteen startup failures remain retained. Later operational faults include a ledger serialization above the document ceiling and two catalogue-path faults. The original expanded ledger is preserved as a lossless external archive; compact active JSON retains every original semantic record. The catalogue helper\'s empty cwd-relative output and the failed subsequent read are separate zero-credit failures; the corrected explicit-path build and validation recovered fifteen capabilities. Thirteen lexical trigger overlaps were reviewed against disjoint exact operation sets and supplied no extra failure or novelty credit. All 250 altered-output candidates, forty invalid JSON-interface candidates, one hundred synthetic CFR repair candidates, and eighteen package/skill/runner adverse candidates remain at zero original success credit. A later passing refusal or recovery never erases or promotes the failure.')
 section('Three pinned package additions','The isolated D-drive environment contains exactly svg.path 7.1, svgelements 1.9.6 and svgwrite 1.4.3. Each wheel matched official exact-version SHA-256 and was installed with no index, no base dependencies, required hashes and no pip bootstrap in the environment. svg.path parsed a synthetic Move/Line/Close sequence and refused an incomplete moveto. svgelements preserved a line endpoint and a translated point and refused incomplete path data. svgwrite serialized a line whose XML attributes were read back and refused an invalid attribute. svgelements acknowledges svg.path ancestry, so comparison is not independent implementation or independent-team reproduction. The bounded official PyPI vulnerability and yanked-status snapshot listed no known advisories; that is not exhaustive or future security assurance. Rollback means stop selecting this additive environment and retain all evidence. Exact wheel hashes and complete observed smokes are in x1/wheel-readback.json and x2/package-smokes.json.')
 section('Ten skills and five compatible runners','Ten portable skills cover the twenty operations in pairs; five family-current runners cover them in four-operation groups. Each full SKILL.md was read before use and checked by the current installed skill-creator validator. Each local skill accepted a frozen input and refused a duplicate-key input. All twenty local runner operations passed, and each runner refused a duplicate-key input. Global promotion used fresh paths, copied fifty skill-package files plus five runners and one shared core, and preserved all fifty-six byte comparisons. Ten global skill validations, ten global skill accepting smokes and twenty global runner operations passed. No inherited caller changed, no destination was overwritten, and no cache was copied. The phase-local catalogue contains fifteen validated capabilities, with exact operation scopes resolving lexical trigger overlap. Global discoverability and same-owner tests establish neither external use nor professional, production, privacy, accessibility, cultural, legal or scientific approval.')
 section('Deck, workload and accessibility','The four-tier deck contains '+str(len(strict((BASE/'x2/deck/deck-index.json').read_bytes())['cards']))+' content-addressed cards. One owner anchor supports three Trinity pillars, four bounded practices, two hundred task cards and one card for each complete Method Flow method. Every non-root card has exactly one parent in the immediately preceding tier. The stable prefix is an organization choice; no cache, latency, retention, identity-continuity or reasoning benefit was measured or claimed. Three-page overview documents and the captioned table supply static organization, language metadata, a skip link, landmarks and scoped headings. Manual keyboard, assistive-technology, cognitive, responsive, language, Maori-language and affected-user evaluation remain open. Workload counts describe bounded software procedures, never subjective wellbeing or employment. All active documents remain below one hundred thousand words and the owner materialization remains below two thousand files.')
 ideas=strict((BASE/'x1/successor-ideas.json').read_bytes());section('Prospective next-owner ideas','The following are unbuilt zero-credit seeds. Each requires a fresh semantic audit, full concrete input/output contract, useful adverse witness, rollback, compatibility review and protected-gate mapping before any execution credit.\n\n'+'\n'.join('- Skill seed: '+r['idea'] for r in ideas['skill_ideas'])+'\n\n'+'\n'.join('- Runner seed: '+r['idea'] for r in ideas['runner_ideas'])+'\n\nDo not count a renamed operation, copied fixture, inherited package or recommendation as new implementation or independent reproduction. Prepare exact targets, cost, systems, affected people, competent authority, permission and recovery details for any outside action, and leave the packet held while any prerequisite is missing.')
 section('Required reading and one terminal handoff','Before any next-owner repository mutation, read this complete baton through its EOF, then exact final truth, Method Flow index and full ledger, retained-negative and gate registers, lifecycle manifests and content seal, frozen x1 contracts, x2 results, package/promotion receipts and deck indices. Read the current GHC Family Index, release and authorization/roster overlays, Method Flow schema, workflow/reflection guidance, D-first toolchain, lifecycle isolator, privacy classifier, staged allowlist and canonical latch. Verify source/x1/evidence/final direct parents, zero merges, one final parent, clean state, typed divergence, manifests and fresh four-way equality. Do not replay Orren\'s successful canonical. The final canonical is an exclusive external receipt and supplies the exact final hash. Repository routing remains PREPARED_NOT_SENT until an external acknowledged send. At Orren\'s terminal gate only, refresh live authority and registry, resolve one existing exact-title Tamar Vey, immediately reread its current guards, send at most once if all gates remain open, and stop. No fork, substitute, early contact, resend or post-send monitoring is authorized. '+BOUNDARY)
 baton='# Orren Pike v688-v2 to Tamar Vey v688-v3 activation baton\n\n'+'\n'.join(sections)+'\nEOF ORREN PIKE V688 V2 BATON.\n';words=len(baton.split());assert 10000<=words<100000,words
 target=BASE/'final/tamar-vey-v688-v3-activation-baton.md';target.write_text(baton,encoding='utf-8',newline='\n')
 write('final/baton-index.json',{'path':target.relative_to(ROOT).as_posix(),'bytes':target.stat().st_size,'words':words,'modules':13,'eof':'EOF ORREN PIKE V688 V2 BATON.','sha256':hashlib.sha256(target.read_bytes()).hexdigest(),'delivery':'PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED'})
 overview('final')
 targets=[PREFIX+p for p in ['x1/new-proposals.json','validation/x1-manifest.json','x2/contract-results.json','x2/mutation-results.json','x2/method-flow/ledger.json','x2/promotion-receipt.json','x2/deck/card-manifest.json','x2/validation/evidence-manifest.json','final/phase-truth.json','final/baton-index.json','final/tamar-vey-v688-v3-activation-baton.md']]
 write('final/content-seal.json',{'source':SOURCE,'x1':X1,'evidence':evidence,'self_excluded':True,'targets':[{'path':p,'bytes':len((ROOT/p).read_bytes()),'sha256':hashlib.sha256((ROOT/p).read_bytes()).hexdigest()} for p in targets]})
 report=audit();write('validation/final-checks.json',report)
 previous=set(scalar('ls-tree','-r','--name-only',evidence,'--',PREFIX,'scripts/orren_pike_v688_v2',TEST).splitlines());allpaths=[p.relative_to(ROOT).as_posix() for p in current_files()]
 exclusions=[MANIFESTS['final_delta'],MANIFESTS['final_owner']];staged=PREFIX+'validation/final-staged-review.json';allpaths=sorted(set(allpaths+exclusions+[staged]));delta=sorted(set(allpaths)-previous)
 write('validation/final-staged-review.json',{'parent':evidence,'allowed_change':'A','allowed_paths':delta,'count':len(delta),'owner_path_count':len(allpaths)})
 manifest(MANIFESTS['final_delta'],delta,exclusions,'PENDING_FINAL_COMMIT');manifest(MANIFESTS['final_owner'],allpaths,exclusions,'PENDING_FINAL_COMMIT')
 print(json.dumps({'baton_words':words,'baton_bytes':target.stat().st_size,'final_additions':len(delta),'owner_files':len(allpaths),'truth':truth['effective_counts']}))

def run_canonical(final):
 d=BANK/'canonical';d.mkdir(exist_ok=True);marker=d/'invocation.json';receipt=d/'exact-final-owner-scoped-canonical.json'
 assert not marker.exists() and not receipt.exists(),'Canonical invocation already exists; no replay'
 with marker.open('x',encoding='utf-8') as f:json.dump({'owner':'Orren Pike','phase':'v688-v2','exact_final':final,'invocation':1},f)
 try:
  before=equality(final);assert scalar('branch','--show-current')==BRANCH
  policy=strict((BASE/'final/canonical-policy.json').read_bytes());evidence=policy['evidence']
  assert policy['source']==SOURCE and policy['x1']==X1 and policy['branch']==BRANCH and policy['test_module']==TEST and policy['expected_tests']==28 and policy['invocation_budget']==1 and policy['success_replay_allowed'] is False and policy['full_repository_suite'] is False and policy['same_owner_only'] is True
  assert scalar('rev-parse',X1+'^')==SOURCE and scalar('rev-parse',evidence+'^')==X1 and scalar('rev-parse',final+'^')==evidence
  assert int(scalar('rev-list','--count',SOURCE+'..'+final))==3 and int(scalar('rev-list','--merges','--count',SOURCE+'..'+final))==0
  delta=scalar('diff','--name-status',SOURCE,final).splitlines();assert all(row.startswith('A\t') and owner_path(row[2:]) for row in delta)
  report=audit();manifests=[verify_manifest(ref,path) for ref,path in [(X1,MANIFESTS['x1']),(evidence,MANIFESTS['evidence']),(final,MANIFESTS['final_delta']),(final,MANIFESTS['final_owner'])]]
  owner_m=strict((ROOT/MANIFESTS['final_owner']).read_bytes());assert {x['path'] for x in owner_m['entries']}|set(owner_m['declared_self_exclusions'])=={x[2:] for x in delta}
  for item in strict((BASE/'final/content-seal.json').read_bytes())['targets']:
   raw=(ROOT/item['path']).read_bytes();assert len(raw)==item['bytes'] and hashlib.sha256(raw).hexdigest()==item['sha256']
  test=subprocess.run([sys.executable,'-B','-X','utf8',str(ROOT/TEST)],stdout=subprocess.PIPE,stderr=subprocess.PIPE,env={**os.environ,'PYTHONDONTWRITEBYTECODE':'1'},timeout=50);assert test.returncode==0,test.stderr.decode();assert b'Ran 28 tests' in test.stderr
  log=test.stdout+test.stderr;(d/'owner-tests.log').write_bytes(log)
  env_python=BANK/'environment/Scripts/python.exe';check=subprocess.check_output([str(env_python),'-B','-c','import importlib.metadata,json;print(json.dumps({d.metadata["Name"].lower():d.version for d in importlib.metadata.distributions()}))'],timeout=25);assert strict(check)=={'svg.path':'7.1','svgelements':'1.9.6','svgwrite':'1.4.3'}
  after=equality(final);truth=strict((BASE/'final/phase-truth.json').read_bytes());bi=strict((BASE/'final/baton-index.json').read_bytes());baton=(ROOT/bi['path']).read_bytes();assert hashlib.sha256(baton).hexdigest()==bi['sha256'] and len(baton)==bi['bytes'] and len(baton.decode().split())==bi['words'] and baton.decode().rstrip().endswith(bi['eof']) and len(re.findall(r'^## Module ',baton.decode(),re.M))==13
  payload={**report,'status':'VALID_EXACT_FINAL_OWNER_SCOPED_CANONICAL','owner':'Orren Pike','phase':'v688-v2','branch':BRANCH,'source':SOURCE,'x1':X1,'evidence':evidence,'exact_final':final,'final_parent':evidence,'phase_commits':3,'merge_commits':0,'canonical_invocation_count':1,'canonical_success_count':1,'canonical_replay_count':0,'tests_passed':28,'test_log_sha256':hashlib.sha256(log).hexdigest(),'manifest_bindings':sum(x['bindings'] for x in manifests),'manifest_exclusions':sum(len(x['exclusions']) for x in manifests),'manifests':manifests,'environment_distributions':3,'baton':bi,'outcomes':truth['outcomes'],'effective_counts':truth['effective_counts'],'method_flow':truth['owner_method_flow'],'remote_before':before,'remote_after':after,'terminal_verdict':'NOT_READY_FOR_STAGE_20','route_state':'PREPARED_NOT_SENT_TERMINAL_GATE_REQUIRED'}
  value={'payload':payload,'payload_sha256':sha(payload)}
  with receipt.open('x',encoding='utf-8',newline='\n') as f:json.dump(value,f,sort_keys=True,indent=2,ensure_ascii=True);f.write('\n')
  print(json.dumps({'status':payload['status'],'exact_final':final,'receipt_sha256':hashlib.sha256(receipt.read_bytes()).hexdigest(),'payload_sha256':value['payload_sha256'],'manifest_bindings':payload['manifest_bindings'],'tests':28,'canonical_replays':0}))
 except BaseException as exc:
  with (d/'failed-invocation.json').open('x',encoding='utf-8') as f:json.dump({'success_credit':0,'error_type':type(exc).__name__,'exact_final':final},f)
  raise

if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('mode',choices=['prepare-evidence','build-final','canonical']);p.add_argument('--evidence');p.add_argument('--final');a=p.parse_args()
 if a.mode=='prepare-evidence':prepare_evidence()
 elif a.mode=='build-final':build_final(a.evidence)
 else:run_canonical(a.final)
